### ISSUE TITLE
[Package Request] Z

### ISSUE THREAD

**Issue by alexcom** [Entware/Entware#1001]
I suggest adding a package for this utility. 
[z github](https://github.com/rupa/z)
It is really annoying to navigate across my shares in shell. Z makes this much more pleasant.
I don't think there's anything else like z. I am ready to test it on my Synology DS220+(x86_64).

**Comment by ryzhovau** [comment]
It''s just a bash script, nothing to compile here.
You may follow https://github.com/rupa/z/blob/master/README to install it.

**Comment by alexcom** [comment]
I didn’t know that Entware is exclusively about compilable things. I
thought package management in general is about convenience. For example,
Homebrew has Z. But you are right, it’s just a script.
