### ISSUE TITLE
Package request: AirConnect

### ISSUE THREAD

**Issue by dokterdok** [Entware/Entware#101]
Package request: AirConnect
https://github.com/philippe44/AirConnect
---
AirConnect: Send audio to UPnP/Sonos/Chromecast players using AirPlay

Only the newest range of Sonos connected home speakers officially support AirPlay. Any Sonos model introduced before late-2015 don't, they don't have sufficient horsepower to support it. A lot of older models are still sold and in-use today.

This is why people are looking for intermediary utilities like AirConnect that you need to run on a device on the same network as your Sonos speakers. This allows your iOS devices to recognize your old-gen Sonos speakers as AirPlay speakers.

- No similar package already added and/or this one got some new killer feature(s),
- Package is in active development (at least, not abandoned for 5 years or more),
- I haven't tested/added the package on my ASUS RT-AC87U ARM platform, but precompiled ARM binaries exist on the repo

**Comment by ryzhovau** [comment]
Too many dependencies, poor organized cross-compilation. Won't add it, sorry.
