### ISSUE TITLE
mipselsf-k3.4: Bus Error

### ISSUE THREAD

**Issue by ChrisLipscombe** [Entware/Entware#1021]
Trying to install Entware while rooting Creality K1 3d printer.  Get bus errors.  Prevents ffmpeg from being installed when I try to install the timelapse feature.

 Installing Entware...

Making /opt directory on data partition where there is space, and adding a symbolic link...
Downloading generic installer script...
Connecting to raw.githubusercontent.com (185.199.108.133:443)
writing to stdout
-                    100% |*****************************************************************************************|  3222  0:00:00 ETA
written to stdout
Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
Info: Opkg package manager deployment...
Info: Basic packages installation...
Bus error
Bus error
Info: Congratulations!
Info: If there are no errors above then Entware was successfully initialized.
Info: Add /opt/bin & /opt/sbin to $PATH variable
Info: Add "/opt/etc/init.d/rc.unslung start" to startup script for Entware services to start
Info: Found a Bug? Please report at https://github.com/Entware/Entware/issues
Adding /opt/bin and /opt/sbin to the start of the PATH in the system profile...
Adding startup script...

**Comment by zyxmon** [comment]
I am afraid entware team cannot help you. You are using instruction and scripts from here - https://github.com/Guilouz/Creality-K1-and-K1-Max/ - so all the installation questions should go there.

**Comment by Guilouz** [comment]
It's looks like there is an issue with latest aarch build of opkg released on February 24: http://bin.entware.net/aarch64-k3.10/installer/

/opt/bin/opkg update
/opt/bin/opkg upgrade

Have stopped to work.

```
Making /opt directory on data partition where there is space, and adding a symbolic link...
Running generic installer script...
Info: Checking for prerequisites and creating folders...
Warning: Folder /opt exists!
Info: Opkg package manager deployment...
Info: Basic packages installation...
Bus error
Bus error
```

When using an old version of opkg it's working.

**Comment by zyxmon** [comment]
opkg was not modified for 9 months an was not changed on February  - https://github.com/Entware/Entware/tree/master/package/system/opkg

**Comment by Guilouz** [comment]
@zyxmon 

<img width="837" alt="Capture d’écran 2024-02-25 à 15 47 25" src="https://github.com/Entware/Entware/assets/12702322/191220f7-812f-467b-aeda-72710b3eb771">

**Comment by ryzhovau** [comment]
Can't reproduce that on Keenetic Router:
```
~ # cd /opt/bin/
/opt/bin # mv opkg opkg.bak
/opt/bin # wget -q http://bin.entware.net/aarch64-k3.10/installer/opkg
/opt/bin # chmod +x ./opkg
/opt/bin # ./opkg --version
opkg version d038e5b6d155784575f62a66a8bb7e874173e92e (2022-02-24)
```
Look like something firmware specific issue. You may find previous version here:
```
/opt/bin # wget -qO opkg.prev http://bin.entware.net/aarch64-k3.10/installer/prev/opkg
/opt/bin # chmod +x ./opkg.prev 
/opt/bin # ./opkg.prev --version
opkg version f2166a89b7e96e2c60002959731eebc5f45fa318 (2020-05-07)
```

**Comment by Guilouz** [comment]
@ryzhovau My bad, i'm not use aarch version, i use mipselsf version.

It's look like not updated since May 2023 but not working, it worked before.

When I use previous version it's working, don't really understand what's happens with current version.

**Comment by ryzhovau** [comment]
Looks like some syscall is missed in kernel. Just checked mipsel version on ancient Padavan frimware from 2016, looks fine:
```
/opt/home/admin # opkg --version
opkg version d038e5b6d155784575f62a66a8bb7e874173e92e (2022-02-24)
/opt/home/admin # uname -a
Linux WT3020H 3.4.113 #1 Wed Oct 16 13:35:50 MSK 2019 mips GNU/Linux
```

**Comment by Guilouz** [comment]
@ryzhovau Could this be related to these updated files?

<img width="793" alt="Capture d’écran 2024-02-25 à 16 32 02" src="https://github.com/Entware/Entware/assets/12702322/8ac3bd72-5977-431f-827d-8053c24718db">

Nothing has changed on the OS, it's a 3D printer (no firmware change, no kernel change).
Installer generic.sh worked before until February 23

**Comment by Guilouz** [comment]
@ryzhovau 
<img width="883" alt="Capture d’écran 2024-02-25 à 19 06 01" src="https://github.com/Entware/Entware/assets/12702322/f090bfda-d8cc-4944-ae2d-83ef2474fc3f">

Last error is normal, I have just downloaded opkg.

Any idea what can cause this ?

Linux K1Max-5992 4.4.94 #332 SMP PREEMPT Thu Jan 11 18:56:04 CST 2024 mips GNU/Linux

**Comment by Guilouz** [comment]
Installer install entware-opt package released on February 24: entware-opt_227000-3_all.ipk

It also replace opkg and it stop to work, I have Bus error with many of my packages.
Previous version was working before, how i can install previous version ?

**Comment by dwaite** [comment]
I believe this is related to https://github.com/Entware/Entware/commit/8ad1c9e99361c675b609425b1af00e38b7bf05eb , as the Ingenic CPU on this board does not support MIPS16.

**Comment by Guilouz** [comment]
Yes it use Ingenic x2000E / xburst II Soc

@ryzhovau is it possible to restore this, a big community use it on many Creality printers.

**Comment by ChrisLipscombe** [comment]
I have been following this thread, but everything is over my head. I hope whatever happened will be fixed. Like Guilouz said, a large community use this on Creality Printers, myself included.

**Comment by Kev608** [comment]
I also have this problem.

``` Installing Entware...

Making /opt directory on data partition where there is space, and adding a symbolic link...
Downloading generic installer script...
Connecting to raw.githubusercontent.com (185.199.111.133:443)
writing to stdout
-                      0% |                                                                                                                                                                                                                      |     0 --:--:-- ETAInfo: Checking for prerequisites and creating folders...
-                    100% |**********************************************************************************************************************************************************************************************************************|  3222  0:00:00 ETA
written to stdout
Warning: Folder /opt exists!
Info: Opkg package manager deployment...
Info: Basic packages installation...
Bus error
Bus error
Info: Congratulations!
Info: If there are no errors above then Entware was successfully initialized.
Info: Add /opt/bin & /opt/sbin to $PATH variable
Info: Add "/opt/etc/init.d/rc.unslung start" to startup script for Entware services to start
Info: Found a Bug? Please report at https://github.com/Entware/Entware/issues
Adding /opt/bin and /opt/sbin to the start of the PATH in the system profile...
Adding startup script...

 ✓ Entware has been installed successfully!```

**Comment by ryzhovau** [comment]
Please, try to install Entware from http://test.entware.net/mipselsf-k3.4. I turned off MIPS16 instruction to make it compatible with  Ingenic x2000.

bcm63xx is the only OpenWrt MIPS32 target without MIPS16 extension. Not sure I want to turn it off in favor of few rare devices, sorry. 

I'll keep this issue open for a while to reveal similar caces.

**Comment by Guilouz** [comment]
@ryzhovau it's working ! Is it possible to keep it ?

**Comment by ryzhovau** [comment]
I’ll keep it for a week, so you'll be able to make your own mirror.

**Comment by ryzhovau** [comment]
We turned off MIPS16 extension for mipsel-k.4 feed, as it was before Feb 2024.

**Comment by Arnie97** [comment]
Would you please also replace the big endian binary at https://bin.entware.net/mipssf-k3.4/installer/opkg to keep the `MIPS16` extension flag off?

It took me a while to figure out that all the ipk packages under https://bin.entware.net/mipssf-k3.4/ are actually still built with `MIPS16` off; only the `installer/opkg` binary was built in Feb 2024 and throws `SIGBUS`. So I just ended up bootstrapping from https://bin.entware.net/mipssf-k3.4/opkg_2025.11.05~80503d94-1_mips-3.4.ipk.

BTW all the `installer/*.so` libs actually irrelevant, as `opkg` is now statically linked. I suggest to remove them from the installer folder and the shell scripts.

**Comment by ryzhovau** [comment]
@Arnie97, thanks for report! https://bin.entware.net/mipssf-k3.4/installer/opkg updated.
