### ISSUE TITLE
compiling all packages needs >150GB free space

### ISSUE THREAD

**Issue by maurerr** [Entware/Entware#1028]
While I know systems are not that resource constraint these days in terms of storage many of us try to compile on VMs with predefined resources and the wiki https://github.com/Entware/Entware/wiki/Compile-packages-from-sources still states `~60 GB` of overall free space should be enough and it isn't anymore.
Can I edit the wiki ?

**Comment by ryzhovau** [comment]
Sure you can:) NP.
