### ISSUE TITLE
Synology install instructions don't work (fails at wget)

### ISSUE THREAD

**Issue by ryndshn** [Entware/Entware#1044]
**Describe the bug**
I'm following [this guide](https://github.com/Entware/Entware/wiki/Install-on-Synology-NAS). I made it through fine until I got to "Run install script", where it seems like `wget` just times out repeatedly. 
<img width="659" alt="image" src="https://github.com/Entware/Entware/assets/10523324/109e5702-880a-486e-8f65-ef32ff656f4c">

**Environment (please complete the following information):**
 - Entware feed: I'm not sure what this means, but I'm assuming it doesn't apply since I'm working through Entware install
 - Device: Synology DS224+
 - Firmware version: DSM 7.2.1-69057 Update 5

**Comment by ryzhovau** [comment]
Looks like a connectivity issue on your side. There's nothing we can do with that.
