### ISSUE TITLE
Package update request for ocserv

### ISSUE THREAD

**Issue by maxduke** [Entware/Entware#105]
Package update request
---
Could you please update the package "ocserv" to Version 0.12.1?

For the current version 0.12, ocserv cannot be run in the background.
https://ocserv.gitlab.io/www/changelog.html

> Version 0.12.1 (released 2018-05-12)
> Fixed crash on initialization when server was running on background (#154)
> Work around issues with GnuTLS 3.4.x on ubuntu 16.04, at the cost of a memory leak on key reload (#152)
>

**Comment by ryzhovau** [comment]
Done.
