### ISSUE TITLE
Python: Exception occurs in tzlocal.get_localzone()

### ISSUE THREAD

**Issue by programatix** [Entware/entware#105]
Calling tzlocal.get_localzone(), caused the following exception,

  File "/opt/lib/python2.7/site-packages/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/lib/python2.7/site-packages/tzlocal/unix.py", line 100, in _get_localzone
    return pytz.tzfile.build_tzinfo('local', tzfile)
  File "/opt/lib/python2.7/site-packages/pytz/tzfile.py", line 30, in build_tzinfo
    typecnt, charcnt) =  unpack(head_fmt, fp.read(head_size))
struct.error: unpack requires a string argument of length 44

**Comment by ryzhovau** [comment]
It comes from OpenWrt where Python packages was totally reworked. All I can offer is a workaround:
https://github.com/Flexget/Flexget/blob/fc85826ce627642464b550010df33d2536ad37be/flexget/plugins/daemon/scheduler.py#L114

**Comment by programatix** [comment]
Thanks for looking into it. I was the one that wrote the workaround in flexget.


Sent from my Samsung device

-------- Original message --------

**Comment by ryzhovau** [comment]
lol
