### ISSUE TITLE
Update / convert from optware to entware

### ISSUE THREAD

**Issue by ghost** [Entware/Entware#106]
Currently I am running optware on my synology NAS. Is there a way to upgrade / convert to entware?
I searched the web, but could not find any information about that.

**Comment by ryzhovau** [comment]
There's no way to convert Optware installation to Entware.

* backup configuration files from `/opt/etc` and other valuable stuff,
* get list of installed packages by `opkg list_installed`,
* make sure necessary packages present in Entware,
* clean `/opt` folder and deploy Entware,
* install necessary packages and restore configuration files.
