### ISSUE TITLE
Permission denied on opkg update

### ISSUE THREAD

**Issue by PandaTheSlayer** [Entware/Entware#1061]
Trying to update opkg using mirror
`$ opkg update
Downloading http://mirrors.bfsu.edu.cn/entware/mipselsf-k3.4/Packages.gz
wget: server returned error: HTTP/1.1 403 Forbidden
*** Failed to download the package list from http://mirrors.bfsu.edu.cn/entware/mipselsf-k3.4/Packages.gz`
[package name]: A clear and concise description of what the bug is and how to reproduce it. 

**Environment (please complete the following information):**
 - Entware feed: e.g. mipselsf-k3.4
 - Device Creality Nebula Pad

**Comment by ryzhovau** [comment]
Make sure Yandex Cloud is available from your location.

Or you may switch to one of mirror from [this list](https://entware.net/mirrors.html).
