### ISSUE TITLE
How to install entware at non /opt path, or compile source code modify /opt path to other path like /jun/opat

### ISSUE THREAD

**Issue by mojun** [Entware/Entware#1062]
My router is readonly file system，but i want use entware .but no /opt path , 
How to modify source code, to make /opt to other path 
Please help me .

**Comment by zyxmon** [comment]
Here is instruction (Russian) to install Entware in any folder - https://web.archive.org/web/20230127183933/https://forums.zyxmon.org/viewtopic.php?f=5&t=5797
It is valid for armv7sf-k3.2

**Comment by you-oops-dev** [comment]
@zyxmon спасибо чувак телики ядренные делают где большинство папок в root директории на RO, а папки opt нет вообще.
![изображение](https://github.com/user-attachments/assets/6b76df2d-76c0-4744-a17d-de32411d88af)
