### ISSUE TITLE
Update prosody to 0.10.2

### ISSUE THREAD

**Issue by Rooby69** [Entware/Entware#107]
Package update due to
- sometimes prosody crashes
- new scurity release 0.10.2 see
http://blog.prosody.im/prosody-0-10-2-security-release/

**Comment by Rooby69** [comment]
Please update, prosody crashes from time to time, not usable.
After some debuggig I found the following crash of prosody using gdb:

Program received signal SIGSEGV, Segmentation fault.
0x2ac9e9a0 in luaL_addlstring () from /opt/lib/liblua.so.5.1.5

this looks like that the liblua library should also be updated.

**Comment by ryzhovau** [comment]
Both `prosody` and `liblua` came from upstream, so please, [send](https://github.com/openwrt/packages/issues) this issue to OpenWrt guys.

Upstream updates will came here after next sync, but I'm not sure `liblua` will be updated. LUCI WebUI depends on it and OpenWrt guys very conservative with it.
