### ISSUE TITLE
rclone panic

### ISSUE THREAD

**Issue by butaford** [Entware/Entware#1075]
**Describe the bug**
[package name]: rclone_1.67.0-1_mipsel-3.4.ipk
```
opkg update
opkg install rclone 
```
**Environment (please complete the following information):**
 - Entware feed: mipselsf-k3.4
 - Device kn-1810
 - Firmware version 4.1.7
Error:
```
panic: DIRECT (8000) overlaps with LARGEFILE (8000)

goroutine 1 [running]:
github.com/hanwen/go-fuse/v2/fuse.(*flagNames).set(0x4b0c488, 0x8000, {0x2463047, 0x6})
        github.com/hanwen/go-fuse/v2@v2.5.1/fuse/print.go:118 +0x258
github.com/hanwen/go-fuse/v2/fuse.init.2()
        github.com/hanwen/go-fuse/v2@v2.5.1/fuse/print_linux.go:13 +0x64
``` 
![2024-08-12 22-41-35](https://github.com/user-attachments/assets/2217bce6-011c-423b-97a8-2ebe77252060)

**Comment by zyxmon** [comment]
fixed via https://github.com/Entware/entware-go/commit/897f1b73d251aed123cc91bfdd75e79f86629b78
The binaries will arrive soon
