### ISSUE TITLE
Synology DS111: "kernel too old" on install

### ISSUE THREAD

**Issue by archfrog** [Entware/Entware#108]
I just got an ancient Synology DS111 NAS from a friend.  It uses ARMv5.  But when I try to install Entware using this command:

```bash
wget -O - http://bin.entware.net/armv5sf-k3.2/installer/generic.sh | /bin/sh
```

I get two "Kernel too old" errors.  My kernel is a v2.6.32.12, which is the one used by the most recent version of Synology DSM (6.2) on my NAS.

Will Entware ever work with Synology DS111 or should I just forget about it?

**Comment by zyxmon** [comment]
You can use Entware-ng for your kernel. Entware-ng is not supported but has ~2000 packages.
https://github.com/Entware/Entware-ng/wiki
