### ISSUE TITLE
Package request: dnscrypt-proxy 2

### ISSUE THREAD

**Issue by J0s3f** [Entware/Entware#109]
Package request
---
[dnscrypt-proxy 2](https://github.com/jedisct1/dnscrypt-proxy) supports dnscrypt and DNS over HTTPS
it is written in go and much more stable than the dnscrypt-proxy available in Entware now

- [x] No similar package already added and/or this one got some new killer feature(s),

dnscrypt-proxy included is unstable in my experience. https_dns_proxy is included in entware
both can only use a single server. dnscrypt-proxy 2 supports many servers and does automatic loadbalancing. This is very useful if servers are down/unstable and also increases privacy a lot

**Comment by zyxmon** [comment]
It is in the repo for several months.
