### ISSUE TITLE
Please upgrade glibc >= 2.28 and libstdc++ >= 3.4.25 for VSCode

### ISSUE THREAD

**Issue by cevznriny** [Entware/Entware#1095]
[package name]: glibc and libstdc++

 - Entware feed: x64-3.2
 - Device: Asustor AS6604T
 - Firmware version: ADM 4.3.2.R9Q2

VSCode needs new versions of glibc and libstdc++ to work after February 2025.
https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-older-linux-distributions

**Comment by ryzhovau** [comment]
No plans to change current toolchain, sorry.

**Comment by cevznriny** [comment]
Doesn't it just need a version update of libc?
