### ISSUE TITLE
rtorrent broken due to OpenSSL upgrade

### ISSUE THREAD

**Issue by NiQ1** [Entware/Entware#1100]
**Describe the bug**
rtorrent does not run because it still depends on OpenSSL 1.1

[package name]: rtorrent

**Environment (please complete the following information):**
 - Entware feed: x64-k3.2
 - Device: QNAP TS-653 Pro
 - Firmware version: 5.2.0.2860

**Comment by NiQ1** [comment]
P.S. Very dirty fix:
Download:
https://bin.entware.net/x64-k3.2/archive/libopenssl_1.1.1s-1_x64-3.2.ipk
Extract manually using tar, then manually extract data.tar.gz
Copy libcrypto.so.1.1 and libssl.so.1.1 to /opt/lib/

**Comment by ryzhovau** [comment]
https://github.com/Entware/Entware/wiki#%EF%B8%8F-package-upgrade-notes
