### ISSUE TITLE
vlmcsd kms server on for, example, aarch64-3.10

### ISSUE THREAD

**Issue by IndeecFOX** [Entware/Entware#1105]
A replacement for Microsoft's KMS server It contains vlmcs a KMS test client, mainly for debugging purposes, that also can "charge" a genuine KMS server designed to run on an always-on or often-on device,e.g. router, NAS Box
No similar package already added
I'm ready to test added package on my platform aarch64-3.10 and get a feedback about it.
I maked .ipk and he great work on my Keenetic KN-3811 (Filogic 820 aarch64)
https://github.com/Wind4/vlmcsd

**Comment by ryzhovau** [comment]
https://github.com/dartraiden/vlmcsd_Entware
