### ISSUE TITLE
DropBox Uploader

### ISSUE THREAD

**Issue by TeHashX** [Entware/entware#111]
Hi, as stated here http://forums.smallnetbuilder.com/showpost.php?p=150516&postcount=14 this line will break dropbox_uploader script because will show file size from remote and /opt/etc/cron.5mins/torrent-watch.sh script will not work because needs only file names. I created a package but will be overwritten by entware package witch is newer.
https://www.asuswrt.eu/download-torrents-using-dropbox/

**Comment by YasharF** [comment]
TeHashX, can you create the Entware patch, and send a git pull request?

**Comment by TeHashX** [comment]
ryzhovau knows about this issue, I will let him to decide, the patch is here http://forums.smallnetbuilder.com/showpost.php?p=150516&postcount=14
If you are using dropbox_uploader script, just delete line 957 from /opt/bin/dropbox_uploader

**Comment by ryzhovau** [comment]
> Hi, as stated here http://forums.smallnetbuilder.com/showpost.php?p=150516&postcount=14 this line will break dropbox_uploader script because will show file size from remote and /opt/etc/cron.5mins/torrent-watch.sh script will not work because needs only file names.

It's better to fix `/opt/etc/cron.5mins/torrent-watch.sh` then. Isn't it? Why we have to fix `dropbox_uploader` just because some script is broken?

**Comment by TeHashX** [comment]
Sure but I don't have enough knowledge to do this, for you should be easy :)

**Comment by ryzhovau** [comment]
I'll try to fix `/opt/etc/cron.5mins/torrent-watch.sh` when SNB forum will be online again.

**Comment by TeHashX** [comment]
Down again?

Use script from here if you want https://www.asuswrt.eu/download-torrents-using-dropbox/
