### ISSUE TITLE
Update package for Shadowsocks-libev

### ISSUE THREAD

**Issue by xupefei** [Entware/entware#112]
Hello, as the shadowsocks-libev source has been updated to 2.1.1, while now in Entware it is still ~~1.8.4~~ 1.4.8, could you update the package in Entware repo? The newer version fixed some memory leak issues so it may have better performance compared to the ~~1.8.4~~ 1.4.8 version.

PS: The source code of shadowsocks-libev is available here: https://github.com/shadowsocks/shadowsocks-libev

Thank you.

**Comment by YasharF** [comment]
I'm looking at http://entware.wl500g.info/binaries/entware/ and the current version is 1.4.8:
shadowsocks-libev-polarssl_1.4.8_entware.ipk       18-Dec-2014 19:24              173129
shadowsocks-libev_1.4.8_entware.ipk                18-Dec-2014 19:24              170489

where do you see the version 1.8.4 listed as part of Entware?

**Comment by xupefei** [comment]
Sorry it's my typo, it is now 1.4.8 in Entware :(

**Comment by YasharF** [comment]
Here is where the version is picked:
https://github.com/Entware/rtndev/blob/master/shadowsocks-libev/Makefile#L12

I suspect that after bumping the version, we may need to modify the patches.

**Comment by xupefei** [comment]
If you have no time to do this, later I can do the modification :) (I now have some exams now)

**Comment by ryzhovau** [comment]
Done! Please, provide a feedback.

**Comment by ryzhovau** [comment]
@xupefei, I have a question, may be you can help. I was going to add [SigmaVPN](https://github.com/mattolenik/sigmavpn-entware) package until I found [ShadowVPN](https://github.com/clowwindy/ShadowVPN), which was inspired by SigmaVPN and looks like it's spread widely between Chinese users, right? I'm asking because google translate from Chinese gives me a very... strange translation:)

**Comment by xupefei** [comment]
The new version of shadowsocks works without any problems.
But I recommend to add this line before `local_port`:
```
"local":"0.0.0.0",
```
because now by default ss-redir will listen on 127.0.0.1 which can not be accessed by iptables redir function. To keep the package easy-to-use, it is better to add that :)

About the ShadowVPN, yes it is now popular among chinese users as a new method to get across the GFW. But as the wiki page it said "Now under development, so there is lot to be done. please come back later if you want to use sth. more stable."

**Comment by ryzhovau** [comment]
> But I recommend to add this line before `local_port`

Done.
