### ISSUE TITLE
Package Request: onedrive

### ISSUE THREAD

**Issue by diman82** [Entware/Entware#113]
Package request: onedrive

https://github.com/abraunegg/onedrive

Single-binary sync & upload CLI client for OneDrive.
Works both with Personal & Business versions.
---

- Single binary
- State caching
- Real-Time file monitoring with Inotify
- Resumable uploads
- Support OneDrive for Business (part of Office 365)
- Shared folders (not Business)

- [ x ] No similar package already added and/or this one got some new killer feature(s),
- [ x ] Package is in active development (at least, not abandoned for 5 years or more),

**Comment by zyxmon** [comment]
It is written in D language and requires Digital Mars Compiler that is not a part of our and openwrt toolchains.
