### ISSUE TITLE
fpcalc request

### ISSUE THREAD

**Issue by pdupreez** [Entware/Entware#114]
Package request
---
{fpcalc}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I successfully tested added package on my {platform}.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by zyxmon** [comment]
Please specify the homepage with sources of fpcalc. There are different fpcalc projects.

**Comment by pdupreez** [comment]
I am a bit out of my depth here, but I think it is this one? x64 platform?

https://github.com/acoustid/chromaprint/blob/master/src/cmd/fpcalc.cpp

**Comment by ryzhovau** [comment]
Done, #27
Binaries will arrive soon.
