### ISSUE TITLE
No driver support for lirc remote devices?

### ISSUE THREAD

**Issue by Nixbligger** [Entware/entware#116]
Hello,

I'm wondering if I am doing something wrong, but I can't get my remote control working with the *lirc* package after my move to the 2.6. kernel and entware. It complains about missing driver support for *atilibusb*: `Driver 'atilibusb' not supported. Supported drivers: default`. 

If I am not mistaken, the above statement of lirc suggests, that this version was compiled completely without driver support (what doesn't make much sense for me, but well...).

What is confusing for me is the statement I found on [this page](https://code.google.com/p/wl500g-repo/source/browse/ipkg/openwrt/Packages?r=828), that suggests that a number of drivers (including atilibusb) were tested and should work with the exact same version of the lirc package:

> Package: lirc
Version: 0.8.7-1
....
Maintainer: OpenWrt Developers Team <openwrt-devel@openwrt.org>
Architecture: entware
Installed-Size: 52349
Filename: lirc_0.8.7-1_entware.ipk
...
**tested drivers**
...
*ok:*
userspace,accent,act200l,act220l,adaptec,alsa_usb,animax,asusdh,
***atilibusb***,atiusb,...

I don't understand why one would remove support for working devices afterwards, so I suppose I am missing something important here.  A more capable user than me might be able to compile it for himself, including the necessary drivers. I wouldn't even know where to start...
Can anyone of you help me to get it working again, and in case, what I would need to compile it on my own?
Any hint, advice or pointer in the right direction would be highly appreciated!

Thanks and cheers,
Nix

Installed version of lirc:
> $ opkg status lirc
Package: lirc
Version: 0.8.7-1
Depends: libc
Status: install user installed
Architecture: mipselsf

Remote device:
> X10 Wireless Technology, Inc. Wireless Transceiver (ACPI-compliant)

System specs:
> $ uname -a
Linux Wl500w 2.6.22.19 #2 Sun Feb 1 03:03:50 MSK 2015 mips GNU/Linux
$ opkg -version
opkg version 0.1.8
$ cat /opt/etc/opkg.conf
src/gz openwrt http://entware.wl500g.info/binaries/mipselsf
dest root /
lists_dir ext /opt/var/opkg-lists

**Comment by YasharF** [comment]
When you say "I can't get my remote control working with the lirc package after my move to the 2.6. kernel and entware", are you referring that it worked before on a prior firmware?  If so, what firmware were you running and what did you move to?

**Comment by YasharF** [comment]
The change in OpenWRT that disabled the driver build is here: https://dev.openwrt.org/browser/packages/utils/lirc/Makefile?rev=30596
>> "lirc: prevent kernel drivers from being built (they break on newer kernels and they are not packaged here)"

**Comment by Nixbligger** [comment]
Thanks for the reply, Yashar.

I moved from a 2.4 kernel (olegs firmware) with optware to [oleg branch](https://code.google.com/p/wl500g/) that comes with a 2.6 kernel and the option to use entware. 
The move was due to the meanwhile dusty ipkg software repositories I used before, and particularly because of difficulties concerning the old version of MusicPlayerDaemon, that refused to refresh its database.

Now I seem to have another showstopper. That's a pity...
Maybe somebody will come up with a good idea how to make lirc running with atlibusb driver support.

**Comment by ryzhovau** [comment]
> Remote device:
> X10 Wireless Technology, Inc. Wireless Transceiver (ACPI-compliant)

Entware is kernel independent repo, no any kernel modules will be provided, sorry.

**Comment by Nixbligger** [comment]
I can accept that, of course - but to my understanding we're not talking about any kernel modules, are we? 
If I am not mistaken, a particular software package was compiled without the support of almost all of the devices it was originally developed for. As YasharF pointed out, it was obviously due to problems with building certain (*other?!*) kernel drivers.

I know, it was a decision made by the OpenWRT team and accordingly is not a shortcoming of Entware. I just hoped that someone of the Entware community with similar problems might have experience how to e.g. compile lirc with the respective drivers and would be willing to share that knowledge...

Thanks anyway,
Nix
