### ISSUE TITLE
dynamic-linker is not set for opkg binary

### ISSUE THREAD

**Issue by zyxmon** [Entware/entware#117]
To fix it modify MAKE_FLAGS. Add --dynamic-linker option to LDFLAGS or set
LDFLAGS="-Wl,--gc-sections $(TARGET_LDFLAGS)"

Please note, that in case of different architectures (https://github.com/zyxmon/qnapware) dynamic-linker may be different for architectures.

**Comment by zyxmon** [comment]
--dynamic-linker option is probably redundant for statically build opkg binary.

**Comment by ryzhovau** [comment]
Ok then.
