### ISSUE TITLE
Save old installation instead of deletion in Entware install script

### ISSUE THREAD

**Issue by TeHashX** [Entware/entware#119]
I reinstalled entware and I had a big surprise, old entware folder was deleted by the script and I lose all chrooted debian instalation, thanks to God my Media folder wasn't mounted in /debian/mnt
I modified the script to rename entware to entware-old+date instead of deleting, and can be deleted manually after :)
Please update and commit to asuswrt-merlin too.
Thanks
````
#!/bin/sh

BOLD="\033[1m"
NORM="\033[0m"
INFO="$BOLD Info: $NORM"
ERROR="$BOLD *** Error: $NORM"
WARNING="$BOLD * Warning: $NORM"
INPUT="$BOLD => $NORM"

i=1 # Will count available partitions (+ 1)
cd /tmp

echo -e $INFO This script will guide you through the Entware installation.
echo -e $INFO Script modifies only \"entware\" folder on the chosen drive,
echo -e $INFO no other data will be touched. Existing installation will be
echo -e $INFO replaced with this one. Also some start scripts will be installed,
echo -e $INFO the old ones will be saved on partition where Entware is installed
echo -e $INFO like /tmp/mnt/sda1/jffs_scripts_backup.tgz
echo 

if [ ! -d /jffs/scripts ]
then
  echo -e "$ERROR Please \"Enable JFFS partition\" & \"JFFS custom scripts and configs\""
  echo -e "$ERROR from router web UI: www.asusrouter.com/Advanced_System_Content.asp"
  echo -e "$ERROR then reboot router and try again. Exiting..."
  exit 1
fi

echo -e $INFO Looking for available  partitions...
for mounted in `/bin/mount | grep -E 'ext2|ext3' | cut -d" " -f3`
do
  isPartitionFound="true"
  echo "[$i] -->" $mounted
  eval mounts$i=$mounted
  i=`expr $i + 1`
done

if [ $i == "1" ]
then
  echo -e "$ERROR No ext2/ext3 partition available. Exiting..."
  exit 1
fi

echo -en "$INPUT Please enter partition number or 0 to exit\n$BOLD[0-`expr $i - 1`]$NORM: "
read partitionNumber
if [ "$partitionNumber" == "0" ]
then
  echo -e $INFO Exiting...
  exit 0
fi

if [ "$partitionNumber" -gt `expr $i - 1` ]
then
  echo -e "$ERROR Invalid partition number!  Exiting..."
  exit 1
fi

eval entPartition=\$mounts$partitionNumber
echo -e "$INFO $entPartition selected.\n"
entFolder=$entPartition/entware

if [ -d $entFolder ]
then
  echo -e "$WARNING Found previous installation, saving..."
  mv $entFolder $entFolder-old_`date +\%F_\%H-\%M`
fi
echo -e $INFO Creating $entFolder folder...
mkdir $entFolder

if [ -d /tmp/opt ]
then
  echo -e "$WARNING Deleting old /tmp/opt symlink..."
  rm /tmp/opt
fi
echo -e $INFO Creating /tmp/opt symlink...
ln -s $entFolder /tmp/opt

echo -e $INFO Creating /jffs scripts backup...
tar -czf $entPartition/jffs_scripts_backup_`date +\%F_\%H-\%M`.tgz /jffs/scripts/* >/dev/nul

echo -e "$INFO Modifying start scripts..."
cat > /jffs/scripts/services-start << EOF
#!/bin/sh

sleep 10
/opt/etc/init.d/rc.unslung start
EOF
chmod +x /jffs/scripts/services-start

cat > /jffs/scripts/services-stop << EOF
#!/bin/sh

/opt/etc/init.d/rc.unslung stop
EOF
chmod +x /jffs/scripts/services-stop

cat > /jffs/scripts/post-mount << EOF
#!/bin/sh

if [ \$1 = "__Partition__" ]
then
  ln -sf \$1/entware /tmp/opt
fi
EOF
eval sed -i 's,__Partition__,$entPartition,g' /jffs/scripts/post-mount
chmod +x /jffs/scripts/post-mount

echo -e "$INFO Starting Entware deployment....\n"
wget http://entware.wl500g.info/binaries/entware/installer/entware_install.sh
sh ./entware_install.sh
````

**Comment by zyxmon** [comment]
This script is a part of asuswrt. Probably Merlin is responsible for such modifications?

**Comment by YasharF** [comment]
Here is the script; it is part of the asuswrt-merlin project: https://github.com/RMerl/asuswrt-merlin/blob/91976ffe32efcb3054d94da7e0506e429de3f726/release/src/router/others/entware.mips/entware-setup.sh

**Comment by TeHashX** [comment]
I know where is it, I made a pull request

**Comment by YasharF** [comment]
What is the issue in entware project's scope that we need to fix up?

**Comment by TeHashX** [comment]
It's not related only to Merlin firmware

**Comment by YasharF** [comment]
If it is for entware-install.sh script, that is called at the end of entware-setup.sh in Merlin's firmware, then I think that is part of Tomato's firmware: https://github.com/tomatofirmware/tomato/blob/fd93c4a074e0a97d76235bd79399692af2417c7d/release/src/router/others/entware-install.sh

**Comment by YasharF** [comment]
Oh, I see your two pull requests to Merlin's:
https://github.com/TeHashX/asuswrt-merlin/commit/10e511f77a5559e1a245f44194c5de52da4382fc
https://github.com/TeHashX/asuswrt-merlin/commit/466f654c48e848a720a71d111aa1d305c35262f2

**Comment by YasharF** [comment]
I could be wrong, but looking at https://github.com/Entware/entware/wiki/USB-Storage-setup it looks like Merlin's AsusWRT is the only firmware with an automated simple install script.  The setup in the other firmwares are fairly manual and I can't see anything in the instructions that are removing the existing files.

**Comment by zyxmon** [comment]
This script is a part of AsusWRT. It prepares writable /opt folder and jffs scripts. The installation is done by a standard Entware script, that does not delete folders.
