### ISSUE TITLE
convert from entware-ng to entware

### ISSUE THREAD

**Issue by darkrain88** [Entware/Entware#119]
as we know Entware-ng and 3 have merged into Entware.

before i install Entware-ng through the following package:

x86-64 - http://pkg.entware.net/binaries/x86-64/Packages.html

now the new Entware use http://bin.entware.net to opkg update/

i want to know any method to update from entware-ng to entware directly without reinstall

just edit '/opt/etc/opkg.conf'  to change the source url, and run 'opkg update' , there are many non-compatible errors. 

thanks.

**Comment by zyxmon** [comment]
There is no official way to upgrade x64 Entware-ng to new Entware. There is a user script that does upgrade for Qnap but should also work for other devices - http://bin.entware.net/other/qnap_entware_ng_upgrade

Use it at your own risk, make a backup before you run the script.

**Comment by darkrain88** [comment]
basic  replace opkg.conf and run opkg update

**Comment by ryzhovau** [comment]
> basic replace opkg.conf and run opkg update

We consider clean installation instead of running any upgrade script. The consequences of upgrade by editing `opkg.conf` might be quite bad. Use at your own risk.

**Comment by zyxmon** [comment]
Do not forget to run script that creates missing symlinks in case you edited opkg.conf manually.
