### ISSUE TITLE
package request: wireshark (tshark)

### ISSUE THREAD

**Issue by kolyshkin** [Entware/Entware#12]
Wireshark (used to be known as Ethereal) is a tcpdump reborn with GUI, bells & whistles. tshark is its CLI component, a modern replacement/alternative to tcpdump CLI (with more features, like decoders for various protocols that tcpdump is not aware of). tshark was (still is) available from optware, so it was a surprise for me it's not in entware.

> Platform

ASUS RT-68U with Tomato by Shibby, ASUS RT-68U with Merlin.

**Comment by ryzhovau** [comment]
Dozen of dependencies, 70+ megabytes of files. Looks monstrous for embedded devices, but... can be handy in some cases.
