### ISSUE TITLE
scanlogd

### ISSUE THREAD

**Issue by Magissia** [Entware/Entware#121]
Package request
---
Detecting ports scan

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I successfully tested added package on my {platform}.

---
[Documentation](http://www.openwall.com/scanlogd/scanlogd.8.shtml)
[Source](http://cvsweb.openwall.com/cgi/cvsweb.cgi/Owl/packages/scanlogd/scanlogd/)

**Comment by ryzhovau** [comment]
It's abandoned 12 years ago.
