### ISSUE TITLE
'iw' command implementation -> reopen old issue?

### ISSUE THREAD

**Issue by Triaholgi** [Entware/Entware#123]
Package request
---
{iw: configuration of wifi interfaces}

Not sure if a comment in an already closed issue will be seen. Pls review my issue here:
[https://github.com/Entware/Entware/issues/30]

**Comment by ryzhovau** [comment]
I'm closing this with the same reason: there's no unified interfaces to control wi-fi modules on embedded devices, it's very vendor specific.
