### ISSUE TITLE
Update rrdtool to version > 1.3

### ISSUE THREAD

**Issue by stevedh42** [Entware/Entware#124]
Could you please update 

rrdtool to a version > 1.3
currently it is on 1.2.30-3a  and 1.7 is available and need > 1.3 for cacti

Could you please update bin.entware.net/armv5sf-k3.2/Packages.gz package

Thanks

**Comment by ryzhovau** [comment]
We use the last version without Cairo/Pango libs dependencoes, which are X libs depended on even more X libs and X configurations.
