### ISSUE TITLE
Broken uClibc patches

### ISSUE THREAD

**Issue by alllexx88** [Entware/entware#126]
ryzhov_al,
According to your suggestion, I tried your uClibc patches to make firmware independent toolchain to build an Optware feed with. However, after rebuilding the entire feed, I discovered that these patches don't really work. After looking a little closer at them, I think I found some simple mistakes. To my understanding, your patches need this kind of a fix:

http://pastebin.com/BBHkAXP1

**Comment by ryzhovau** [comment]
Thank you! This bug was still undiscovered because we aren't used `/opt/X11R6/lib` before.

**Comment by alllexx88** [comment]
You're welcome! This is a little bit outside of your domain, but for some reason these patches don't work the way they should in my case. I've patched uClibc, re-built toolchain, re-built the feed, and yet I discover that /lib/ld-uClibc.so.0 is being hardcoded into executables, leading to undesired behaviour. Another thing I'm trying now is setting RUNTIME_PREFIX="/opt/" in uClibc config instead of patching. Also, I see that in your toolchain HARDWIRED_ABSPATH in uClibc Library Installation Options is disabled, I'll try to disable it as well (have it enabled now). Sorry for off-topic

**Comment by ryzhovau** [comment]
It's not enough. You have to add some [options](https://github.com/Entware/entware/blob/master/buildroot/patches/rules.patch#L20) for linker too.

>  Sorry for off-topic
It's OK. Glad to help.

**Comment by alllexx88** [comment]
Great, this '-Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.0' option is precisely what I needed! You've made my day, thank you!
