### ISSUE TITLE
Entware MSMTP error Bad value for ai_flags' exitcode=EX_NOHOST

### ISSUE THREAD

**Issue by KernelPicnic** [Entware/entware#127]
This issue causes msmtp to exit prematurely with error status below.

Mar 01 23:31:43 host=smtp.gmail.com tls=on auth=on user=from@gmail.com from=admin recipients=to@gmail.com errormsg='cannot locate host smtp.gmail.com: Bad value for ai_flags' exitcode=EX_NOHOST

If you google it seems to have appeared in late Dec '14, and there are several recommendations for "--disable-gai-idn"

**Comment by ryzhovau** [comment]
msmtp has been recompiled with `--disable-gai-idn`, anyway, IDN was disabled by `--without-libidn` before.
```
opkg update
opkg upgrade
```
 If you still receive the this error message, please, [add an issue](https://github.com/openwrt/packages/issues) for OpenWrt guys.

**Comment by ryzhovau** [comment]
Got [feedback](wl500g.info/showthread.php?28036&p=268315#post268315) (in russian) about it. 
Fixed.

**Comment by KernelPicnic** [comment]
Tested and works! Now I can email voicemails from my router/pbx :D
Bolshoi Spasiba! (sorry dont have cyrillic fonts) Thank you for your fast
response!
Brian

On Wed, Mar 4, 2015 at 1:57 AM, Alexander Ryzhov <notifications@github.com>
wrote:

> msmtp has been recompiled with --disable-gai-idn, anyway, IDN was
> disabled by --without-libidn before.
>
> opkg update
> opkg upgrade
>
> If you still receive the this error message, please, add an issue
> <https://github.com/openwrt/packages/issues> for OpenWrt guys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Entware/entware/issues/127#issuecomment-77111341>.
>



-- 
Brian Chostner
Email: brian.chostner@gmail.com
Mobile: 314 308 7362
