### ISSUE TITLE
CUPS PDF Filters

### ISSUE THREAD

**Issue by mrengles** [Entware/entware#128]
Hello,

This ticket is not so much an issue, but a package request. Can you please add a PDF Filter for the CUPS print server? If one wants to setup an AirPrint server (CUPS/Avahi/Python) a PDF filter is needed so the iOS Devices can print.

Please consider this request, and thanks for your development.

Gratitude,

Robert aka Mrengles

**Comment by token0** [comment]
I want to mention that there are no mips or arm ppd drivers for some printers.

**Comment by zyxmon** [comment]
cups-pdf for entware.arm is here (test version) 
http://qnapware.zyxmon.org/binaries-armv7/test/cups-pdf_3.0beta2-1_armv7soft.ipk
I was asked to build the package on smallnetbuilder forum.
In case on needs it for mips, here is the Makefile with patches
http://qnapware.zyxmon.org/binaries-armv7/test/cups-pdf.tar.gz

**Comment by mrengles** [comment]
Thank you zyxmon & ryzhovau!

**Comment by mrengles** [comment]
@zyxmon @ryzhovau  The cups-pdf package installs correctly, however its missing the actually pdf filters such as pdftops. With the right filters I'm pretty sure AirPrint and pdf printing will work. More info about the filters at the link below.

http://www.linuxfoundation.org/collaborate/workgroups/openprinting/pdf_as_standard_print_job_format
http://www.openprinting.org/download/cups-filters/

Thanks!

**Comment by zyxmon** [comment]
Openwrt Makefile (2 years old) for cups-filters is here - https://github.com/FranciscoBorges/openwrt-printing-packages/tree/master/net/openprinting-cups-filters
I'm afraid this package depends on other new packages. May be openwrt team must be responsible for such a bundle of packages?

**Comment by mrengles** [comment]
I see the cups-filters package, actually had it installed but It's just super old. I guess openwrt would need to upgrade to a newer release that supports pdf? Is that what your saying? Thanks again!

**Comment by zyxmon** [comment]
>>  Is that what your saying?

No. Making cups-pdf was easy. No it needs  cups-filters (not part of openwrt).  cups-filters depend on libijs poppler qpdf (not in openwrt). This packages may depend on other packages, that are not part of openwrt. To many new packages. One needs to understand how they work together. So it is a task for openwrt maintainers.

**Comment by mrengles** [comment]
Oaky I understand now. Thanks for all of the help guys!

**Comment by ryzhovau** [comment]
Package has been added 00be14a38430a047726c3132af6664103dac0e5c. Closing for now.

@zyxmon, I've included appropriate *.pdd files too.

**Comment by mrengles** [comment]
Thanks @zyxmon  and @ryzhovau I was just going to post the OpenWRT Printing Packages github link here but it looks like you already have. Thanks again!
