### ISSUE TITLE
nginx with option '--with-ipv6 ' support

### ISSUE THREAD

**Issue by darkrain88** [Entware/Entware#128]
Package request
---
{Describe killer feature of package}

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I successfully tested added package on my {platform}.

since ipv6  is coming soon in most place,  

i run nginx -V, i cant find '--with-ipv6' in the output

would you please compile a new nginx with '--with-ipv6' support.

many thanks.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
Please, search harder:)

**Comment by darkrain88** [comment]
root@Openwrt:~# nginx -V
nginx version: nginx/1.14.0
built by gcc 7.3.0 (OpenWrt GCC 7.3.0 r626-0e46861)
built with OpenSSL 1.0.2o  27 Mar 2018
TLS SNI support enabled
configure arguments: --crossbuild=Linux::x86_64 --with-cc=x86_64-openwrt-linux-gnu-gcc --with-cc-opt='-I                             /media/ware3/Entware.2018.05/staging_dir/target-x86_64_glibc-2.27/opt/include -I/media/ware3/Entware.201                             8.05/staging_dir/toolchain-x86_64_gcc-7.3.0_glibc-2.27/include -O2 -pipe -fomit-frame-pointer -fno-calle                             r-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -I/media/ware3/Entwar                             e.2018.05/staging_dir/target-x86_64_glibc-2.27/opt/include/libxml2 -Wno-error=parentheses -Wno-error=imp                             licit-fallthrough' --with-ld-opt='-L/media/ware3/Entware.2018.05/staging_dir/target-x86_64_glibc-2.27/op                             t/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link=/media/ware3/Entware.2018.05/staging_dir/target-x86_64_glibc-2                             .27/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux-x86-64.so.2 -L/media/ware3/Entware.2018.05/staging_di                             r/toolchain-x86_64_gcc-7.3.0_glibc-2.27/lib -lxml2' --prefix=/opt --conf-path=/opt/etc/nginx/nginx.conf                              --http-log-path=/opt/var/log/nginx/access.log --error-log-path=/opt/var/log/nginx/error.log --lock-path=                             /opt/var/lock/nginx.lock --pid-path=/opt/var/run/nginx.pid --modules-path=/opt/lib/nginx --http-client-b                             ody-temp-path=/opt/var/lib/nginx/body --http-fastcgi-temp-path=/opt/var/lib/nginx/fastcgi --http-proxy-t                             emp-path=/opt/var/lib/nginx/proxy --http-scgi-temp-path=/opt/var/lib/nginx/scgi --http-uwsgi-temp-path=/                             opt/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_modu                             le --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_modul                             e --with-http_slice_module --without-http_upstream_zone_module --without-stream_upstream_zone_module --w                             ith-http_addition_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module                              --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_random_index_module --with-h                             ttp_secure_link_module --with-http_sub_module --with-http_xslt_module=dynamic --with-mail=dynamic --with                             -mail_ssl_module --with-stream=dynamic --with-stream_ssl_module --add-dynamic-module=/media/ware3/Entwar                             e.2018.05/build_dir/target-x86_64_glibc-2.27/nginx-1.14.0/modules/http-headers-more-filter --add-dynamic                             -module=/media/ware3/Entware.2018.05/build_dir/target-x86_64_glibc-2.27/nginx-1.14.0/modules/http-auth-p                             am --add-dynamic-module=/media/ware3/Entware.2018.05/build_dir/target-x86_64_glibc-2.27/nginx-1.14.0/mod                             ules/http-cache-purge --add-dynamic-module=/media/ware3/Entware.2018.05/build_dir/target-x86_64_glibc-2.                             27/nginx-1.14.0/modules/http-dav-ext --add-dynamic-module=/media/ware3/Entware.2018.05/build_dir/target-                             x86_64_glibc-2.27/nginx-1.14.0/modules/http-ndk --add-dynamic-module=/media/ware3/Entware.2018.05/build_                             dir/target-x86_64_glibc-2.27/nginx-1.14.0/modules/http-echo --add-dynamic-module=/media/ware3/Entware.20                             18.05/build_dir/target-x86_64_glibc-2.27/nginx-1.14.0/modules/http-fancyindex --add-dynamic-module=/medi                             a/ware3/Entware.2018.05/build_dir/target-x86_64_glibc-2.27/nginx-1.14.0/modules/nchan --add-dynamic-modu                             le=/media/ware3/Entware.2018.05/build_dir/target-x86_64_glibc-2.27/nginx-1.14.0/modules/http-lua --add-d                             ynamic-module=/media/ware3/Entware.2018.05/build_dir/target-x86_64_glibc-2.27/nginx-1.14.0/modules/rtmp                              --add-dynamic-module=/media/ware3/Entware.2018.05/build_dir/target-x86_64_glibc-2.27/nginx-1.14.0/module                             s/http-uploadprogress --add-dynamic-module=/media/ware3/Entware.2018.05/build_dir/target-x86_64_glibc-2.                             27/nginx-1.14.0/modules/http-upstream-fair --add-dynamic-module=/media/ware3/Entware.2018.05/build_dir/t                             arget-x86_64_glibc-2.27/nginx-1.14.0/modules/http-subs-filter

**Comment by ryzhovau** [comment]
Got it, you've got `nginx-extras` package. Plain `nginx` built with IPv6 support.

**Comment by ryzhovau** [comment]
`--with-ipv6` is [deprecated](http://hg.nginx.org/nginx/rev/a6d116645c51) since 1.11.5+ and IPv6 support is compiled in unless it not disabled manually. Just tried on MIPSEL router, works fine:
```
# opkg install nginx-extras
# mcedit /opt/etc/nginx.conf
# /opt/etc/init.d/S80nginx start
# netstat -tlpn | grep 5380
tcp        0      0 0.0.0.0:5380            0.0.0.0:*               LISTEN      17487/nginx: master
tcp        0      0 :::5380                 :::*                    LISTEN      17487/nginx: master
```

**Comment by darkrain88** [comment]
thanks
