### ISSUE TITLE
Support for MIPSEL kernel 3.0

### ISSUE THREAD

**Issue by J0s3f** [Entware/Entware#130]
Do you plan to provide a repository for MIPSEL devices with kernel 3.0?

**Comment by zyxmon** [comment]
We do support kernel 3.4 for mips and mipsel.

**Comment by J0s3f** [comment]
Yes, but do you plan to ever support kernel 3.0?

**Comment by ryzhovau** [comment]
No, there's no plans to add any other toolchains.
