### ISSUE TITLE
FreeRADIUS cannot be started anymore with new OpenSSL libs

### ISSUE THREAD

**Issue by procopius** [Entware/entware#130]
When started like "/opt/sbin/radiusd -X" it says:

"libssl version mismatch.  built: 100010af linked: 1000200f"

Please recompile FreeRADIUS.

**Comment by ryzhovau** [comment]
Works for me. Please, reinstall package.

**Comment by procopius** [comment]
# ls -l /opt/sbin/radiusd ; md5sum /opt/sbin/radiusd 
-rwxr-xr-x    1 root     root        317428 Dec 18 14:26 /opt/sbin/radiusd
584b2805588b7c67cdce6805faecdacf  /opt/sbin/radiusd

(ipkg file downloaded by hand and unpacked:)
# ls -l opt/sbin/radiusd ; md5sum opt/sbin/radiusd 
-rwxr-xr-x    1 root     root        317428 Feb 24 13:12 opt/sbin/radiusd
4942c88fcbed6121342988d0f31585cb  opt/sbin/radiusd

# opkg list-installed | grep freeradius2
freeradius2 - 2.2.6-1
...

# opkg list | grep freeradius2
freeradius2 - 2.2.6-1 - A flexible RADIUS server (version 2)
...

Since installed FreeRADIUS package is 2.2.6-1 and downloaded one ALSO 2.2.6-1, but opt/sbin/radiusd binares are different, I cannot see how opkg can know when to update FreeRADIUS packages. What is the point of having versions of packages than in the first place then?

**Comment by ryzhovau** [comment]
> Since installed FreeRADIUS package is 2.2.6-1 and downloaded one ALSO 2.2.6-1, but opt/sbin/radiusd binares are different, I cannot see how opkg can know when to update FreeRADIUS packages. 

Every package in repo is being recompiled during [per-month update](https://github.com/Entware/entware/wiki/Changelog). It's normal (and necessary) part of update process both for OpenWrt trunk and for Entware.

> What is the point of having versions of packages than in the first place then?

Nor me, nor OpenWrt is going to increment version number with every build. You may fall into this issue with `freeradius2-*` and `asterisk*` packages from time to time.

**Comment by procopius** [comment]
Good to know that. I have been under impression that opkg update ; opkg upgrade will do the right thing. Is there any workaround except reinstalling all entware packages every month?

**Comment by ryzhovau** [comment]
> Is there any workaround except reinstalling all entware packages every month?

Only Optware or some other conservative repo, where packages are not updated too often.
