### ISSUE TITLE
Package request: Exim

### ISSUE THREAD

**Issue by basti122303** [Entware/Entware#131]
Package request Exim
---
Exim is a message transfer agent (MTA). Its more flexible then Postfix. You an also include Perl scripts on runtime. 

- No similar package already added and/or this one got some new killer feature(s),

**Comment by basti122303** [comment]
I have  build it on QNAP-TS231P with a minimal set of options. I cant build-in Perl.

**Comment by ryzhovau** [comment]
We've got working package, but no one can test it. Closing for now.
