### ISSUE TITLE
OpenVPN startup script

### ISSUE THREAD

**Issue by oldgringo** [Entware/entware#131]
tun.ko is never in the folder /opt/lib/modules but /opt/lib/modules/2.6.22.19/kernel/drivers/net
'insmod tun.ko' is enough, complete path is wrong

**Comment by ryzhovau** [comment]
This is firmware-depended, so I can't say where it is in current installation.
May be I have to comment this out if it's confusing users. I'll do it when somebody will add a similar issue. Closing for now.
