### ISSUE TITLE
Help: /opt/etc/init.d/rc.unslung[38]: sort: not found

### ISSUE THREAD

**Issue by alienx2** [Entware/Entware#133]
```
root@rk3188:/opt/etc/init.d # /opt/etc/init.d/rc.unslung start
/opt/etc/init.d/rc.unslung[38]: sort: not found
```

```
root@rk3188:/opt/etc/init.d # uname -a
Linux localhost 3.0.36+ #175 SMP PREEMPT Thu May 22 11:44:15 CEST 2014 armv7l GNU/Linux
```

After i installed entware kernel 2.6 on Android TV box successfully, but one problem is ‘rc.unslung' wont start.

**Comment by ryzhovau** [comment]
Looks like you installed Busybox without `sort` applet.

**Comment by zyxmon** [comment]
Entware installation script installs findutils package as a dependency. It looks like you have not used installation script or installation failed.
