### ISSUE TITLE
Mosquitto (MQTT) support

### ISSUE THREAD

**Issue by snoowman** [Entware/entware#134]
In OpenWrt there are couple libraries that support MQTT.  
libmosquitto - 0.15-1
mosquitto-client - 0.15-1

It would be nice to have feature parity.
MQTT provides a lightweight method of carrying out messaging using a publish/subscribe model.
Mosquitto is an open source (BSD licensed) message broker that implements MQTT protocol.

This enable the router to send/receive information to/from a message broker.

Possible use case:
Instead of SNMP poll router for stats we can push information to the cloud with guarantee delivery.

**Comment by ryzhovau** [comment]
To be continued here - https://github.com/Entware-ng/Entware-ng/issues/5
