### ISSUE TITLE
Package request: ddclient

### ISSUE THREAD

**Issue by keith555** [Entware/Entware#135]
Please consider adding ddclient. It's a fairly straightforward perl installation.
ddclient is a dynamic dns client used to update a dns nameserver with a dynamic a ip address. Very handy for assigning a domain name to a NAS which has a dynamic ip address.

https://github.com/ddclient/ddclient

**Comment by ryzhovau** [comment]
It's just a perl script. Did you tried to run it on NAS?

**Comment by keith555** [comment]
OK. I'll do that.
