### ISSUE TITLE
OpenFlow/OpenVSwitch Support

### ISSUE THREAD

**Issue by JGrana01** [Entware/entware#135]
I have been looking into the possibility of having OpenFlow support for the Asuswrt routers. There are a few projects that have used DD-WRT but I am having a tough time with the build environment.
This project implement OpenVswitch which could be very useful in a home router, especially for those of us that work at home:
http://archive.openflow.org/wk/index.php/UoR_:_Openflow_Kernel_space_on_DD-WRT#What_is_needed 
Any chance someone more skilled at cross development would want to give it a shot?

**Comment by ryzhovau** [comment]
> OpenFlow is implemented as a loadable kernel module based on OpenvSwitch.

No, sorry. Entware is a firmware independent repo, so no any kernel modules can be added here.
