### ISSUE TITLE
Samba4 nmbd missing.

### ISSUE THREAD

**Issue by AceStrider1** [Entware/Entware#136]
Hi all,

I am using entware for mipssf-k3.4

About a week ago I installed Samba 4 using opkg install samba4x-server.   Today it has changed to install samba4-server.  I also noticed that on the new package the nmbd executable in not included.

**Comment by zyxmon** [comment]
This is now default in openwrt. Here is an explanation:
https://github.com/Entware/entware-packages/blob/master/net/samba4/Config.in#L69
