### ISSUE TITLE
Update Package Request - rrdtool

### ISSUE THREAD

**Issue by ondrej-bartos** [Entware/entware#136]
Hello,

is there any specific reason that rrdtool is provided with 1.2 version only? http://oss.oetiker.ch/rrdtool/pub/?M=D provides even 1.5. There some fixes in higher than 1.2 I'd like to use.

thanks,

**Comment by ryzhovau** [comment]
Hi.
The reason is [OpenWrt package](https://github.com/Entware/openwrt-oldpackages/commits/master/utils/rrdtool), which was ported to Entware. I don't know why they [support](https://github.com/openwrt/packages/tree/master/utils/rrdtool1) rrdtool 1.0.50 and abandoned 1.2.30.

**Comment by ondrej-bartos** [comment]
i am sorry, but can we take rrdtool from other sources and port it here? or is there any reason why this is not possible?

**Comment by ryzhovau** [comment]
I'll plan to update it next week. I'm just in the middle of updating those abandoned OpenWrt packages from `oldpackages` feed.

**Comment by ryzhovau** [comment]
Unfortunately, 1.2.30 is the last version without Cairo/Pango dependencies — a X libs, depending on even more X libs and X configurations. 

1.2.30 stays here for the long times.
