### ISSUE TITLE
Tinyproxy - Enable reverse proxying

### ISSUE THREAD

**Issue by cminois** [Entware/Entware#137]
Hi,

Could you modify the configuration of the Tinyproxy package to enable reverse proxying?
Adding --enable-reverse argument in the makefile should do it.

Thanks.

**Comment by ryzhovau** [comment]
`tinyproxy` came from [upstream](https://github.com/openwrt/packages/tree/master/net/tinyproxy) without any modifications. Please, send this issue to OpenWrt guys.
