### ISSUE TITLE
Nano syntax highlighting files removed?

### ISSUE THREAD

**Issue by jerrm** [Entware/entware#139]
Was this intentional?  Am I missing something?

Thanks...

**Comment by YasharF** [comment]
Hi @jerrm ,
Can you provide more details on what you are referring to?

Thanks

**Comment by jerrm** [comment]
The http://entware.wl500g.info/binaries/entware/archive/nano_2.2.6-1b_entware.ipk package includes the /opt/etc/nanorc config file and /opt/share/nano/*.nanorc syntax definition files.  These files are missing in the current package.

**Comment by ryzhovau** [comment]
To be continued here - https://github.com/Entware-ng/Entware-ng/issues/8
