### ISSUE TITLE
Collectd

### ISSUE THREAD

**Issue by ryzhovau** [Entware/entware#14]
https://code.google.com/p/wl500g-repo/issues/detail?id=311

---
Collectd is a modular daemon which collects system performance data and provides mechanisms to store the values in a variety of ways.

http://collectd.org/

I am running Merlin's build on my ASUS RT-N66U.  I have setup graphite on a separate server and would like to feed it data from the router.  I haven't looking into how to build for Entware yet as time is tight right now.

Ideally I'd like to track the standards (CPU, memory, interfaces, etc), plus maybe ip-tables, and others -- there are quite a few.  I would also require the network plugin to send to graphite.  Not sure if each collectd plugins must be compiled separately...

**Comment by YasharF** [comment]
OpenWRT package feed - collectd: https://github.com/openwrt/packages/blob/085e028855d59f2cbcfc079f4ac5dcb1b0b59cad/utils/collectd

**Comment by ryzhovau** [comment]
Closing for now. If it's  still necessary, please add a new issue here - https://github.com/Entware-ng/Entware-ng/issues
