### ISSUE TITLE
Package request : museek+

### ISSUE THREAD

**Issue by vlotho** [Entware/Entware#14]
hi,

**Package: museek+**

Museek+ is a GPL licensed file-sharing application for the ​Soulseek peer-to-peer network.

http://www.museek-plus.org

Soulseek is an ad-free, spyware free, just plain free file sharing network for Windows, Mac and Linux. Our rooms, search engine and search correlation system make it easy for you to find people with similar interests, and make new discoveries!

http://www.slsknet.org/news/

**Platform:**

i use the adm asustor platform (x86_64) AS3104T

**Comment by ryzhovau** [comment]
Requires bunch of gnome libraries as sub-dependencies, which I'm not ready to port.

* libxml++ 3.0,
 * sigc++-3.0,
* GLib 2.59.2,
* GObject 2.59.2,
* GModule 2.59.2

and some other.
