### ISSUE TITLE
Squid 3.x Issues

### ISSUE THREAD

**Issue by jerrm** [Entware/entware#140]
I had a few issues with the new squid packages.  

For the sake of others I am posting here. Delete if inappropriate.

This was all  running on Tomato Shibby 128.

1: Permissions for /opt/etc/squid/mime.conf should be 444.  This is probably the item here that could be addressed by the Entware team.

2: The Squid 3.5.2 package needs  "chmod 777 /dev/shm" in Tomato before Squid will run.  Not really sure what Entware could do about this.

3: Seems Squid's IPv6 support doesn't play well with Tomato. I have not tested all IPv6 scenarios or other platforms, but the solution is to bind the intercept port only to an IPv4 address.

In squid.conf, instead of: http_port 3129 intercept

Use(edited to use a valid IP): http_port 192.168.1.1:3129 intercept

I don't know if this is a Tomato-ism, Entware-ism, or general squid-ism. I didn't see this as an issue in any google search though, so would assume it is not a general squid problem

For the sake of search engines, Squid was reporting: ERROR: NF getsockopt(ORIGINAL_DST) failed on local=10.10.10.1:3128 remote=10.10.10.10:59290 FD 15 flags=33: (99) Protocol not available

**Comment by ryzhovau** [comment]
That's not a right place for HOW-TO instructions. You can add a wiki page if you wish.
If nr3 will be confirmed by other users, I'll reopen this issue.

**Comment by jerrm** [comment]
I'll keep the wiki in mind.  These are all issues Entware could choose to (or not to) address. I'm OK either way,

My primary goal of giving google something to find for others has been achieved.
