### ISSUE TITLE
Error p7zip: not decompress iso file, help me

### ISSUE THREAD

**Issue by vinhpaint** [Entware/Entware#140]
Scanning the drive for archives 1 file, 7516979200 bytes (7169 MiB) 
Extracting archive: asia47.iso 
ERROR: asia47.iso 
Can not open the file as archive 
Can't open as archive: 1 
Files: 0 
Size: 0
Compressed: 0

**Comment by ryzhovau** [comment]
That's not a full `7zip`, it's a `7za`. 
https://github.com/tehmul/p7zip-zstd/blob/master/p7zip_16.02/README#L12
