### ISSUE TITLE
Rubygem detection script causing #! interpreter selector in scripts to fail

### ISSUE THREAD

**Issue by codyit** [Entware/entware#141]
admin@host:/tmp/home/root# gem
>/opt/bin/gem: line 8: require: not found
>...
>/opt/bin/gem: line 22: rescue: not found
>/opt/bin/gem: exit: line 23: Illegal number: e.exit_code

And it's leaking a file "e", looks dangerous to me :E
>admin@host:/tmp/home/root# ls
>e

To fix:
>mv /opt/bin/ruby ruby.bug
>ln -s /opt/lib/ruby/ruby2.2-bin /opt/bin/ruby

**Comment by codyit** [comment]
And I'm getting this..
>admin@host:/tmp/home/root# gem help install
>ERROR:  Loading command: install (LoadError)
>	failed to load encoding (Windows-31J)
>ERROR:  While executing gem ... (NoMethodError)
>    undefined method `invoke' for nil:NilClass

It might belong to the forum but it's in Russian only and hey it means the package ruby-gems doesn't work so it's an issue.

**Comment by ryzhovau** [comment]
This bug is still present and I still have no graceful solution for that.

**Comment by zyxmon** [comment]
Try to install 'opkg install ruby-enc-extra'

**Comment by ryzhovau** [comment]
Fixed in Entware-ng. Please, provide feedback [here](https://github.com/Entware-ng/Entware-ng/issues) if necessary.
