### ISSUE TITLE
multiple php version

### ISSUE THREAD

**Issue by hcollini** [Entware/Entware#141]
Package request
---
Should very useful to have multiple version of php. so we can assign a specific version to a specific web site.
I have asked qnap support if I can use the build in php 5.6 with a php7 from Entware but they are very unfair to people that ask them such type of question giving only the answer "it is an appliance that you cannot modify".
The same request can be applied to the different version of php7  (7.0, 7.1, 7.2 etc)
I've alse noticed that the actual binary of php7-fpm module is named php-fpm as the QNAP integrated and this make it impossible to execute them at the same time.

**Comment by zyxmon** [comment]
There is no package request present. Closing. Try to use different php versions yourself.
