### ISSUE TITLE
Package request: simpleproxy (aka. Simple-TCP-proxy)

### ISSUE THREAD

**Issue by lars18th** [Entware/Entware#142]
https://github.com/vzaliva/simpleproxy

Very small TCP "redirector" with HTTP proxy tunnel support with authentication.
Similar to others like 3proxy, but more lightweight!

Please consider to add it.

**Comment by ryzhovau** [comment]
What's the killer feature of `simpleproxy`? 
I see no sense to add several packages with similar purpose, sorry. There's already bunch of proxies present: `tinyproxy`, `haproxy`, `privoxy`, `redsocks`, `dante`, `srelay` and so on.

**Comment by lars18th** [comment]
> What's the killer feature of simpleproxy?

+ Very, very small TCP redirector! Just only a few KBs for the binary.
+ Not an HTTP proxy, so direct TCP redirection that is more fast than a web proxy.
+ Supports the connection through an HTTP proxy... and with BASIC Authentication (this feature is unique in TCP redirectors).

> I see no sense to add several packages with similar purpose, sorry. There's already bunch of proxies present: tinyproxy, haproxy, privoxy, redsocks, dante, srelay and so on.

- tinyproxy: fully HTTP proxy, not a TCP redirector.
- haproxy: fat HTTP proxy.
- privoxy: HTTP proxy... small as simpleproxy, but isn't a _redirector_.
- redsocks: need iptables to work, it can run standalone.
- dante: SOCKS proxy, not TCP relayer.
- srelay: SOCKS proxy, not TCP relayer.
- etc. etc. etc.

So, please forget the "proxy" part of the name. This piece of code can be named "Simple-TCP-redirector", like when you use SSH for stablishing TCP tunnels.

**Comment by ryzhovau** [comment]
> haproxy: fat HTTP proxy.

See `mode tcp`.  So, there's at least couple of packages with similar purpose and the only `simpleproxy` killer feature is the binary size. Still not sure it will be useful, sorry.

**Comment by lars18th** [comment]
Hi @ryzhovau ,

Thank you for your feedback. This project is amazing, and your work is great.

>>haproxy: fat HTTP proxy.

>See mode tcp. So, there's at least couple of packages with similar purpose and the only simpleproxy killer feature is the binary size. Still not sure it will be useful, sorry.

It's true. The `haproxy` can work as a TCP redirector (when using the reverse proxy mode). Futhermore, the well known `nginx` can do it as well. However, these projects are FAT... very fat. But, for a very simple, small and fast TCP redirection no more simple than this project exists. Even with the added killer functionality of pass through an HTTP proxy with user/pass Authentication.

Please, take note that the source of this project is very simple. It compiles in a lot of platforms. And all regular Linux distributions include it in the standalone repos. So support it can be very easy.

Futhermore, the target of the ENT-WARE project isn't small devices?
In this case, an small footprint is a must have!

Thus, please consider it. :wink: 
Thank you!

**Comment by ryzhovau** [comment]
No more TCP/UPD/HTTP proxies, sorry.

Consider using one of already available.
