### ISSUE TITLE
msmtp Bad value for ai_flags

### ISSUE THREAD

**Issue by stavultras** [Entware/entware#142]
After end of April updates msmtp broken [again](http://wl500g.info/showthread.php?28036-Entware-%ED%EE%E2%FB%E9-%F0%E5%EF%EE%E7%E8%F2%EE%F0%E8%E9-%E4%EB%FF-%F0%EE%F3%F2%E5%F0%EE%E2-(MIPS)&p=268315#post268315) with error:
sendmail: cannot locate host smtp.yandex.ru: Bad value for ai_flags
sendmail: could not send mail (account default from /opt/etc/msmtprc)

msmtp version 1.6.1

**Comment by ryzhovau** [comment]
Fixed, please, provide a feedback.

**Comment by stavultras** [comment]
All works good. Thank you.
