### ISSUE TITLE
squid 3.5.2  does not start at all on N65U (Padavan)

### ISSUE THREAD

**Issue by escot** [Entware/entware#143]
squid does not start (regardless of options, even with "-z"):

==============================================
2015/04/29 15:53:47.741| main.cc(1426) SquidMain: running RegisteredRunner::finalizeConfig
2015/04/29 15:53:47.741| main.cc(1427) SquidMain: running RegisteredRunner::claimMemoryNeeds
2015/04/29 15:53:47.742| main.cc(1428) SquidMain: running RegisteredRunner::useConfig
2015/04/29 15:53:47.743| mem/Segment.cc(94) create: shm_open /squid-cf__metadata.shm: (2) No such file or directory
2015/04/29 15:53:47.744| tools.cc(543) leave_suid: leave_suid: PID 19331 called
2015/04/29 15:53:47.744| storeDirWriteCleanLogs: Starting...
2015/04/29 15:53:47.744|   Finished.  Wrote 0 entries.
2015/04/29 15:53:47.744|   Took 0.00 seconds (  0.00 entries/sec).
FATAL: Ipc::Mem::Segment::create failed to shm_open(/squid-cf__metadata.shm): (2) No such file or directory

Squid Cache (Version 3.5.2): Terminated abnormally.
==============================================

The previous version ( squid_3.4.11-2_entware.ipk)   worked fine.

**Comment by jerrm** [comment]
See item #2 on my post: https://github.com/Entware/entware/issues/140

**Comment by ryzhovau** [comment]
@escot, the same on RT-N66U, asuswrt-merlin. You have to `chmod 777 /dev/shm` before starting squid.
```
admin@RT-N66U:/tmp/mnt/OPT/tmp# squid -z
2015/07/23 20:37:37| storeDirWriteCleanLogs: Starting...
2015/07/23 20:37:37|   Finished.  Wrote 0 entries.
2015/07/23 20:37:37|   Took 0.00 seconds (  0.00 entries/sec).
FATAL: Ipc::Mem::Segment::create failed to shm_open(/squid-cf__metadata.shm): (13) Permission denied

admin@RT-N66U:/tmp/mnt/OPT/tmp# chmod 777 /dev/shm
admin@RT-N66U:/tmp/mnt/OPT/tmp# squid -z
admin@RT-N66U:/tmp/mnt/OPT/tmp# 2015/07/23 20:37:56 kid1| Current Directory is /tmp/mnt/OPT/tmp
2015/07/23 20:37:56 kid1| Creating missing swap directories
2015/07/23 20:37:56 kid1| No cache_dir stores are configured.
```

**Comment by fungijus** [comment]
при настройке squid в системном журнале вылезает ошибка

syslog: Ipc::Mem::Segment::create failed to shm_open(/squid-cf__metadata.shm): (2) No such file or directory
в папке /dev  shm нет , что делать помогите
раньше старый squid 2.7 заводился без проблем. но его увы нет.

**Comment by ryzhovau** [comment]
See my post above.

**Comment by 1951FDG** [comment]
Running `chmod 777 /dev/shm/` allows squid to run, but this is probably not a good solution, and gets reset every reboot. Is there a better fix/workaround that is permanent?

**Comment by 1951FDG** [comment]
Found a good solution:
`sed -i '/PREARGS=""/a PRECMD="chmod 777 /dev/shm"' /opt/etc/init.d/S22squid`
