### ISSUE TITLE
dnscrypt-proxy "hostip" not included in the ipkg-entware

### ISSUE THREAD

**Issue by leandroong** [Entware/entware#144]
hostip is compiled but not installed. Is this not needed anymore?

**Comment by ryzhovau** [comment]
It's in separate package:
```
opkg install hostip
```

**Comment by leandroong** [comment]
you miss 2 lines
define Package/dnscrypt-proxy/install
	$(INSTALL_DIR) $(1)/opt/bin
	$(CP) $(PKG_INSTALL_DIR)/opt/bin/hostip $(1)/opt/bin/
	$(INSTALL_DIR) $(1)/opt/sbin
.....

**Comment by ryzhovau** [comment]
Please, read my comment above again: dnscrypt [was split](https://github.com/Entware/openwrt-packages/blob/master/net/dnscrypt-proxy/Makefile) into two packages.
