### ISSUE TITLE
blkid busybox applet does not work

### ISSUE THREAD

**Issue by zyxmon** [Entware/entware#145]
/opt/home/admin # /sbin/blkid
/dev/sda1: LABEL="ASUS56" UUID="ea516580-9abc-f697-348c-e8da6749f527" TYPE="ext2"
/dev/sda2: TYPE="swap"
/opt/home/admin # /opt/sbin/blkid
/opt/home/admin #

**Comment by zyxmon** [comment]
Probably BB config is not set correctly:

# CONFIG_BUSYBOX_DEFAULT_VOLUMEID is not set
# CONFIG_BUSYBOX_DEFAULT_FEATURE_VOLUMEID_<FILE_SYSTEM>.....

**Comment by zyxmon** [comment]
blkid is fixed by the above busybox settings in Entware-arm

**Comment by ryzhovau** [comment]
Done! ef1f6e15632415a1a11fd2167d6a23351f8e8679
Thanks.
