### ISSUE TITLE
clamav

### ISSUE THREAD

**Issue by swetoast** [Entware/Entware#145]
Package request
clamav 
- An antivirus for linux

- [x]  No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my arm5 and arm7 and get a feedback about it.

**Comment by swetoast** [comment]
@zyxmon @ryzhovau still working on entware ?

**Comment by Dmole** [comment]
clamav is RAM heavy, so on embedded devices will not scan larger files ( just pointing out the RoI on this might be lower than expected)

**Comment by swetoast** [comment]
Works just fine on my nas without issues all it takes is a bit of swap
