### ISSUE TITLE
Package request : mono

### ISSUE THREAD

**Issue by itdaboyz** [Entware/Entware#146]
Hi,

Package request : mono
---

On embedded device we rely a lot on manufacturer for update of mono.
Would it be possible to include in Entware? This way we could be sure to have an up-to-date version.

Thanks

**Comment by cuadedanh** [comment]
i need  it too, pls add

**Comment by vortex1024** [comment]
me too

**Comment by ryzhovau** [comment]
What are you trying to run? We tried mono several years ago, even "hello world" binary causes OOM on 64MB RAM devices.

**Comment by ryzhovau** [comment]
There's a [separate Debian team](https://salsa.debian.org/dotnet-team/mono/tree/master) to adjust mono for cross-compilation. We should drop any other activities to start support mono.

Sorry, won't do that.
