### ISSUE TITLE
rtorrent plugins dependances

### ISSUE THREAD

**Issue by zyxmon** [Entware/entware#147]
I have a report on this:

>rutorrent-plugin-_task -> Not installing procps-pgrep dependency
>rutorrent-plugin-geoip -> Missing php5-mod-geoip module dependency
>rutorrent-plugin-retracker -> Breaking the plugins from loading
>rutorrent-plugin-rss -> Missing php5-mod-json module dependency
>rutorrent-plugin-mediainfo - Package not in repository

**Comment by ryzhovau** [comment]
To be continued here - https://github.com/Entware-ng/Entware-ng/issues/9
