### ISSUE TITLE
Hostapd package on repo but not opkg install

### ISSUE THREAD

**Issue by siliconhippy** [Entware/Entware#148]
The popular hostapd package seems to be here:
https://github.com/Entware/Entware/tree/master/package/network/services/hostapd

But $opkg install hostapd 
returns error.

How to install hostapd on a read only OS like CoreElec.org with Entware package manager installed?

**Comment by paulhybryant** [comment]
+1. Want to ask the same question

**Comment by ryzhovau** [comment]
`hostapd` from upstream is highly tied to OpenWrt firmware, we can't add it in current state. 
Please, consider using another solution.
