### ISSUE TITLE
Can't install Entware

### ISSUE THREAD

**Issue by ghost** [Entware/Entware#149]
Hello,

When attempting to install Entware on my DD-WRT router, I get the following output with `sh -xv generic.sh`:

#!/bin/sh

unset LD_LIBRARY_PATH
+ unset LD_LIBRARY_PATH
unset LD_PRELOAD
+ unset LD_PRELOAD

echo "Info: Checking for prerequisites and creating folders..."
+ echo 'Info: Checking for prerequisites and creating folders...'
Info: Checking for prerequisites and creating folders...

if [ -d /opt ]
then
    echo "Warning: Folder /opt exists!"
else
    mkdir /opt
fi
+ '[' -d /opt ]
+ echo 'Warning: Folder /opt exists!'
Warning: Folder /opt exists!
# no need to create many folders. entware-opt package creates most
for folder in bin etc lib/opkg tmp var/lock
do
  if [ -d "/opt/$folder" ]
  then
    echo "Warning: Folder /opt/$folder exists!"
    echo "Warning: If something goes wrong please clean /opt folder and try again."
  else
    mkdir -p /opt/$folder
  fi
done
+ '[' -d /opt/bin ]
+ mkdir -p /opt/bin
+ '[' -d /opt/etc ]
+ mkdir -p /opt/etc
+ '[' -d /opt/lib/opkg ]
+ mkdir -p /opt/lib/opkg
+ '[' -d /opt/tmp ]
+ mkdir -p /opt/tmp
+ '[' -d /opt/var/lock ]
+ mkdir -p /opt/var/lock

echo "Info: Opkg package manager deployment..."
+ echo 'Info: Opkg package manager deployment...'
Info: Opkg package manager deployment...
DLOADER="ld.so.1"
+ DLOADER=ld.so.1
URL=http://bin.entware.net/mipselsf-k3.4/installer
+ URL=http://bin.entware.net/mipselsf-k3.4/installer
wget $URL/opkg -O /opt/bin/opkg
+ wget http://bin.entware.net/mipselsf-k3.4/installer/opkg -O /opt/bin/opkg
Connecting to bin.entware.net (81.4.123.217:80)
chmod 755 /opt/bin/opkg
+ chmod 755 /opt/bin/opkg
wget $URL/opkg.conf -O /opt/etc/opkg.conf
+ wget http://bin.entware.net/mipselsf-k3.4/installer/opkg.conf -O /opt/etc/opkg.conf
Connecting to bin.entware.net (81.4.123.217:80)
wget $URL/ld-2.27.so -O /opt/lib/ld-2.27.so
+ wget http://bin.entware.net/mipselsf-k3.4/installer/ld-2.27.so -O /opt/lib/ld-2.27.so
Connecting to bin.entware.net (81.4.123.217:80)
wget $URL/libc-2.27.so -O /opt/lib/libc-2.27.so
+ wget http://bin.entware.net/mipselsf-k3.4/installer/libc-2.27.so -O /opt/lib/libc-2.27.so
Connecting to bin.entware.net (81.4.123.217:80)
wget $URL/libgcc_s.so.1 -O /opt/lib/libgcc_s.so.1
+ wget http://bin.entware.net/mipselsf-k3.4/installer/libgcc_s.so.1 -O /opt/lib/libgcc_s.so.1
Connecting to bin.entware.net (81.4.123.217:80)
wget $URL/libpthread-2.27.so -O /opt/lib/libpthread-2.27.so
+ wget http://bin.entware.net/mipselsf-k3.4/installer/libpthread-2.27.so -O /opt/lib/libpthread-2.27.so
Connecting to bin.entware.net (81.4.123.217:80)
cd /opt/lib
+ cd /opt/lib
chmod 755 ld-2.27.so
+ chmod 755 ld-2.27.so
ln -s ld-2.27.so $DLOADER
+ ln -s ld-2.27.so ld.so.1
ln -s libc-2.27.so libc.so.6
+ ln -s libc-2.27.so libc.so.6
ln -s libpthread-2.27.so libpthread.so.0
+ ln -s libpthread-2.27.so libpthread.so.0

echo "Info: Basic packages installation..."
+ echo 'Info: Basic packages installation...'
Info: Basic packages installation...
/opt/bin/opkg update
+ /opt/bin/opkg update
generic.sh: line 43: /opt/bin/opkg: not found
/opt/bin/opkg install entware-opt
+ /opt/bin/opkg install entware-opt
generic.sh: line 44: /opt/bin/opkg: not found

# Fix for multiuser environment
chmod 777 /opt/tmp
+ chmod 777 /opt/tmp

# now try create symlinks - it is a std installation
if [ -f /etc/passwd ]
then
    ln -sf /etc/passwd /opt/etc/passwd
else
    cp /opt/etc/passwd.1 /opt/etc/passwd
fi
+ '[' -f /etc/passwd ]
+ ln -sf /etc/passwd /opt/etc/passwd

if [ -f /etc/group ]
then
    ln -sf /etc/group /opt/etc/group
else
    cp /opt/etc/group.1 /opt/etc/group
fi
+ '[' -f /etc/group ]
+ ln -sf /etc/group /opt/etc/group

if [ -f /etc/shells ]
then
    ln -sf /etc/shells /opt/etc/shells
else
    cp /opt/etc/shells.1 /opt/etc/shells
fi
+ '[' -f /etc/shells ]
+ cp /opt/etc/shells.1 /opt/etc/shells

if [ -f /etc/shadow ]
then
    ln -sf /etc/shadow /opt/etc/shadow
fi
+ '[' -f /etc/shadow ]

if [ -f /etc/gshadow ]
then
    ln -sf /etc/gshadow /opt/etc/gshadow
fi
+ '[' -f /etc/gshadow ]

if [ -f /etc/localtime ]
then
    ln -sf /etc/localtime /opt/etc/localtime
fi
+ '[' -f /etc/localtime ]

echo "Info: Congratulations!"
+ echo 'Info: Congratulations!'
Info: Congratulations!
echo "Info: If there are no errors above then Entware was successfully initialized."
+ echo 'Info: If there are no errors above then Entware was successfully initialized.'
Info: If there are no errors above then Entware was successfully initialized.
echo "Info: Add /opt/bin & /opt/sbin to your PATH variable"
+ echo 'Info: Add /opt/bin & /opt/sbin to your PATH variable'
Info: Add /opt/bin & /opt/sbin to your PATH variable
echo "Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware services to start"
+ echo 'Info: Add '"'"'/opt/etc/init.d/rc.unslung start'"'"' to startup script for Entware services to start'
Info: Add '/opt/etc/init.d/rc.unslung start' to startup script for Entware services to start
echo "Info: Found a Bug? Please report at https://github.com/Entware/Entware/issues"
+ echo 'Info: Found a Bug? Please report at https://github.com/Entware/Entware/issues'
Info: Found a Bug? Please report at https://github.com/Entware/Entware/issues

**Comment by ryzhovau** [comment]
Something firmware specific, better ask on some DD-wrt forum.

**Comment by brendoncdrew** [comment]
I have same problem using broadcom / latest DD-WRT v3.0-r41892 mega (01/05/20)

 firmware
