### ISSUE TITLE
Logrotate patch

### ISSUE THREAD

**Issue by oldgringo** [Entware/entware#149]
Please, can you apply the patch for the logrotate util from here?
https://fedorahosted.org/logrotate/changeset/446
I guess the functionality shouldn't be strictly related to "root" named user.
Thanks.

Edit: There is version 3.9.1 on the same site already updated.

**Comment by zyxmon** [comment]
I am planing to build 3.9.1 in Qnapware/Entware.arm

**Comment by ryzhovau** [comment]
Fixed in Entware-ng.
