### ISSUE TITLE
APF v9.7-2 (Advanced Policy Firewall)

### ISSUE THREAD

**Issue by wetux** [Entware/entware#150]
Package Request: APF-9.7-2 (Advanced Policy Firewall)
URL: https://www.rfxn.com/projects/advanced-policy-firewall/

Description:
Advanced Policy Firewall (APF) is an iptables(netfilter) based firewall system designed around the essential needs of today’s Internet deployed servers and the unique needs of custom deployed Linux installations. The configuration of APF is designed to be very informative and present the user with an easy to follow process, from top to bottom of the configuration file.

**Comment by ryzhovau** [comment]
Iptables/netfilter firewall is a part of every router f\w, I see no sense to add another firewall, sorry.

Also, it [relies](https://www.rfxn.com/appdocs/README.apf) on bunch of kernel modules, so you need (in most cases) to recompile kernel with required modules. APF is just a bash script, you may use it after recompiling f\w, if you want.
