### ISSUE TITLE
padavan, entware not working on restart or power failure

### ISSUE THREAD

**Issue by sudtanj** [Entware/Entware#150]
hello, so i got this problem after restarting or power failure happen. when i ssh, i'm getting this message when i typing opkg.

> /opt/home/admin # opkg
> -sh: opkg: Input/output error

i don't know where is the source of the problem. my temporary solution that i found myself is to turn off entware -> reboot -> delete all files and folder under opt on my ext hdd -> turn on entware again -> reboot. it solve the problem until a power failure or restart happen again. are there any better solution for this type of problem?

**Comment by ryzhovau** [comment]
We do not provide personal support, sorry.
It's something firmware-specific.
