### ISSUE TITLE
Package update: dnscrypt-proxy2 to 2.0.19

### ISSUE THREAD

**Issue by ghost** [Entware/Entware#151]
Please update to the latest 2.0.17
https://github.com/jedisct1/dnscrypt-proxy

**Comment by jamesmacwhite** [comment]
Would be nice, because there is also an issue with the existing dnscrypt-proxy2 package on Entware on certain arch, see: https://github.com/Entware/Entware/issues/147

**Comment by ryzhovau** [comment]
Done, binaries will arrive soon.
