### ISSUE TITLE
BFD v1.5-2 (Brute Force Detection)

### ISSUE THREAD

**Issue by wetux** [Entware/entware#151]
Package Request: BFD v1.5-2 (Brute Force Detection)
URL: https://www.rfxn.com/projects/brute-force-detection/

Description
BFD is a modular shell script for parsing application logs and checking for authentication failures. It does this using a rules system where application specific options are stored including regular expressions for each unique auth format. The regular expressions are parsed against logs using the ‘sed’ tool (stream editor) which allows for excellent performance in all environments. In addition to the benefits of parsing logs in a single stream with sed, BFD also uses a log tracking system so logs are only parsed from the point which they were last read. This greatly assists in extending the performance of BFD even further as we are not constantly reading the same log data. The log tracking system is compatible with syslog/logrotate style log rotations which allows it to detect when rotations have happened and grab log tails from both the new log file and the rotated log file.

**Comment by ryzhovau** [comment]
The same as in APF.
