### ISSUE TITLE
The N2N armv7 version doesn't work. No error no message no succeed.

### ISSUE THREAD

**Issue by fordiy** [Entware/entware#152]
I run the opkg install n2n. It installed and have two files to /opt/sbin. One is edge and other is supernode. Both two are NOT work on N18U router(Tomato or Asuswrt-Merlin).

No error, no prompt, no any message and quit  when I run them. What's wrong?

It download from:
Downloading http://qnapware.zyxmon.org/binaries-armv7/n2n_2.1.0-r7223-1_armv7soft.ipk.

**Comment by zyxmon** [comment]
You can open tickets specific for Entware-arm here - https://github.com/zyxmon/entware-arm/issues

Have you loaded tun kernel module before running n2n? Firmware/kernel specific parts of scripts are to by added by user.

**Comment by fordiy** [comment]
tun kernel module?  What's this for? Have you success run N2N arm version on Tomato or Asuswrt-Merlin?

**Comment by zyxmon** [comment]
google for tun - AFAIK it is needed to run N2N.
I fo not use N2N.

**Comment by ryzhovau** [comment]
@fordiy, can you confirm tun.ko module is loaded before n2n start?

**Comment by fordiy** [comment]
I can confirm TUN interface is work. As the OpenVPN server/client is
runable.

Jun

2015-07-24 1:29 GMT+08:00 Alexander Ryzhov <notifications@github.com>:

**Comment by ryzhovau** [comment]
This is a last update of `n2n` package. It was abandoned twice: both [original](http://www.ntop.org/n2n/using-n2n-with-amazon-aws-ec2/) and [fork](https://github.com/lukablurr/n2n_v2_fork) No updates for two years, plus, it's not proven as working.

So, it will be removed from repo soon. You can always find it in [archive](http://entware.wl500g.info/binaries/entware/archive/), if you wish.
