### ISSUE TITLE
Package "znc_1.7.1-2_mipsel-3.4" appears to ship with a broken executable

### ISSUE THREAD

**Issue by StepS-** [Entware/Entware#153]
After upgrading from Entware-3x to the new Entware repo and then upgrading from **znc_1.6.5-1_mipsel-3x** to **znc_1.7.1-2_mipsel-3.4**, the znc executable no longer works. Trying to invoke "**znc**" results in "**not found**", even if done inside the /opt/bin directory, no matter the permissions. Same issue with opkg reinstalled completely from scratch (tried 2 or 3 times). At the same time, the executable from 1.6.5-1 works. I went through the manual process of rolling back to 1.6.5-1 with its dependencies and that worked.

NDMS 2.13.C.0.0-0, if that matters.

**Comment by The-BB** [comment]
please, update the package list, reinstall znc, and try again

**Comment by StepS-** [comment]
Thank you, it's working now.

It seems that the problem was due to it linking to /lib/ld.so.1 instead of /opt/lib/ld.so.1.
