### ISSUE TITLE
Cannot install Flexget

### ISSUE THREAD

**Issue by zilexa** [Entware/entware#153]
I followed these instructions to install Entware on my Asus RT-AC56U router with AsusWRT Merlin installed:
https://github.com/RMerl/asuswrt-merlin/wiki/Entware

I succesfully installed nano editor as a test. Then I used these instructions to install Flexget:
http://flexget.com/wiki/InstallWizard/OpenWrt

But the first command "opkg install python python-sqlite3 pyyaml" failed due to "Unknown package 'pyyaml'." also the next command, 'python-sqlite' is an unknown package.

I cannot imagine nobody is using Flexget in combination with their AsusWRT-Merlin router. Should I install something else first before following the Flexget guide?

**Comment by zyxmon** [comment]
For arm specific tickets please use https://github.com/zyxmon/entware-arm/issues
You can get the names of all python packages with
    opkg list } grep Python
This will help you!

**Comment by ryzhovau** [comment]
`pyyaml` package was replaced by `python-yaml`. 
OpenWrt instructions are outdated, and I can't support it, it's out of project goal, sorry.

**Comment by zilexa** [comment]
ok, I'll follow zyxmon advice, thanks!
