### ISSUE TITLE
PHP-CGI Missing Modules

### ISSUE THREAD

**Issue by wetux** [Entware/entware#154]
When using php-cgi and enabling "curl.so" in php.ini file it gives this error;

PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/lib/php/curl.so' - File not found in Unknown on line 0

**Comment by zyxmon** [comment]
As a suggestion - install
`opkg install php5-mod-curl`

**Comment by wetux** [comment]
@zyxmon Thank You. I should of tried ``opkg find php5-*``
