### ISSUE TITLE
Package Request: MHDDFS 

### ISSUE THREAD

**Issue by whega** [Entware/Entware#154]
Package request: MHDDFS 
---
To transparently merge multiple drives into a single mount point. Drives can be either real (hdd) or virtual (loop devices) or even network mount points (NFS and so on). 
This driver is a high - level add-on for the file system (unlike LVM, which can provide the same functionality but at a lower level), so when the number of file systems involved changes, you do not need to run tools like fsck / resize * fs for order to restore system performance.

This driver will allow you to share the disk space of several file systems as one large storage device.

For more information, see the README in the source code.

How it works?
You mount several file systems using this driver in one directory, then the driver intercepts almost all file operations and distributes data between file systems in such a way that a shared file system is obtained. 
If any of the devices runs out of space, the driver transparently for the application will transfer the file with which it works to another device. Thus, applications operate with data volumes approximately equal to the total volume of all mounted file systems.

This is the main difference from analogs ( unionfs , aufs, etc.) - this driver emulates a file system that can be written to the size of the sum of all the terms.

This driver was written to use several hard drives on a server storing mirrors of large sites (like Debian repositories ). But can be used for other purposes.

The driver is written using the FUSE library , so for assembly and installation it requires its presence on your computer.

Source Download
http://mhddfs.uvw.ru/downloads/mhddfs_0.1.39.tar.gz

**Comment by ryzhovau** [comment]
Did you tried `unionfs` from repo? We won't add packages with similar functionality as existing ones, sorry.

**Comment by whega** [comment]
HI there, I've tied unionfs but it doesn't seem to have the ability to write data across disks. It spits out errors when 1 disk fills up even though there is ample space left on the pool.

From what I can read, unionfs was designed more of read only file systems in mind. MHDDFS is expanded version which can behave much like a RAID pool. Not quite as good, but similar.

Unless I'm missing something with unionfs.

Thanks

**Comment by whega** [comment]
MHDDFS has a mount -o mlimit=size option which sets the minimum amount of free space on a disk before transparently moving data to another disk. Even data being currently write when the limit is hit. Or if all disks in the pool have free space, the disk withe most space is used. Effectively emulating one large file system (http://svn.uvw.ru/mhddfs/trunk/README)

MergerFS seems to also have a similar function using moveonenospc=true mount option. When enabled (set to true) if a write fails with ENOSPC or EDQUOT a scan of all drives will be done looking for the drive with the most free space which is at least the size of the file plus the amount which failed to write. An attempt to move the file to that drive will occur.

Since both seem to have been built on the back unionfs, I thought one of them could be packed for Entware. I definitely think they provide expanded functionality.

If i'm wrong about unionfs, if anyone knows what mount options i should be using to see the above effects. Please let me know.

My end goal is to have a set of external USB Drives mounted as one pool. RAID and LVM arn't suitable options for me as I want to replace the drives as they fill but still be able to access the data on them.  RAID and LVM wouldn't allow access to a single drives data.

Thanks

**Comment by ryzhovau** [comment]
`mergerfs` will be [added](https://github.com/Entware/Entware/issues/199) instead.

`mhddfs` got some major [bugs](https://github.com/trapexit/mhddfs), which will never be fixed, as long as it's abandoned in 2012.
