### ISSUE TITLE
About shadowsocks operational issues

### ISSUE THREAD

**Issue by houzi-** [Entware/entware#156]
My router is a Netgear R6300 V1 Configuration After installing shadowsocks successful run shadowsocks success, but can not over the wall, I do not know why this is? Any error message did not appear.

**Comment by ryzhovau** [comment]
Will wait up to month and keep this issue open. 
If there will be no confirmation of this bug from others, I'll close it.

**Comment by ryzhovau** [comment]
Closing for now.
