### ISSUE TITLE
oidentd and ipv6

### ISSUE THREAD

**Issue by jimerickson** [Entware/Entware#156]
Package request
---
{it would be excellent if you could compile oidentd to listen on ipv6. currently it is only listening on ipv4.}

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
Can't confirm that.
```
# opkg install oidentd
# /opt/etc/init.d/S39oidentd start
# netstat -tulpn | grep oidentd
tcp        0      0 0.0.0.0:113             0.0.0.0:*               LISTEN      20470/oidentd
tcp        0      0 :::113                  :::*                    LISTEN      20470/oidentd
```
