### ISSUE TITLE
Dropbox-Uploader updated

### ISSUE THREAD

**Issue by AndreDVJ** [Entware/entware#157]
v0.14 is currently broken. Author updated the script. I tested and it works. Please update the package.

https://github.com/andreafabrizi/Dropbox-Uploader/releases/tag/0.15

**Comment by AndreDVJ** [comment]
I discovered another issue. Shibby's AIO builds from 130 includes an old version of curl, and it's incompatible with this script. The curl binary path must be hardcoded "/opt/bin/curl" else you'll get errors like below:

Jun 21 17:55:41 WNR3500Lv2 user.notice root: grep: /opt/tmp/du_resp_11216: No such file or directory
Jun 21 17:55:41 WNR3500Lv2 user.notice root: grep: /opt/tmp/du_resp_11216: No such file or directory
Jun 21 17:55:41 WNR3500Lv2 user.notice root: grep: /opt/tmp/du_resp_11216: No such file or directory
Jun 21 17:55:41 WNR3500Lv2 user.notice root: grep: /opt/tmp/du_resp_11216: No such file or directory
Jun 21 17:55:41 WNR3500Lv2 user.notice root: grep: /opt/tmp/du_resp_11216: No such file or directory
Jun 21 17:55:41 WNR3500Lv2 user.notice root: grep: /opt/tmp/du_resp_11216: No such file or directory
Jun 21 17:55:41 WNR3500Lv2 user.notice root:  > Uploading "/opt/tmp/Backup_WNR3500Lv2_21-06-2015_1755.tar.gz" to "///Backup_WNR3500Lv2_21-06-2015_1755.tar.gz"... grep: /opt/tmp/du_resp_11216: No such file or directory
Jun 21 17:55:41 WNR3500Lv2 user.notice root: grep: /opt/tmp/du_resp_11216: No such file or directory


I don't what grep has to do with them, but hardcoding curl binary solved another issue here.

**Comment by ryzhovau** [comment]
> I discovered another issue. Shibby's AIO builds from 130 includes an old version of curl, and it's incompatible with this script. The curl binary path must be hardcoded "/opt/bin/curl" else you'll get errors like below when you run a backup script from Tomato scheduler:

IMHO, it's question of environment settings. If `$PATH` shows no `/opt/...` paths, you can get similar errors. Please, set up `$PATH` both in user shell and cron scripts.

**Comment by AndreDVJ** [comment]
Yes you're right I overlooked that. Added PATH and curl picks up from /opt and worked fine from cron script. I'll close this case, no point leaving it open, eventually you can update the package,
