### ISSUE TITLE
ser2net serial proxy is bult with a fatal error

### ISSUE THREAD

**Issue by andrew-xdn** [Entware/entware#158]
ser2net serial proxy build is useless in case of a bug described in the topic on the official ser2net resource:
http://sourceforge.net/p/ser2net/discussion/90083/thread/b8220fa4/

The problem was solved in the actual version 2.10.

**Comment by ryzhovau** [comment]
Last sync with OpenWrt brought 2.10.0 to Entware. Hope it will solve those issue.
