### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by diman82** [Entware/Entware#158]
Suddenly, I get an error of "Illegal instruction" for every Entware command I run on my Asus RT-AC86U router.
Tried to run the [Entware installation script](https://github.com/Entware/Entware/wiki/Install-on-asuswrt-merlin-firmware), but it finishes right away with the same error.
Upgarded the router to the newest RT-AC86U_384.7_0 firmware, which didn't help as well.

What could be the problem and how to fix it?

**Comment by amplatfus** [comment]
Hi,

I know this is old, but could you please share how did you solved this if you solved.
Thanks!

**Comment by diman82** [comment]
@amplatfus Had ro reinstall Entware completely.
P.S  backup all important files prior..

**Comment by amplatfus** [comment]
Thank you. Posted [here](https://github.com/Entware/Entware/issues/201#issuecomment-449758161) and solve it already.
Merry Christmas and Happy New year!
