### ISSUE TITLE
Package request: fio (flexible i/o tester)

### ISSUE THREAD

**Issue by brianredbeard** [Entware/Entware#159]
Package request: fio
---
[fio](https://github.com/axboe/fio) (flexible i/o tester) is a cli tool for generating input output workloads for the purpose of testing disk performance.  It is similar in this sense to iperf/iperf3, but for block devices.

>Fio spawns a number of threads or processes doing a particular type of I/O
action as specified by the user. fio takes a number of global parameters, each
inherited by the thread unless otherwise parameters given to them overriding
that setting is given.  The typical use of fio is to write a job file matching
the I/O load one wants to simulate.

- [X] No similar package already added and/or this one got some new killer feature(s), (this package far outshines many of the comparable ones e.g. `iozone` or `bonnie++`).
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my x86_64 & armv5 and get a feedback about it.

For what it's worth, this package is [already in the Entware Openwrt package mirror](https://github.com/Entware/entware-packages/tree/3e272cc02aef3fd7790acc08ef7fd102aa4e4b21/utils/fio), it just needs to be added to the build farm.

**Comment by ryzhovau** [comment]
x86_64 & armv5 binaries will arrive soon.
