### ISSUE TITLE
Strongswan 5.3 issues

### ISSUE THREAD

**Issue by bain64** [Entware/entware#159]
Hello, & Awesome work with this package!  Spent way too many hours trying to get this figured out, hope others can confirm or deny my troubles.. My goal is an IPsec VPN. Strongswan is not a requirement, but the only option I know of for this hardware. 

My setup: Asus RT-N66u, TomatoUSB 130 (128 and 120 also tested), latest install script - wget from entware.wl500g

The Issue: Ipsec through Strongswan 5.3 is not operational 

root@:/opt/stronginstall# ipsec statusall
root@:/opt/stronginstall# ipsec restart
Stopping strongSwan IPsec failed: starter is not running
root@:/opt/stronginstall# ipsec starter
root@:/opt/stronginstall# ipsec start
root@:/opt/stronginstall#

To test, I tried different firmware versions, and also tried to install a known working version 5.1.3, but opkg forces install of the latest 5.3.  

5.1 install force changed to 5.3, CLI log
root:/# opkg install http://entware.wl500g.info/binaries/entware/archive/strongswan-charon_5.1.3-1_entware.ipk
Downloading http://entware.wl500g.info/binaries/entware/archive/strongswan-charon_5.1.3-1_entware.ipk.
Installing strongswan-charon (5.3.0-1) to root...
Downloading http://entware.wl500g.info/binaries/mipselsf/strongswan-charon_5.3.0-1_mipselsf.ipk.
Installing strongswan (5.3.0-1) to root...
Downloading http://entware.wl500g.info/binaries/mipselsf/strongswan_5.3.0-1_mipselsf.ipk.
Configuring strongswan.
Configuring strongswan-charon.

I also tried to manually download all Strongswan .ipk files to local /opt/stronginstalls/ , then opkg install *.ipk from the local drive, but again it downloads and installs the latest 5.3 version. 

Can anyone else confirm Strongswan works on 5.3? Do you get a response with 'ipsec statusall' ?

Any way to force install an older version, without it installing the latest version?  

-Bain

**Comment by ryzhovau** [comment]
I'll keep this issue open for month, waiting a confirmation from others.

> I also tried to manually download all Strongswan .ipk files to local /opt/stronginstalls/ , then opkg install *.ipk from the local drive, but again it downloads and installs the latest 5.3 version. 

[See FAQ](https://github.com/Entware/entware/wiki/FAQ#q-my-favorite--package-was-updated-i-want-the-previous-version-back).

**Comment by bain64** [comment]
Ryzhovau, 
Thanks for link to FAQ, somehow I missed the double hyphen on the force downgrade command when i had previously tried that. I can now install previous versions, thanks. I'll try some other versions and combinations of ipk files now. 

I'm still not getting ipsec response on Strongswan 5.1.3. even after downgrading. 

If someone else could please confirm or deny by installing strongswan and testing for output with 'ipsec statusall' or 'ipsec starter' it would be much appreciated. 

-Bain

**Comment by bain64** [comment]
Strongswan is working now for me. I had to comment out a line within the default strongswan.conf to get responses to 'ipsec status' or other ipsec commands. 

To document for others
/opt/etc/strongswan.conf
# load_modular = yes
 
This was tested on Strongswan 5.1.3, but very may well work on the latest 5.3.2. 
Thanks for all the contributory work on this and other projects.
