### ISSUE TITLE
Package request: cdrtools

### ISSUE THREAD

**Issue by bartoszcisek** [Entware/Entware#16]
### Package: cdrtools

Re-added issue from [previous repository](https://github.com/Entware/Entware-ng/issues/638). 

> I think there is a need for the cdrtools or genisoimage package so that mkisofs is available. optware ipkg used to have cdrtools but this is not available with entware opkg without these tools there is no clear way to create iso images from a folder of files on a nas, for example dd may be available but creating an iso from a folder still requires mkisofs also the other cdrtools are very useful for a range of things
> 
> [ ... ]
>
>please consider including the cdrtools or something similar like debian's genisoimage tools
>I think cdrtools would be the prefered choice.

I personally would like to use this package to prepare backup written to USB attached BR/DVD-R 
Platform: cross, x86
- HS-251+

**Comment by ryzhovau** [comment]
This package is not cross compile friendly, so you may try to compile it natively.

PS If `cdrtools` authors didn't get cross compilation support for 20 years, why we should?:(
