### ISSUE TITLE
dnsmasq-proxy [Support for plugins hasn't been compiled in]

### ISSUE THREAD

**Issue by opav** [Entware/entware#161]
Tried to enable use of below feature but it seems dnscrypt-proxy 1.4.3 is not compiled with plugins support, error is 'Support for plugins hasn't been compiled in'

Appreciate if it can be compiled in with newer version 1.5.0.

--- http://dnscrypt.org -----------------------------------------------------------------------------------------------------

>AAAA blocking

>If your network doesn't support IPv6, chances are that your applications are still constantly trying to resolve IPv6 addresses, causing unnecessary slowdowns.

>This plugin causes the proxy to immediately reply to IPv6 requests, without having to send a useless request to upstream resolvers, and having to wait for a response.

>Usage:

>   *dnscrypt-proxy ... --plugin=example-ldns-aaaa-blocking.la*

**Comment by ryzhovau** [comment]
Not sure I want to change current package structure, [taken from OpenWrt](https://github.com/Entware/openwrt-packages/blob/master/net/dnscrypt-proxy/Makefile). It they add plugins, I'll port it to Entware.
