### ISSUE TITLE
Package request: Zabbix 4

### ISSUE THREAD

**Issue by cerebralmisfire** [Entware/Entware#161]
Package request
---
The new completely redesigned graph widget provides an exceptional way to get insights from the collected data. The widget allows to create a variety of graphs, work with multiple data sets, select sets of metrics or individual metrics for graphing, configure graph line-style configuration, legend layout as well as supporting displaying of information about discovered problems straight on the graphs. Additional information is displayed by placing your cursor over the graph.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
As long as it came from upstream, It's up to OpenWrt guys. 
Please, [ask](https://github.com/openwrt/packages/issues) them about it.
