### ISSUE TITLE
BRO -  A good IDS for entware

### ISSUE THREAD

**Issue by opav** [Entware/entware#162]
https://github.com/krkhan/openwrt-bro
http://inspirated.com/tag/bro-ids

It will be great if BRO can be added to Entware.  It is already available for openwrt.  

Thanks.

**Comment by ryzhovau** [comment]
Minimal [prerequisites ](https://www.bro.org/sphinx/install/install.html#id5) are met. 

To be continued here - https://github.com/Entware-ng/Entware-ng/issues/10
