### ISSUE TITLE
SSHL failing to start

### ISSUE THREAD

**Issue by EZarnosky** [Entware/entware#163]
I have a Netgear WNT3500L running version 130 of Tomato shibby. I have been able to get the NZGBet package to install and run. However I am having an issue getting SSHL working. when I execute the S14sslh script the daemon attempts to start but ends with "failed".

I would troubleshoot this more but I have no idea if and where errors might be logging to. Can you point me in a direction to stat investigating? Thanks

**Comment by EZarnosky** [comment]
I think I just identified the problem, the SSLH script S14sslh does not specify a litening port.

Can you tell me, does Entware support a default directory (ex. /opt/etc/default) that I can use to store settings for the scripts in the /opt/etc/init.d folder to read and use?

**Comment by ryzhovau** [comment]
`sslh` has no config file, please, specify necessary option in `S14sslh` script.
