### ISSUE TITLE
Package request: php7-mod-bcmath

### ISSUE THREAD

**Issue by dlvandenberg** [Entware/Entware#164]
Package request
---
A Binary Calculator module for PHP. It's an official extension, but there is no such package yet (there are for other PHP extensions). I think PHP also needs to be compiled with the 'enable-bcmath' flag?

An application that I'm trying to install (firefly-iii) requires the bcmath extension.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my Synology DS216play and get a feedback about it.

**Comment by runforrestrun** [comment]
+1

**Comment by ryzhovau** [comment]
Done, binaries will arrive soon.
