### ISSUE TITLE
 urlsnarf is not working

### ISSUE THREAD

**Issue by zyxmon** [Entware/entware#164]
urlsnarf (dsniff package) does not show any output.
dsniff works with "-c" flag. As documentation states ""The *snarf tools do not yet support this mode of operation." Tested on rt-56u.

**Comment by jerrm** [comment]
I'd love to see this working.  I am just now really evaluating arm routers and really need the urlsnarf or equivalent functionality.

If it helps this is my experience for dsniff/urlsnarf:
entware-arm - doesn't work.  No output as stated above.  
entware-mips - works great.  Billions of lines logged.
Shibby's optware-arm based package - works (under optware of course).
chroot'ed debian package - works.

Maybe something can be gleaned from the differences.

This is all tested under Shibby Tomato 130.

**Comment by zyxmon** [comment]
I have checked urlsnarf/dsniff on rt-n56u (entware-mips). I was able to capture a couple of UPnP packets (8080 port). Nothing more.
Your information gives no information - what is wrong. Use strace output and compare working and not workin situations. This can give some info - what is wrong.
