### ISSUE TITLE
apcupsd 3.14.13 with NaN values

### ISSUE THREAD

**Issue by waltermodbus** [Entware/entware#165]
apcupsd (v3.14.13-4a) does not fully work with modbus and also plain USB delivering NaN values due to FP error.
Nan values apcaccess readout with both feeds mipselsf and entware.
Platform is wl-500gp with oleg 2.6.22.9 kernel.   Please assist to sort this out.

**Comment by waltermodbus** [comment]
also releases 3.14.13-2 or -2a or -4 show the same NaN values behaviour.
Please help.

**Comment by ryzhovau** [comment]
Closing as duplicate, details is [here](https://github.com/Entware/entware/commit/f2e17c85164756e656d43c56a776b0de77afdb0d#commitcomment-12219393).

**Comment by waltermodbus** [comment]
Alexander, my last question on this topic:
On the Entware homepage I read: "Soft-float ( Works with both soft-float &
hard-float firmwares.)".
Why is only hard-float working (no NaN values) on my wl-500gp, 2.6.22.19
kernel setup as soft-float should also do?


On Fri, Jul 17, 2015 at 10:33 AM, Alexander Ryzhov <notifications@github.com
