### ISSUE TITLE
Package request: znc-push

### ISSUE THREAD

**Issue by RogueScholar** [Entware/Entware#166]
Package request: [znc-push](https://github.com/jreese/znc-push)
---
Having a running instance of ZNC on my home router is one of my primary reasons for using Entware (though Gerbera and Netdata also rank high on that list, not to mention using Python3 for access to Certbot.) One lingering issue I've been trying to eliminate with ZNC is the absence of a customizable system of notifications that can call my attention to certain activity in IRC channels even when I'm not in front of one of my computers.

This ZNC mod fills that need abundantly with a plethora of services it can use to transmit the notifications, several of which I already make use of on my smartphone. The presence of many different contextual conditions for the configured alerts, including channel of origin and whether or not I've set myself as AWAY on that IRC server further enhance its attractiveness. I would like to imagine that this package could prove useful for many other Entware/ZNC users besides myself.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

_I did first attempt to build the module myself using ZNC's znc-buildmod function, but it appears the current package was compiled without that functionality. If adding this package is untenable for any reason, having the core znc Entware package compiled with the buildmod function enabled would be acceptable as well._

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
As long as it came from upstream, It's up to OpenWrt guys. 
Please, [ask](https://github.com/openwrt/packages/issues) them about it.
