### ISSUE TITLE
Package request: Adblock

### ISSUE THREAD

**Issue by Terr2** [Entware/Entware#167]
Package request
---
Powerful adblock script to block ad/abuse domains via dnsmasq, unbound, named, kresd or dnscrypt-proxy. The script supports many domain blacklist sites plus manual black- and whitelist overrides.

It is present in Entware-ng and Entware package repos (https://github.com/Entware/entware-packages/tree/master/net/adblock) but I can't find it among available packages at http://bin.entware.net/mipselsf-k3.4/ 
Upstream source: https://github.com/openwrt/packages/tree/master/net/adblock/

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on MT7620 and get a feedback about it.

**Comment by ryzhovau** [comment]
This is just a script, tightly intergrated to OpenWrt firmware.
We keep our repo firmware independent, so we won't add it, sorry.
