### ISSUE TITLE
Please update mkvtoolnix

### ISSUE THREAD

**Issue by TheBlackBush** [Entware/Entware#168]
Package: MKVtoolnix 19.0
Hi,

Can you please update the package mkvtoolnix to the latest version (v28.2.0)?

Thanks,
Idan

**Comment by ryzhovau** [comment]
Done, binaries will arrive soon.

**Comment by marcounetB** [comment]
Hello !
I have mkvtoolnix v19.0.0 with entware. Is there a more recent version available ?

have a great day
