### ISSUE TITLE
Package request: GOG Downloader

### ISSUE THREAD

**Issue by panther7** [Entware/Entware#169]
Package request
---

LGOGDownloader is open source downloader to GOG.com for Linux users using the same API as the official GOGDownloader
It is licensed under WTFPL licence

Features:
* List available games
* Resume downloads
* Batch downloading
* Repair downloaded files
* Read/create XML files used by the official GOG Downloader
* Check for orphaned files
* Check status of files
* Download individual files by id number
* List/download updated files
* Blacklist unwanted files
* Perl regular expressions for filtering games

 Dependencies
* libcurl >= 7.32.0
* liboauth
* librhash
* jsoncpp
* htmlcxx
* tinyxml2
* boost (regex, date-time, system, filesystem, program-options, iostreams)
* libcrypto (libssl) if libcurl is built with OpenSSL
* zlib

repo: https://github.com/Sude-/lgogdownloader

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my QNAP TS-228 and get a feedback about it

**Comment by ryzhovau** [comment]
It make sense for x86 only, so I'm not sure it's handy for our repo.

**Comment by panther7** [comment]
@ryzhovau thanks for response, but example build for arm: https://launchpad.net/ubuntu/+source/lgogdownloader/3.4-1/+build/15629725 (?)
