### ISSUE TITLE
DELUGE & DELUGE-UI-WEB packages request

### ISSUE THREAD

**Issue by TeHashX** [Entware/entware#170]
Like title say, already available on entware-arm http://deluge-torrent.org/
http://qnapware.zyxmon.org/binaries-armv7/deluge_1.3.11-1_armv7soft.ipk
http://qnapware.zyxmon.org/binaries-armv7/deluge-ui-web_1.3.11-1_armv7soft.ipk

**Comment by ryzhovau** [comment]
Sure. I just in the middle of `openwrt-oldpackages-ports` feed update, which is needed by deluge.

**Comment by ryzhovau** [comment]
Already done in https://github.com/entware-ng
Stay tuned!

**Comment by ryzhovau** [comment]
Unfortunately, Deluge stays unavailable for MIPS as long as it crashes while using uClibc.
