### ISSUE TITLE
Package request: Wine

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware/Entware#170]
Package request
---
Run Windows applications.

- [✓] No similar package already added and/or this one got some new killer feature(s),
- [✓] Package is in active development (at least, not abandoned for 5 years or more),
- [✓] I'm ready to test added package on my mipsel-sf/mipsel-3.4 and get a feedback about it.

**Comment by zyxmon** [comment]
We do not plan to build Wine -
it is architecture specific;;
we do not have X-server in Entware.

**Comment by ProBackup-nl** [comment]
Don't need X-server; there are also console only  exe that run inside Wine.
