### ISSUE TITLE
Update Subversion to 1.7/1.8

### ISSUE THREAD

**Issue by Jatzoo** [Entware/entware#171]
Is it possible to update old subversion packages to 1.7 or above?

PS. Maybe migrate svn-1.7.7-1 packages from original Optware?

**Comment by ryzhovau** [comment]
The current package is a forgotten and unmaintained part of `openwrt-oldpackages` feed, I'm just in the middle of updating this feed.

**Comment by ryzhovau** [comment]
ETA: 7 days.

**Comment by alllexx88** [comment]
I remember that to build svn 1.8.11 I had to patch the configure script not to fail with "cannot run test program while cross compiling". Also, if you ever happen to wish to build svn swigs too, there're also some additional steps needed. See: https://github.com/alllexx88/Optware-ng/blob/master/make/svn.mk

**Comment by zyxmon** [comment]
@alllexx88 - if autoreconf is used it is enough to delete macosx.m4 -

**Comment by alllexx88** [comment]
@zyxmon that's a more elegant solution, I'll try it soon, thanks

**Comment by Jatzoo** [comment]
@zyxmon, @alllexx88, @ryzhovau - thanks for help and update packages

**Comment by ryzhovau** [comment]
Binaries will arrive soon.

30.07.2015, 09:22, "Jatzoo" <notifications@github.com>:
> @zyxmon, @alllexx88, @ryzhovau - thanks for help and update packages
>
> —
> Reply to this email directly or view it on GitHub.

--- 
С уважением, Александр Рыжов.

**Comment by alllexx88** [comment]
@zyxmon - deleting macosx.m4 works for building subversion itself, but if you try to build swig-py, swig-rb or swig-pl (python, ruby and perl SWIGs), you get this error:

    SWIG disabled at configure time

So I reverted to patching the configure script
