### ISSUE TITLE
mpd-full_0.19.10-1 error

### ISSUE THREAD

**Issue by monosoul** [Entware/entware#172]
Getting this error when starting mpd:

mpd: can't resolve symbol 'inotify_init1' in lib 'mpd'

mpd-full_0.18.21 doesn't have this error.

**Comment by ryzhovau** [comment]
Router? Firmware?
Can't confirm that on asuswrt-melin (Asus RT-N66U) or Oleg's f\w (D-Link DIR-320).

**Comment by monosoul** [comment]
Oh, sorry.

Asus RT-n66u, merlin's 378.55

**Comment by ryzhovau** [comment]
Got another report from RT-N66U user with TomatoUSB 130. 
It's working on 3 different firmwares so I'm closing this issue, sorry.
