### ISSUE TITLE
Package request: exempi

### ISSUE THREAD

**Issue by kfeeeeee** [Entware/Entware#172]
Package request
---
"exempi is a port of Adobe XMP SDK to work on UNIX". This would be especially useful for all OCR-related topics.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

Wasn't able to compile it by myself yet, since I am stuck with with some boost issues -.-

GitHub: https://github.com/hfiguiere/exempi

**Comment by zyxmon** [comment]
We have tesseract OCR in Entware. Have you tried it?

**Comment by kfeeeeee** [comment]
Yes, and I use it regularly. exempi would be useful for reembedding ocr'd PDFs. There is a project (Python based, though dependent on various libs) called OCRmyPDF ( https://github.com/jbarlow83/OCRmyPDF ) that would be really beneficial for NAS based OCR that also relies on exempi. AFAIK, this package outperforms all other OCR packages in reembedding the PDFs nicely.

**Comment by kfeeeeee** [comment]
It might be possible to compile on my armv7 but I think libboost-dev is missing.

**Comment by zyxmon** [comment]
There are no *dev packages in Entware - this is wiki for compiling
https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation

**Comment by kfeeeeee** [comment]
So, I tried to compile exempi but got an

> ../libtool: line 2639: func__fatal_error: command not found

It seems to be a bug in libtool that was fixed in > 2.4.6 - 26. I am not an expert on this so I am really not sure what the problems is.

**Comment by zyxmon** [comment]
https://lists.gnu.org/archive/html/bug-libtool/2016-06/msg00001.html

**Comment by kfeeeeee** [comment]
Yes, I found this as well. However, I am really stuck now. I did build an older version of libtool as well but still cannot build exempi. It seems to compile well till the end but fails just when it's packaging the libs with this libtool error...:(

**Comment by zyxmon** [comment]
It is much easier. You needed to modify one line in text file. We cannot give such sort of support here.

**Comment by kfeeeeee** [comment]
okay, so, again I am stuck with 

> libtool:   error: unsupported hardcode properties See the libtool documentation for more information. Fatal configuration error.


And this point, I'll give up tbh. Might be just impossible to compile it on this architecture dont know. Thanks for your help. You might close this issue.
