### ISSUE TITLE
Pyload don't work

### ISSUE THREAD

**Issue by przemasisko** [Entware/entware#173]
After the recent updates entware stopped working Pyload.
Crashes problem of the lack of module six and cryptography.hazmat.bindings.openssl.binding:

* 31.07.2015 22:12:30 ERROR     Remote backend error: No module named cryptography.hazmat.bindings.openssl.binding *

Six module was able to overdub by pip, pip cryptography but there is a problem. Crashes errors:

Collecting cffi>=0.8 (from cryptography)
  Using cached cffi-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    unable to execute 'mipsel-linux-uclibc-gcc': No such file or directory
    unable to execute 'mipsel-linux-uclibc-gcc': No such file or directory

**Comment by zyxmon** [comment]
Entware upgraded pyopenssl to the version 0.15.1 that depends on missing
https://pypi.python.org/pypi/six/1.9.0
and
https://pypi.python.org/pypi/cryptography/0.9.3
(may be these two missing packages depend on some other)

The possible solution is to add missing dependancies to Entware or use pypenssl 0.13.1 (as in Entware.arm)

**Comment by przemasisko** [comment]
Thanks for the information!
I'll wait as commander in chief would say :-)
If you will need to downgrade, it's very please with the instructions.

**Comment by zyxmon** [comment]
If you are using hardfloat version (not mipselsf feed), you can try if this package works for you
http://entware.wl500g.info/binaries/entware/archive/pyopenssl_0.13.1-1_entware.ipk
The downgrade instructions are here
https://github.com/Entware/entware/wiki/FAQ#q-my-favorite--package-was-updated-i-want-the-previous-version-back

**Comment by przemasisko** [comment]
Thank you!

**Comment by zyxmon** [comment]
pyload works now?

**Comment by przemasisko** [comment]
Yes. Pyload work now! Thanks.

**Comment by alllexx88** [comment]
Indeed, starting from 0.14, pyopenssl uses python cryptography to access openssl libraries. I have latest py-openssl and py-cryptography working on Optware-ng, and there're quite a few dependencies to be satisfied to get them to work: https://github.com/alllexx88/Optware-ng/blob/master/make/py-cryptography.mk

Also, cross-compiling python cryptography is a pain because you first have to build all the dependencies for the host for the build setup.py script to be satisfied with your build system.

**Comment by ryzhovau** [comment]
Oh, my. There was no such deps in 0.14.x, previous one was a [pure Python code](https://pyopenssl.readthedocs.org/en/latest/install.html). Still thinking about better solution: add 3 mode deps or roll back to 0.14.

**Comment by alllexx88** [comment]
@ryzhovau - it is indeed pure Python code as of 0.14, but requires python cryptography during runtime to access openssl libraries functionality

**Comment by alllexx88** [comment]
See

    Please take the time to read the errors and report them/ask help from the appropriate project. The most likely culprit being cryptography that contains OpenSSL’s library bindings.

**Comment by lancethepants** [comment]
The pyopenssl project 0.14 made big changes with their implementation. 
I've been using egenix's maintainance of the abandoned 0.13 versions
http://www.egenix.com/products/python/pyOpenSSL/
They've been coming out with new releases on a regular schedule.
Not sure how easy to cross-compile it is, I've been natively compiling on my routers.

**Comment by ryzhovau** [comment]
@lancethepant, thanks. This is a 3rd way.

**Comment by lancethepants** [comment]
i remmber there being a rediculous amount of dependencies in 0.14 to get it going..  The 0.13 branch might hold some performance benefits as it's written in C, as apposed to the pure python method in 0.14.

http://grokbase.com/t/python/pyopenssl-users/142vdnbntr/0-14-pure-python-implementation-performance-question

**Comment by alllexx88** [comment]
@lancethepants - the link you posted doesn't hold any benchmarks. Based on my experience, I didn't notice any real performance difference between 0.13 and 0.14-0.15.1. As for dependencies amount, it's not that ridiculous: py-enum34, py-cparser, py-six, py-asn1, py-cffi, py-setuptools, py-idna, py-ipaddress, openssl I believe are sufficient for latest python cryptography for python 2.7. The annoying part is that you have to build host variants of them all first, otherwise cryptography's setup.py errors out complaining about unsatisfied dependencies.

**Comment by lancethepants** [comment]
Yes, I'm not sure whether it would or not be more efficient. I was meaning to put 'might' in italics. I did do a test at one point, but I don't remember the results.I might revisit this. I just know 0.13 is much easier for me to compile. 
I guess we just have a difference of opinion on what  a 'rediculous amount" is. 8 dependencies for me falls squarely into that category, particularly when compared to 0.13's 0 dependences (excepting openssl itself).   I tend to take the path of least resistance, particulary if you say you don't notice any performance benefits.

**Comment by zyxmon** [comment]
My choise (for Entware.arm) was version 0.13. I have made a patch based on egenix's version. No problem was to build egenix's version also.

**Comment by ryzhovau** [comment]
>  are sufficient for latest python cryptography 0.9.3 for python 2.7.
Python cryptography required by deluge, which I plan to backport form Entware ARM fork, so I'll try pyopenssl 0.15 first.

**Comment by zyxmon** [comment]
deluge requires only pyopenssl (an old one version from openwrt does not work) - http://dev.deluge-torrent.org/wiki/Installing/Source 
The problem I had when building - I had to restore ssl2 in openssl.

**Comment by alllexx88** [comment]
deluge indeed works fine with pyopenssl 0.13. Didn't have to enable ssl2 (is it on by default?), but at some point I had to enable md2 hash function (though don't remember whether it was for deluge or not)

**Comment by zyxmon** [comment]
>> is it on by default?
Yes. Openwrt disables it (to save space???)

**Comment by lancethepants** [comment]
@zyxmon Where can I find your patch for egenix pyopenssl? Does it aid in cross-compiling? I'd like to be able to cross compile egenix's, but have only managed to natively compile it so far.

**Comment by zyxmon** [comment]
@lancethepants - it is a parch for 'standard' pyopenssl 0.13 made from egenix's code
https://github.com/zyxmon/openwrt-oldpackages-ports-arm/tree/master/pyopenssl
This code compiles in Entware-mipsel, - arm, -x86.

**Comment by ryzhovau** [comment]
I've decided to roll back to 0.13.1 with @zyxmon patch.
https://github.com/Entware/openwrt-oldpackages-ports/commit/7dd01e83d7171d78cf48ec86b744256471936269

**Comment by ryzhovau** [comment]
BTW, stable 0.4.9 uses some 404 URLs in plugin update or cypher\captha check, so I've switched to [url=https://github.com/pyload/pyload]dev sources[/url] where this problems solved.
