### ISSUE TITLE
Package request: unison

### ISSUE THREAD

**Issue by nickma82** [Entware/Entware#173]
Package request [Unison]( https://www.cis.upenn.edu/~bcpierce/unison/)
---
Describe killer feature of package: two way file sync.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my QNAP aarch64 and get a feedback about it.

Requires [OCaml](https://ocaml.org/releases/) - another feature request ([this](https://patchwork.ozlabs.org/patch/518982/) works for some platforms although with dependency issues) ?
Thoughts appreciated.

**Comment by zyxmon** [comment]
https://github.com/Entware/Entware-ng/issues/446
https://github.com/Entware/Entware-ng/issues/477

**Comment by nickma82** [comment]
In https://github.com/Entware/Entware-ng/issues/446#issuecomment-260117887 you'r basically saying "I'm able to build it from scratch, so we don't pack it" - or am I missing something here?

**Comment by zyxmon** [comment]
Ocaml is not crosscompiling friendly. If you need unison you can try to build it natively.

**Comment by nickma82** [comment]
That is true, although there are [openWRT patches](https://patchwork.ozlabs.org/patch/518982/) available to do the first steps in that direction.

**Comment by ryzhovau** [comment]
We won't modify our toolchain in a favor of couple Ocalm utilities, sorry.
