### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by Sporrdig** [Entware/entware#174]
After this commend:
wget -O - http://entware.wl500g.info/binaries/mipselsf/installer/entware_install.sh | sh

Command Log:
sh: line 27: /opt/bin/opkg: cannot execute binary file
sh: line 28: /opt/bin/opkg: cannot execute binary file

But the files exist.

**Comment by ryzhovau** [comment]
No firmware, no router model. So, nothing I can do about that.

**Comment by lancethepants** [comment]
Sounds like an architecture mixup. arm  vs mipsel. 
This is the mipsel repo.

The following is the arm repo.
https://github.com/zyxmon/entware-arm

**Comment by alllexx88** [comment]
I can imagine two possible reasons for this error:

* insufficient space to extract opkg (but proper unbugged tar would complain about it)
* wrong architecture. Probably, the router isn't MIPS, but ARM

**Comment by Sporrdig** [comment]
Is a QNAP NAS TS-269Pro

Sorry for no model

**Comment by alllexx88** [comment]
All QNAP are ARM if I'm not mistaken

**Comment by Sporrdig** [comment]
but is a Intel Atom processor

**Comment by alllexx88** [comment]
Then I suggest you use my [Optware-ng](https://github.com/alllexx88/Optware-ng) project. That's the only modern Optware-like packages feed I know of

**Comment by Sporrdig** [comment]
and what i should use:
ARM EABI?
MIPSEL?
I686?

**Comment by alllexx88** [comment]
Intel is I686

**Comment by Sporrdig** [comment]
ingenious

It works.

Thanks you.

**Comment by alllexx88** [comment]
You're welcome. File bug reports on the project page if you encounter isues

**Comment by ryzhovau** [comment]
> Then I suggest you use my Optware-ng project. That's the only modern Optware-like i686 packages feed I know of.

[What](http://qnapware.zyxmon.org/binaries-x86/Packages.html)?:)

```
wget -O - http://qnapware.zyxmon.org/binaries-x86/installer/qnapware_install_x86.sh | sh
```

**Comment by alllexx88** [comment]
My bad. I thought qnapware was ARM only, sorry)))
