### ISSUE TITLE
Please update netdata to v1.11

### ISSUE THREAD

**Issue by sinancetinkaya** [Entware/Entware#174]
Package update request
---
Developer's notice https://www.facebook.com/groups/251560641854558/permalink/764757460534871/
> We just released netdata v1.11. This release fixes a number of known vulnerabilities, so please update asap.

**Comment by ryzhovau** [comment]
Done, binaries will arrive soon.

**Comment by camkidd** [comment]
Netdata seems to have been updated to `1.11.0-1`, but program version still says `1.10.1_rolling`, so not sure if it is actually new version.

```
$ opkg list netdata
netdata - 1.11.0-1 - netdata is a highly optimized Linux daemon providing real-time ...
$ netdata -V
netdata 1.10.1_rolling
```

**Comment by zyxmon** [comment]
@camkidd - this is a bug in version reporting ftom netdata sources
https://github.com/netdata/netdata/issues/4572
