### ISSUE TITLE
Package request : Neofetch

### ISSUE THREAD

**Issue by NatoBoram** [Entware/Entware#177]
# Package request

[Neofetch](https://github.com/dylanaraps/neofetch) is a command-line system information tool written in bash 3.2+. Neofetch displays information about your operating system, software and hardware. It is useful for debugging and creating bug reports with the system's information.

[![neofetch](https://camo.githubusercontent.com/289c5b1c6fe6b77fde4fab691b1f07acd73c996b/68747470733a2f2f692e696d6775722e636f6d2f47466d433541642e706e67)](https://github.com/dylanaraps/neofetch)

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my `armv7l` and get a feedback about it.

---

Oh, hey, would you look at that?

![image](https://user-images.githubusercontent.com/10495562/48686554-84c02800-eb8a-11e8-9c21-0eab26976989.png)

Here's how to install it : 
```bash
# Just in case, I don't actually know what I needed.
opkg install bash git make curl ca-certificates

# Clone it somewhere in /opt
cd /opt/root
mkdir github
cd github
git clone git://github.com/dylanaraps/neofetch

# Install it!
cd neofetch
export PREFIX=/opt/usr
make install

# It works!
cd
neofetch
```

The [Makefile](https://github.com/dylanaraps/neofetch/blob/master/Makefile) can give useful insights on how it works.

**Comment by ryzhovau** [comment]
> Neofetch displays information about your operating system, software and hardware in an aesthetic and visually pleasing way.

…which is useless on most of embedded devices. We see no sense no add this, sorry.

**Comment by NatoBoram** [comment]
Personally, I don't use it for the "aesthetic and visually pleasing way". It's essentially an easier way to get all pertinent information about the hardware in a quick command.
