### ISSUE TITLE
Angband wont work without UTF-8

### ISSUE THREAD

**Issue by rodoviario** [Entware/entware#178]
Don't remember if previous version did, but the recent update to 4.XX says that it requires UTF-8 to work.
Tryed opkg remove angband and then opkg install angband and it claims the same.

**Comment by ryzhovau** [comment]
This is new Angband requirements. You may change locale or roll back to previous version. 
As for me, I've tested new Angband with no issues on Asus RT-N66U and D-Link DIR320.

**Comment by rodoviario** [comment]
Thanks! It worked!!
Just uncommented the 2 locale lines in profile, choosed es_ES instead of ru_RU on each, and angband worked like charm.

**Comment by rodoviario** [comment]
I have added the steps to change locale in the entware wiki if thats ok with you
Thanks again!
