### ISSUE TITLE
lighttpd: 1.4.48-2 - missing openssl module

### ISSUE THREAD

**Issue by yecarrillo** [Entware/Entware#179]
Package request
---
Please add support for openssl on lighttpd armv7 (again)

Openwrt resolved this [already](https://github.com/openwrt/packages/issues/6012)

**Comment by ryzhovau** [comment]
Lighty came from OpenWrt with all it's modules, except `authn_gssapi` (Kerberos authentification). 
The issue you referenced was resolved in May 2018, at Entware was synced with OpenWrt at least twice since than. 
Could it be just a mis-configuration, no?

**Comment by yecarrillo** [comment]
Thank you Alexander. Maybe packagename changed?
```
/tmp/home/root# opkg install lighttpd-mod-openssl                                                                                                              
Unknown package 'lighttpd-mod-openssl'.                                                                                                                                         
Collected errors:                                                                                                                                                               
 * opkg_install_cmd: Cannot install package lighttpd-mod-openssl.     
```

http://pkg.entware.net/binaries/armv7/Packages.html 
<img width="433" alt="2018-12-31 13_09_17-packages list" src="https://user-images.githubusercontent.com/569294/50565527-c1408100-0cfd-11e9-98a7-3a4e70b4a16a.png">

**Comment by ryzhovau** [comment]
No any additional modules required. Just use SSL features as you planned.
You may check compile-time features by `lighttpd -V`.
