### ISSUE TITLE
Netatalk upgrade

### ISSUE THREAD

**Issue by ryzhovau** [Entware/entware#18]
https://code.google.com/p/wl500g-repo/issues/detail?id=60

---
Is someone needs a new netatalk for Time Machine?

I've got a request from openlinksys.info forum.

**Comment by YasharF** [comment]
Pending OpenWRT package feed upgrade (currently on 2.2.4)
https://github.com/openwrt/packages/blob/c3cfd145356e3461eeb8ae2c3a4ba3386ef312c7/net/netatalk/Makefile

Once upgrade we can pick up the new version as part of the monthly syncs.

**Comment by ryzhovau** [comment]
Great.

**Comment by ryzhovau** [comment]
Done.
