### ISSUE TITLE
iptables -m conntrack

### ISSUE THREAD

**Issue by bersbersbers** [Entware/entware#180]
I am using Entware on  Shibby's tomato builds (Linksys E3200), and I had "iptables -m conntrack" working for weeks on his version 130. Last week, I did two things:
I upgraded to version 131 and did a opkg update/upgrade (which I regularly do and had been doing at the last upgrade from build 129 to 130, about 4-6 weeks ago). Since then, iptables -m conntrack returns

iptables v1.3.8: Couldn't load match `conntrack':File not found

(strace tells me it's looking for libipt_conntrack.so)

The differences between build 131 and 130 are fairly small, so I guessed this difference could not be the culprit. Just to be sure, I cleared the NVRAM and installed build 130 again - same result: both on build 130 and 131 I am not able to use iptables -m conntrack, but I have been before! So I wonder whether there were any recent changes to the package repository used by my Entware installation (http://entware.wl500g.info/binaries/entware/Packages.gz) which may have changed that behavior

**Comment by ryzhovau** [comment]
Please, provide output of following command: `which iptables`.

**Comment by bersbersbers** [comment]
I will double-check tomorrow, but I am 99% positive it is the Tomato version in /usr/sbin/iptables.

**Comment by bersbersbers** [comment]
I have found two commits which may (or may not? I don't know) be relevant in this issue:
https://github.com/Entware/entware/commit/48ed2986c9c7120623354d8a00fc93fac080e9b1
https://github.com/Entware/entware/commit/20121607cbbc3e24c6e4c6351009dffcde5eb429


Did these maybe change anything in the package repository which was not meant to be changed?

**Comment by ryzhovau** [comment]
> root@unknown:/tmp/home/root# which iptables
> /usr/sbin/iptables

So, there is nothing related Entware (which resides in `/opt`).

**Comment by bersbersbers** [comment]
Yes, this is well possible, but I would definitely appreciate some help in tracking down my issue :)

I was definitely using "iptables -m conntrack" before (like in June). However, Shibby's Tomato does not contain the required "libipt_conntrack.so". So I have no idea why it worked before, and I can only guess that Entware has been (is still?) serving this file. Is that possible?

**Comment by ryzhovau** [comment]
No, sorry. Entware is firmware independent repo, so no any kernel modules will be provided.

**Comment by bersbersbers** [comment]
Interestingly, Shibby's Tomato builds have all the required kernel modules installed; they seem to be only missing the iptables extensions "libipt_conntrack.so" (which is not a kernel module if I am not mistaken). One could, for example, obtain it for OpenWrt from the package "iptables-mod-conntrack" previously:
http://wiki.openwrt.org/doc/howto/netfilter#modules_for_matchtarget

However, I cannot find this package in Entware. I wonder if may have been there in the past and has been removed? Anyway, would it make sense to add some of these packages, or add an "iptables" package if "iptables-mod-conntrack" is integrated in there?
