### ISSUE TITLE
[BUG?] How to change default user/group when installing packages ?

### ISSUE THREAD

**Issue by ulyssesric** [Entware/Entware#180]
I'm trying to install package [at] on QNAP / QTS 4.3.4.0644 and I've got this error message:

`[~] # opkg install at`
`Installing at (3.1.20-1) to root...`
`Downloading http://bin.entware.net/x64-k3.2/at_3.1.20-1_x64-3.2.ipk`
`Configuring at.`
`chown: unknown user/group nobody:nobody`
`check owner of /opt/var/spool/cron/atjobs`
`chown: unknown user/group nobody:nobody`
`check owner of /opt/var/spool/cron/atspool`
`[~] # at`
`Cannot get uid for nobody: Success`
`[~] # atq`
`Cannot get uid for nobody: Success`
`[~] # atrm`
`Cannot get uid for nobody: Success`

There is no user/group `nobody` in QTS, only `admin`:

`[~] # id`
`uid=0(admin) gid=0(administrators) groups=0(administrators),100(everyone)`

Is there any way to change the default user/group when installing packages ?

**Comment by zyxmon** [comment]
> Is there any way to change the default user/group when installing packages ?

If you use alternative install script, you will have full control over users and groups in Entware. These users and groups will be independent on Qanp firmware.
Another option is to add missing users and groups in Qnap firmware.

Entware is a universal repo for many devices. Different devices have different preconfigured users and groups.

**Comment by ulyssesric** [comment]
> If you use alternative install script, you will have full control over users and groups in Entware. These users and groups will be independent on Qanp firmware.

OK then where can I find that alternative install script ? All I need is making `atd` able to work on Qnap. Tried to post on Qnap forum and StackOverflow but got no response.

**Comment by zyxmon** [comment]
Please read my answer on qnap forum.
