### ISSUE TITLE
Python2.7 & Python3.5 - Error loading shared library libpython*.*.so.1.0 

### ISSUE THREAD

**Issue by victordeleau** [Entware/Entware#181]
Hi. I installed opkg on a A68U with a DD-WRT v3.0-r37015M kongac build. I want to have python2.7 or python3.5 working on the router. So I installed those packages with opkg to my jffs partition by binding /opt to /jffs/opt. For both python 2.7 and 3.5 the command line interpreter is working well, but when starting some python programs I get the following error:

Error loading shared library libpython3.5.so.1.0: No such file or directory (needed by /opt/usr/bin/python3.5)
Error relocating /opt/usr/bin/python3.5: _PyMem_RawStrdup: symbol not found
Error relocating /opt/usr/bin/python3.5: Py_Main: symbol not found
Error relocating /opt/usr/bin/python3.5: PyMem_RawFree: symbol not found
Error relocating /opt/usr/bin/python3.5: Py_DecodeLocale: symbol not found
Error relocating /opt/usr/bin/python3.5: PyMem_RawMalloc: symbol not found
Error relocating /opt/usr/bin/python3.5: PyMem_RawFree: symbol not found

Now I located the file libpython3.5.so.1.0 in the /opt/usr/lib/ folder. Is it a package problem or is it me ? Or is there a quick and dirty fix to link this file to python3.5 or 2.7 ? Thank you

**Comment by zyxmon** [comment]
You have installed some old Entware version that is not supported now (Entware-ng or Entware-3x). Current version has
```
# opkg files python3-base | grep  libpython
/opt/lib/libpython3.7.so.1.0
/opt/lib/libpython3.7.so

```
Probably you need to run
```
opkg update
opkg upgrade
```
