### ISSUE TITLE
Asterisk 11.18.x packages missing: asterisk11-res-xmpp && asterisk11-chan-motif

### ISSUE THREAD

**Issue by jpap** [Entware/entware#181]
The last version I've seen is 11.16.0-4, which no-longer loads on asterisk 11.18.0.

Without these, Google voice channels are not possible.  (My Google voice connections are down as a result.)

**Comment by jpap** [comment]
Looking at the [changelog](https://github.com/Entware/entware/wiki/Changelog), it looks like these packages were deleted intentionally.

Can we please add them back in? :D

**Comment by ryzhovau** [comment]
It was deleted by [upstream](https://github.com/openwrt/telephony) for some reasons. Most common reason it's broken.

You have to ask upstream for details.

**Comment by jpap** [comment]
Thanks Alexander. I've offered a [pull request to openwrt/telephony](https://github.com/openwrt/telephony/pull/83) that fixes this; can't wait to see it restored in Entware!
