### ISSUE TITLE
Requesting that Asterisk should be upgraded to 13

### ISSUE THREAD

**Issue by ghost** [Entware/Entware#182]
Please upgrade asterisk packages to asterisk 13. The current version is missing features like pjsip and the opus codec.

Also please use upstream as naf’s gvsip branch for google voice functionality:

https://github.com/naf419/asterisk/tree/gvsip

Here’s some research on the gvsip:
https://gvsip.info

**Comment by ryzhovau** [comment]
Вщтую

**Comment by ryzhovau** [comment]
Done.
