### ISSUE TITLE
Running daemon as nobody

### ISSUE THREAD

**Issue by thuantran** [Entware/entware#183]
Hi there,

Is it possible to run daemons as low privilege user such as nobody? I'm trying to run transmission as nobody so I can have it working it with Samba share on my Asus router RT-AC56U.

Best regards,
Thuan

**Comment by ryzhovau** [comment]
This is not a discussion platform, sorry.
Take a look at [nonroot](https://github.com/hampus/nonroot), it's in Entware.

**Comment by thuantran** [comment]
Thank you, and sorry for the inconvenience. I don't know how to reach you otherwise so I use this ;).
