### ISSUE TITLE
early patch before next sync.

### ISSUE THREAD

**Issue by odkrys** [Entware/Entware#183]
@zyxmon 
https://github.com/getdnsapi/stubby/issues/140#issuecomment-442855821

getdns patch arrived from upstream. 
But I think its too long time to wait until getdns release next stable version. 
And then, Openwrt will update it and it comes into entware.
I hope you publish patched version to repository before next sync.

**Comment by ryzhovau** [comment]
This package came from OpenWrt feed with no changes, so it's up to upstream.
Please, ask OpenWrt guys to do it.

We trying to minimize any changes with upstream, sorry.
