### ISSUE TITLE
How could I set the HOME for perl cache everytime I run perl CPAN?

### ISSUE THREAD

**Issue by Akronix** [Entware/Entware#184]
In the section of [Using CPAN](https://github.com/Entware/Entware/wiki/Self-installation-of-perl-modules#using-cpan) it says that we should set a cache dir for Perl so it doesn't use in-memory file systems.

Is there any nice way to force or automate the `HOME=` assignment so I don't forget or write it wrongly by mistake? something that set this variable before to run any Perl or any CPAN command? a shell alias maybe?

I tried setting:
`alias perl='HOME=/volume1/perl-cache perl`
at the end of the /etc/profile but it doesn't seem to work.

**Comment by zyxmon** [comment]
Please use Issues for bug reports and feature requests.
