### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by JameLeung** [Entware/entware#185]
The hardware I used is QNAP TS-653 Pro

When I tried to install the opkg using the command

wget -O - http://entware.wl500g.info/binaries/mipselsf/installer/entware_install.sh | sh

The result is like this:

......
.....
Saving to: ‘opkg.conf’

opkg.conf           100%[=====================>]     107  --.-KB/s   in 0.01s

2015-08-29 20:32:16 (10.0 KB/s) - ‘opkg.conf’ saved [107/107]

Info: Basic packages installation...
sh: line 27: /opt/bin/opkg: cannot execute binary file
sh: line 28: /opt/bin/opkg: cannot execute binary file
Info: Cleanup...
Info: Congratulations!
Info: If there are no errors above then Entware successfully initialized.
Info: Found a Bug? Please report at https://github.com/Entware/entware/issues

Any clue?

**Comment by ryzhovau** [comment]
Wrong fork. Please use [Qnapware.](https://github.com/zyxmon/qnapware).
