### ISSUE TITLE
libio-socket-ssl

### ISSUE THREAD

**Issue by Razzbiz** [Entware/Entware#186]
Package request
---
I would like libio-socket-ssl added for Entware on Asustor ADM platform.

**Comment by zyxmon** [comment]
Have you tried to add it yourself - https://github.com/Entware/Entware/wiki/Self-installation-of-perl-modules

**Comment by Razzbiz** [comment]
No I haven't.  I'm not sure how to proceed with that. I have done what was described in the github wiki  including the Manual Installation section, but I don't know how to install the libio-socket-ssl, where to get it and which version I should be using.

**Comment by kayee72** [comment]
I would alsomlike this so I can get Logitech Media Server runing on ADM with Spotify plugin
