### ISSUE TITLE
python 2.7.10-6 segfaults

### ISSUE THREAD

**Issue by jcejohnson** [Entware/entware#186]
Python segfaults when I execute it. Even a simple 'python --version'. I'm not quite sure where to start looking. Any help would be greatly appreciated.

OS:  DD-WRT v3.0-r27506 (07/09/15) big (soft-float)
Hardware: Asus RT-N66U 
opkg: 0.1.8

```
# ldd /opt/bin/python2.7
ldd: LD_LIBRARY_PATH not included in search path: it needs ld.so stand-alone execution enabled
        libpython2.7.so.1.0 => /opt/lib/libpython2.7.so.1.0 (0x77b6d000)
        libpthread.so.0 => /opt/lib/libpthread.so.0 (0x77b48000)
        libdl.so.0 => /opt/lib/libdl.so.0 (0x77b35000)
        libutil.so.0 => /opt/lib/libutil.so.0 (0x77b24000)
        libz.so.1 => /opt/lib/libz.so.1 (0x77b00000)
        libm.so.0 => /opt/lib/libm.so.0 (0x77adb000)
        libc.so.0 => /opt/lib/libc.so.0 (0x77a28000)
        ld-uClibc.so.0 => /opt/lib/ld-uClibc.so.0 (0x77d22000)
```

**Comment by zyxmon** [comment]
It does not segfault on ZyXEL Keenetic Ultra that uses the same mipselsf feed
    /opt/etc/init.d # python --version
    Python 2.7.10

**Comment by jcejohnson** [comment]
What OS are you using? Could the 3x kernel be an issue?

**Comment by ryzhovau** [comment]
DD-WRT is the most weird firmware I ever seen, sorry. Too many unexplainable bugs with different software, which is rock-stable on other firmwares. 

Kernel 3.x is not an issue. Checked on RT-N56U/65U routers with Padanan's f\w, there is no issues with python packages on linux-3.0.x or linux-3.4.x.

**Comment by jcejohnson** [comment]
Do you have a recommended firmware for the RT-N66U?
