### ISSUE TITLE
Add Dante package

### ISSUE THREAD

**Issue by zoocey** [Entware/entware#187]
http://www.inet.no/dante/
Note: Dante is both a SOCKS server and client. The client part is unnecessary to me.

**Comment by ryzhovau** [comment]
Can't see any reasons to add another proxy server for this moment, sorry. I'll keep this issue open for couple of months too see if someone wants the Dante too.

**Comment by zoocey** [comment]
The reason I want it is that it is one of the few/only SOCKS5 severs that supports UDP traffic. (SSH and Srelay don't). See https://superuser.com/questions/639425/linux-socks5-tunneling-not-working-with-udp-traffic. I understand it is a very fringe use case.

**Comment by ryzhovau** [comment]
Got it. 

To be continued here - https://github.com/Entware-ng/Entware-ng/issues/13
