### ISSUE TITLE
Package request: transmission-create

### ISSUE THREAD

**Issue by SpamBot2** [Entware/Entware#188]
Package request
---
It allows to create torrents, and it's included with transmission-daemon in most repos

- [x] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my ArmV7 QNAP NAS and get a feedback about it.

**Comment by zyxmon** [comment]
transmission-cli* packages have transmission-create binary inside.
