### ISSUE TITLE
Package request: vnstat 2.1 (update)

### ISSUE THREAD

**Issue by J0s3f** [Entware/Entware#189]
Package request
---
vnstat gained the ability to output traffic statistics in 5min intervals instead of the hour intervals in 1.18

Downside might be that it uses sqlite for databases now and thus depeds on sqlite. (I don't see this as downside)

**Comment by ryzhovau** [comment]
As long as it came from upstream, It's up to OpenWrt guys. 
Please, [ask](https://github.com/openwrt/packages/issues) them about it.
