### ISSUE TITLE
shadowsocks (.ipk) packages are broken

### ISSUE THREAD

**Issue by starter48** [Entware/entware#189]
Both required binaries (/opt/bin/ss-server and /opt/bin/ss-local, referenced from /opt/etc/init.d/S22shadowsocks) is absent in the following packages:
http://entware.wl500g.info/binaries/entware/shadowsocks-libev-polarssl_2.2.2-1_entware.ipk
http://entware.wl500g.info/binaries/entware/shadowsocks-libev_2.2.2-1_entware.ipk

**Comment by ryzhovau** [comment]
Not sure I understand how it must be started right, so I deleting start script until somebody will contribute new one.

**Comment by starter48** [comment]
The script is right! I have previous build of this package installed, and both ss-server and ss-local are there. Shadowsocks package must contain at least 4 binaries:

**Comment by ryzhovau** [comment]
There is no more `ss-local` and `ss-server` binaries, the newer versions [contains](https://github.com/openwrt/packages/blob/master/net/shadowsocks-libev/Makefile) `ss-redir` and `ss-tunnel` bins.

**Comment by starter48** [comment]
Yes, currently it contains only 2 of 3 clients, and no server.
But I see [Shadowsocks/openwrt](https://github.com/shadowsocks/shadowsocks-libev/blob/master/openwrt/Makefile) still contains **ss-local** client, however no **ss-server**...  May be they plan to separate a server part into another package...
2All: If somebody need it, I've put both [**ss-local** and **ss-server** binaries v2.2.1, dated May 2015, here](http://pcb.tomsk.ru/ss-local-server.tgz) from previous release.

**Comment by ryzhovau** [comment]
You can find previous versions of any package [here](http://entware.wl500g.info/binaries/entware/archive/).

**Comment by mklnz** [comment]
I ran into this problem yesterday, apart from using an old version - anyone have any idea with what's going on with the future of this package?
