### ISSUE TITLE
Package request: procmail

### ISSUE THREAD

**Issue by fnxweb** [Entware/Entware#19]
### Package: procmail

[Website](http://www.procmail.org/)
Exists in openwrt (under [packages/utils](https://dev.openwrt.org/browser/packages/utils/procmail/) - don't know why not under _mail_).

I only know of one alternative: maildrop; neither seems to be in Entware-NG yet, and procmail appears to be the most commonly used (and is the one I currently use).

It allows on-delivery mail filtering (just prior to local mail delivery, from such as sendmail/postfix), mailing-list filtering, interaction with spamassassin).

While not _updated_ in years, is not thought of as abandoned, as it is effectively just “finished”, and has no significant outstanding issues (and continues to pass new static analysis tests/compiler analyses). Still shipped with major Linux distros.

### Platform:

My platform is an x86_64 QNAP.

**Comment by ryzhovau** [comment]
Please, consider using `imapfiler` and other tools.

Procmail is effectively dead, including home page.
