### ISSUE TITLE
Request for GNU which package

### ISSUE THREAD

**Issue by JediNite** [Entware/entware#190]
Hi,

I was wondering if it would be possible to add the GNU which package to the entware repository as it would be useful to quickly find out where in the PATH certain binaries are being run from (especially when used to override native commands with stock firmware).

Cheers,

JediNite

**Comment by lancethepants** [comment]
Just curious what firmware you're running. I'd be surprised that it doesn't already include 'which'. I know it tomato some functionalities are built into busybox, but don't have a symlink created, ie, awk.

**Comment by JediNite** [comment]
Lance,

I'm actually running Qnapware on a WD EX4100 NAS (Arm based CPU), so a little bit removed from Entware, but know how Qnapware is a downstream release based on Entware so thought the request should be placed here.

Let me know if you think the request might be better in the qnapware issues page instead.

Cheers,

JediNite

**Comment by lancethepants** [comment]
I was just curious what environment wouldn't have 'which'.  I would assume it's fine to request here though.

**Comment by zyxmon** [comment]
@JediNite - you can install busybox on your NAS. It has which applet.

**Comment by JediNite** [comment]
@zyxmon - I just tried it on my NAS and you are indeed correct.  Thanks for the tip.  I'll close this issue...
