### ISSUE TITLE
git is broken

### ISSUE THREAD

**Issue by zyxmon** [Entware/entware#191]
symlinks in /opt//lib/git-core are broken. This leads to errors in "git pull" and other commands

    /opt/lib/git-core/git-pull: line 340: exec: git-merge: not found
    fatal: 'pull' appears to be a git command, but we were not able to execute it. Maybe git-pull is broken?

Adding a symlink

     ln -s /opt/bin/git /opt/lib/git-core/git

fixes the error

**Comment by ryzhovau** [comment]
Fixed in https://github.com/entware-ng
