### ISSUE TITLE
Package update request: pyload

### ISSUE THREAD

**Issue by skydreamer888** [Entware/Entware#192]
The pyload package in the repository is quite old. Please provide an updated package [(https://github.com/pyload/pyload/archive/stable.zip)](https://github.com/pyload/pyload/archive/stable.zip). Thank you very much.

**Comment by ryzhovau** [comment]
We see no sense to catch every beta release and relying on [releases](https://github.com/pyload/pyload/releases) only. 

Also, pyload can update it's code in runtime.
