### ISSUE TITLE
Please restore asterisk18-chan-gtalk and asterisk11-chan-motif packages

### ISSUE THREAD

**Issue by fktpa813** [Entware/entware#192]
asterisk18-chan-gtalk and asterisk11-chan-motif packages are no longer getting built. Package asterisk18-chan-gtalk was still present in 1.8.32.2-3, but it's not in 1.8.32.3-3. The module from 1.8.32.2-3 can't be loaded with the 1.8.32.3-3 binaries.
Not sure from what version the asterisk11-chan-motif stopped getting built.

Please restore these packages - they are still fully functional.

**Comment by ryzhovau** [comment]
Duplicate of https://github.com/Entware/entware/issues/181

**Comment by fktpa813** [comment]
Yes, it's a duplicate -  but it's still not fixed in Entware.
Upstream restored the packages by this commit: https://github.com/openwrt/telephony/commit/7fb39ad0fc9152e999c19442bbe47248bc2c241f

But in Entware they are still disabled by default by settings in buildroot/.config (since this commit: 
https://github.com/Entware/entware/commit/69eedcd99b94a55a37879c1fe45c04f8c75788e8)

To restore packages in Entware, the following settings should be changed in buildroot/.config:
CONFIG_PACKAGE_asterisk11-chan-motif=m
CONFIG_PACKAGE_asterisk11-res-xmpp=m
CONFIG_PACKAGE_asterisk18-chan-gtalk=m
