### ISSUE TITLE
Download GO_rclone-1.45-1.tar.bz2  404 error

### ISSUE THREAD

**Issue by earthGavinLee** [Entware/Entware#193]
curl: (22) The requested URL returned error: 404 OK
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.lede-project.org/GO_rclone-1.45-1.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 OK
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/GO_rclone-1.45-1.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 OK
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.openwrt.org/sources/GO_rclone-1.45-1.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    189      0 --:--:-- --:--:-- --:--:--   189
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 404 OK
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://src.entware.net/GO_rclone-1.45-1.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 OK

**Comment by zyxmon** [comment]
We are now updating Entware. Some packages may fail to compile for some feeds.
As for GO* packages - I have uploaded the sources a minute ago. You can always comment one line - https://github.com/Entware/entware-go/blob/master/rclone/Makefile#L17 not to wait for the sources to be uploaded.
