### ISSUE TITLE
valgrind error

### ISSUE THREAD

**Issue by earthGavinLee** [Entware/Entware#195]
k_mips32_linux-mc_machine.o memcheck_mips32_linux-mc_errors.o ../coregrind/libcoregrind-mips32-linux.a ../VEX/libvex-mips32-linux.a -lgcc 
 {standard input}: Assembler messages:
{standard input}:88106: Error: `fp=64' used with a 32-bit fpu
{standard input}:88110: Error: opcode not supported on this processor: mips32 (mips32) `cvt.s.l $f24,$f24'
{standard input}:88131: Error: `fp=64' used with a 32-bit fpu
{standard input}:88135: Error: opcode not supported on this processor: mips32 (mips32) `cvt.l.d $f24,$f24'
{standard input}:88156: Error: `fp=64' used with a 32-bit fpu
{standard input}:88160: Error: opcode not supported on this processor: mips32 (mips32) `cvt.l.s $f24,$f24'
{standard input}:88181: Error: `fp=64' used with a 32-bit fpu
{standard input}:88185: Error: opcode not supported on this processor: mips32 (mips32) `cvt.d.l $f24,$f24'
{standard input}:88205: Error: `fp=64' used with a 32-bit fpu
{standard input}:88229: Error: `fp=64' used with a 32-bit fpu
{standard input}:88254: Error: `fp=64' used with a 32-bit fpu
{standard input}:88279: Error: `fp=64' used with a 32-bit fpu
{standard input}:88304: Error: `fp=64' used with a 32-bit fpu
{standard input}:88329: Error: `fp=64' used with a 32-bit fpu
{standard input}:88354: Error: `fp=64' used with a 32-bit fpu
{standard input}:88358: Error: opcode not supported on this processor: mips32 (mips32) `trunc.l.d $f24,$f24'
{standard input}:88379: Error: `fp=64' used with a 32-bit fpu
{standard input}:88383: Error: opcode not supported on this processor: mips32 (mips32) `trunc.l.s $f24,$f24'
{standard input}:88404: Error: `fp=64' used with a 32-bit fpu
{standard input}:88429: Error: `fp=64' used with a 32-bit fpu
{standard input}:88454: Error: `fp=64' used with a 32-bit fpu
{standard input}:88458: Error: opcode not supported on this processor: mips32 (mips32) `round.l.d $f24,$f24'
{standard input}:88479: Error: `fp=64' used with a 32-bit fpu
{standard input}:88483: Error: opcode not supported on this processor: mips32 (mips32) `round.l.s $f24,$f24'
{standard input}:88504: Error: `fp=64' used with a 32-bit fpu
{standard input}:88528: Error: `fp=64' used with a 32-bit fpu
{standard input}:88553: Error: `fp=64' used with a 32-bit fpu
{standard input}:88557: Error: opcode not supported on this processor: mips32 (mips32) `floor.l.d $f24,$f24'
{standard input}:88578: Error: `fp=64' used with a 32-bit fpu
{standard input}:88582: Error: opcode not supported on this processor: mips32 (mips32) `floor.l.s $f24,$f24'
{standard input}:88603: Error: `fp=64' used with a 32-bit fpu
{standard input}:88628: Error: `fp=64' used with a 32-bit fpu
{standard input}:88652: Error: `fp=64' used with a 32-bit fpu
{standard input}:88656: Error: opcode not supported on this processor: mips32 (mips32) `ceil.l.d $f24,$f24'
{standard input}:88676: Error: `fp=64' used with a 32-bit fpu
{standard input}:88680: Error: opcode not supported on this processor: mips32 (mips32) `ceil.l.s $f24,$f24'
{standard input}:88701: Error: `fp=64' used with a 32-bit fpu
{standard input}:88726: Error: `fp=64' used with a 32-bit fpu
lto-wrapper: fatal error: mipsel-openwrt-linux-gnu-gcc returned 1 exit status
compilation terminated.
/mnt/Ext4Datapart/OpenWRT/Entware/staging_dir/toolchain-mipsel_mips32r2_gcc-7.3.0_glibc-2.27/lib/gcc/mipsel-openwrt-linux-gnu/7.3.0/../../../../mipsel-openwrt-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
Makefile:1017: recipe for target 'memcheck-mips32-linux' failed
make[7]: *** [memcheck-mips32-linux] Error 1
make[7]: Leaving directory '/mnt/Ext4Datapart/OpenWRT/Entware/build_dir/target-mipsel_mips32r2_glibc-2.27/valgrind-3.14.0/memcheck'
Makefile:1323: recipe for target 'all-recursive' failed
make[6]: *** [all-recursive] Error 1
make[6]: Leaving directory '/mnt/Ext4Datapart/OpenWRT/Entware/build_dir/target-mipsel_mips32r2_glibc-2.27/valgrind-3.14.0/memcheck'
Makefile:835: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/mnt/Ext4Datapart/OpenWRT/Entware/build_dir/target-mipsel_mips32r2_glibc-2.27/valgrind-3.14.0'
Makefile:704: recipe for target 'all' failed
make[4]: *** [all] Error 2

**Comment by ryzhovau** [comment]
Please, update package and try again.
