### ISSUE TITLE
Add Pcap_DNSProxy

### ISSUE THREAD

**Issue by houzi-** [Entware/entware#196]
A local DNS server based on WinPcap and LibPcap.
Pcap_DNSProxy is a tool based on WinPcap/LibPcap for filtering DNS contamination, providing support for regular expressions of Hosts to provide more convenient and powerful method to modify the Hosts, as well as the DNSCurve/DNSCrypt protocol, parallel and TCP protocol request support. Multi server parallel request function, it can improve the reliability of the domain name resolution in the bad network environment.

Do not know whether you can add support?

https://github.com/wongsyrone/openwrt-Pcap_DNSProxy

**Comment by ryzhovau** [comment]
To be continues here - https://github.com/Entware-ng/Entware-ng/issues/15
