### ISSUE TITLE
Restore asterisk18-chan-gtalk and asterisk11-chan-motif packages

### ISSUE THREAD

**Issue by fktpa813** [Entware/entware#199]
I don't have permissions to re-open issues, so I have to create a new one since the issue #192 has been closed (as duplicate of issue #181), but it's not fixed in Entware.

Upstream restored the Asterisk packages by this commit: openwrt/telephony@7fb39ad. But in Entware they are still disabled by default via settings in buildroot/.config (since this commit: 
69eedcd).

To restore packages in Entware, the following settings should be changed in buildroot/.config:
CONFIG_PACKAGE_asterisk11-chan-motif=m
CONFIG_PACKAGE_asterisk11-res-xmpp=m
CONFIG_PACKAGE_asterisk18-chan-gtalk=m

Thank you!

**Comment by ryzhovau** [comment]
https://github.com/Entware/entware#note
