### ISSUE TITLE
Package request: mergerfs 

### ISSUE THREAD

**Issue by quekky** [Entware/Entware#199]
Package request: mergerfs 
---
https://github.com/trapexit/mergerfs

- Support for extended attributes (xattrs)
- Support for file attributes (chattr)
- Runtime configurable (via xattrs)
- Handling of writes to full drives (transparently move file to drive with capacity)

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by zyxmon** [comment]
We have unionfs in Entware. What are the killer features of mergefs compared with unionfs?

**Comment by quekky** [comment]
mergefs have policy, so you can choose where to put new files at (eg first found, least free space, most free space, etc)

unionfs is kindof unpredictable, so new files sometimes goes to the wrong place


mergefs  allows runtime editing of mounts (https://zackreed.me/mergerfs-neat-tricks/)
