### ISSUE TITLE
busybox.postinst

### ISSUE THREAD

**Issue by kaztost** [Entware/Entware#20]
To avoid the error
_sh: /opt/bin/busybox: unknown operand_
during installation, instead of
_...
for file in /opt/sbin/*; do
    if [ -L $file  -a \`/opt/bin/busybox readlink -f $file\` = $bb_fc ]; then
       /opt/bin/busybox rm -f $file
    fi
done
..._
should be something like
_...
for file in /opt/sbin/*; do
    if [ -L $file  -a x\`/opt/bin/busybox readlink -f $file\` = x$bb_fc ]; then
       /opt/bin/busybox rm -f $file
    fi
done
..._

**Comment by zyxmon** [comment]
Thanks. Fixed via https://github.com/Entware/Entware/commit/777606ea27b201e3e57420e733ca2529ca8e38cf
