### ISSUE TITLE
fish error

### ISSUE THREAD

**Issue by earthGavinLee** [Entware/Entware#200]
. /mnt/Ext4Datapart/OpenWRT/Entware/include/shell.sh; gzip -dc /mnt/Ext4Datapart/OpenWRT/Entware/dl/fish-2.7.1.tar.gz | tar -C /mnt/Ext4Datapart/OpenWRT/Entware/build_dir/target-mipsel_mips32r2_glibc-2.27/fish-2.7.1/.. -xf - 
[ ! -d ./src/ ] || cp -fpR ./src/. /mnt/Ext4Datapart/OpenWRT/Entware/build_dir/target-mipsel_mips32r2_glibc-2.27/fish-2.7.1

Applying ./patches/001-no-hostname-and-whoami.patch using plaintext: 
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/share/functions/prompt_hostname.fish b/share/functions/prompt_hostname.fish
|index 4348bce2..8502ce3f 100644
|--- a/share/functions/prompt_hostname.fish
|+++ b/share/functions/prompt_hostname.fish
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 18
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/share/tools/web_config/sample_prompts/pythonista.fish b/share/tools/web_config/sample_prompts/pythonista.fish
|index 9529035c..57ffaf86 100644
|--- a/share/tools/web_config/sample_prompts/pythonista.fish
|+++ b/share/tools/web_config/sample_prompts/pythonista.fish
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 31
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/share/tools/web_config/sample_prompts/screen_savvy.fish b/share/tools/web_config/sample_prompts/screen_savvy.fish
|index 411a5501..5cdcfb69 100644
|--- a/share/tools/web_config/sample_prompts/screen_savvy.fish
|+++ b/share/tools/web_config/sample_prompts/screen_savvy.fish
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 46
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/share/tools/web_config/sample_prompts/terlar.fish b/share/tools/web_config/sample_prompts/terlar.fish
|index d49ef340..59b3d267 100644
|--- a/share/tools/web_config/sample_prompts/terlar.fish
|+++ b/share/tools/web_config/sample_prompts/terlar.fish
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch failed!  Please fix ./patches/001-no-hostname-and-whoami.patch!
Makefile:71: recipe for target '/mnt/Ext4Datapart/OpenWRT/Entware/build_dir/target-mipsel_mips32r2_glibc-2.27/fish-2.7.1/.prepared_f329c0c5c287b9b5bc7bd3ecc0367f15_6664517399ebbbc92a37c5bb081b5c53' failed
make[3]: *** [/mnt/Ext4Datapart/OpenWRT/Entware/build_dir/target-mipsel_mips32r2_glibc-2.27/fish-2.7.1/.prepared_f329c0c5c287b9b5bc7bd3ecc0367f15_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/mnt/Ext4Datapart/OpenWRT/Entware/feeds/packages/utils/fish'
time: package/feeds/packages/fish/compile#0.22#0.13#1.55
package/Makefile:107: recipe for target 'package/feeds/packages/fish/compile' failed
make[2]: *** [package/feeds/packages/fish/compile] Error 2
make[2]: Leaving directory '/mnt/Ext4Datapart/OpenWRT/Entware'
package/Makefile:103: recipe for target '/mnt/Ext4Datapart/OpenWRT/Entware/staging_dir/target-mipsel_mips32r2_glibc-2.27/stamp/.package_compile' failed
make[1]: *** [/mnt/Ext4Datapart/OpenWRT/Entware/staging_dir/target-mipsel_mips32r2_glibc-2.27/stamp/.package_compile] Error 2
make[1]: Leaving directory '/mnt/Ext4Datapart/OpenWRT/Entware'
/mnt/Ext4Datapart/OpenWRT/Entware/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
gavin@Dell:/mnt/Ext4Datapart/OpenWRT/Entware$

**Comment by ryzhovau** [comment]
Works for me.
Can't reproduce it, sorry.
