### ISSUE TITLE
Add package ruby-dev

### ISSUE THREAD

**Issue by manoloonline** [Entware/entware#203]
Thank you for your work!

It will be very usefull for everybody have the package "ruby-dev" in the repository, it is necesary for installing a lot of gems of ruby and one of the most important gems Rails Framework. Without this package the log of installing it is always the same:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
...
mkmf.rb can't find header files for ruby at /opt/lib/ruby/include/ruby.h
```

I will be very gratefull and I suposse thounsands of people.

**Comment by ryzhovau** [comment]
https://github.com/Entware/entware#note
