### ISSUE TITLE
install guide not work for ds214play (platform i686)

### ISSUE THREAD

**Issue by jheroy** [Entware/Entware#203]
Package request
---
install guide

**Comment by zyxmon** [comment]
Entware developers do not have synology nases to check Entware. We cannot help you without any logs and additional info.

**Comment by jheroy** [comment]
I use this command to install    `wget -O -
http://bin.entware.net/x64-k3.2/installer/generic.sh | /bin/sh`

/bin/sh: line 43: /opt/bin/opkg: cannot execute binary file: Exec format
error
/bin/sh: line 44: /opt/bin/opkg: cannot execute binary file: Exec format
error

**Comment by zyxmon** [comment]
It looks like your kernel does not have 64 bit support. What is the output of 'uname -a'. In case your kernel is 32 bit, you can install Entware-ng. But it is not supported and updated.

**Comment by jheroy** [comment]
Thanks ，its works for me.

zyxmon <notifications@github.com>于2018年12月25日 周二下午4:53写道：
