### ISSUE TITLE
Fix i2pd init script

### ISSUE THREAD

**Issue by dartraiden** [Entware/Entware#204]
i2pd на старте не может найти требуемые сертификаты:
```
warn - Family: Can't load family certificates from /opt/var/lib/i2pd/certificates/family
warn - Reseed: Can't load reseed certificates from /opt/var/lib/i2pd/certificates/reseed
```

логично, поскольку при установке пакета сертификаты помещаются в /opt/share/i2pd. Без этого дальнейшая работа невозможна:
`error - NetDb: runtime exception: No known routers, reseed seems to be totally failed`
 
Аналогичная проблема и с tunnels.conf, он расположен в /opt/etc/i2pd, но i2pd безуспешно будет пытаться найти его в рабочем каталоге /opt/var/lib/i2pd

Похоже, что init писался на основе OpenWrt-шного, там была такая же несостыковка, которую решили созданием симлинков при каждом запуске
https://github.com/openwrt/packages/commit/86106ecb8020645a932c237f635424198734ddf6

Таким образом, имеет смысл:
- дополнить init-скрипт созданием симлинков на certificates и tunnels.conf
- возможно, переименовать сам init-скрипт, который сейчас называется S30i2p (должно быть S30i2pd?)
- возможно, убрать из init-скрипта явное указание пути к pid-файлу и лог-файлу, поскольку эти пути уже присутствуют в i2pd.conf
- почему-то после успешного выполнения команды `/opt/etc/init.d/S30i2p stop` pid-файл остаётся лежать в /var/run

**Comment by ryzhovau** [comment]
> Похоже, что init писался на основе OpenWrt-шного

Изначально это наш пакет, позже затащенный в OpenWrt.
Спасибо за репорт. Действительно, это наш [косяк](https://github.com/Entware/entware-packages/commit/4150fbb627b90a3cc503b19e7c37f2bcd177dd68#diff-e55a23c0fe1b9b382562440f26c5c537) в процессе проведения последней синхронизации с OpenWrt.

**Comment by dartraiden** [comment]
Да, вижу, проблема с tunnels.conf, получается, решалась (до синхронизации) простым указанием пути к нему в конфиге, поэтому остаётся только вопрос с симлинком на сертификаты.

**Comment by ryzhovau** [comment]
Если приглядется, пакет в OpenWrt не в самой лучшей форме:

* subscriptions.txt не используются, а если бы использовались, то всё равно deprecated,
* конфиги копируются с помощью `$(INSTALL_BIN)` вместо `$(INSTALL_CONF)`  и перечислены в conffiles через TAB, в итоге при очередном обновлении будут затёрты.

**Comment by dartraiden** [comment]
Если вернусь на OpenWrt, когда-нибудь, то надо будет поправить, да :D

**Comment by dartraiden** [comment]
Можно где-то почитать, почему subscriptions.txt deprecated? В репозитории они пока присутсвуют
https://github.com/PurpleI2P/i2pd/blob/openssl/contrib/subscriptions.txt

**Comment by ryzhovau** [comment]
https://github.com/Entware/entware-packages/commit/a5bb998912b3ea18b720dd1d36ec75ba9e9813c6
