### ISSUE TITLE
transmission: error while loading shared libraries: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kpiris** [Entware/Entware#205]
Today, “opkg upgrade” upgraded a bunch of packages on my qnap (x86_64). Amongst them:

libminiupnpc - 2.0.20170509-1 - 2.1-1
libmbedtls - 2.12.0-1 - 2.13.0-1

Then transmission stopped working:

error while loading shared libraries: libminiupnpc.so.16: cannot open shared object file: No such file or directory
error while loading shared libraries: libmbedtls.so.11: cannot open shared object file: No such file or directory

I solved the problem momentarily symlinking both shared libraries to the name transmission expects to find them

I guess transmission packages sould be upgraded to reflect the new library names.

Thanks.

**Comment by amplatfus** [comment]
It happened to me the same. I found the 17 version and copied and renamed to 16. And works well.

**Comment by amplatfus** [comment]
In my case the error was for libminiupnpc.so.16 only.

**Comment by amplatfus** [comment]
PS2: in my case transmission worked. The error appeared when tried to run add_trackers.sh.

**Comment by zyxmon** [comment]
Do not create symlinks - this can leed to bugs. Use this - https://github.com/Entware/Entware/wiki#note-about-packages-upgrade
There are also instruction in Issues - how to reinstall all libraries.

**Comment by kpiris** [comment]
Sorry for the wrong issue, did'nt know that about libraries.

Thanks!!

**Comment by amplatfus** [comment]
Thank you too. I deleted the symlink created and solved like @zyxmon said:
```
--this was the problem
user@router:/jffs/scripts# ./add_trackers.sh
transmission-remote: error while loading shared libraries: libminiupnpc.so.16: cannot open shared object file: No such file or directory

user@router:/jffs/scripts# opkg --autoremove remove transmission-web 
user@router:/jffs/scripts# opkg --autoremove remove transmission-daemon-openssl
user@router:/jffs/scripts# opkg --autoremove remove transmission-remote-openssl

user@router:/jffs/scripts# opkg install transmission-web
user@router:/jffs/scripts# opkg install transmission-daemon-openssl
user@router:/jffs/scripts# opkg install transmission-remote-openssl
--test to see if is solved
user@router:/jffs/scripts# ./add_trackers.sh
Processing torrent #2...
```

Thank you again!
