### ISSUE TITLE
Transmission not starting since last update

### ISSUE THREAD

**Issue by HazMatt69** [Entware/Entware#206]
[/opt/etc/init.d] # ./S88transmission start
 Starting transmission-daemon...              failed. 
[/opt/etc/init.d] #

**Comment by amplatfus** [comment]
A suggestion is to uninstall and install again. On your risk.

Before please take a look here:
https://github.com/Entware/Entware/issues/205#issuecomment-449954732

Good luck!

**Comment by HazMatt69** [comment]
Yeah, that's what I did but no luck :-(

**Comment by amplatfus** [comment]
I am sorry. You could try again like in the link I shared.
Good luck!

**Comment by HazMatt69** [comment]
As I've said, I tried that but it doesn't work... Thanks anyways

**Comment by zyxmon** [comment]
@HazMatt69 - you can reinstall all libs with `opkg list-installed|grep -v "libc "|sed 's/ - .*$//'|grep lib|grep -v libpthread|grep -v libgcc|xargs -n 5 opkg --force-reinstall install`.
You can also install and use ldd to find out what is wrong with libs.

**Comment by HazMatt69** [comment]
@zyxmon Thanks man!
