### ISSUE TITLE
Ruby Gems Error

### ISSUE THREAD

**Issue by templarundead** [Entware/Entware#208]
adminius@RT-AC87U:/tmp/home/root# gem install opal
ERROR:  Loading command: install (LoadError)
        failed to load encoding (Windows-31J)
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
adminius@RT-AC87U:/tmp/home/root#

**Comment by The-BB** [comment]
You need to install ruby-enc-extra and ruby-openssl packages.

**Comment by templarundead** [comment]
Спаибо!
