### ISSUE TITLE
https at the very least, DANE for some hope of security vs. MitM attacks.

### ISSUE THREAD

**Issue by lulcat** [Entware/entware#209]
Hi there.. entware is awesome as such, but downloading binaries which root uses on the router via http! and even tls (illusorytls) is backdorred by at least US agencies, it would be nice if the entware repos were set up with DANE?

I guess donations would be in order. I do use a debian local mipsel distro sometimes as an alternative but still.. Anyway, just throwing it out there for future implementations.

Toodelidoo.

**Comment by ryzhovau** [comment]
https://github.com/Entware/entware/#note
