### ISSUE TITLE
Package request: lua-dbi-*

### ISSUE THREAD

**Issue by vfiuchcikicshuusrch** [Entware/Entware#209]
Package request: lua-dbi-*
---
{lua-dbi-* is need to prosody (jabber server) support mysql (or other db)}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] I'm ready to test added package on my {armv7sf-k2.6} and get a feedback about it.
- [ ] Package is in active development (at least, not abandoned for 5 years or more),

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
We keep `prosody` as close as possible to [upstream](https://github.com/openwrt/packages/tree/master/net/prosody), so there's no lua-event, lua-zlib, bitop, icu or any other optional dependencies.

Please, [ask](https://github.com/openwrt/packages/issues) OpenWrt guys to add it and new version of prosody will arrive here during next sync.
