### ISSUE TITLE
Package request : GeoIP Legacy C API

### ISSUE THREAD

**Issue by Firmaprim** [Entware/Entware#21]
### Package: [GeoIP Legacy C API](https://github.com/maxmind/geoip-api-c) or [this](https://packages.debian.org/fr/sid/libgeoip-dev)

- make sure there's no similar package already added.
**Done.**

- describe killer features of new package.
**This package can be used with [GoAccess](https://goaccess.io/download) to get country informations about visitors of our website.**

- make sure it's open source and not abandoned (at least for last 5 years or so),
**Obviously not !**

### Platform:

- please, tell us what feed and\or devices are you using.
**Synology DS116
ARM v7**

- be ready to check issue-related changes or it will be closed after 30 days with "no response" status.
**Yes.**

**Comment by ryzhovau** [comment]
We going to keep minimal dependencies for `goaccess` and we'll keep it in current state, sorry.
