### ISSUE TITLE
Please add gprof

### ISSUE THREAD

**Issue by l-g** [Entware/Entware#211]
Package request
---
Profiling! I have a problem with another entware package and the developers have asked me to profile it.

https://sourceware.org/binutils/docs/gprof/index.html

- [X] No similar package already added and/or this one got some new killer feature(s),

```
# opkg find .*profil.*
# 
```
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
We've got `valgrind` and `orpofile`. What's the killer feature of `gprof`?
We trying to avoid to add several packages with the same purpose.

**Comment by ryzhovau** [comment]
```
opkg install binutils
```
