### ISSUE TITLE
rtorrent unable to download torrents from private trackers

### ISSUE THREAD

**Issue by qriousguy** [Entware/entware#212]
Hey,
I have an ASUS AC51U with the latest version of padavan firmware.
Yesterday, I installed rtorrent 0.9.6 and rutorrent 3.7 from entware-ng using the rtorrent easy install script.

Torrents from public torrent sites work. However, in case of private torrent websites (Tried 3) I get a tracker error.
The logs are empty.

Also, rtorrent is ignoring the rtorrent.rc file so I am unable to get detailed logs or change any settings.

Any help would be appreciated.

**Comment by ryzhovau** [comment]
We are using `rtorrent` sources with no any changes. So it's better to ask `rtorrent` author about this.
