### ISSUE TITLE
Please add nmon

### ISSUE THREAD

**Issue by d1nd141** [Entware/Entware#212]
Package request
---
nmon

Please add nmon for Linux
http://nmon.sourceforge.net/pmwiki.php
Much better to monitor System than top,iotop etc.
Also really useful in conjunction with Splunk https://splunkbase.splunk.com/app/1753/
Thanks

**Comment by ryzhovau** [comment]
Why should we add another benchmark?

**Comment by d1nd141** [comment]
You have one Gui for all (CPU, Memory, Disk IO etc....)
You can see exactly which CPU is used ("U" is user time, "s" is System time and "W" id waiting for Disk I/O time.)
Disk Writing or Reading usage(The graph shows "W" for Writing and "R" for Reading I/O)
Just please take a look at the screenshots

And as i said, it's needed for the Splunk addon which is really usefull to long time archive statistics.
(i suggest also take a look at these screenshots)

Thanks.
