### ISSUE TITLE
Package request - mdadm

### ISSUE THREAD

**Issue by xtrars** [Entware/Entware#213]
Package request
---
you can do an software raid. I have an USB-Hub and i want to combine old sticks

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my dd wrt router (WRT1200AC) and get a feedback about it.

**Comment by Dmole** [comment]
Use the "similar package" LVM2
