### ISSUE TITLE
OpenSSH, Privilege separation user sshd does not exist

### ISSUE THREAD

**Issue by kerner1000** [Entware/entware#213]
I installed entware OpenSSH on a QNAP NAS (firmware 4.2.3).

Starting the service via `/opt/sbin/sshd`, fails with 

> Privilege separation user sshd does not exist

**Comment by zyxmon** [comment]
You need to create user sshd. Please read instructions on qnap forum - https://forum.qnap.com/viewtopic.php?f=351&t=128514 and other topics.

**Comment by zyxmon** [comment]
https://github.com/Entware/entware#note

**Comment by kerner1000** [comment]
Thanks, that forum topic helped! Nevertheless, when I log-in with a non-root user, I get the following error:

```
id: cannot find name for user ID 1000
[I have no name!@j
```
