### ISSUE TITLE
coreutils-su

### ISSUE THREAD

**Issue by kerner1000** [Entware/entware#214]
How can I install the `su` command?

**Comment by ryzhovau** [comment]
https://github.com/Entware/entware#note

**Comment by kerner1000** [comment]
I read the notes thanks. It says:

> Ask new packages or report about bugs on Issues

**Comment by ryzhovau** [comment]
No, you didn't. Sorry. Please, read first sentence.

**Comment by kerner1000** [comment]
You are right, not read very carefully. Sorry for that.
