### ISSUE TITLE
Package request: tunsafe

### ISSUE THREAD

**Issue by odkrys** [Entware/Entware#215]
Package request
---
{Describe killer feature of package}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my aarch64 and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

https://github.com/TunSafe/TunSafe
TunSafe is WireGuard userspace client written in c++.
Though It doesn't look support mips yet, I executed 32bit arm version in my device successfully. (Asus RT-AC86U)

ldd ./tunsafe
```
        librt.so.1 => /lib/librt.so.1 (0xf713f000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xf703c000)
        libm.so.6 => /lib/libm.so.6 (0xf6f91000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xf6f64000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf6f3b000)
        libc.so.6 => /lib/libc.so.6 (0xf6dfd000)
        /lib/ld-linux.so.3 (0xf7156000)
```
file ./tunsafe
```
./tunsafe: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.32, stripped
```
It achieved 180Mbps in my test. (single thread)
```
iperf -l 1M -w 2M -c 10.99.99.1 -t 20 -P 2
------------------------------------------------------------
Client connecting to 10.99.99.1, TCP port 5001
TCP window size: 2.00 MByte
------------------------------------------------------------
[  4] local 10.99.99.2 port 52639 connected with 10.99.99.1 port 5001
[  3] local 10.99.99.2 port 52638 connected with 10.99.99.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-20.0 sec   247 MBytes   103 Mbits/sec
[  3]  0.0-20.1 sec   184 MBytes  76.9 Mbits/sec
[SUM]  0.0-20.1 sec   431 MBytes   180 Mbits/sec
```

I think it has worth to test.

**Comment by ryzhovau** [comment]
Looks like it poorly designed for cross-compilation. 
Some of our architectures doesn't supported at all. Can't add it, sorry.
