### ISSUE TITLE
Package request zcat

### ISSUE THREAD

**Issue by cuadedanh** [Entware/Entware#216]
Package request zcat
zcat
{Describe killer feature of package}
Basic package. When i run entware on ddwrt, no command zcat found. Because i use debootstrap to install debian but it show that zcat command not found
- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
```
opkg install gzip
```
