### ISSUE TITLE
Documentation glitch in usb-mounted start script

### ISSUE THREAD

**Issue by djromero** [Entware/entware#216]
In page https://github.com/Entware/entware/wiki/USB-Storage-setup I think there is an error.
In the usb-mounted script where it says:
```
ln -sf \$1 /tmp/opt
```

shouldn't it say:
```
ln -sf \$1/entware /tmp/opt
```
?

**Comment by ryzhovau** [comment]
Looks like it's `asuswrt-merlin` related part, so it's absolete as a whole repo.

https://github.com/Entware/entware#note
