### ISSUE TITLE
Installation onto QNAP TS-419P II (4.3.3.02010) fails; installs x86 binaries

### ISSUE THREAD

**Issue by bentolor** [Entware/entware#218]
I have problems getting Entware to run. Following the [wiki entry for QNap](https://github.com/Entware-ng/Entware-ng/wiki/Install-on-QNAP-NAS) I downloaded [Entware-ng_0.97.qpkg](http://pkg.entware.net/binaries/x86-32/installer/Entware-ng_0.97.qpkg) and installed it using the App manager. It appears correctly installed in the app manager.

After new login:

```
-sh: /opt/etc/profile: No such file or directory
[~] # opkg
-sh: opkg: command not found
[~] # ls /opt
/opt@
[~] # ls /opt/
.list                .qpkg_icon_80.gif    .uninstall.sh        bin/                 include/             sbin/                tmp/                 var/
.qpkg_icon.gif       .qpkg_icon_gray.gif  Entware-ng.sh        etc/                 lib/                 share/               usr/                 
[~] # ls /opt/bin/
opkg*
[~] # /opt/bin/opkg 
-sh: /opt/bin/opkg: cannot execute binary file
[~] # cat /opt/etc/opkg.conf 
src/gz packages http://pkg.entware.net/binaries/x86-32
dest root /
dest ram /opt/tmp
lists_dir ext /opt/var/opkg-lists
option tmp_dir /opt/tmp
[~] # cat /proc/cpuinfo 
Processor name	: Feroceon 88F6282 rev 1 (v5l) @ 2 GHz 
BogoMIPS	: 1980.82
Features	: swp half thumb fastmult edsp 
CPU implementer	: 0x56
CPU architecture: 5TE
CPU variant	: 0x2
CPU part	: 0x131
CPU revision	: 1

Hardware	: Feroceon-KW ARM
Revision	: 0000
Serial		: 0000000000000000
[~] #
```

What am I missing?

**Comment by zyxmon** [comment]
Please read https://github.com/Entware/entware#note
This project is closed! Install Entware-ng - https://github.com/Entware-ng/Entware-ng/wiki or Entware-3x - https://github.com/Entware-for-kernel-3x/Entware-ng-3x/wiki
New installers will choose architecture automatically. You have installed intel Qnapware on an arm nas.
