### ISSUE TITLE
Package update: inadyn to version 2.5

### ISSUE THREAD

**Issue by jorhett** [Entware/Entware#218]
Package request
---
The version of inadyn is very out of date. Version 2.5 has been out for 4 months and is quite stable, and contains many more providers.

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my {platform} and get a feedback about it.

resolves entware/entware-ng#781

**Comment by ryzhovau** [comment]
It's up to OpenWrt guys. Please, [ask](https://github.com/openwrt/packages/issues) them to update package and it will arrive here during next sync.
