### ISSUE TITLE
shadowsocks-libev very slow after update to 3.xx.

### ISSUE THREAD

**Issue by zw963** [Entware/entware#219]
Hi, I use entware in my ASUS routes, AC-66U.

after update to shadowsocks 3.0.6. (original shadowsocks-libev split into seperate packages)
, i install only following needed three package:

shadowsocks-libev-config 
shadowsocks-libev-ss-redir
shadowsocks-libev-ss-tunnel

(Addtionally, we need install `rng-tool` or `haveged` to make ss-tunnel work correct.)

it worked, as a forward transparent proxy. but, very very slow now.
(previous old version is worked quite well, but, I don't remember that version all)

I can confirm the problem is happen in client,  previous old version, Youtube in my Android
phone speed is very well, but, when update to new version, Youtube only can open page,
almost could not play normally, But, if use shadowsocks android client, speed is very quickly
as usual.

So, I think maybe some issue happen for newest version, could you please told me, where
to download old shadowsocks-libev ?

Thanks

**Comment by zw963** [comment]
Please give me a link of old shadowsocks entware package, I want to tried it again for speed

**Comment by zw963** [comment]
close,  new issue here: https://github.com/Entware-ng/Entware-ng/issues/739

**Comment by ryzhovau** [comment]
https://github.com/Entware/entware#note
