### ISSUE TITLE
mount problems and could not find init.d /rc.unslug

### ISSUE THREAD

**Issue by twistuba** [Entware/Entware#219]
Hi i try to use on my zyxel542 the entware, but i have problems installing  it.

#!/bin/sh

mkdir -p /i-data/da290f2e/opt > /dev/null 2>&1
mkdir -p /opt
mount -o bind /i-data/da290f2e/opt /opt
/opt/etc/init.d/rc.unslung start
exit 0

i get a mount error : 
/ # mount -o bind /i-data/da290f2e/opt /opt
mount: wrong fs type, bad option, bad superblock on /i-data/da290f2e/opt,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

and i have the folder /opt/etc -  but init.d are not available here ...

regards Thomas

**Comment by zyxmon** [comment]
Entware developers do not have zyxel542 and cannot help you. Ask your question on Zyxel forums.
