### ISSUE TITLE
Ltrace

### ISSUE THREAD

**Issue by ryzhovau** [Entware/entware#22]
https://code.google.com/p/wl500g-repo/issues/detail?id=295

---
Could You include ltrace package to Your repo? 

http://en.wikipedia.org/wiki/Ltrace :
ltrace is a debugging utility in Linux, used to display the calls a userland application makes to shared libraries. It does this by hooking into the dynamic loading system, allowing it to insert shims which display the parameters which the applications uses when making the call, and the return value which the library call reports. ltrace can also trace Linux system calls. 

It's simular to strace program, but can trace not only kernel syscalls, and sometimes can be very useful for debugging.

Thank You.

**Comment by YasharF** [comment]
It looks like getting ltrace to compile properly on MIPS is going to be challenging per other's experience: http://www.gossamer-threads.com/lists/gentoo/mips/58396#58396

**Comment by ryzhovau** [comment]
Won't fix, too hard to cross-compile. Still, some native tools for debugging is present: gdb, ldd, binutils, strace.
