### ISSUE TITLE
fsck.ext4: error while loading shared libraries: libext2fs.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by jamieburchell** [Entware/entware#221]
On a QNAP TS-228 ARM v7 I'm getting this error all of a sudden.

I confirmed with opkg that the mentioned library was already installed.

I removed the library and installed again and fsck.ext4 worked as expected.

However, I've just run in to the same issue again. I'm thinking (but I'm not certain) that a reboot might "break" things but haven't been able to test this. It could also be the result of a new firmware update.

**Comment by zyxmon** [comment]
https://github.com/Entware/entware#note
Entware-3x is strongly recommended for your NAS! Please use appropriate place for bug reports.
Opkg system is not clever enough to update libraries in some cases. The standard way to fix it is here
http://forums.zyxmon.org/viewtopic.php?p=16474#p16474
