### ISSUE TITLE
Package request : noping

### ISSUE THREAD

**Issue by cloneman** [Entware/Entware#221]
Package request 
https://noping.cc/
https://screenshots.debian.net/package/oping
---
{Graphical Ping tool}

- [x] No similar package already added and/or this one got some new killer feature(s),
Graphical pinging , multiple host pinging, and set Type of Service to outgoing packets
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
n.b. uses needs full-fat "ping" to work (currently available in entware) and should not use busybox ping.

**Comment by ryzhovau** [comment]
We've got `apinger`, `fping`, `httping`, `mtr`, `nping` with similar purpose and features you requested.
I see no sense to add several tools with the same functions, sorry.
