### ISSUE TITLE
ruby gem

### ISSUE THREAD

**Issue by stevebovy** [Entware/entware#223]
Linux RT-AC66U_B1 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jan 31 17:32:52 CST 2018 armv7l GNU/Linux

admin-280@RT-AC66U_B1:/tmp/home/root# gem install rake
ERROR:  Loading command: install (LoadError)
        failed to load encoding (Windows-31J)
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
admin-280@RT-AC66U_B1:/tmp/home/root#

**Comment by ryzhovau** [comment]
https://github.com/Entware/entware#note
