### ISSUE TITLE
Transmission-daemon-openssl

### ISSUE THREAD

**Issue by TonyPuryer** [Entware/Entware#223]
Transmission-daemon-openssl 2.94-2 depends upon libminiupnpc.so.16 but it has been upgraded to libminiupnpc.so.17. Renaming it to xx.so.16 is a dirty workaround.

**Comment by ryzhovau** [comment]
https://github.com/Entware/Entware/wiki#note-about-packages-upgrade

**Comment by TonyPuryer** [comment]
Can you give advice rather than a link? It was update & upgrade that caused this issue. What is the proper fix?

Edit - I used opkg --autoremove remove and reinstalled as advised, it worked. Thank you.
