### ISSUE TITLE
Package request: PHP Wrapper for ImageMagick

### ISSUE THREAD

**Issue by Tost69** [Entware/Entware#224]
Package request: PECL Imagick Extension for PHP7 (https://pecl.php.net/package/imagick/3.4.3)
---

The php extension imagick.so is needed for accessing ImageMagic functions by php7 applications.
There are some popular php applications (e.g. Nextcloud) for NAS which would provide more and/or more efficient functionality when the imagick extension is available.

- [X] No similar package already added

Would be nice if this package could be added, Kind regards, Tom

**Comment by ryzhovau** [comment]
We switched from imagemagick to graphicsmagick fork recently. 
I'll keep this issue open if [gmagick](https://pecl.php.net/package/gmagick) is suitable for your needs.
