### ISSUE TITLE
modprobe command not found 

### ISSUE THREAD

**Issue by AbuYahyaa** [Entware/Entware#230]
Thanks guys for your excellent work here with Entware...

running Aarch64 on and android headless system 
I am unable to run the modprobe command while SSH'ed as root ...need it for some scripts.

I cant see a kmod package or coreutils-kmod... 
I installed a libkmod but it made no differnce

I have read it may have something to do with small modprobe option in busybox and need to select standard modprobe version. 
unsure how to do this though !

Any ideas will be much appreciated, thanks

**Comment by zyxmon** [comment]
`opkg install kmod`
