### ISSUE TITLE
Please add fim/fbi

### ISSUE THREAD

**Issue by Evidlo** [Entware/Entware#236]
Package request for [fim](https://www.nongnu.org/fbi-improved/)
---
Allows one to view png, jpg, etc. in the framebuffer.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---

**Comment by ryzhovau** [comment]
We've got no framebuffer support as long as we keep Entware firmware-independent.
