### ISSUE TITLE
Package request: Bareos (fully open source fork of Bacula)

### ISSUE THREAD

**Issue by flipsa** [Entware/Entware#239]
Package request
---
{[Bareos](https://www.bareos.org/en/) is a fully open source (AGPL v3) fork of the popular Bacula backup suite. Bareos implements a number of features which - in Bacula - are only available in the Enterprise (paid & closed source) version. See [Bareos - Why fork from Bacula?](https://www.bareos.org/en/faq/why_fork.html) for more information.

It would be really great to have Bareos available, especially since most backup features on embedded devices (such as Synology / QNAP NAS) only offer proprietary backup solutions (and possibly rsync, which is awesome but lacks all the management features a full-blown backup software needs).

Thanks for considering it and thanks for Entware in general!

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
Bacula is overkill for most of embedded devices. We won't add another fork of existing solution, sorry.
