### ISSUE TITLE
php7-mod-redis 

### ISSUE THREAD

**Issue by omega69** [Entware/Entware#24]
Package: php7-mod-redis to be added

For existing package:

    expected behavior: needed package to have redis working with owncloud
    actual behavior:

For new package to be added:

    make sure there's no similar package already added, : only opcache which is not mentioned on any Owncloud wiki

    describe killer features of new package, > memory caching for Owncloud. This package is missing for Redis to work. Current redis package 4.0.6-1

    make sure it's open source and not abandoned (at least for last 5 years or so), : yes

    please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

Platform:

    please, tell us what feed and\or devices are you using > AC56U latest RMerlin
    be ready to check issue-related changes or it will be closed after 30 days with "no response" status.

**Comment by darkrain88** [comment]
https://github.com/pewpewu/phpredis-php7

already included
