### ISSUE TITLE
Urlsnarf package

### ISSUE THREAD

**Issue by tylut** [Entware/Entware#240]
Can I add the urlsnarfa package to dsniff? Please:)

**Comment by tylut** [comment]
Can I add the urlsnarfa package to dsniff? Please:)

**Comment by ryzhovau** [comment]
Which [target](https://bin.entware.net/) you are using?
```
~ # opkg install dsniff 
~ # opkg files dsniff | grep urlsnarf
/opt/sbin/urlsnarf
```
