### ISSUE TITLE
Package request: proxychains

### ISSUE THREAD

**Issue by razielaka** [Entware/Entware#242]
Package request: proxychains
---
proxychains ng (new generation) - a preloader which hooks calls to sockets in dynamically linked programs and redirects it through one or more socks/http proxies.
https://github.com/rofl0r/proxychains-ng
Many websites cannot be accessed direct from my country. I need proxychains on my router to temporarily redirect specific apps network usage through proxy.

- [yes] No similar package already added and/or this one got some new killer feature(s),
- [yes] Package is in active development (at least, not abandoned for 5 years or more),
- [yes] I'm ready to test added package on my {mipsel RT-N66U} and get a feedback about it.

**Comment by ryzhovau** [comment]
We discussed this kind of utilities few years ago and found it quite useless, sorry.

It can be handy to (rare) programs without native proxy support, but this LD_PRELOAD hack works unstable is some cases.

Consider using `socksify` - a part of Dante project.
