### ISSUE TITLE
armv5 kernel 2.6

### ISSUE THREAD

**Issue by ckuetbach** [Entware/Entware#248]
Am I correct, that I am stuck with entware-ng for an armv5 with kernel 2.6 (Zyxel NSA325v2)?

Would it be possible to create pakages for this combination? armv7 are available for older kernel.

**Comment by ryzhovau** [comment]
We won't do that, sorry. 
Too many limitations with old kernel.

Somebody tried to do it with NSA310 before, you may follow discussion [here](https://t.me/Entware/3012).
