### ISSUE TITLE
Package update: Monit to version 5.25.3

### ISSUE THREAD

**Issue by JACK-THINK** [Entware/Entware#252]
Package update: Monit to version 5.25.3 (Current Version: 5.25.2)

**Comment by ryzhovau** [comment]
This package came from [upstream](https://github.com/openwrt/packages/blob/master/admin/monit/Makefile) with no any changes.

Please, [ask](https://github.com/openwrt/packages/issues) maintainers to update it, the new version will arrive here during next sync.
