### ISSUE TITLE
Package list seems to be incomplete

### ISSUE THREAD

**Issue by robolaf** [Entware/Entware#253]
Hi,
I tried to install zlib on MIPS. The package seems to be available - but it is not listed in  http://bin.entware.net/mipssf-k3.4/Packages and hence cannot be installed. 
BTW: There are other packages missing as well. 

How can I fix that?

Thanks.

**Comment by ryzhovau** [comment]
Thanks for report! That's was a bug on our side.

Don't mind, the uprising of robots is suppressed on earlier steps.
