### ISSUE TITLE
Can't update the Package List

### ISSUE THREAD

**Issue by JACK-THINK** [Entware/Entware#254]
I have installed Entware at 18:00, 2019/3/25 UTC+8.
But something wrong happens as following
`opkg update` gives out
![1](https://user-images.githubusercontent.com/21015855/54896706-697e7400-4f00-11e9-88c2-4549a7037439.png)

But in the repo, the current Package List should be like this.
![2](https://user-images.githubusercontent.com/21015855/54896729-82872500-4f00-11e9-9384-bc6014d63ec6.png)

Apparently, `opkg update` didn't update its database. How to fix this problem?

**Comment by zyxmon** [comment]
```
~ # opkg update
Downloading http://bin.entware.net/armv7sf-k2.6/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
~ # ls -al /opt/var/
lock/        log/         opkg-lists/  run/
~ # ls -al /opt/var/opkg-lists/
drwxr-xr-x    2 root     root          4096 Mar 25 08:37 .
drwxr-xr-x    6 root     root          4096 May 12  2018 ..
-rw-r--r--    1 root     root        358703 Mar 25 08:37 entware

```
Just update web page. Package index was updated 2 or 3 times when some packages were fixed and updated.
