### ISSUE TITLE
Package: transmission-cfp

### ISSUE THREAD

**Issue by cfpp2p** [Entware/Entware#26]
### Package: transmission-cfp

re: entware-ng merge
existing package transmission-cfp
there is important updtaes to the DHT, and updates to cURL implementation.

PKG_NAME:=transmission-cfp
PKG_VERSION:=2.77plus-20180220
PKG_REV:=d0c97a058d1d5f81028d3b91f209d36582cfc756
PKG_RELEASE:=1

thank you

**Comment by zyxmon** [comment]
Thanks
Upgraded via https://github.com/Entware/rtndev/commit/7e8934e2ecb5664025f63b014c40883036173dba
binaries will be available with next repo build.

**Comment by zyxmon** [comment]
upgraded via https://github.com/Entware/rtndev/commit/7e8934e2ecb5664025f63b014c40883036173dba
binaries will be available with nex repo build.
