### ISSUE TITLE
trouble wget'ing upgrades/installing fresh on R7000 dd-wrt

### ISSUE THREAD

**Issue by 8VhyJEYUH71CGe60** [Entware/Entware#266]
Hi,
I tried rolling the latest upgrade last week and something broke.
Now I can't even install fresh entware (sh generic.sh).
My wget is dd-wrt's busybox.
My issue is that wget seems to stall mid download from bin.entware.net and pkg.entware.net (after waiting get generic error (code 1)).
editing generic.sh to curl instead of wget works, but then i get stuck on "opkg install entware-opt" (due to underlying wget).
Is there currently an issue with the server(s)? tcpdump seems to suggest the servers stop responding out of the blue.

**Comment by zyxmon** [comment]
If your busybox version 1.26.2 - it has broken wget, that downloads corrupted files from nginx powered servers. You need to use another firmware in this case.

**Comment by 8VhyJEYUH71CGe60** [comment]
I apologize I did not have the foresight to include the version number (because I already troubleshot the issue you are talking about :))
BusyBox v1.30.1 (2019-04-03 20:01:01 CEST) multi-call binary.

**Comment by zyxmon** [comment]
There are no server problems now.

**Comment by zyxmon** [comment]
You can manually download and unpack busybox (Entware version), create a symlink /opt/bin/busybox -> /opt/bin/wget and set your PATH=/opt/bin:$PATH and try again

**Comment by dnmTX** [comment]
@zyxmon  any way to substitute `wget` with `curl` when downloading packages or it's all baked in the `opkg` app? I couldn't find any additional scripts so i'm assuming it is.

**Comment by 8VhyJEYUH71CGe60** [comment]
Hi,

> 
> 
> You can manually download and unpack busybox (Entware version), create a symlink /opt/bin/busybox -> /opt/bin/wget and set your PATH=/opt/bin:$PATH and try again

Did it. 
stalled on "opkg install entware-opt" sub-process
"wget -q -O /opt/tmp/opkg-f74VXI/libgcc_7.4.0-8_armv7-3.2.ipk http://bin.entware.net/armv7sf-k3.2/libgcc_7.4.0-8_armv7-3.2.ipk"

(To show I'm not a (total) brainlet)
which wget
/opt/bin/wget

wget --help
BusyBox v1.30.1 () multi-call binary.

**Comment by zyxmon** [comment]
You need working wget in your PATH. All the requests to http://bin.entware.net/armv7sf-k3.2/libgcc_7.4.0-8_armv7-3.2.ipk" returned 200 today (server logs).

**Comment by 8VhyJEYUH71CGe60** [comment]
> 
> 
> You need working wget in your PATH. All the requests to http://bin.entware.net/armv7sf-k3.2/libgcc_7.4.0-8_armv7-3.2.ipk" returned 200 today (server logs).

Am I missing something? (serious question)

echo $PATH
/opt/bin:/bin:/usr/bin:/sbin:/usr/sbin:/jffs/sbin:/jffs/bin:/jffs/usr/sbin:/jffs/usr/bin:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin

which wget
/opt/bin/wget

ls -la /opt/bin/wget
lrwxrwxrwx    1 root     root            16 Apr  6 21:05 /opt/bin/wget -> /opt/bin/busybox

**Comment by dnmTX** [comment]
@8VhyJEYUH71CGe60  just FYI. I did test it on my end to just download that package with `wget` to some test dir of mine and all went well.I think the problem is somewhere on your end and not in general so why don't you try with `nvram erase && reboot` and go from there.
![Capture](https://user-images.githubusercontent.com/34774426/55673837-04693d80-5873-11e9-84c2-6c51b058983d.PNG)

**Comment by 8VhyJEYUH71CGe60** [comment]
> 
> 
> @8VhyJEYUH71CGe60 just FYI. I did test it on my end to just download that package with `wget` to some test dir of mine and all went well.I think the problem is somewhere on your end and not in general so why don't you try with `nvram erase && reboot` and go from there.
> ![Capture](https://user-images.githubusercontent.com/34774426/55673837-04693d80-5873-11e9-84c2-6c51b058983d.PNG)

I'm sure the problem is on my end, but that doesn't prove it works. The wgets sometimes work and sometimes don't  on my end - sometimes it stalls on packages before libgcc_7.4.0-8_armv7-3.2.ipk, sometimes after

**Comment by zyxmon** [comment]
I see no problems with installing or downloading packages from my NAS that has the same armv7 Entware version.

**Comment by zyxmon** [comment]
Some strange behaviour was observed from users that have connections through some "transparent proxies". Changing ISP (to 4G for example) helped in this cases.

**Comment by 8VhyJEYUH71CGe60** [comment]
> 
> 
> Some strange behaviour was observed from users that have connections through some "transparent proxies". Changing ISP (to 4G for example) helped in this cases.

Correct. Successfully installed w/ USB tethering.
Thank you both!

**Comment by 8VhyJEYUH71CGe60** [comment]
It *did* work. Today I got the same issues w/ 4G tether. wget froze on "opcodes" dependency for gcc.
I will continue troubleshooting my router. 
Is it possible that I am being flagged by the servers?

**Comment by zyxmon** [comment]
Nobody is blocked on servers now.

**Comment by 8VhyJEYUH71CGe60** [comment]
Can't reproduce the issue for troubleshooting w/ wireshark.

**Comment by 8VhyJEYUH71CGe60** [comment]
> 
> 
> You can manually download and unpack busybox (Entware version), create a symlink /opt/bin/busybox -> /opt/bin/wget and set your PATH=/opt/bin:$PATH and try again

FYI, no issues at all when using entware version wget (wget-ssl).
When I change back to busybox wget (of dd-wrt and of entware), or use wget-nossl the problems return.

If anyone is having similar issues in the future they can try to bootsrap entware by manually unpacking wget-ssl and by using it instead. (alternative to manually unpacking: install through opkg -> pkill wget when stuck -> install through opkg. this cowardly way *might* get you through all the dependencies a little by little. (and I'm sure entware team *won't* appreciate the extra traffic))
