### ISSUE TITLE
check_dig missing from nagios-plugins package

### ISSUE THREAD

**Issue by kiwiz** [Entware/Entware#272]
This command might've been available in an older version of the package - I have one box that _does_ have the `check_dig` command.

I'm still getting a dev environment set up for debugging, but I'll report back if I figure anything out.

**Comment by kiwiz** [comment]
Hmm, I just tried compiling the package per the Wiki instructions and I *do* get a `check_dig`. Not sure why it's missing from the resulting pkg.

**Comment by ryzhovau** [comment]
That's depends on which package compiled first: nagios-plugins or bind:). 
Thanks for report.
