### ISSUE TITLE
Request package: ttyload

### ISSUE THREAD

**Issue by jaalto** [Entware/Entware#279]
Package request: ttyload
---
https://packages.debian.org/testing/ttyload

Console based color-coded graphs of CPU load average

Display fairly standard, but hard-coded, ANSI ASCII escape sequences for screen manipulation and colorization for different graphs: 1 minute, 5 minute, 15 minute load averages.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] MATURE/STABLE
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
We've got `htop`, `atop` and standard `top` utility, showing system load avg over the last 1, 5 and 15 minutes. Why we should add another tool, abandoned 5 years ago?

**Comment by jaalto** [comment]
- Not similar. TTYLOAD will display load in ASCII graphics when run. Very useful under non-X11
  Pic: https://www.cyberciti.biz/media/new/cms/2017/04/ttyload-demo-screenshot-on-linux-unix.jpg

  Has also monochrome mode: ttyload -m

- The code is mature, never had had any problems. No bugs. Abandoned is not a problem,

**Comment by ryzhovau** [comment]
Can't say ASCII art is a major feature of `top`-like utility. 
Won't add it, sorry.
