### ISSUE TITLE
Request package: pv

### ISSUE THREAD

**Issue by jaalto** [Entware/Entware#282]
Package request: pv
---
https://packages.debian.org/testing/pv
Examples - https://catonmat.net/unix-utilities-pipe-viewer
Examples - https://www.cambus.net/visualizing-progression-of-file-operations-using-pv-pipe-viewer/

Shell pipeline element to meter data passing through

pv (Pipe Viewer) can be inserted into any normal pipeline between two processes to give a visual indication of how quickly data is passing through, how long it has taken, how near to completion it is, and an estimate of how long it will be until completion.

To use it, insert it in a pipeline between two processes, with the appropriate options. Its standard input will be passed through to its standard output and progress will be shown on standard error.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
Already added.
