### ISSUE TITLE
SAFE Network Vault Package Request

### ISSUE THREAD

**Issue by MathewCNichols** [Entware/Entware#285]
Package request
---
{The SAFE Network is a decentralized data storage and communications network that replaces data centers and servers with the spare computing resources of its users.}

- [ X] No similar package already added and/or this one got some new killer feature(s),
- [ X] Package is in active development (at least, not abandoned for 5 years or more),
- [ X] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

Find more at:
https://safenetforum.org/
https://safenetforum.org/t/launch-of-a-community-safe-network/26930

Thank you!

**Comment by ryzhovau** [comment]
Too heavy for embedded devices.
Written in Rust which isn't cross-compile friendly.
