### ISSUE TITLE
sane-backends ipkg installation errors

### ISSUE THREAD

**Issue by davygravy** [Entware/Entware#286]
Hello @ryzhovau , @zyxmon and all of you working hard on this... Thank you so much for your efforts.  Next time in Russia I buy you all a few rounds of beer.  

**A**, **B**  listed below.

I noticed  odd or broken behavior when installing `sane-backends`.

**A**.  Upon installation...It appears that hplip-full and sane-backends are both trying to install the same conf file:
```
root@AirGate:/tmp/home/root# opkg install sane-backends
Installing sane-backends (1.0.27-2) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/sane-backends_1.0.27-2_armv7-2.6.ipk
Collected errors:
 * check_data_file_clashes: Package sane-backends wants to install file /opt/etc/sane.d/dll.conf
	But that file is already provided by package  * hplip-full
 * opkg_install_cmd: Cannot install package sane-backends.
```
I can use the ` --force-overwrite` option to get past that, but then another  error is triggered.

-------------------------

**B**.  After forcing the installation, the system naturally wants to start the service `sane-backends` 

The system complains (naturally) that  `/etc/services` can't be written to... /etc/init.d/S01sane-backends perhaps needs a path change (prepend with /opt) at the beginning of the path for the services:
```
#!/bin/sh

PATH=/sbin:/bin:/usr/bin:/usr/sbin:/opt/bin:/opt/sbin

if !( grep -q ^saned.*6566 /etc/services ); then
        echo "saned             6566/tcp        # SANE network scanner daemon" >> /opt/etc/services
fi
```
This change at least quiets the script so that it doesn't throw an error.

-------------------------

Best regards to you all, 
Dave

**Comment by ryzhovau** [comment]
Unfortunately, there's no any graceful solution. Some Entware instances relying on `/etc/services`, the others (aka alternative installations) relying on `/opt/etc/services`. 

Most of embedded firmwares keeps `/etc` as writeable tmpfs, but the rest ones are not. So we'll keep existing variant.
