### ISSUE TITLE
hplip-full  & Makefile config question

### ISSUE THREAD

**Issue by davygravy** [Entware/Entware#287]
I accidentally ran into a potential problem with a package.   hplip-full has some odd interaction with sane-backends, noted in #286 .

Looking at sane-backends,  `sane-backends/opt/etc/sane.d/dll.conf` seems to be an long list of scanners to be enabled for **network access**.

Entware's Makefile for hplip (feeds/packages/util/hplip) shows:
```
CONFIGURE_ARGS += \
	--disable-gui-build \
	--disable-network-build \
	--disable-fax-build \
	--disable-pp-build \
	--enable-hpijs-install \
	--enable-cups-ppd-install \
	--disable-doc-build
```
... **--disable-network-build**  seems to conflict with the network-centric intent of sane-backends?

**Comment by ryzhovau** [comment]
This CONFIGURE_ARGS came from [upstream](https://github.com/openwrt/packages/blob/master/utils/hplip/Makefile) with no changes. We'll keep it as close as possible to upstream.

Please, [ask](https://github.com/openwrt/packages/issues) OpenWrt guys why they picked this options.
