### ISSUE TITLE
wget IRI support

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#289]
/tmp/home/root# wget -V
GNU Wget 1.20.1 built on linux-gnu.

-cares +digest -gpgme +https +ipv6 **-iri** +large-file -metalink **-nls**
+ntlm +opie -psl +ssl/openssl

**Comment by ryzhovau** [comment]
We prefer to stay close to [upstream](https://github.com/openwrt/packages/blob/master/net/wget/Makefile#L72). as possible. This feature will stay turned off, sorry.
