### ISSUE TITLE
Package request: axel-download-accelerator

### ISSUE THREAD

**Issue by romualdoag** [Entware/Entware#29]
### Package: axel-download-accelerator

https://github.com/axel-download-accelerator/axel

Axel tries to accelerate the downloading process by using multiple connections for one file, similar to DownThemAll and other famous programs. It can also use multiple mirrors for one download.

Using Axel, you will get files faster from Internet. So, Axel can speed up a download up to 60% (approximately, according to some tests).

Axel tries to be as light as possible, so it might be useful as a wget clone (and other console based programs) on byte-critical systems.

Axel supports HTTP, HTTPS, FTP and FTPS protocols.

### Platform: Asus RT-N56U [Padavan]

**Comment by zyxmon** [comment]
Added via https://github.com/Entware/rtndev/commit/3a77fdab80eba73a78964b2c6a9e9ecfdaadac54
Package will be in binary repo with next openwrt sync.
