### ISSUE TITLE
gotty crashes with Illegal instruction on Asus AC routers with Merlin firmware

### ISSUE THREAD

**Issue by ErvinBrs** [Entware/Entware#294]
**opkg install gotty**
Installing gotty (2.0.0-2017-12-13-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/gotty_2.0.0-2017-12-13-1_armv7-2.6.ipk
Configuring gotty.

**gotty -v**
Illegal instruction

file /opt/bin/gotty gives statically linked (same with go that is also crashing the same way):
/opt/bin/gotty: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked

while all the rest of the packages (that seem dynamically linked) work fine.

**uname -a**
Linux RT-AC88U-9700 2.6.36.4brcmarm #1 SMP PREEMPT Fri May 17 23:42:32 EDT 2019 armv7l ASUSWRT-Merlin

**Comment by zyxmon** [comment]
You need to instal gotty_nohf for your CPU.
