### ISSUE TITLE
[Package Request] shellcheck

### ISSUE THREAD

**Issue by RogueScholar** [Entware/Entware#299]
Package request: [shellcheck](https://github.com/koalaman/shellcheck)
---
shellcheck is a shell script linter/debugger/testing tool that aids in catching poor coding choices when automating processes via ash/bash/dash/ksh. As much of what I use Entware for on my networking appliances ultimately involves such scripting (a use case I suspect is relevant to at least a plurality of the userbase), I believe this could be a worthwhile addition to the repository.

![Shellcheck screen capture](https://github.com/koalaman/shellcheck/raw/master/doc/terminal.png)

That said, I would understand if you decided it wasn't worth the effort. The fact that it's written in Haskell, which entails both the installation of the Cabal compilation suite and a need for a not-insignificant-amount of system resources during compilation have admittedly kept me from attempting to do so yet myself, something I try to do before making requests here. On the other hand I'm also aware that you both are far more skilled at the process than I am and that I might be overestimating the investment required.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
Haskel/Cabal tools is not so cross-compile friendly as we expect.

Also, I'm not sure embedded device is a suitable place to IDE or script debugging like this one.

Sorry, @RogueScholar. Won't add it.
