### ISSUE TITLE
ip utility error with running command in namespace

### ISSUE THREAD

**Issue by LeftPinkie** [Entware/Entware#3]
### Package: ip-full

For the `ip` utility in `ip-full` package, I am having issues running commands in namespace.

- expected behavior:
```
# Create the network namespace
ip netns add test_ns

# Create the virtual network pair
ip link add test_v0 type veth peer name test_v1

# Move test_v0 to the test_ns namespace
ip link set test_v0 netns test_ns

# Configure the ends of the virtual network pairs
ip netns exec test_ns ifconfig test_v0  10.1.1.10/24 up
```
- actual behavior:
I get an error running `ip netns exec test_ns ifconfig test_v0  10.1.1.10/24 up`. The error message is:
setting the network namespace "test_ns" failed: Function not implemented

I cannot even run a basic command:
`ip netns exec test_ns ip addr list`

### Platform:
Linux 4.2.8
ip utility, iproute2-ss4.4.0-10-entware

**Comment by zyxmon** [comment]
Please check if your linux kernel is compiled with namespaces support.

```
CONFIG_NAMESPACES=y
...
CONFIG_NET_NS=y
```

**Comment by LeftPinkie** [comment]
I cannot find the `.config` file.  This is a NAS from QNAP so I do not know how the kernel was compiled.  Any idea as to how I can query for this info?

**Comment by zyxmon** [comment]
Just google for the answer. iproute2 error indicates there is no namespace support in the kernel.
