### ISSUE TITLE
hostapd

### ISSUE THREAD

**Issue by Zingisa1** [Entware/Entware#305]
Package request
---
{Creating Wi-Fi hotspot}

- [ x] No similar package already added and/or this one got some new killer feature(s),
- [x ] Package is in active development (at least, not abandoned for 5 years or more),
- [ x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by Zingisa1** [comment]
Please help with hostapd-full package.

**Comment by ryzhovau** [comment]
Duplicate of https://github.com/Entware/Entware/issues/337
