### ISSUE TITLE
Package request: opendkim

### ISSUE THREAD

**Issue by jsonoine1111** [Entware/Entware#308]
Package request
---
DomainKeys Identified Mail (DKIM) is an email authentication method designed to detect forged sender addresses in emails.
DKIM allows the receiver to check that an email claimed to have come from a specific domain was indeed authorized by the owner of that domain.
DKIM standard must be used to help prevent email spoofing on outgoing messages.
DKIM adds an encrypted signature to the header of all outgoing messages. Email servers that get these messages use DKIM to decrypt the message header,  and verify the message was not changed after it was sent. 

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my x86_64 and get a feedback about it.

Asustor AS6204T,  x86_64 GNU/Linux (bin/entware.net/x64-k3.2)

**Comment by skittlesvampir** [comment]
*+ 1*
They have postfix and some other stuff but no opendkim. My mails get always rejected.
 - [x] I would test added package on my armv7l machine.
