### ISSUE TITLE
Package request: uvcdynctrl

### ISSUE THREAD

**Issue by jankais3r** [Entware/Entware#319]
Package request: uvcdynctrl
---
Useful for controlling USB webcams (e.g. turning off LEDs, etc.)

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on **armv5tel** (Synology DS411j) and get a feedback about it.

---

The package is available for [OpenWRT](https://openwrt.org/packages/pkgdata/uvcdynctrl), would be nice to have it available also in Entware repository. Thank you for your consideration.

**Comment by ryzhovau** [comment]
It is available. Are you sure you've got Entware?
Entware-ng and Entware-3x forks are obsolete.
