### ISSUE TITLE
Package request: miredo

### ISSUE THREAD

**Issue by nickonline2005** [Entware/Entware#32]
### Platform: mipsel, ARMv7

Currently I am using 6to4 or 6in4 tunnel, but both of them are unstable (some time unreachable) or have a high latency. For now, the teredo tunnel is the most reliable and fast service that I can use. So for as I know, miredo is the only choice to use the toredo tunnel on linux platform, so I tried to compile the miredo package myself, but I failed. So, please, add the package for armv7 and mipsel platform, thanks a lot.
Devices that I am using: Asus RT-N16 and Asus RT-AC56U

**Comment by buzhangsan** [comment]
my device is padavan(cpu_mt7260a)
