### ISSUE TITLE
write_log for collectd

### ISSUE THREAD

**Issue by d1nd141** [Entware/Entware#321]
write_log for collectd

Plugin write_log for collectd

Please add write_log
https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_write_log

It would be much easier to parse the metrics.
At the moment only
collectd-mod-write-graphite - 5.8.1-6 - Carbon/Graphite output plugin
collectd-mod-write-http - 5.8.1-6 - HTTP POST output plugin
Are available.

Maybe for others, write_prometheus and write_kafka would be also of interest.

Thanks

**Comment by ryzhovau** [comment]
This package came from upstream with no changes and we sync it once per month (or two).
I don't know why OpenWrt guys wont pack write_log while [keeping it enabled](https://github.com/openwrt/packages/blob/61423689f9d09c56dd0e6c5fc34e7a2449d1dd7b/utils/collectd/Makefile#L103).

Please, [ask](https://github.com/openwrt/packages/issues) OpenWrt guys to fix that and new version will arrive here in next month.
