### ISSUE TITLE
Package update: inadyn to version 2.5 (revisit)

### ISSUE THREAD

**Issue by deekayw0n** [Entware/Entware#323]
Package request
---
As requested in [#218](https://github.com/Entware/Entware/issues/218?_pjax=%23js-repo-pjax-container), v2.5 of inadyn has been out for sometime and would be great to package up for use on my QNAP device. Additionally, it provides a key fix needed to make dynamic dns updating work for folks like myself with a registrar using a new fangled 200 response message that v2.2-1 sees as an error but v2.5 should address. Looking upstream to openWRT, v2.5 now has a Makefile [here](https://github.com/openwrt/packages/tree/master/net/inadyn) so I would imagine is ready for Entware consumption in some form. Fingers crossed. Thanks for all that you do!

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
Done via https://github.com/Entware/entware-packages/commit/62e0e030410213d2b8af2ad1dadb6480e81551df
