### ISSUE TITLE
MD5 Module Not Found in Padavan

### ISSUE THREAD

**Issue by Evyde** [Entware/Entware#325]
`opkg install python`
  
 `opkg install python-pip`
  
  Then I ran `pip install xxxxxx`, it showed that it didn’t find the md5 module, is the python in entware don’t support md5?

**Comment by ryzhovau** [comment]
Can't reproduce that, sorry.
Please keep in mynd some packages requires native compilation and additional dependencies.
Please, refer to https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules
