### ISSUE TITLE
Remove Endware on Synology please ?

### ISSUE THREAD

**Issue by PoseidonFR** [Entware/Entware#328]
Hello,
How to uninstall Entware from a Synology NAS please? Synology support asks me to remove OPKG to try to solve a problem with "python module".

Thanks in advance.

**Comment by zyxmon** [comment]
Just remove Entware autostart from /etc/rc.local or any other place you've added autostart.
Better ask Synology forum for support.

**Comment by PoseidonFR** [comment]
Ok thanks ;)
