### ISSUE TITLE
socksify start error

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#330]
# socksify
test: '/opt/lib/libc.so.6' library contains unsupported TLS
test: '/opt/lib/libc.so.6' library contains unsupported TLS
test: can't load library 'libc.so.6'

# uname -mro
2.6.36.4brcmarm armv7l Tomato

# opkg status socksify
Package: socksify
Version: 1.4.1-3
Depends: libc, libssp, librt, libpthread
Status: install user installed
Architecture: armv7-2.6
Installed-Time: 1568277452

**Comment by ryzhovau** [comment]
Looks like DLL injection is not working on MIPS and on ARM. So we'll remove this script from packages.

**Comment by zyxmon** [comment]
It looks like socksify does not work for all architectures.
We will probably remove this package, but leave dante (sockd) package.
