### ISSUE TITLE
Package request: torsocks

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#331]
Package request: torsocks
---
Torrify applications connections and name resolution. Pure C not shell script. Non LD_PRELOAD use or other dirty hacks. Official app from Tor Project.

* [x]  No similar package already added and/or this one got some new killer feature(s),
* [x]  Package is in active development (at least, not abandoned for 5 years or more),
* [x]  I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
From readme:
```
Torsocks is an ELF shared library that is loaded before all others. The library overrides every needed Internet communication libc function calls such as connect(2) or gethostbyname(3).
```
It IS LD_PRELOAD hack.

**Comment by garycnew** [comment]
[[SOLUTION] Cross-Compile Torsocks Entware Package via Debian Live DVD](https://www.snbforums.com/threads/solution-cross-compile-torsocks-entware-package-via-debian-live-dvd.73260/)
