### ISSUE TITLE
Package request: proxybound

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#332]
Package request: proxybound
---
Replacement of not working socksify in pure C and actively developed I think.
https://github.com/Intika-Linux-Proxy/Proxybound

* [x]  No similar package already added and/or this one got some new killer feature(s),
* [x]  Package is in active development (at least, not abandoned for 5 years or more),
* [x]  I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
This is the same LD_PRELOAD hack, which is not stable on ARM/MIPS.
