### ISSUE TITLE
Package request: GCC missing from Mipsel repository

### ISSUE THREAD

**Issue by intel777** [Entware/Entware#333]
Yeah, I saw request from back in 2016, in now old and deprecated Entware-ng git page, but maybe something changed from that time.
Cross compiling python modules it's a hell of a lot pain in ass so I'm desperately requesting GCC for Mipsel cause shortly after installing python I tried to install some module and got `unable to execute 'mipsel-openwrt-linux-uclibc-gcc': No such file or directory`. Of course I tried `opkg install gcc` that returned `Unknown package 'gcc'.`

I got Mi3 Router and will willingly test anything as long as it needed to be tested.

**Comment by ryzhovau** [comment]
Entware-ng is deprecated, no any changes since 2016 there.
