### ISSUE TITLE
Please update Expat from 2.2.6 to 2.2.8 with security fixes

### ISSUE THREAD

**Issue by hartwork** [Entware/Entware#334]
https://blog.hartwork.org/posts/expat-228-with-security-fixes-has-been-released/

Thank you!

**Comment by ryzhovau** [comment]
Done via https://github.com/Entware/entware-packages/commit/3d639c54105c08966df6bbf4c005872ac5381800

**Comment by hartwork** [comment]
Thank you!

**Comment by hartwork** [comment]
@ryzhovau are you aware that you updated to 2.2.7 rather than 2.2.8 and that as a result your Expat is still vulnerable?

**Comment by ryzhovau** [comment]
This package came [from upstream](https://github.com/openwrt/packages/tree/master/libs/expat) with no changes. Please. [ask](https://github.com/openwrt/packages/issues) OpenWrt guys to update package and it will arrive here after next sync.
