### ISSUE TITLE
check_data_file_clashes: Package python-chardet wants to install file /opt/bin/chardetect But that file is already provided by package  * python3-chardet

### ISSUE THREAD

**Issue by diman82** [Entware/Entware#336]
Use `--force-overwrite` flag in opkg command. There are only few _dev packages in entware. Please use wiki to install development environment.
Please note we do not support native compilation and recommend cross-compilation.

_Originally posted by @zyxmon in https://github.com/Entware/Entware-ng/issues/559#issuecomment-280229396_

**Comment by ahmadkarim** [comment]
@diman82 can you provide some details exactly where to set this flag. Thanks

**Comment by diman82** [comment]
@ahmadkarim opkg install _some_package_ **--force-overwrite**

**Comment by ahmadkarim** [comment]
thanks but I realize this was a general issue I am having this issue in Yocto build system

**Comment by diman82** [comment]
> thanks but I realize this was a general issue I am having this issue in Yocto build system

It shouldn't matter too much, as long it's running Entware
