### ISSUE TITLE
Неполадки в Debootstrap

### ISSUE THREAD

**Issue by templarundead** [Entware/Entware#339]
RT-AC57U 
прошивка Padavan

При попытке установить Debian среду из Debootstrap выдаёт ошибку: 

opt/home/admin # install-debian
/opt/sbin/debootstrap: line 424: command: not found
W: Cannot find binary for checking sha256 checksums, falling back to sha1
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving InRelease 
I: Retrieving Release 
E: Invalid Release file, no entry for main/binary-mipsel/Packages
/opt/bin/install-debian: line 37: can't create /opt/debian/usr/sbin/policy-rc.d: nonexistent directory
chmod: /opt/debian/usr/sbin/policy-rc.d: No such file or directory
/opt/bin/install-debian: line 44: can't create /opt/debian/etc/profile: nonexistent directory
/opt/bin/install-debian: line 47: can't create /opt/debian/etc/securetty: nonexistent directory
/opt/bin/install-debian: line 48: can't create /opt/debian/etc/securetty: nonexistent directory
/opt/bin/install-debian: line 49: can't create /opt/debian/etc/securetty: nonexistent directory
Please run /opt/etc/init.d/S99debian start
Please run start-debian,change password with passwd command and run 'apt-get update'
/opt/home/admin #

**Comment by zyxmon** [comment]
1. Debootstarap не гарантирует установку конкретного дистрибутива debian, То, что ставилось месяц назад может не устанавливаться сегодня, т.к. ропозиторий debian меняется.
2. Если отсутствует необходимая утилита (например sha256sum - установите). Она входит в состав busybox от entware и отсутствует у Padavan'а.
3. Удалите папку, куда устанавливается debian и попробуйте установить менее свежий дистрибутив.
