### ISSUE TITLE
Package request libssh-dev

### ISSUE THREAD

**Issue by maulvi** [Entware/Entware#340]
Package request libssh-dev
---
{libssh is an independent project that provides a multiplatform C library implementing the SSHv2 and SSHv1 protocols for client and server implementations.}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---

**Comment by ryzhovau** [comment]
We don't add libraries without application which depends on it. Which package will use this library?
