### ISSUE TITLE
Google Authenticator

### ISSUE THREAD

**Issue by diogeneos** [Entware/entware#35]
Hi everyone,-

This is more like a question than a suggestion/request.
And might have a simple "no" answer for good reasons.
I'm not a coder and can't offer any help in this "department"...

Nevertheless, here it is:
Would it be possible to consider including two-factor authentication as a package?

Here is a good one (I think) and is easily installed on Debian (what I tried)
http://linotp.org/news.html

Ideally, I'd like to see the router run the authentication for the household.
Running RADIUS (DD-WRT can do RADIUS server). 
Maybe two routers for failover.

The very fact routers run 24/7 makes them perfect candidates for this job.
And running Google Authenticator makes it almost platform agnostic... 

Thanks for reading.

**Comment by ryzhovau** [comment]
To be continued here - https://github.com/Entware-ng/Entware-ng/issues/3
