### ISSUE TITLE
Enable python3-mysqlclient package in armv7-3.2 config

### ISSUE THREAD

**Issue by stefaang** [Entware/Entware#350]
Entware provides python-mysqlclient but not the python3 equivalent.

See here: https://github.com/Entware/Entware/blob/master/configs/armv7-3.2.config#L3221

**Comment by stefaang** [comment]
Just for the record, I've enabled+build the package and it works fine.
But it's unclear to me why several python3 packages are not enabled... is there any info available on this matter?

**Comment by ryzhovau** [comment]
Thanks for tests!

Those packages was added as some dependencies long time ago. I totally agree python3-* packages is more needed than similar python2-* variants today. 

We support [python3 transitions](https://github.com/openwrt/packages/issues/8893) and going to remove all python2-* packages in 2020 as OpenWrt guys plan.
