### ISSUE TITLE
All 4.x samba in armv7sf-k3.2 are broken as a matter of fact...

### ISSUE THREAD

**Issue by lokapal** [Entware/Entware#353]
Hello, Entware/Optware developers! :)

I've spent a couple of days in attempts of run properly samba at HiMedia Q10 Pro mediaplayer (Android 7.xx). Well, I've found that ALL samba 4.x releases are lame in the tree armv7sf-k3.2:
1. All samba4x-server packages after samba4x-server_4.8.0-1_armv7-3.2.ipk doesn't have nmbd included. It even commented out in /opt/etc/init.d/S91samba. Farewell network discovery and normal samba working! Well, I know that nmbd right now is in OpenWRT. The problem is that there is NO OpenWRT in Android, and there is no need to install full system for one service. Is it possible to compile/include nmbd as optional samba4x package (just like net package) ?
2. Both samba4x-server_4.8.0-1_armv7-3.2.ipk  and samba4x-server_4.7.3-1_armv7-3.2.ipk doesn't show/copy files that are greater than 2GB. 
3. The bright side: it seems that samba36-server_3.6.25-14_armv7-3.2.ipk is fully functional package (although all Windows 10 that have turned OFF SMB2 support will not work with Samba 3.6).

Thanks in advance! It's pure fantastic, I know, but I'd like to know - why arm7hf tree is not compiled by default?

**Comment by zyxmon** [comment]
1. https://github.com/Entware/Entware/issues/304
2. This issue was already reported. No solution yet.
3. Samba4 is still may be considered beta.

**Comment by lokapal** [comment]
Frankly speaking, I don't understand why it's impossible to compile/create an ADDITIONAL package (like it's done for net tool) for those people who don't use OpenWRT. It easily can be done even by hands (I've tried to use nmbd from 4.0.8.0 with the latest smbd), the single problem is that nmbd has version dependency hardcoded, so adding libraries by hand to /opt/lib cannot help to run the service.

**Comment by lokapal** [comment]
https://linoxide.com/linux-how-to/install-specific-version-packages-rhel-centos-7/
Even in the Enterprise environment RedHat/CentOS samba 4.1 is the MINIMAL version allowed to install.

**Comment by zyxmon** [comment]
We will add nmbd to samba4 next build since openwrt reverted default option to build nmbd.

The issue is reopened

**Comment by zyxmon** [comment]
nmbd added to package
