### ISSUE TITLE
rtorrent package uses old config syntax

### ISSUE THREAD

**Issue by yannfill** [Entware/Entware#357]
Since version 0.9.x, rtorrent uses a different config file syntax (see [this page](https://github.com/rakshasa/rtorrent/wiki/rTorrent-0.9-Comprehensive-Command-list-(WIP)) for old/new command matching) and Entware still ships old style config file, so rtorrent can't start.

Also, the init file (and /opt/etc/init.d/rc.func) relies on pidof to get the PID of running rtorrent process and fails to get it, seemingly failing to start while rtorrent is in fact properly started in a screen process. For the same reason, check and restart commands fail too.

This issue occurs on armv7 QNAP NAS.

**Comment by ryzhovau** [comment]
Yep, [noticed](https://github.com/Entware/Entware/issues/342#issuecomment-549162595). Can't say it's a top priority task for us, sorry.

PRs are welcome.
