### ISSUE TITLE
How can i get following package in opkg?

### ISSUE THREAD

**Issue by satoshinosekai** [Entware/Entware#359]
Hello., i need to use curl http2

I following step from link
https://serversforhackers.com/c/curl-with-http2-support?fbclid=IwAR0Qo84Gs968u0HL-sY0H228FxYE3_2qT6PI7zGz-weHT6B3ejRlrPc0sr0
but i get some unknown package, how can i get them？

Unknown package 'g++'.
Unknown package 'autotools-dev'.
Unknown package 'libtool'.
Unknown package 'zlib1g-dev'.
Unknown package 'libcunit1-dev'.
Unknown package 'libssl-dev'.
Unknown package 'libxml2-dev'.
Unknown package 'libev-dev'.
Unknown package 'libevent-dev'.
Unknown package 'libjansson-dev'.
Unknown package 'libjemalloc-dev'.
Unknown package 'cython'.

**Comment by ryzhovau** [comment]
Better to [use cross-compilation](https://github.com/Entware/Entware/wiki/Compile-packages-from-sources).
