### ISSUE TITLE
ecryptfs-utils

### ISSUE THREAD

**Issue by g34rl00s3** [Entware/Entware#36]
ecryptfs-utils (version 111)

My NAS supports the ecryptfs filesystem which is buildin into the kernel.
To be able to use this feature you'll need userland utilities which are provided by ecryptfs-utils

**Comment by zyxmon** [comment]
What is wrong with build in encryption interface?
![qnapencrypt](https://user-images.githubusercontent.com/6533749/37988565-e66f81c6-3209-11e8-8c09-9b04dcb6ed0a.png)

**Comment by g34rl00s3** [comment]
The encrypted drive isn't the internal drive of the NAS itself but an external network drive.
Does this encrypt feature also work with mounted network shares on the NAS? I've so I could try to
migrate.

**Comment by zyxmon** [comment]
There are other encrypted filesystems in Entware. May be they will be useful. They are fuse (userspace), not kernel space.

**Comment by ryzhovau** [comment]
Closing for now.
