### ISSUE TITLE
Package request: xidel

### ISSUE THREAD

**Issue by MegaCron** [Entware/Entware#361]
Package request
---

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
https://sourceforge.net/projects/videlibri/files/Xidel/Xidel%200.9.8/xidel-0.9.8.src.tar.gz/download

Утилита по извлечению данных из HTML/XML/JSON. 

Мне интересна возможностью извлечения данных с использованием выражений xpath/xquery/css из html. Аналогов в entware не нашёл.

Ну и в довесок к ввшесказанному, извлекать данные из xml через xidel проще, нежели чем через xmlstarlet.

Утилита необходима для платформы mips. Для ARM имеется авторская сборка. Хотя если xidel будет в составе entware для ARM, могу проверить и там.

**Comment by ryzhovau** [comment]
Программа [написана на Pascal](https://github.com/benibela/xidel) и, к сожалению, никак не предусматривает кросс-компиляцию привычными средствами.
