### ISSUE TITLE
freeradius3-mod-eap-mschapv2 - wrong library

### ISSUE THREAD

**Issue by IMEIICCID** [Entware/Entware#363]
starting radiusd -X
#################################################################
error:
/opt/etc/freeradius3/radiusd.conf[719]: Failed to link to module 'rlm_mschapv2': /opt/lib/freeradius3/rlm_mschapv2.so: cannot open shared object file: No such file or directory 
#################################################################
radiusd.conf Line [719] = mschapv2 { }
#################################################################
I did install all avalible Freeradius3 packages but the is no   rlm_mschapv2.so

The package freeradius3-mod-eap-mschapv2 - release_3_0_19-2 - EAP/MS-CHAPv2 module contains a  rlm_eap_mschapv2.so library. I did try to rename but it does not work.

My EAP-TLS  config is working with freeradius2 entware and tomato.

I did something wrong or is the package containes a wrong library :-(

---
{Describe killer feature of package}

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by zyxmon** [comment]
rlm_mschap.so is in the freeradius-mod-mschap package.
