### ISSUE TITLE
Package request: octoprint & klipper

### ISSUE THREAD

**Issue by mittkonto** [Entware/Entware#366]
Package request
---

[Octoprint](https://octoprint.org/) is a well known webinterface for 3dprinters and shines how it is.

Most 3dprinter hardware uses [Marlin](http://marlinfw.org) firmware to make the movement calculations on the mcu locally.

[Klipper](https://www.klipper3d.org) on the other hand, is mcu firmware that 
lets the host system do all the [heavy lifting](https://www.klipper3d.org/Features.html) and just telling the 3dprinter to "go there, do that".

Coupled with as there are a plethora of devices able to utilize Entware, many of them with hardware way more powerful then your average 3d printer electronics.

Packages such as octoprint & klipper and their dependencies in Entware, would give users of 3dprinters  access to a vast variety of possible hardware to upgrade their system, with hardware they already own.

{x} No similar package already added and/or this one got some new killer feature(s),
{x} Package is in active development (at least, not abandoned for 5 years or more),
{x} Of course, I'm a happy guinea pig and would help this on my odroid c2 amongst other things.

**Comment by ryzhovau** [comment]
Quite a rare specific utilities for embedded repo, sorry. Odroid C2 and other similar devices are powerful enough to use full blown Linux distros, where Octoprint/Klipper much easier to get.
