### ISSUE TITLE
Package request: cloud-print-connector

### ISSUE THREAD

**Issue by sxiii** [Entware/Entware#367]
Package request
---
Cloud-print-connector allows you to use Android phone or your google account to send documents to a connected printer.

- [+] No similar package already added and/or this one got some new killer feature(s),
- [+] Package is in active development (at least, not abandoned for 5 years or more),
- [+] I'm ready to test added package on my {platform} and get a feedback about it.

---

**Comment by ryzhovau** [comment]
Did you tried `python-cloudprint`?

**Comment by sxiii** [comment]
@ryzhovau о, спасибо! А есть информация по тому что будет работать на OpenWRT MIPS32EL и как его туда "добыть" лучше всего? Ещё раз спасибо!

**EDIT:** я так понял, что требуется ```libcups2-dev```, которого нету в OpenWRT. Плюс ```pycups``` тоже нужен. Но уже хоть какой-то шаг в направлении... Попробую собрать с libcups и python2.7. Вдруг их хватит...

**Comment by ryzhovau** [comment]
We don't provide personal support here, sorry.

`python-cloudprint` is working on MIPS ([checked](https://pastebin.com/VT3eV5xi) 7 years ago), all print jobs will arrive as PDF files. You need to set up CUPS for PDF printing.
