### ISSUE TITLE
request package python3-readline

### ISSUE THREAD

**Issue by listenfree** [Entware/Entware#371]
Package request
---
{aarch64-k3.10,need python3-readline,the new python3.7x without readline package,when interact with python3,press up down left right not working,return ^[[A^[[C^[[D}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by zyxmon** [comment]
You can add it yourself - https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules

**Comment by listenfree** [comment]
running on my arm synology nas ds119j,please help

admin@fisher:/opt/bin$ python3 pip install readline
Collecting readline
  Using cached https://files.pythonhosted.org/packages/f4/01/2cf081af8d880b44939a5f1b446551a7f8d59eae414277fd0c303757ff1b/readline-6.2.4.1.tar.gz
Installing collected packages: readline
    Running setup.py install for readline ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/tmp/pip-install-iwwqg0oj/readline/setup.py'"'"'; __file__='"'"'/opt/tmp/pip-install-iwwqg0oj/readline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /opt/tmp/pip-record-2ccdnu7n/install-record.txt --single-version-externally-managed --compile
         cwd: /opt/tmp/pip-install-iwwqg0oj/readline/
    Complete output (230 lines):
    
    ============ Building the readline library ============
    
    readline-6.2/
    readline-6.2/doc/
    readline-6.2/doc/Makefile.in
    readline-6.2/doc/texinfo.tex
    readline-6.2/doc/version.texi
    readline-6.2/doc/fdl.texi
    readline-6.2/doc/rlman.texi
    readline-6.2/doc/rltech.texi
    readline-6.2/doc/rluser.texi
    readline-6.2/doc/rluserman.texi
    readline-6.2/doc/history.texi
    readline-6.2/doc/hstech.texi
    readline-6.2/doc/hsuser.texi
    readline-6.2/doc/readline.3
    readline-6.2/doc/history.3
    readline-6.2/doc/texi2dvi
    readline-6.2/doc/texi2html
    readline-6.2/doc/readline.ps
    readline-6.2/doc/history.ps
    readline-6.2/doc/rluserman.ps
    readline-6.2/doc/readline.dvi
    readline-6.2/doc/history.dvi
    readline-6.2/doc/rluserman.dvi
    readline-6.2/doc/readline.info
    readline-6.2/doc/history.info
    readline-6.2/doc/rluserman.info
    readline-6.2/doc/readline.html
    readline-6.2/doc/history.html
    readline-6.2/doc/rluserman.html
    readline-6.2/doc/readline.0
    readline-6.2/doc/history.0
    readline-6.2/doc/readline_3.ps
    readline-6.2/doc/history_3.ps
    readline-6.2/doc/history.pdf
    readline-6.2/doc/readline.pdf
    readline-6.2/doc/rluserman.pdf
    readline-6.2/examples/
    readline-6.2/examples/autoconf/
    readline-6.2/examples/autoconf/BASH_CHECK_LIB_TERMCAP
    readline-6.2/examples/autoconf/RL_LIB_READLINE_VERSION
    readline-6.2/examples/autoconf/wi_LIB_READLINE
    readline-6.2/examples/rlfe/
    readline-6.2/examples/rlfe/ChangeLog
    readline-6.2/examples/rlfe/Makefile.in
    readline-6.2/examples/rlfe/README
    readline-6.2/examples/rlfe/config.h.in
    readline-6.2/examples/rlfe/configure
    readline-6.2/examples/rlfe/configure.in
    readline-6.2/examples/rlfe/extern.h
    readline-6.2/examples/rlfe/os.h
    readline-6.2/examples/rlfe/pty.c
    readline-6.2/examples/rlfe/rlfe.c
    readline-6.2/examples/rlfe/screen.h
    readline-6.2/examples/Makefile.in
    readline-6.2/examples/excallback.c
    readline-6.2/examples/fileman.c
    readline-6.2/examples/manexamp.c
    readline-6.2/examples/readlinebuf.h
    readline-6.2/examples/rl-fgets.c
    readline-6.2/examples/rlcat.c
    readline-6.2/examples/rlevent.c
    readline-6.2/examples/rltest.c
    readline-6.2/examples/rl.c
    readline-6.2/examples/rlptytest.c
    readline-6.2/examples/rlversion.c
    readline-6.2/examples/histexamp.c
    readline-6.2/examples/Inputrc
    readline-6.2/examples/rlwrap-0.30.tar.gz
    readline-6.2/support/
    readline-6.2/support/config.guess
    readline-6.2/support/config.rpath
    readline-6.2/support/config.sub
    readline-6.2/support/install.sh
    readline-6.2/support/mkdirs
    readline-6.2/support/mkdist
    readline-6.2/support/mkinstalldirs
    readline-6.2/support/shobj-conf
    readline-6.2/support/shlib-install
    readline-6.2/support/wcwidth.c
    readline-6.2/shlib/
    readline-6.2/shlib/Makefile.in
    readline-6.2/COPYING
    readline-6.2/README
    readline-6.2/MANIFEST
    readline-6.2/INSTALL
    readline-6.2/CHANGELOG
    readline-6.2/CHANGES
    readline-6.2/NEWS
    readline-6.2/USAGE
    readline-6.2/aclocal.m4
    readline-6.2/config.h.in
    readline-6.2/configure
    readline-6.2/configure.in
    readline-6.2/Makefile.in
    readline-6.2/ansi_stdlib.h
    readline-6.2/chardefs.h
    readline-6.2/history.h
    readline-6.2/histlib.h
    readline-6.2/keymaps.h
    readline-6.2/posixdir.h
    readline-6.2/posixjmp.h
    readline-6.2/readline.h
    readline-6.2/posixselect.h
    readline-6.2/posixstat.h
    readline-6.2/rlconf.h
    readline-6.2/rldefs.h
    readline-6.2/rlmbutil.h
    readline-6.2/rlprivate.h
    readline-6.2/rlshell.h
    readline-6.2/rlstdc.h
    readline-6.2/rltty.h
    readline-6.2/rltypedefs.h
    readline-6.2/rlwinsize.h
    readline-6.2/tcap.h
    readline-6.2/tilde.h
    readline-6.2/xmalloc.h
    readline-6.2/bind.c
    readline-6.2/callback.c
    readline-6.2/compat.c
    readline-6.2/complete.c
    readline-6.2/display.c
    readline-6.2/emacs_keymap.c
    readline-6.2/funmap.c
    readline-6.2/input.c
    readline-6.2/isearch.c
    readline-6.2/keymaps.c
    readline-6.2/kill.c
    readline-6.2/macro.c
    readline-6.2/mbutil.c
    readline-6.2/misc.c
    readline-6.2/nls.c
    readline-6.2/parens.c
    readline-6.2/readline.c
    readline-6.2/rltty.c
    readline-6.2/savestring.c
    readline-6.2/search.c
    readline-6.2/shell.c
    readline-6.2/signals.c
    readline-6.2/terminal.c
    readline-6.2/text.c
    readline-6.2/tilde.c
    readline-6.2/undo.c
    readline-6.2/util.c
    readline-6.2/vi_keymap.c
    readline-6.2/vi_mode.c
    readline-6.2/xfree.c
    readline-6.2/xmalloc.c
    readline-6.2/history.c
    readline-6.2/histexpand.c
    readline-6.2/histfile.c
    readline-6.2/histsearch.c
    readline-6.2/patchlevel
    patching file vi_mode.c
    patching file callback.c
    patching file support/shobj-conf
    patching file patchlevel
    patching file input.c
    patching file patchlevel
    patching file vi_mode.c
    patching file patchlevel
    checking build system type... ./support/config.guess: unable to guess system type
    
    This script, last modified 2008-03-12, has failed to recognize
    the operating system you are using. It is advised that you
    download the most up to date version of the config scripts from
    
      http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
    and
      http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
    
    If the version you run (./support/config.guess) is already up to date, please
    send the following data and any information you think might be
    pertinent to <config-patches@gnu.org> in order to provide the needed
    information to handle your system.
    
    config.guess timestamp = 2008-03-12
    
    uname -m = aarch64
    uname -r = 4.4.59+
    uname -s = Linux
    uname -v = #24922 SMP Mon Aug 19 12:12:56 CST 2019
    
    /usr/bin/uname -p = unknown
    /bin/uname -X     =
    
    hostinfo               =
    /bin/universe          =
    /usr/bin/arch -k       =
    /bin/arch              =
    /usr/bin/oslevel       =
    /usr/convex/getsysinfo =
    
    UNAME_MACHINE = aarch64
    UNAME_RELEASE = 4.4.59+
    UNAME_SYSTEM  = Linux
    UNAME_VERSION = #24922 SMP Mon Aug 19 12:12:56 CST 2019
    configure: error: cannot guess build type; you must specify one
    
    ============ Building the readline extension module ============
    
    running install
    running build
    running build_ext
    building 'readline' extension
    creating build
    creating build/temp.linux-aarch64-3.7
    creating build/temp.linux-aarch64-3.7/Modules
    creating build/temp.linux-aarch64-3.7/Modules/3.x
    aarch64-openwrt-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -O2 -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -DNDEBUG -fno-inline -O2 -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -DNDEBUG -fno-inline -I/media/ware/Entware.2019.10/staging_dir/target-aarch64_cortex-a53_glibc-2.27/opt/include -I/media/ware/Entware.2019.10/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.4.0_glibc-2.27/include -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/opt/include/python3.7 -c Modules/3.x/readline.c -o build/temp.linux-aarch64-3.7/Modules/3.x/readline.o -Wno-strict-prototypes
    In file included from /opt/include/python3.7/Python.h:99:0,
                     from Modules/3.x/readline.c:8:
    Modules/3.x/readline.c: In function 'on_completion':
    /opt/include/python3.7/unicodeobject.h:1166:29: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     #define _PyUnicode_AsString PyUnicode_AsUTF8
                                 ^
    Modules/3.x/readline.c:842:23: note: in expansion of macro '_PyUnicode_AsString'
                 char *s = _PyUnicode_AsString(r);
                           ^~~~~~~~~~~~~~~~~~~
    Modules/3.x/readline.c: In function 'PyInit_readline':
    Modules/3.x/readline.c:1179:34: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         PyOS_ReadlineFunctionPointer = call_readline;
                                      ^
    creating build/lib.linux-aarch64-3.7
    aarch64-openwrt-linux-gnu-gcc -shared -L/media/ware/Entware.2019.10/staging_dir/target-aarch64_cortex-a53_glibc-2.27/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link=/media/ware/Entware.2019.10/staging_dir/target-aarch64_cortex-a53_glibc-2.27/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux-aarch64.so.1 -L/media/ware/Entware.2019.10/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.4.0_glibc-2.27/lib -L/media/ware/Entware.2019.10/build_dir/target-aarch64_cortex-a53_glibc-2.27/Python-3.7.4 -L/media/ware/Entware.2019.10/staging_dir/target-aarch64_cortex-a53_glibc-2.27/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link=/media/ware/Entware.2019.10/staging_dir/target-aarch64_cortex-a53_glibc-2.27/opt/lib -Wl,--dynamic-linker=/opt/lib/ld-linux-aarch64.so.1 -L/media/ware/Entware.2019.10/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.4.0_glibc-2.27/lib -L/media/ware/Entware.2019.10/build_dir/target-aarch64_cortex-a53_glibc-2.27/Python-3.7.4 build/temp.linux-aarch64-3.7/Modules/3.x/readline.o readline/libreadline.a readline/libhistory.a -L/opt/lib -lncurses -lpython3.7 -o build/lib.linux-aarch64-3.7/readline.cpython-37.so
    aarch64-openwrt-linux-gnu-gcc: error: readline/libreadline.a: No such file or directory
    aarch64-openwrt-linux-gnu-gcc: error: readline/libhistory.a: No such file or directory
    error: command 'aarch64-openwrt-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/tmp/pip-install-iwwqg0oj/readline/setup.py'"'"'; __file__='"'"'/opt/tmp/pip-install-iwwqg0oj/readline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /opt/tmp/pip-record-2ccdnu7n/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by listenfree** [comment]
> You can add it yourself - https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules

would you please help me,thanks

**Comment by zyxmon** [comment]
We do not suggest this sort of support.  Sorry.

Ask openwrt developers to add this package. We will add it in Entware after openwrt.
