### ISSUE TITLE
installation not possible on stock ax88u

### ISSUE THREAD

**Issue by cputoaster** [Entware/Entware#376]
At least I could not figure out how, and [this](https://www.snbforums.com/threads/opt-folder-on-stock-rt-ac86u-firmware.48895/#post-432269) seems to suggest the same. Should probably be mentioned on https://github.com/Entware/Entware/wiki/Install-on-Asus-stock-firmware

**Comment by zyxmon** [comment]
You can modify wiki yourself.

**Comment by cputoaster** [comment]
done, added to wiki. I hope its true.
