### ISSUE TITLE
Node & npm - updated version

### ISSUE THREAD

**Issue by indigob0y** [Entware/Entware#377]
Package request: Node 12.13.1, npm 6.13.4
---
Can we expect updated version of these packages?

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by zyxmon** [comment]
Please ak upstream (openwrt developers) to update node.
