### ISSUE TITLE
p7zip -> p7zip-full

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#378]
In Ubuntu f.e. we have p7zip-full package. It includes p7zip and adds 7z binary and 7z.so library to work with all formats 7z supports.

https://packages.ubuntu.com/eoan/i386/p7zip-full/filelist

Can we have p7zip-full in Entware? Maybe with p7zip package together.

**Comment by ryzhovau** [comment]
Package was updated recently. https://github.com/Entware/rtndev/commit/f3203d0f74bc2b1dfbd1921a598c912882352e4a

This is all utils we can add at this moment.
