### ISSUE TITLE
ghostscript package missing

### ISSUE THREAD

**Issue by redcitybass** [Entware/Entware#379]
Hello! I'm trying to set up CUPS with entware on OpenWRT, but when i'm trying to install cups-pdf, I get an error:

root@OpenWrt:/# epkg install cups-pdf
Installing cups-pdf (3.0.1-1) to root...
Downloading http://bin.entware.net/armv7sf-k3.2/cups-pdf_3.0.1-1_armv7-3.2.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for cups-pdf:
 * 	ghostscript
 * opkg_install_cmd: Cannot install package cups-pdf.
root@OpenWrt:/#

**Comment by ryzhovau** [comment]
You can't use OpenWrt and Entware packages mutually.

**Comment by zyxmon** [comment]
ghostscript package was corrupted, reuploaded it.
This should fix the problem.

**Comment by redcitybass** [comment]
Now it can be installed, thanks!
