### ISSUE TITLE
Package Request: SmartDNS

### ISSUE THREAD

**Issue by tomyangsh** [Entware/Entware#381]
Package request: [https://github.com/pymumu/smartdns](https://github.com/pymumu/smartdns)

SmartDNS is a local DNS server. SmartDNS accepts DNS query requests from local clients, obtains DNS query results from multiple upstream DNS servers, and returns the fastest access results to clients.
Avoiding DNS pollution and improving network access speed, supports high-performance ad filtering.
Unlike dnsmasq's all-servers, smartdns returns the fastest access resolution. 

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
Whats the killer feature of SmartDNS? We've got 5 or 6 DNS servers in repo, why we should add another one?

**Comment by tomyangsh** [comment]
It can test results from multiple upstream DNS server and choose the fastest one (lowest delay). Supports the latest TLS, HTTPS protocol and provides secure DNS query capabilities. DNS anti-poison mechanism, and a variety of mechanisms to avoid DNS pollution. These features are quite important for users in China for the terrible network environment.
