### ISSUE TITLE
Update Alaya

### ISSUE THREAD

**Issue by anch665** [Entware/Entware#383]
Update https://github.com/ColumPaget/Alaya
---
Alaya is a chrooting webserver with basic webdav extensions. It can serve both http and https and is intended to provide a simple means for people to share directories with webdav. Although it chroots it supports running CGI programs outside of the chroot via a trusted-path method. Alaya aims at ease of use, so all options can be configured via command-line args, though a config file is also supported.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
Done before. I forgot to close this issue, sorry.
