### ISSUE TITLE
Package elinks fails to compile

### ISSUE THREAD

**Issue by egorenar** [Entware/Entware#388]
elinks doesn't compile with the latest master.

/home/egorenar/Repositories/Entware/staging_dir/toolchain-arm_cortex-a9_gcc-7.4.0_glibc-2.27_eabi/lib/gcc/arm-openwrt-linux-gnueabi/7.4.0/../../../../arm-openwrt-linux-gnueabi/bin/ld: lib.o: in function `set_nonblocking_fd':
vs.c:(.text+0x43704): undefined reference to `fcntl64'
/home/egorenar/Repositories/Entware/staging_dir/toolchain-arm_cortex-a9_gcc-7.4.0_glibc-2.27_eabi/l`

**Comment by zyxmon** [comment]
We have no problems compiling elinks. In case you compile a different version or with different options - you'll need to make patches or other fixes yourself.
