### ISSUE TITLE
failed to install on synology NAS

### ISSUE THREAD

**Issue by tantrumToBlind** [Entware/Entware#39]
i'm on Synology DS211, with armv5 CPU Marvell Kirkwood 88F6282.
followed the instruction to execute http://bin.entware.net/armv5sf-k3.2/installer/generic.sh
however, it failed at command lines
/opt/bin/opkg update
and
/opt/bin/opkg install entware-opt
getting error msg of "FATAL: kernel too old"
My DSM version is DSM 6.1.4-15217 Update 5

**Comment by zyxmon** [comment]
Your kernel is old -2.6.32. It is not supported/ Try to install Enware-ng. Your installer script is - http://pkg.entware.net/binaries/armv5/installer/entware_install.sh
