### ISSUE TITLE
jq not working on Asuswrt-Merlin 384.14 (RT-AC88U)

### ISSUE THREAD

**Issue by Xentrk** [Entware/Entware#391]
I have a new error with the jq package:
 
`# jq -r '.prefixes | .[].ip_prefix' < ip-ranges.json`
`jq: error while loading shared libraries: libonig.so: cannot open shared object file: No such file or directory`
`# jq`
`jq: error while loading shared libraries: libonig.so: cannot open shared object file: No such file or directory`
`# echo $PATH`
`/opt/bin:/opt/sbin:/bin:/usr/bin:/sbin:/usr/sbin:/home/wizard:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin`
`# find / -name libonig.so`
`  `
`# `

**Comment by ryzhovau** [comment]
```
opkg install oniguruma
```
Looks like `opkg` fails to detect new `jq` dependency. This error can't be reproduced on fresh install, so I'm closing this issue.

**Comment by Xentrk** [comment]
Thank you @ryzhovau 

````opkg install oniguruma
Package oniguruma (6.9.3-1) installed in root is up to date.
# jq
jq: error while loading shared libraries: libonig.so: cannot open shared object file: No such file or directory
````

**Comment by Xentrk** [comment]
I am now on 384.15 beta 1 release and applied the entware updates that were pushed yesterday. I still have the jq error message:

`jq: error while loading shared libraries: libonig.so: cannot open shared object file: No such file or directory`

From /jffs/scripts directory, I used the command below to see if libonig.so was installed:

`find / -iname libonig.so*`

The command returned:

`/tmp/mnt/entware/entware/lib/libonig.so.5`

I then navigated to the directory and issued the command below to copy libonig.so.5 to libonig.so:

`cp libonig.so.5 libonig.so`

jq now works!

**Comment by ryzhovau** [comment]
Can't reproduce on fresh install:
```
~ # opkg install jq
Installing jq (1.6-1) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/jq_1.6-1_mipsel-3.4.ipk
Installing oniguruma (6.9.3-1) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/oniguruma_6.9.3-1_mipsel-3.4.ipk
Configuring oniguruma.
Configuring jq.
~ # ldd /opt/bin/jq
        linux-vdso.so.1 (0x771d0000)
        libm.so.6 => /opt/lib/libm.so.6 (0x77098000)
        libonig.so.5 => /opt/lib/libonig.so.5 (0x77005000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x76fdf000)
        libc.so.6 => /opt/lib/libc.so.6 (0x76e52000)
        /opt/lib/ld.so.1 (0x7719e000)
```
Please, reinstall `jq` and `oniguruma` and try again.

**Comment by jackyaz** [comment]
@Xentrk you could use something like
```
opkg update && opkg remove --autoremove jq && opkg install jq
```

**Comment by Xentrk** [comment]
> 
> 
> @Xentrk you could use something like
> 
> ```
> opkg update && opkg remove --autoremove jq && opkg install jq
> ```
Thank you Mr. Yaz,

The command solved the problem.  Thank you @jackyaz and @ryzhovau
