### ISSUE TITLE
libcurl: curl-config missing

### ISSUE THREAD

**Issue by oke24** [Entware/Entware#392]
On my Synology DS218play (aarch64) I installed the actual Entware distribution.
Also I installed the packages curl 7.66 and libcurl 7.66.

When compiling a source using 
`./configure --prefix=/opt`
I get an error
`checking for curl-config... no
configure: error: curl-config not found`
 
What have I to do to get curl-config installed ?
As I saw curl-config is part of libcurl since V 7.7.x. The acutal Entware distribution contains V 7.66.x, but curl-config isn't included in the /opt tree .

**Comment by zyxmon** [comment]
We provide native compilation mostly for perl and python - users can build there own modules.
We do not provide support for native compilation.
You can build curl yoursel to get curl-config

**Comment by UserX404** [comment]
same problem here
Can anyone please give some information how to build curl with curl-config.
Thanks

**Comment by zyxmon** [comment]
@UserX404 - make a patch to build without curl-config if possible or use crosscompiling.
