### ISSUE TITLE
GeoIP update

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#395]
Package request - geoipupdate

Incremental updater for MaxMind GeoIP databases

- [x] No similar package already added
- [x] C version is frozen but 1 year old
- [x] I'm ready to test added package on my RT-N18U and get a feedback about it.

New versions are in Go AFAIK compilation is problematic - https://github.com/maxmind/geoipupdate

Legacy C version - https://github.com/maxmind/geoipupdate-legacy

**Comment by ryzhovau** [comment]
GeoIP isn't a free software anymore, so we won't add it, sorry.

**Comment by pasha-zzz** [comment]
Its free but downloadable with login/pass (for free too).
