### ISSUE TITLE
Package-request: Portproxy

### ISSUE THREAD

**Issue by wellloaded** [Entware/Entware#396]
Portproxy official site: http://klub.com.pl/portproxy/

Portproxy allows to pass proxy UPNP requests to the upstream router router in case of cascade router scenario (multiple nat-ted devices). Last release is 2010 but to be fair UPNP hasn't evolved either. Looking to run this within Tomato/DD-WRT devices. 

- [X] No similar package already added and/or this one got some new killer feature(s),
- [ ]  Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my {platform} and get a feedback about it.

I have found a MIPS compiled version we would need the ARM version too.
https://tomato.groov.pl/repo/portproxy_2010-03-02-1_mipsel.ipk

Thanks!

**Comment by ryzhovau** [comment]
Won't add abandoned software, sorry.
