### ISSUE TITLE
Update mpd to 0.21.18 version

### ISSUE THREAD

**Issue by AndriiZ** [Entware/Entware#397]
Package request

mpd in repo has a version 0.20.23-3
---
mpd in 0.21 branch added few usefull features, for example forcing charset for icecast streams with cp1251 header. Existing version can not properly decode header in cp1251, while 0.21 can

- [+ ] No similar package already added and/or this one got some new killer feature(s),
- [+] Package is in active development (at least, not abandoned for 5 years or more),
- [+] I'm ready to test added package on my {platform} and get a feedback about it.

---

**Comment by AndriiZ** [comment]
https://github.com/MusicPlayerDaemon/MPD/issues/616

**Comment by ryzhovau** [comment]
It's up to upstream. We synced recently, mpd updated to 0.21.16.
