### ISSUE TITLE
MiniDLNA, Dovecot: file not found /opt/etc/passwd

### ISSUE THREAD

**Issue by blackfuel** [Entware/Entware#4]
### Package: MiniDLNA and Dovecot
Since the new Entware merge, I now must do this once before starting MiniDLNA or Dovecot.  These programs try to lookup the user in this password file `/opt/etc/passwd`, and it fails to start.  My workaround fix links to the real ones.
`for F in passwd group shadow gshadow; do ln -sf /etc/$F /opt/etc/$F; done`

### Platform: RT-AC68U Asuswrt-Merlin
Entware armv7-2.6 compiled from source.

**Comment by zyxmon** [comment]
How have you installed Entware? These simlinks should be created by install script?

The only scenario when these symlinks are missing for armv7 is probably when you have used asuswrt-install.sh script for armv7 that was given in snbforum topic.
In this case I'd recomend to run
```
opkg remove asuswrt-opt
opkg install entware-opt
wget http://bin.entware.net/other/symlinks.sh -O- | sh
```
Some more symlinks will be created. Your installation will be correct.
Symlinks are created for 64 arm asuswrt installation - it was tested.

**Comment by blackfuel** [comment]
Running the `symlinks.sh` script fixed my problem.  I use a local Entware repo that I compiled myself.  Just recently I switched from Entware-ng to the new Entware.
