### ISSUE TITLE
Package request: pinentry

### ISSUE THREAD

**Issue by vimanderer934** [Entware/Entware#403]
Package request: https://www.gnupg.org/software/pinentry/index.html
---
pinentry is a small collection of dialog programs that allow GnuPG to read passphrases and PIN numbers in a secure manner. 

This is necessary for GPG integration with Vim and other interactive programs.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my armv7 Synology and get a feedback about it.

**Comment by vimanderer934** [comment]
I created a Makefile that successfully compiles this package.

The pull request for rtndev is here if this is appropriate:
https://github.com/Entware/rtndev/pull/13

**Comment by ryzhovau** [comment]
Thanks for PR again.
