### ISSUE TITLE
Package request: Additional iptables/x-table support modules

### ISSUE THREAD

**Issue by raisindetre** [Entware/Entware#405]
Package request
---
Standard 4.14.x kernel (on Asustor NAS at least) lacks a lot of iptables modules which are used by Docker instances to provide useful functions like a Deluge installation configured through a VPN tunnel (i.e. [binhex/arch-delugevpn](https://hub.docker.com/r/binhex/arch-delugevpn/). 

Would it be possible to build a package which provides [the following](http://forum.banana-pi.org/t/kernel-very-limited-x-table-support/6502/2) iptables modules compatible with the v1.4.13 iptables install?

- [X ] No similar package already added and/or this one got some new killer feature(s),

**Comment by zyxmon** [comment]
I am afraid it is impossible.
