### ISSUE TITLE
"make menuconfig" fails because hostapd package cannot find wpad package

### ISSUE THREAD

**Issue by egorenar** [Entware/Entware#407]
Tested with armv7-3.2 config.

WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-basic', which does `

**Comment by ryzhovau** [comment]
You may ignore this messages. As you can see from `make menuconfig`, not all upstream packages are used.

**Comment by zyxmon** [comment]
Please note - we cannot help with packages that are not part of Entware. hostapd is not in Entware.

**Comment by egorenar** [comment]
hmm, i would like to ignore it but i get a syntax error in tmp/.config-packages.in.
Only if i remove hostapd package completely can i do make menuconfig

Here is the error:
tmp/.config-package.in:4522: syntax error
tmp/.config-package.in:4521: invalid option
tmp/.config-package.in:5105: syntax error
tmp/.config-package.in:5104: invalid option


I traced it back to this:
 config PACKAGE_hostapd-utils
4513         tristate "hostapd-utils.......................... IEEE 802.1x Authenticator (utils)"
4514         default y if DEFAULT_hostapd-utils
4515         default m if ALL
4516         select PACKAGE_libc
4517         depends on PACKAGE_PACKAGE_hostapd-basic
4518         select PACKAGE_libssp if GCC_LIBSSP
4519         depends on PACKAGE_PACKAGE_wpad-openssl
4520         depends on PACKAGE_PACKAGE_hostapd-mini
4521         depends on PACKAGE_PACKAGE_wpad-wolfssl||            <-------- HERE !!!     || seems to be the reason
4522         depends on PACKAGE_hostapd
4523         depends on PACKAGE_PACKAGE_hostapd-wolfssl
4524         select PACKAGE_libpthread if USE_GLIBC
4525         depends on PACKAGE_PACKAGE_wpad-mini
4526         depends on PACKAGE_PACKAGE_wpad-basic
4527         depends on PACKAGE_PACKAGE_wpad
4528         depends on PACKAGE_PACKAGE_wpad-mesh-openssl
4529         depends on PACKAGE_PACKAGE_hostapd-openssl
4530         depends on PACKAGE_PACKAGE_wpad-mesh-wolfssl
4531         select PACKAGE_librt if USE_GLIBC
4532         help
4533          This package contains a command line utility to control the
4534           IEEE 802.1x/WPA/EAP/RADIUS Authenticator.
4535          http://hostap.epitest.fi/
4536          Felix Fietkau <nbd@nbd.name>
4537


Note: i cleaned my repo and updated all the package repos. No local modifications.

**Comment by zyxmon** [comment]
The instructions in wiki are valid for debian 9 and 10 x64. What is your distro?
Try to clean tmp subfolder and remove hostapd folder.

**Comment by egorenar** [comment]
My distro is void linux and it worked fine in december 2019.
I cleaned everything with git clean, removing packages/network/services/hostapd helps but i consider it a hack.

**Comment by egorenar** [comment]
It works on Debian, sorry for spamming :)
