### ISSUE TITLE
mpd-mini 0.21: libraries not found

### ISSUE THREAD

**Issue by bayonne** [Entware/Entware#408]
Hello, 

After the February 2020 update, package mpd-mini 0.21.16-1 is installed on my nas.
I get this:

ldd /opt/bin/mpd
	linux-vdso.so.1 (0x00007ffca8f2c000)
	libz.so.1 => not found
	libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f1677588000)
	libasound.so.2 => /usr/lib/libasound.so.2 (0x00007f1677264000)
	libFLAC.so.8 => not found
	libmpg123.so.0 => not found
	libvorbisidec.so.1 => not found
	libogg.so.0 => not found
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f1677039000)
	libmpdclient.so.2 => not found
	libiconv.so.2 => not found
	libstdc++.so.6 => not found
	libm.so.6 => not found
	libgcc_s.so.1 => not found
	libpthread.so.0 => not found
	libc.so.6 => not found
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007f1676bdc000)
	liblber-2.4.so.2 => not found
	libldap-2.4.so.2 => /usr/lib/libldap-2.4.so.2 (0x00007f1676998000)
	libz.so.1 => not found
	libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007f167678d000)
	libiconv.so.2 => not found
	libidn.so.11 => /usr/lib/libidn.so.11 (0x00007f167655b000)
	/opt/lib/ld-linux-x86-64.so.2 (0x00007f16777f0000)
	libc.so.6 => not found
	libm.so.6 => not found
	libdl.so.2 => not found
	libpthread.so.0 => not found
	librt.so.1 => not found
	libc.so.6 => not found
	libc.so.6 => not found
	libdl.so.2 => not found
	libc.so.6 => not found
	liblber-2.4.so.2 => //lib/liblber-2.4.so.2 (0x00007f1676349000)
	libresolv.so.2 => //lib/libresolv.so.2 (0x00007f1676131000)
	libssl.so.1.0.0 => //lib/libssl.so.1.0.0 (0x00007f1675eb7000)
	libc.so.6 => //lib/libc.so.6 (0x00007f1675b12000)
	libdl.so.2 => /lib/libdl.so.2 (0x00007f167590e000)
	libiconv.so.2 => not found

Please advise.

**Comment by zyxmon** [comment]
Fixed now via https://github.com/Entware/entware-packages/commit/a175bdcfe3dc6a940999dc9a26b854acf69417fe
