### ISSUE TITLE
Prosody

### ISSUE THREAD

**Issue by exclamationgm** [Entware/entware#41]
I'm curious, that we have no xmpp server in the repo and I need one right now ;-). So I would like to request prosody. There was such an issue on google-code:

https://code.google.com/p/wl500g-repo/issues/detail?id=263

thx !gm

**Comment by YasharF** [comment]
OpenWRT package feed - prosody: https://github.com/openwrt/packages/tree/21e7de8f066449b91454097d63e7ceb138bf26df/net/prosody

**Comment by ryzhovau** [comment]
Done.
