### ISSUE TITLE
Request to update Transmission to 2.93

### ISSUE THREAD

**Issue by minglespy** [Entware/Entware#41]
Package request

versions earlier than 2.93 have been blocked by a number of trackers due to security flaws. Could you update the package to the latest version?

Many thanks.

**Comment by zyxmon** [comment]
Transmission was updated to 2.93 two months ago
https://github.com/Entware/entware-packages/blob/master/net/transmission/Makefile

**Comment by minglespy** [comment]
OK thanks - I was looking trying to upgrade a mipsel device rather than arm. The repository still has Transmission at 2.92 [http://pkg.entware.net/binaries/mipsel/Packages.html](url)

**Comment by zyxmon** [comment]
@minglespy - you are using Entware-ng that will never be updated. If your kernel is 3.4 or higher - you'll need to upgrade to Entware. Mipsel devices with 2.6.22 kernel were a headache to adopt modern sources to compile and run. That is why Entware-ng development stopped.

**Comment by minglespy** [comment]
@zyxmon - thanks for your help. I'm on using the ASUS AC66U on kernel 2.6.22 so it doesn't look like I'll be able to upgrade. Thanks anyway!
