### ISSUE TITLE
Package Request: GDriveFS

### ISSUE THREAD

**Issue by greyltc** [Entware/Entware#413]
Package request GDriveFS
---
https://github.com/dsoprea/GDriveFS
Looks like an actively maintained tool to fuse mount my google drive space in my NAS. I've tried the solution that QNAP gives us in its App Center and it seems to be garbage, maybe this is better?
I don't immediately see another Entware package that provides this. Is there one?

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my armv5tel QNAP NAS and get a feedback about it.

**Comment by zyxmon** [comment]
You can try to compile it yourself with 0 https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules
