### ISSUE TITLE
Package Request : icu-full-data

### ISSUE THREAD

**Issue by DaPoHou** [Entware/Entware#417]
Package request http://site.icu-project.org/
---
icu-full-data provide complete icu transliteration algorithm.
After installing the php7-mod-intl extension, many programs will have errors because there is no corresponding transliteration algorithm.
As a result, the php7-mod-intl module is useless.
http://downloads.openwrt.org/snapshots/packages/x86_64/packages/icu-full-data_65.1-2_x86_64.ipk
https://github.com/openwrt/packages/tree/master/libs/icu

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my X86_64 and get a feedback about it.
---
Tried to build myself but was unsuccessful but I have no experience cross-compiling, or embedded development or with Openwrt or entware development.

**Comment by The-BB** [comment]
Done.
