### ISSUE TITLE
Upgrade ZeroTireOne

### ISSUE THREAD

**Issue by illuminateX** [Entware/Entware#419]
Package upgrade request
---
ZeroTier is a smart programmable Ethernet switch for planet Earth. It allows all networked devices, VMs, containers, and applications to communicate as if they all reside in the same physical data center or cloud region.

current package version is 1.4.0 (1.0.3 with Entware now), too old to connect to sever, it will be very helpful to upgrade to new version.

thanks

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
I presume you are using Entware-ng which is obsolete.
