### ISSUE TITLE
Package Request: Nix

### ISSUE THREAD

**Issue by ghost** [Entware/Entware#420]
Package request https://nixos.org/nix/
---
Nix is a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible. It provides atomic upgrades and rollbacks, side-by-side installation of multiple versions of a package, multi-user package management and easy setup of build environments.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by zyxmon** [comment]
Entware uses opkg package manager - an openwrt fork of https://www.yoctoproject.org/software-item/opkg/
