### ISSUE TITLE
Suggestion: Add version to Entware

### ISSUE THREAD

**Issue by JACK-THINK** [Entware/Entware#421]
## Suggestion

Please give every release of Entware a version (ex. v20191007) and organize all the packages according to the specific version of Entware. In this way, people could install the specific release of Entware they like. (ex. `wget -O - "http://bin.entware.net/armv7sf-k2.6/installer/generic.sh_v20191007" | sh`). When people execute 'opkg install python', opkg will just install the package python_2.7.16-9_armv7-2.6.ipk which belongs to Entware_v20191007, not the package python_2.7.17-1_armv7-2.6.ipk which belongs to Entware_v20200201.

**Comment by ryzhovau** [comment]
This isn't possible, sorry.
