### ISSUE TITLE
Package request: rsync-bpc

### ISSUE THREAD

**Issue by adamgolebiowski** [Entware/Entware#422]
Rsync-bpc (https://github.com/backuppc/rsync-bpc/) is a customized version of rsync that is used as part of BackupPC. 
By adding this package it will be possible to make full potential of BackupPC while making backups of devices running Entware.

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by ryzhovau** [comment]
We've got 5+ backup solution in repo, couple of them based on rsync. 
Why should we add another one? Please, describe the killer feature of `rsync-bpc`.
