### ISSUE TITLE
Package request: Gotify

### ISSUE THREAD

**Issue by drlauridsen** [Entware/Entware#423]
Package request
---
Free selfhosted notification/message server with a free android app. 

- [x ] No similar package already added and/or this one got some new killer feature(s),
- [x ] Package is in active development (at least, not abandoned for 5 years or more),
- [ x] I'm ready to test added package on my {RTAC87U} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by zyxmon** [comment]
Not now. Because of - https://gotify.net/docs/dev-setup
