### ISSUE TITLE
p7zip 19.00

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#425]
Author of Total Commander partially ported 19.00 to Android (and I think Linux):
https://www.ghisler.ch/board/viewtopic.php?p=370688#p370688

Asm includes and creating of archives are removed. Maybe make standalone package like "unp7zip 19.00"? p7zip 16.02 is 4 years old.

**Comment by ryzhovau** [comment]
We going to sit on current p7zip version (as Debian do) until some newer version will be ready for cross-compilation, sorry.

Please, don't create any new p7zip-related issues until then.
