### ISSUE TITLE
curses.h

### ISSUE THREAD

**Issue by bulbalion** [Entware/Entware#428]
Package request
---
curses.h needed. First or all I want to thank You for You huge effort to make this software alive. What I'm not up to is installing the entware on my device and I'm very satisfied with that. I would have a question whether it is feasible to port curses development libraries to the packages. I'm currently using my NAS device as a Bulletin Board System. And for that I would need to compile several programs. To do so curses.h is all I need above gcc (that's already working very good).

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my {platform} and get a feedback about it.

---

**Comment by ryzhovau** [comment]
https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation
