### ISSUE TITLE
Package request - Gerbera

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#432]
Package request - Gerbera
---
DLNA server, successor of MediaTomb. F.e. supports HEVC streaming.
https://github.com/gerbera/gerbera

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my N18U and get a feedback about it.

**Comment by ryzhovau** [comment]
Gerbera is present in repo since 2017.
