### ISSUE TITLE
nodejs v12.16.1 or at least v10.x (v10.19.0) for armv7l kernel 2.6.36?

### ISSUE THREAD

**Issue by foodtourama** [Entware/Entware#433]
Hi!
I'm on Entware-ng:
Linux RT-AC56U-A5C0 2.6.36.4brcmarm #2 SMP PREEMPT Wed Mar 29 00:48:09 EDT 2017 armv7l ASUSWRT-Merlin

My ASUS router has 256 MB RAM,  2 core 800 MHz armv7l
And I can only successfully install node v6.11.2, but it is pretty outdated now...

Package request:
Is it possible to install at least node v10.x (v12.x would be awesome) or is there a hardware/software limitation for armv7l ?

{
Killer feature of package?
Nodejs version 10 or above is required to interpret Cloudflare's obfuscated JavaScript challenge.
I can confirm node v12.16.1 works great on Ubuntu 18 for this purpose.
I can confirm node v6.11.2 doesn't work on ASUS Entware-ng armv7l for this. (kernel 2.6.36)
}

- [x] There is node v6.11.2 for armv7l but it's outdated. Version 10+ got some new killer feature(s),
- [x] Nodejs is in active development,
- [x] I'm ready to test added package on my {ASUS Entware-ng armv7l} and get a feedback about it.
---
Cheers!

**Comment by zyxmon** [comment]
Entware contains node 12.x. Entware-ng is not supported and updated.
