### ISSUE TITLE
please update padavan tvheadend(mipsel) 4.0.10 to 4.2.x,thanks

### ISSUE THREAD

**Issue by cjd6568358** [Entware/Entware#434]
Package request
---
{Describe killer feature of package}

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
Won't do that, sorry. You can find explanation here https://github.com/Entware/Entware/issues/58#issuecomment-420265299
