### ISSUE TITLE
php7_PDO_firebird support! the interbase wrapper for PDO in PHP 

### ISSUE THREAD

**Issue by marcionnc** [Entware/Entware#435]
Package request
---
The php - PDO wrapper for firebird databases (interbase). It was discontinued but please provide a *.so package for use in QNAP NAS

- [ X ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ X ] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
No firebird/interbase support in repo is planned. Won't add it, sorry.
