### ISSUE TITLE
Issue with tcpdump/libpcap

### ISSUE THREAD

**Issue by theofficialgman** [Entware/Entware#436]
Currently trying to run tcpdump produces errors
Error relocating /opt/lib/libpcap.so.1: getnetbyname_r: symbol not found
Error relocating /opt/lib/libpcap.so.1: getprotobyname_r: symbol not found

Both tcpdump and libpcap were installed using entware and are fully up to date packages.

Linksys EA6500 V1
Firmware: DD-WRT v3.0-r42681 giga (3/13/20)
Kernel: Linux 3.19.108-d10

**Comment by ryzhovau** [comment]
Can't reproduce with fresh install, you may fall into [this issue](https://github.com/Entware/Entware/wiki#note-about-packages-upgrade). Please, install Entware from scratch.
```
/opt/home/admin # opkg install tcpdump
Installing tcpdump (4.9.3-1) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/tcpdump_4.9.3-1_mipsel-3.4.
Installing libpcap (1.9.1-2) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/libpcap_1.9.1-2_mipsel-3.4.
Configuring libpcap.
Configuring tcpdump.

/opt/home/admin # ldd  `which tcpdump`
        libpcap.so.1 => /opt/lib/libpcap.so.1 (0x77059000)
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x77033000)
        libc.so.6 => /opt/lib/libc.so.6 (0x76ea6000)
        /opt/lib/ld.so.1 (0x770a7000)
/opt/home/admin # tcpdump -V
tcpdump: option requires an argument -- 'V'
tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
…
```
