### ISSUE TITLE
Package libopenssl improvement

### ISSUE THREAD

**Issue by kvic-z** [Entware/Entware#44]
**Package libopenssl**

I think both Openwrt and Entware shall add '-DOPENSSL_NO_BUF_FREELISTS' to CFLAGS. 

Considering both targeting embedded devices usually with small memory footprints, this flag will save tremendous RAM on medium to high SSL workload.

I think this will be very good for Entware.

**Comment by ryzhovau** [comment]
Not sure such devices with minimal memory footprints capable for medium to high SSL workload, sorry.

We've got 170+ `openssl` dependent packages, so we leave `openssl` configuration as close as possible to upstream to avoid compatibility and/or stability issues.
