### ISSUE TITLE
Missing Perl package

### ISSUE THREAD

**Issue by thebigft** [Entware/Entware#441]
Package request
---
Perl Try::Tiny package

This package is needed by perl's LWP package, specifically the UserAgent.pm file.

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my nas (armv7) platform and get a feedback about it.

Thanks.

**Comment by zyxmon** [comment]
Please use wiki - https://github.com/Entware/Entware/wiki/Self-installation-of-perl-modules
This module is easily installed via CPAN - `install Try:Tiny`:
```
Result: PASS
  ETHER/Try-Tiny-0.30.tar.gz
  /opt/bin/make test -- OK
Running make install
Installing /opt/lib/perl5/5.28/Try/Tiny.pm
Appending installation info to /opt/lib/perl5/5.28/perllocal.pod
  ETHER/Try-Tiny-0.30.tar.gz
  /opt/bin/make install  -- OK

```
