### ISSUE TITLE
Package Request : mtd-utils, mkfs.jffs2

### ISSUE THREAD

**Issue by ghost** [Entware/Entware#442]
Package request
---
mtd-utils, especially mkfs.jffs2 is indispensable tool for routers and other embedded devices.

- [x] No similar package already added,
- [x] Package is in active development,
- [ ] I'm ready to test added package on my router (arm-brcm) and get a feedback about it.

Thank you.

**Comment by KyleSanderson** [comment]
@ryzhovau any update on this one? I'm in quite a jam and am quite surprised https://github.com/Entware/Entware/tree/master/package/utils/mtd-utils is in the tree but not built...

**Comment by ghost** [comment]
I had to compile it myself from the [official sources](http://linux-mtd.infradead.org/), not entware.

**Comment by KyleSanderson** [comment]
@M95D can you help me out with how you built it (I'm 2.6.36brcm / armv7)? My jffs2 partition is still messed up unfortunately.

**Comment by ghost** [comment]
Sure. I used Asus Merlin sources. There's a toolchain included.
[mtd-utils-2.1.1-brcmarm.tar.gz](https://github.com/Entware/Entware/files/4604896/mtd-utils-2.1.1-brcmarm.tar.gz)

**Comment by KyleSanderson** [comment]
Thanks fellow human, I owe you a beer.
