### ISSUE TITLE
msmtpq requires bash

### ISSUE THREAD

**Issue by davygravy** [Entware/Entware#443]
I installed msmtpq/msmtp-queue and it works (after some modifications), but the basic executable script located at /opt/bin/msptpq seems to have a typo in it.  

Line 1 reads:
`#! /bin/sh`
which of course causes the script to be executed with the built-in Busybox shell, which is `ash`.

Invoking it gives:
`
root@host:/tmp/home/root# msmtpq
/opt/bin/msmtpq: line 117: declare: not found
/opt/bin/msmtpq: line 118: declare: not found
/opt/bin/msmtpq: line 357: syntax error: bad substitution`

The `declare` function is not included in `ash`, but is included in `bash`.

Changing line 1 to 
`#! /opt/bin/bash` fixed it for me.

I am -not- sure that this is the best way to fix it.

**Comment by ryzhovau** [comment]
Thanks for report. We should find some graceful way to solve it.

**Comment by davygravy** [comment]
Thanks Alexander!  Cheers & stay well!

**Comment by ryzhovau** [comment]
The easiest way is to install bash and change shebang strings.
The best way is to rewrite those scripts with no bash'ism.

Our upstream already [tried](https://github.com/openwrt/packages/issues/11547#issuecomment-597427384) to get best way with no success, so we pick the easiest way for now.

**Comment by eigood** [comment]
#!/usr/bin/env bash

Then normal $PATH lookup occurs, and finds bash in /opt.

**Comment by ryzhovau** [comment]
Since 1.8.7 `msmtp-queue` requires bash.
