### ISSUE TITLE
knockd throws pcap syntax error on Asuswrt-Merlin

### ISSUE THREAD

**Issue by pjm111** [Entware/Entware#445]
After installing and configuring knockd 0.7.8.1 from Entware on a router running Asuswrt-Merlin, I see the following error when attempting to start knockd:
**pcap: can't parse filter expression: syntax error**

The knockd start attempt was with the following command line:
**/opt/sbin/knockd -d -c '/opt/etc/knockd.conf' -i eth0**

A web search reveals a possibly related issue being discussed here:
**https://forums.opensuse.org/showthread.php/536111-Knockd-unable-to-start-after-upgrade-from-15-0-to-15-1**

Is this error a known problem and is there a fix on the way?  Does Entware have the latest knockd build?

**Comment by ryzhovau** [comment]
Works for me, can't reproduce on other firmwares.
