### ISSUE TITLE
Asterisk cdr_mysql

### ISSUE THREAD

**Issue by e-crewing** [Entware/Entware#446]
Package request
---
{Asterisk11 cdr mysql module}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by zyxmon** [comment]
We do not compile Asterisk 11 for Entware. Probably you still use old Entware-ng.
