### ISSUE TITLE
Package Request : atool

### ISSUE THREAD

**Issue by druchoo** [Entware/Entware#448]
Package request
---

> [atool](http://www.nongnu.org/atool) is a script for managing file archives of various types (tar, tar+gzip, zip etc).

atool's best feature is allowing easy conversion of any supported archive format to another. This can be done for one or multiple files.

Supported file types are `7z`, `ace`, `alzip`, `arc`, `arj`, `bzip`, `bzip2`, `cpoi`, `gzip`, `lda`, `lzip`, `lzma`, `lzop`, `pbzip2`, `plzip`, `rar`, `rpm`, `tar` & `zip`

The complete set of functionality are symlinked to separate commands. Along with `--each` options allows operations on multiple files; avoiding the need for any shell `for` loops.

> Usage: atool [OPTION]... ARCHIVE [FILE]...
>        atool -e [OPTION]... [ARCHIVE]...
> Manage file archives of various types.
> 
> Commands:
>   -l, --list               list files in archive (`als`)
>   -x, --extract            extract files from archive (`aunpack`)
>   -X, --extract-to=PATH    extract archive to specified directory
>   -a, --add                create archive (`apack`)
>   -c, --cat                extract file to standard out (`acat`)
>   -d, --diff               generate a diff between two archives (`adiff`)
>   -r, --repack             repack archives to a different format (**`arepack`**)
>       --help               display this help and exit
>       --version            output version information and exit
> 
> Options:
>   -e, **--each**               execute command above for each file specified
>   -F, --format=EXT         override archive format (see below)
>   -O, --format-option=OPT  give specific options to the archiver
>   -D, --subdir             always create subdirectory when extracting
>   -f, --force              allow overwriting of local files
>   -q, --quiet              decrease verbosity level by one
>   -v, --verbose            increase verbosity level by one
>   -V, --verbosity=LEVEL    specify verbosity (0, 1 or 2)
>   -p, --page               send output through pager
>   -0, --null               filenames from standard in are null-byte separated
>   -E, --explain            explain what is being done by atool
>   -S, --simulate           simulation mode - no filesystem changes are made
>   -o, --option=KEY=VALUE   override a configuration option
>       --config=FILE        load configuration defaults from file

I was able to compile atool from source. Just needed to install `make` to build. Then some Perl packages to run; `perlbase-bytes`, `perlbase-config`, `perlbase-encode`, `perlbase-essential`, `perlbase-file`, `perlbase-getopt`, `perlbase-storable`. Might be others but I already had Perl installed.

I'm currently using atool to convert my ROM collection from `zip` to `7z`.

```
$ arepack --each --format=7z --format-option=-mx=9 --explain *.zip
```

- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

**Comment by zyxmon** [comment]
1. Please follow the wiki - https://github.com/Entware/Entware/wiki/Self-installation-of-perl-modules
(**note** you do not need to install gcc, but you need make and other binaries).
2. Unpack atool to any dir and run
```
./configure --prefix=/opt
make install
```
You will have working atool.
