### ISSUE TITLE
update git to 2.26.1

### ISSUE THREAD

**Issue by auge** [Entware/Entware#452]
Package update request
---
to include security fix as announced by [[1]](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.26.1.txt)

- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my {platform} and get a feedback about it.

---

**Comment by ryzhovau** [comment]
It's up to [upstream](https://github.com/openwrt/packages/blob/master/net/git/Makefile). 
Please, [ask](https://github.com/openwrt/packages/issues) OpenWrt guys to update it.
