### ISSUE TITLE
Make stable version of SoftEther VPN server available on Entware.

### ISSUE THREAD

**Issue by Myron-S** [Entware/Entware#456]
SoftEther VPN (Stable Edition Repository): Open Cross-platform Multi-protocol VPN Software. This branch is officially managed by Daiyuu Nobori, the owner of SoftEther VPN Project.
---
{The stable edition of SoftEther VPN is not available on Entware. Can this be included so stable or developer version can be selected for install?}

https://github.com/SoftEtherVPN/SoftEtherVPN_Stable

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
It's up to [upstream](https://github.com/openwrt/packages/tree/master/net/softethervpn). 
Please, [ask](https://github.com/openwrt/packages/issues) OpenWrt guys to update it.

**Comment by Myron-S** [comment]
I'm told from the OpenWRT side; "Entware problem. Version 9674 is already available here."
Who on entware need to get this and do what is needed to get this on the entware repo?

**Comment by ryzhovau** [comment]
We'll update SoftEther VPN in first half of september.
