### ISSUE TITLE
Package request: dnscrypt-proxy 2

### ISSUE THREAD

**Issue by ghost** [Entware/Entware#46]
Package request for dnscrypt-proxy 2

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ x] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I successfully tested added package on my {platform}.

_"A flexible DNS proxy, with support for modern encrypted DNS protocols such as DNSCrypt v2 and DNS-over-HTTP/2."_
Info: [https://github.com/jedisct1/dnscrypt-proxy](url)
Probably not a whole lot different from dnscrypt-proxy - 1.9.5-7 for those who use and knows what this is but they have added a few bells and whistles here and there and some new servers in their resolver list most notably the newly started Cloudflare DNS 1.1.1.1 / 1.0.0.1.

My device: Xiaomi WiFi Router 3G
SoC: MediaTek MT7621AT - mips
Firmware: Padavan 3.4.3.9-099_dff9a34
Info: [https://wiki.openwrt.org/toh/xiaomi/mir3g](url)

**Comment by zyxmon** [comment]
This is the third issue on  dnscrypt-proxy 2. Please use "search". The package was already added. Binaries will be with next openwrt sync. There is a test package for your arch. The link is in one of the previous issues.
