### ISSUE TITLE
Package Requests: lttng-ust

### ISSUE THREAD

**Issue by jprigal** [Entware/Entware#460]
Package request
---
This package is a tracing framework for Linux. ust is user stack tracing.
https://lttng.org/download/

What makes it unique is that it is the only missing pre-requisite for having the .Net Core framework running on Linux.
https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux#linux-distribution-dependencies

So, once available, we should be able to run all  applications developed using the .Net Core.

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my QNAP NAS and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
.Net Core framework is not ready for cross-compilation to our feeds, so we won't add it.
https://github.com/dotnet/runtime/issues/4234

We've got another stack tracing utilities in repo, including `gdb`, so there's no sense to add `LTTng-UST` I'm afraid. Sorry.
