### ISSUE TITLE
Package request: pdftocairo

### ISSUE THREAD

**Issue by andjar** [Entware/Entware#461]
Package request
---
pdftocairo converts Portable Document Format (PDF) files, using the cairo output device of the poppler PDF library, to any of the following output formats:
* Portable Network Graphics (PNG)
* JPEG Interchange Format (JPEG)
* Tagged Image File Format (TIFF)
* Portable Document Format (PDF)
* PostScript (PS)
* Encapsulated PostScript (EPS)
* Scalable Vector Graphics (SVG)

It used to be a part of the poppler-utils that already is available. It can be used to preprocess pdfs for rendering, OCR etc (eg. in [I, librarian](https://github.com/mkucej/i-librarian-free))

- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my Synology DS218 and get a feedback about it.

**Comment by ryzhovau** [comment]
We trying to keep balance between number of features and lightness for such kind of packages. Not sure we want to add such heavy dependencies for `poppler`, sorry.
