### ISSUE TITLE
Package Request : qemu

### ISSUE THREAD

**Issue by kornero** [Entware/Entware#462]
Package request
---
Hello. QEMU (https://www.qemu.org/download/#source) can allow us to run any OS or run modern kernel on old devices. My device has old kernel and I can't use such things as docker.
I tried to build it by myself (on my arm device), but got stuck on 'gthread' package from glibs.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my (Android 4.4 TV box with allwinner A31 - armv7hl) and get a feedback about it.

---

What is my final goal: run home-assistant on my old device. But it requires docker. Docker requires modern kernel (3.10>=). So the only way I found is to run modern kernel with qemu. Home-assistant has ready to use image for raspberry pi, which we can run with qemu.

I also tried chroot with fedora, but something goes wrong and qemu always shows a black screen, can attach to terminal inside chroot.

Thank you very much!

**Comment by ryzhovau** [comment]
QEMU isn't cross-compilation friendly, so we can't provide it for our architectures.
