### ISSUE TITLE
Nodejs

### ISSUE THREAD

**Issue by mentalisit** [Entware/Entware#467]
Please upgrade to version 8-10

http://pkg.entware.net/binaries/mipsel/node-npm_v6.11.2-3_mipselsf.ipk
http://pkg.entware.net/binaries/mipsel/node_v6.11.2-3_mipselsf.ipk

**Comment by zyxmon** [comment]
You are still using Entware-ng that is not supported and will not be upgraded.
Please switch to Entware if your hardware is supported.
