### ISSUE TITLE
SSHUTTLE 

### ISSUE THREAD

**Issue by Stryp** [Entware/Entware#469]
Package request
---
Hello,

I really would like to have SSHUTTLE package 
https://github.com/sshuttle/sshuttle

This is really useful when you want  to forward all traffic (or specific subnets) from my local network (served by the router) to a remote server transparently without configure proxy on the clients. (See https://superuser.com/questions/641273/how-to-use-sshuttle-on-a-router-running-openwrt)

- [ x] No similar package already added and/or this one got some new killer feature(s),
- [ x] Package is in active development (at least, not abandoned for 5 years or more),
- [ x] I'm ready to test added package on my platform** and get a feedback about it.

**platform
Router Model Netgear Nighthawk X10
Firmware Version DD-WRT v3.0-r43099 std (05/09/20)
Kernel Version Linux 4.9.222 #449 SMP armv7l

---

**Comment by zyxmon** [comment]
This is a python package - try to install it yourself - https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules

**Comment by Stryp** [comment]
Hi zyxmo,

Thank you for your answer, you're right indeed I managed to install it, but seems that I need also the following two packages which are not in the repo: 

 * opkg_install_cmd: Cannot install package iptables-mod-nat-extra.
 * opkg_install_cmd: Cannot install package iptables-mod-ipopt.

https://github.com/sshuttle/sshuttle/blob/master/docs/openwrt.rst

**Comment by Stryp** [comment]
I just tried to start SSHUTTLE and it works for what I need!
