### ISSUE TITLE
Package update: tty-solitaire

### ISSUE THREAD

**Issue by yoyoma2** [Entware/Entware#475]
Package update request for **tty-solitaire**

Entware version: 1.1.1
Latest version: **1.2.0**

Project version page: https://github.com/mpereira/tty-solitaire/releases

Fixes:

- Large memory leaks
- Card shuffling bug
- Screen refresh/card drawing fix

**Comment by ryzhovau** [comment]
Done. Binaries will arrive in a week.

**Comment by yoyoma2** [comment]
Wow so fast, impressive!
