### ISSUE TITLE
Setup quagga on TomatoUSB

### ISSUE THREAD

**Issue by chrisjosuearzu** [Entware/Entware#479]
Hi there!

I installed Entware on a tomato router and I'm trying to set up quagga
<img width="598" alt="tomatoversion" src="https://user-images.githubusercontent.com/66445964/83816829-8e33b700-a680-11ea-8fe6-d53e5a278d1a.png">

Notice that quagga and the other packages are also installed
<img width="613" alt="image" src="https://user-images.githubusercontent.com/66445964/83817116-36498000-a681-11ea-866c-fb6a60178897.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/66445964/83817165-4bbeaa00-a681-11ea-8dc3-7b92ae66059c.png">

I tried to follow [this youtube video](https://www.youtube.com/watch?v=Dz_sKcYAfA4&t=750s) to set up quagga, which shows how to do it in ubuntu, but I could not find the "Daemons" file to start  the ospfd for example

I found this s50quagga file, which apparently is to start the services but I got this error
<img width="818" alt="image" src="https://user-images.githubusercontent.com/66445964/83818161-e3bd9300-a683-11ea-8dc8-76770fcbf7f8.png">

I was not able to find any documentation anywhere on the internet, can someone please assist me or point me in the correct direction?

**Comment by ryzhovau** [comment]
We don't provide personal support, sorry.
