### ISSUE TITLE
Dnscrypt proxy v2 

### ISSUE THREAD

**Issue by Ninjanoir87** [Entware/Entware#481]
Package request
---
A flexible DNS proxy, with support for modern encrypted DNS protocols such as DNSCrypt v2, DNS-over-HTTPS and Anonymized DNSCrypt.
3 new releases since the last one on entware. 

-  this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
 

---

**Comment by ryzhovau** [comment]
Already there.

**Comment by Ninjanoir87** [comment]
thanks, now the 2.0.44 is up
