### ISSUE TITLE
Package Request : xupnpd

### ISSUE THREAD

**Issue by mesb1** [Entware/Entware#482]
Package request
---
xupnpd

https://github.com/clark15b/xupnpd

As usual, dlna, iptv and many other features related to media services.
In new version support for pictures was added.

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---

**Comment by ryzhovau** [comment]
Now it's up to [upstream](https://github.com/openwrt/packages/tree/master/multimedia/xupnpd). Please, ask OpenWrt maintainers to update it and new version will be here after next sync.
