### ISSUE TITLE
Mkvtoolnix v47 misses dependency pugixml

### ISSUE THREAD

**Issue by udochrist** [Entware/Entware#488]
With the latest upgrade to mkvtoolnix 47 on x64 k3.2 there is an unresolved dependency on pugixml. Mkvtoolnix is not upgradable and can no longer be started since the other deps (boost,...) have been upgraded to the latest version. 

Could you please publish this package?

**Comment by zyxmon** [comment]
Try to install it with force-depends
`opkg install mkvtoolnix --force-depends`
I'll fix wrong dependency later

**Comment by zyxmon** [comment]
fixed
