### ISSUE TITLE
test.entware.net is down

### ISSUE THREAD

**Issue by XanderXAJ** [Entware/Entware#489]
Possibly related to #486. http://test.entware.net

![image](https://user-images.githubusercontent.com/191109/85206391-c3473700-b319-11ea-93ea-52fd90da4ab8.png)

This causes installations for arch `armv7sf-k3.2` to fail since the `opkg.conf` on bin.entware.net seems to point to test. Raised #490.

**Comment by ryzhovau** [comment]
`bin.entware.net` is back online, no any links leads to `test.entware.net` for now.
