### ISSUE TITLE
Stable armv7sf-k3.2 opkg.conf points to test.entware.net

### ISSUE THREAD

**Issue by XanderXAJ** [Entware/Entware#490]
The stable `opkg.conf` for arch `armv7sf-k3.2` seems to refer to test.entware.net:
http://bin.entware.net/armv7sf-k3.2/installer/opkg.conf

```
src/gz entware http://test.entware.net/armv7sf-k3.2
```

I've confimed this doesn't seem to be the case for other architectures.

I noticed this because test.entware.net is down (#489).

**Comment by zyxmon** [comment]
fixed it. thanks for reporting.
