### ISSUE TITLE
package archive(s) missing? 

### ISSUE THREAD

**Issue by OneCDOnly** [Entware/Entware#491]
Hi guys. :nerd_face: 

It looks like the `archive` path is now missing. Is this a permanent change? 

Example: `http://bin.entware.net/x64-k3.2/archive` is not there anymore. 

Any chance of making the older packages available again? I have a Python project that only runs on Python 3.7.4 :disappointed: so I need to force-downgrade by using files from this (and other arch) archives.

Thank you.

**Comment by ryzhovau** [comment]
Only main feeds of `bin.entware.net` is back online. Archive, sources and other stuff will be added later.

**Comment by OneCDOnly** [comment]
Thanks @ryzhovau :smile: 

I hate to ask, but can you suggest when that will be? It's just so I can keep people up-to-date and let them know when this Python app can be reinstalled.

Cheers.

**Comment by ryzhovau** [comment]
ETA is June, 23, but can't promise that, sorry.

**Comment by OneCDOnly** [comment]
Oh, that's not so bad.

 Cheers mate! :smile:

**Comment by xRose1** [comment]
thanks too.

**Comment by ryzhovau** [comment]
Archive is back online.
