### ISSUE TITLE
Could you, please, include the transmission with the sequential support to entware?

### ISSUE THREAD

**Issue by lokapal** [Entware/Entware#493]
Hello, developers/maintainers!

Could you, please, include (or replace) the "Transmission" package to the version with the sequential support? This feature lowers CPU load many times and is very important at relatively weak CPUs (that is the main entware target CPUs). The transmission fork with this feature is available https://github.com/Mikayex/transmission.
I'm ready to test added/modified package on my armv7sf-k3.2 platform and get a feedback about it.

**Comment by konst2000** [comment]
This will be extremely useful. many people need it

**Comment by ryzhovau** [comment]
Please, use `transmission-cfp`, sequental download feature is present there.

I see no sense to add third variant of transmission, sorry.
