### ISSUE TITLE
xslt problem

### ISSUE THREAD

**Issue by listenfree** [Entware/Entware#494]
Package request
---xslt-dev

after through opkg install python3-lxml

admin@fisher:/opt$ python3
Python 3.8.3 (default, Jun 12 2020, 20:24:48)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /opt/lib/python3.8/site-packages/lxml/etree.cpython-38.so: undefined symbol: xsltGetProfileInformation
>>>

then I use pip3 install lxml
it said miss xslt development package
please help me,thanks a lot

**Comment by zyxmon** [comment]
fixed via https://github.com/Entware/entware-packages/commit/bddf51109799820980c37d69c3c53976e05d590e

Plz note - there are no dev packages in Entware.
