### ISSUE TITLE
Package request: BubbleUPnP Server

### ISSUE THREAD

**Issue by qguv** [Entware/Entware#497]
Package request: BubbleUPnP Server
---

BubbleUPnP server allows users to stream their UPnP library from outside their network. Normally a VPN would be sufficient, but in case you're trying to stream to _another_ UPnP player (which requires that you be on its LAN), something like this software is necessary. It supports fancy stuff too, such as transcoding to support popular players (Chromecast etc.) which may not otherwise support playback for arbitrarily encoded media.

This morning I wrote [a simple but consistently reproducible script](https://gist.github.com/qguv/6f76e4e8178e8398b66a6da3780acc65) to install BubbleUPnP on CoreELEC/LibreELEC/OpenELEC which should serve as a decent starting point for an entware package. Note the dependency on a JRE—this zulu build of OpenJDK seems to be sufficient.

The transcoding feature optionally requires ffmpeg for server-side transcoding—otherwise transcoding happens on the client device doing the streaming (mobile/computer). To avoid excessive clientside resource use, it would be really nice to have ffmpeg installed as well, but it's not a strict requirement.

Entware is sweet, thanks for all the hard work!

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my **CoreELEC Odroid N2** and get a feedback about it.

**Comment by zyxmon** [comment]
We do not support java applications in Entware.
