### ISSUE TITLE
Support for MIPS, not just MIPSEL

### ISSUE THREAD

**Issue by ian5142** [Entware/Entware#5]
Is there planned support for MIPS, not just MIPSEL. I am looking for MIPS support such as those found in Atheros based routers, TP-Link Archer C7 v2, etc.

**Comment by zyxmon** [comment]
It is here - http://bin.entware.net/mipssf-k3.4/
Installers - http://bin.entware.net/mipssf-k3.4/installer/

(It is mips softfloat kernel 3.4 or higher)

**Comment by zyxmon** [comment]
Entware-3x users will upgrade to Entware automatically running `opkg update; opkg upgrade` 2 times.
If there are problems with upgrade - please report!

**Comment by ian5142** [comment]
Why is it not located in the same location as the other installers for MIPSEL and ARM? 
See the wiki page here on github: https://github.com/Entware/Entware/wiki/Install-on-DD-WRT

**Comment by zyxmon** [comment]
Wiki pages are old. All new installers are on bin.entware.net.

**Comment by ian5142** [comment]
I am maintaining a wiki page on the dd-wrt wiki here: https://www.dd-wrt.com/wiki/index.php/Installing_Entware-3X

**Comment by zyxmon** [comment]
Thanks for DD-WRT wiki.
The project now is call Entware without any suffix. The complete list of installers is here
http://forums.zyxmon.org/viewtopic.php?p=17841#p17841

I hope we will update our wiki soon.
