### ISSUE TITLE
Postfix

### ISSUE THREAD

**Issue by ryzhovau** [Entware/entware#5]
https://code.google.com/p/wl500g-repo/issues/detail?id=243

---
I'd like to have postfix in entware...

www.postfix.org

**Comment by ryzhovau** [comment]
No response. Closing for now.

**Comment by ryzhovau** [comment]
Tested newer build. Sendmail from Postfix still complains about `/etc/postfix/main.cf` when started with no command line keys. I know about this issue.

**Comment by zyxmon** [comment]
One may try to patch file src/global/mail_params.h
and change 
#define DEF_CONFIG_DIR          "/etc/postfix"
to
#define DEF_CONFIG_DIR          "/opt/etc/postfix"

**Comment by ryzhovau** [comment]
To be continued here - https://github.com/Entware-ng/Entware-ng/issues/2
