### ISSUE TITLE
Update to Step 2 - Install on Synology NAS

### ISSUE THREAD

**Issue by shawnhank** [Entware/Entware#503]
Just an update to the documentation for Synology NAS (https://github.com/Entware/Entware/wiki/Install-on-Synology-NAS)

---
Running DSM 6.2.3-25426 on DS1817+

Step 2 reads: "Remove /opt and mount optware folder"

In this version of DSM, there is no /opt folder at all. 

`ash-4.3# pwd
/volume1
ash-4.3# ls -alh /opt
ls: cannot access /opt: No such file or directory`

Hopefully, this helps others
---

//SWH

**Comment by ryzhovau** [comment]
Wiki is writeable to any Github member, you may edit it directly.
