### ISSUE TITLE
Package request: JSON (perl)

### ISSUE THREAD

**Issue by RGaenssler** [Entware/Entware#504]
Hi,

I'm looking for the package JSON which is needed for fhem. Unfortunately, it's impossible for me to create it by myself because I've got tons of errors while creating it in CPAN.

Thanks. 

---
{Describe killer feature of package}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by zyxmon** [comment]
Please use wiki - https://github.com/Entware/Entware/wiki/Self-installation-of-perl-modules
I have just tested perl-json is installed via CPAN command `install JSON`:
```
.....
Installing /opt/lib/perl5/5.28/auto/JSON/XS/XS.so
Installing /opt/lib/perl5/5.28/JSON/XS.pm
Installing /opt/lib/perl5/5.28/JSON/XS/Boolean.pm
Installing /opt/bin/json_xs
Appending installation info to /opt/lib/perl5/5.28/perllocal.pod
  MLEHMANN/JSON-XS-4.02.tar.gz
  /opt/bin/make install  -- OK

cpan[2]> bye

```
