### ISSUE TITLE
Package SOAP::Lite

### ISSUE THREAD

**Issue by RGaenssler** [Entware/Entware#505]
Hi.

I'm looking for SOAP::Lite for my fhem installation.
---
{Describe killer feature of package}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
Look like `SOAP::Lite` requires [too many dependencies](https://cpandeps.grinnz.com/?dist=SOAP-Lite), so there's no easy way to compile it neither natively, nor cross-compilation way.

Closing for now.
