### ISSUE TITLE
[Package Request] bsdmainutils (apollolake)

### ISSUE THREAD

**Issue by sturla78** [Entware/Entware#51]
Request:
Package Name: bsdmainutils
Architecture: Apollolake (Intel Celeron J3355)

Hello,
i'm not sure if this is the correct location for post request for new package, i try to do and sorry if is not correct.
It would be very interesting having the bsdmainutils ready to use with apollolake, above all the command "column" that is in the bsdmainutils packages a very helpfull command for format bash output and that it allows creation of table.

Thanks in advance for the help.

**Comment by zyxmon** [comment]
We have column package. It is a part of util-linux
