### ISSUE TITLE
Package Request - mjpg-streamer with v4l2 MJPEG support (modify existing?)

### ISSUE THREAD

**Issue by russinnes** [Entware/Entware#510]
The existing MIPS and ARM package for mjpg-streamer (181-2) does not support MJPG format streams direct from v4l devices, it defaults to the less-than-desirable YUV streams. Looking through the configs, the default mips config stipulates #CONFIG_MJPG_STREAMER_V4L2 is not set, although "CONFIG_MJPG_STREAMER" is. Interestingly, the openwrt package on an openwrt system (same hardware) *does* support MJPG streams right from an external device. Supporting MJPG right from the device drops CPU usage to a fraction of processing a (raw) YUV stream. There was some discussion years ago about libv4l and libjpeg, but both are currently available via opkg. Perhaps someone has already tried this - I will try building it locally but perhaps someone has more insight or has already tried it.

**Comment by The-BB** [comment]
https://github.com/Entware/Entware/blob/master/configs/mips-3.4.config#L4849 
for others arch come at soon
