### ISSUE TITLE
Firefly (mt-daapd) wants 

### ISSUE THREAD

**Issue by bayonne** [Entware/Entware#512]
Hello,

The firefly package (version r1696-2) is installed on my Qnap NAS (x64-3.2).
/opt/sbin/mt-daapd wants an older version of libavcodec than the one provided by libffmpeg-full_4.2.2-4_x64-3.2.
It wants libavcodec.so.57, libavformat.so.57, libavutil.so.55;
libffmpeg-full provides libavcodec.so.58, libavformat.so.58.29.100, libavutil.so.56.31.100.

**Comment by ryzhovau** [comment]
We removed `firefly` from repo as obsolete. But you may find all necessary packages (including every `ffmpeg` version ever been compiled) in https://bin.entware.net/x64-k3.2/archive/ folder.
