### ISSUE TITLE
Package request: vsftpd-tls

### ISSUE THREAD

**Issue by lelik** [Entware/Entware#514]
Прошу собрать пакет vsftpd-tls для роутеров Keenetic

В текущем репозитории есть пакет vsftpd-ext, но он не поддерживает защищенное соединение TLS
http://pkg.entware-keenetic.ru/binaries/keenle/Packages.html 
Готов протестировать на своем роутере Keenetic Ultra (KN-1810) 
Платформа - MIPSel

**Comment by The-BB** [comment]
Для начала, рекомендую обновить систему (Entware-Keenetic => Entware).

**Comment by lelik** [comment]
Как бы и нечего обновлять, устанавливался отсюда.
https://forum.keenetic.net/topic/4223-entware-3x-и-entware-ng-объединились-новый-проект-называется-просто-entware/?do=findComment&comment=49963

http://bin.entware.net/mipselsf-k3.4/installer/mipsel-installer.tar.gz
Если только opkg update && opkg upgrade то это тоже делал.

Я понял вас смутила ссылка "http://pkg.entware-keenetic.ru/binaries/keenle/Packages.html"
Кончена, вот правильная http://bin.entware.net/mipselsf-k3.4/Packages.html

**Comment by The-BB** [comment]
Тогда вопрос к Entware team maintainer: какая killer feature y vsftpd-ext (ext - extended?) vs vsftpd (openwrt packages)?

**Comment by ryzhovau** [comment]
Насколько могу вспомнить, собирал `vsftpd-ext` из-за нормальной [поддержки](https://vsftpd.devnet.ru/rus/#extensions) кодировок.
