### ISSUE TITLE
Request for nsf4 to be added to nfs-kernel-server

### ISSUE THREAD

**Issue by markc** [Entware/Entware#515]
Would it be possible to include nfs4 in the entware nfs-kernel-server package?

**Comment by zyxmon** [comment]
It is enabled already - https://github.com/Entware/Entware/blob/master/configs/aarch64-3.10.config#L5054

**Comment by markc** [comment]
Apologies for persisting with this but maybe something else in the nfs-kernel-server package needs to be enabled?
```
~ mount /home/markc/illareen
mount.nfs4: Protocol not supported

# /etc/fstab reference
192.168.20.1:/mnt/USB4TB/illareen /home/markc/illareen nfs4 user,defaults 0 4

ax88u:/tmp/home/root# cat /etc/exports
/mnt/USB4TB/illareen *(no_root_squash,rw,async,insecure,no_root_squash,no_subtree_check)
```
