### ISSUE TITLE
Instructions are WRONG!!!

### ISSUE THREAD

**Issue by Pachacouti** [Entware/Entware#519]
Instruction:
mount /dev/sda2 /tmp/opt
cd /root
chmod 644 .wget-hsts <-FILE NOT FOUND!!!

where in the instructions does it say to download this? in fact, where do we get it or find it?

I had a perfectly good install until I noticed you 'merged' all three versions I was aware of, when it came to a re-install, voila, no can do, why cant you write full instructons? What was wrong with the origional install procedure? (oh, i get it, it worked, so you all got together to bork it so you could make us all come back!)

**Comment by zyxmon** [comment]
These are not instructions made by Entware team. If it is in our wiki - you can correct it yourself.
