### ISSUE TITLE
Package request numpy & pandas for Pyhton3

### ISSUE THREAD

**Issue by nkgiovannivl** [Entware/Entware#521]
Package request
---
{Include numpy & pandas because those python modules are critical for mathematical procedures}

- [X] No similar package already added and/or this one got some new killer feature(s),

**Comment by zyxmon** [comment]
Have you tried to install packages yourself - https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules ?

**Comment by zyxmon** [comment]
Entware toolchain does not have fortran compiler. So it cannot be built from source - https://numpy.org/doc/stable/user/building.html
