### ISSUE TITLE
Suricata with PFRing support

### ISSUE THREAD

**Issue by faux123** [Entware/Entware#525]
Currently suricata is built against libpcap 1.9 and with NO pfring support.

libpfring is part of the feeds list but not currently being used.  libpfring uses its own forked libpcap 1.8.1, so this will affect libpcap as well.  So far the only consumer of libpcap is suricata and the differences between 1.9 and 1.8.1 isn't monumental.

Please add libpfring support into suricata and please use the forked libpcap 1.8.1 from pfring.

Thanks

PS:  af_packet has major connection issues with Asus router, so having af_packet support is pointless and suricata IPS mode is broken with the current iteration.

---
{Describe killer feature of package}

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
No any changes will be applied to suricata, sorry. We'll keep current package state with no further development.

The newer versions (5.0+) requires Rust, so we going to stay on 4.1.8. 
Any other changes to 4.1.8 requires additional dependencies and/or modified libraries.
