### ISSUE TITLE
Package request: Dart SDK

### ISSUE THREAD

**Issue by mr7hr0w4w4y** [Entware/Entware#526]
Package request
---
"Dart is a client-optimized programming language for apps on multiple platforms. It is developed by Google and is used to build mobile, desktop, server, and web applications. Dart can compile to either native code or JavaScript. Dart can be used to develop applications for Android, iOS, Linux, Mac, Windows, and the web from a single codebase with the Flutter SDK."

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [*] Package is in active development (at least, not abandoned for 5 years or more),
- [*] I'm ready to test added package on my {platform} and get a feedback about it.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by ryzhovau** [comment]
Entware is repo for embedded devices, so we not sure Dart VM with JIT and other heavy things must be present there.

Won't add it, sorry.

**Comment by metaspook** [comment]
@mr7hr0w4w4y 
@Matthewjarredondo 
@themiron 
@MercuryV 
@ryzhovau 

at this stage Dart as programming language and it's UI framework Flutter become one of the best cross-platform development stack even for embedded device. Front to back all ends, this stack has bright future.

* So we don't need Flutter SDK on entware as it would be heavy and as it's a UI toolkit I see no point to add it here.
* What we need is the Dart sdk as its compiler binaries only to write small backend or programs or scripts in dart, if golang, python can be added I think it also can and I also saw dart sdk as [package](https://github.com/termux/termux-packages/tree/master/packages) in Termux (a terminal emulator app of Android), only dart sdk not supposed to be that much heavy.

Please and Please 🙏🏽 reconsider about this package, if it could be added. 
Thanks in advance.
