### ISSUE TITLE
Help requested with:  gerbera 1.6.0-2  ( "libavformat.so.57: No such file or directory" )

### ISSUE THREAD

**Issue by randykwood** [Entware/Entware#528]
Hi. I finally got around to configuring my installation of gerbera (v. 1.6.0-2, latest release) and, unfortunately, I am presented with the following error message:

_**gerbera: error while loading shared libraries: libavformat.so.57: cannot open shared object file: no such file or directory**_

I am running Entware on a Linksys WRT32X under DD-WRT as follows:

Router Name:  WRT32X
Router Model:  Linksys WRT32X
Firmware Version:  DD-WRT v3.0-r41380 std (10/24/19)
Kernel Version:  Linux 4.9.197 #1368 SMP Thu Oct 24 07:06:09 CEST 2019 armv7l

Can anyone help me with this?  I would really appreciate it.  IIRC, gerbera 1.4 and 1.5 didn't spit this error out - however I'm not certain about that.  Aaarrrggghhhh!

Thanks in advance.

Randy

**Comment by ryzhovau** [comment]
Can't reproduce on fresh install. 
https://github.com/Entware/Entware/wiki#note-about-packages-upgrade
