### ISSUE TITLE
entware-go/obfs4proxy: invalid version

### ISSUE THREAD

**Issue by mkszuba** [Entware/Entware#529]
The obfs4proxy version specified in Entware/entware-go@9e36cfb, and subsequently still present on the master branch as of now, is 0.0.12. This is incorrect - there is no 0.0.12 yet (see https://gitlab.com/yawning/obfs4/-/tags) and a quick look at the upstream commit referenced in the Makefile shows that this is in fact version 0.0.11 with the version string changed to 0.0.12-dev.

Given nothing of notice has changed in obfs4proxy since the release of 0.0.11, I would suggest simply "downgrading" to that version.

**Comment by ryzhovau** [comment]
Thanks for report.
