### ISSUE TITLE
[Package Request] golang support

### ISSUE THREAD

**Issue by mengxd** [Entware/Entware#53]
Package request
---
Golang has become a popular programming language for network programming. However, it has not been enabled in entware and the default binary packages from golang.org does not work out of box 
with every embedded devices. So it would be nice to have it included.

**Comment by zyxmon** [comment]
We support golang from 2016.

**Comment by mengxd** [comment]
I did not see any golang packages from here:
http://pkg.entware.net/binaries/armv7/Packages.html

Regards,

Alex Meng <mengxiandong@gmail.com>
mengxiandong@gmail.com
