### ISSUE TITLE
Build chrony with support for dropping root privileges

### ISSUE THREAD

**Issue by jackyaz** [Entware/Entware#536]
**Describe the bug**
Chrony is unable to drop root privileges, I believe it needs to be built with lib-pcap support for this

**Environment**
 - Entware feed: aarch64/armv8
 - Device Asus RT-AC86U router
 - Firmware version Asuswrt-merlin 384.19

**Comment by ryzhovau** [comment]
Also, start script has been added. 
Thanks for report.

**Comment by jackyaz** [comment]
what name will the start script use please?

**Comment by jackyaz** [comment]
Thanks!
