### ISSUE TITLE
Chromium for headless browsing for armv7l ASUSWRT-Merlin kernel 2.6.36?

### ISSUE THREAD

**Issue by foodtourama** [Entware/Entware#538]
Hi!
I'm on latest Entware for an ASUS router FW 384.6:
Linux RT-AC56U-A5C0 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jul 25 12:43:03 EDT 2018 armv7l ASUSWRT-Merlin

My ASUS router has 256 MB RAM, 2 core 800 MHz armv7l (32 bit)
Would it be possible to run Chromiun (arm 32 bit) for headless browsing?

Package request:
Is it possible to install Chromium (for ARM 32 bit) or is there a hardware/software limitation for armv7l ?

{
Killer feature of package?
Chromium is becoming the standard for headless browsing.
I know there are Debian distributions that have ARM versions of Chromium (but I guess they are ARM 64 bit and mine is 32 bit)
}

    There is Chromium for ARM processors in Debian distributions (but don't know if there is a 32bit version),
    Chromium is becoming the standard for headless browsing and is in active development,
    I'm ready to test added package on my {ASUS Entware armv7l} and get feedback about it.

Cheers!

**Comment by ryzhovau** [comment]
No way: too heavy fo embedded devices, too many dependencies, weakly portable to MIPS.
