### ISSUE TITLE
syntax error: unexpected ")" OR not found <any_package>

### ISSUE THREAD

**Issue by diman82** [Entware/Entware#540]
**Describe the bug**
nano OR tmux: I get:
`syntax error: unexpected ")"` when running _tmux_ and
`/opt/bin/nano: /opt/bin/nano: line 1: line 1: ▒0a,▒m4Yn1: not founELF▒▒R@@8▒@8: not found` when running _nano_

Basically, I can't run any opkg package at all

**Environment (please complete the following information):**
 - Entware feed: don't know
 - Device: RT-AX56U
 - Firmware version: asuswrt-merlin, 384.18

**Comment by zyxmon** [comment]
Cannot confirm. Please try to reinstall nano.

**Comment by diman82** [comment]
> Cannot confirm. Please try to reinstall nano.

Like I said - nano was only an example.. The same exceptions are with EVERY package I try to run..

**Comment by diman82** [comment]
Ok, reinstalled entware completely - now all works fine..
