### ISSUE TITLE
pyload-ng

### ISSUE THREAD

**Issue by diman82** [Entware/Entware#541]
**Describe the solution you'd like**
Please add [pyload-ng](https://pypi.org/project/pyload-ng/)

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by zyxmon** [comment]
It "is currently in alpha phase". You can try to install it yourself - https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules
