### ISSUE TITLE
Package Request: scream

### ISSUE THREAD

**Issue by khseal** [Entware/Entware#542]
Scream audio receiver using Pulseaudio, ALSA or stdout as audio output.
Need support at least alsa.
https://github.com/duncanthrax/scream/tree/master/Receivers/unix

**Comment by ryzhovau** [comment]
Please, describe your `scream` use case. 
Which platform/feed you are on?

**Comment by khseal** [comment]
I have router MI-R3G(mipselsf-k3.4?). DAC is connected by usb. I am transmitting sound over a laptop at 5GHz Wi-Fi.
I have built an old version of Scream and it works, but there are problems.
The new version of the many dependencies and it is more difficult.

**Comment by ryzhovau** [comment]
Please, provide a feedback.

**Comment by khseal** [comment]
Everything works thanks for the help.
