### ISSUE TITLE
Chrony (for MIPS)

### ISSUE THREAD

**Issue by sumerland** [Entware/Entware#543]
Chrony has recently been made available for aarch64 (e.g. Asus RT-AC86U) - many thanks for that!

However, I cannot install the same package via opkg on mips (Asus RT-N66U)

Is that a lack of competence on my end or is the package actually missing?

**Comment by ryzhovau** [comment]
Chrony available for every modern Entware feeds.

My guess, you've got Entware-ng, which is abandoned for now.

**Comment by sumerland** [comment]
Your are right - opkg.conf points towards
`src/gz entware-ng http://pkg.entware.net/binaries/mipsel`

whereas on my aarch64 router it looks at
`src/gz entware http://bin.entware.net/aarch64-k3.10`

The configuration file is automatically created by the amtm script, which comes along with John's fork of Merlin's Asus firmware. I will contact the developers.

Edit: Just to make sure... does "modern feeds" apply to this architecture?
`Linux RT-N66U 2.6.22.19 #1 Sun Jul 12 19:01:06 MST 2020 mips ASUSWRT-Merlin-LTS`

Edit again: got the answer already - ("no" to my last question). Issue can be closed. Thanks for your patience!
