### ISSUE TITLE
not working instruction

### ISSUE THREAD

**Issue by rah66** [Entware/Entware#548]
in instruction:

That last command will show you the partitions of your USB-drive storage. Look for the 'opt' label(for the NTFS partition you created) and take note of the '/dev/sdX#' (where X is the partition letter and # the number) of the 'opt' partition:

```
mount /dev/sdX# /tmp/opt
cd /root
chmod 644 .wget-hsts
``` 
this metod not working, solution:

`mount /dev/sdX# /opt`

**Comment by zyxmon** [comment]
You can edit instruction in Wiki yourself. A lot of fixes there are made by Entware users.
