### ISSUE TITLE
openssl s_server failing

### ISSUE THREAD

**Issue by jtbr** [Entware/Entware#55]
Current versions of openssl executable fail when running openssl_s_server. This previously used to work on my dd-wrt router. I have run opkg upgrade to update all installed packages.

Here is the error:
```
root@DD-WRT:~# openssl s_server --cert tls.validation.cert --key tls.validation.key --accept 443
Using default temp DH parameters
ACCEPT
1996096664:error:02004061:system library:socket:Address family not supported by:crypto/bio/b_sock2.c:49:
1996096664:error:2008C076:BIO routines:BIO_socket:unable to create socket:crypto/bio/b_sock2.c:50:
   0 items in the session cache
   0 client connects (SSL_connect())
   0 client renegotiates (SSL_connect())
   0 client connects that finished
   0 server accepts (SSL_accept())
   0 server renegotiates (SSL_accept())
   0 server accepts that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
   0 callback cache hits
   0 cache full overflows (128 allowed) 
```

Instead of opening a socket and waiting for connections, it exits immediately with the error:

```
1996096664:error:02004061:system library:socket:Address family not supported by:crypto/bio/b_sock2.c:49:
1996096664:error:2008C076:BIO routines:BIO_socket:unable to create socket:crypto/bio/b_sock2.c:50:
```

Could some needed library be missing?

This is blocking the validation of domain ownership which is needed to obtain or renew web server SSL certificates using automated tools (in particular acme.sh).

**Comment by zyxmon** [comment]
Please tell us - what was your previous Entware installation. What is your hardware and kernel.

**Comment by zyxmon** [comment]
It looks like you are not using Entware. Probably you use Entware-ng or Entware-3x that are closed now. Ther is no file `crypto/bio/b_sock2.c` in openssl sources used in Entware.

**Comment by jtbr** [comment]
I had been using entware-ng, but I had assumed that doing opkg upgrade had converted me to using entware, since it had changed the servers it was pointing to. I guess not.

In any case, I have re-installed with entware and I have the same exact problem except the address is slightly different:

```
1996346520:error:02004061:system library:socket:Address family not supported by:crypto/bio/b_sock2.c:49:
1996346520:error:2008C076:BIO routines:BIO_socket:unable to create socket:crypto/bio/b_sock2.c:50:
```

I am running on a Netgear AC1450, which has an armv7 processor. Here is the output from `uname -a`:
`Linux DD-WRT 4.4.95 #472 SMP Fri Nov 3 23:27:37 CET 2017 armv7l DD-WRT`

As for the missing file, perhaps that is the problem? Or some compilation flag is disabling this feature now? My best guess is that this stopped working when I updated around the new year; it took a few months for me to notice.

**Comment by zyxmon** [comment]
Please run `cat /opt/etc/opkg.conf` to show your Entware version.
I hope you have manually deleted  /opt contents before reinstalling Entware!

**Comment by jtbr** [comment]
Yes, I moved the old `/opt` directory and started over. Here is my /opt/etc/opkg.conf:

```
src/gz entware http://bin.entware.net/armv7sf-k3.2
dest root /
dest ram /opt/tmp
lists_dir ext /opt/var/opkg-lists
option tmp_dir /opt/tmp
arch all 100
arch armv7-3.x 150
arch armv7-3.2 160
```

**Comment by zyxmon** [comment]
I have no idea - what is wrong. Try to run `strace openssl s_server .... ` and publish the output on https://pastebin.com/

**Comment by jtbr** [comment]
@zyxmon Looking at the strace results put me on track to figure this out. It turns out that somehow my router was now pointing at an openssl install that was distributed with my latest version of DD-WRT, rather than the one from entware. I'm not sure if it's new that they distribute this, or if the path changed, or if somehow it worked before because the libs were the same between the dd-wrt and entware versions but no longer are. But in any case, I've got it sorted. Make sure entware comes first in the path. 

Sorry to incorrectly think this was an entware issue, but many thanks for the help. It probably would have taken me much longer to figure this simple error out on my own.
