### ISSUE TITLE
Request "nohf" packages be marked in their description

### ISSUE THREAD

**Issue by VA1DER** [Entware/Entware#550]
**Describe the bug**
Packages annie, dnscrypt_proxy2, go, gotty, nebula, nextdns, rclone, shell2http, syncthing, yggdrasil-go and possibly others all exist with matching "_nohf" packages.  These _nohf versions are for platforms that don't have a hardware float, and yet are marked nowhere in their descriptions as to their purpose.  People who don't otherwise know the difference may install the wrong package.  The "nohf" suffix doesn't intuitively suggest its meaning, and it's not something that is readily apparent even through internet searches.

Recommend the packages be renamed to change the "_nohf" suffix to "_nohardwarefloat", and/or that the package descriptions be altered to specify their difference from the standard packages.

**Comment by ryzhovau** [comment]
`hf` suffix is widely used in embedded world and we see no reason to change it, sorry.
