### ISSUE TITLE
Please update chrony from 3.5 to 4.0

### ISSUE THREAD

**Issue by JGrana01** [Entware/Entware#552]
Chrony has been update to 4.0. It adds a number of improvements and a new Network Time Security option.
I have compiled 4.0 but cannot get it to add NTS - it requires gnutls. The configuration uses pkg-config to check for gnutls - I have installed both gnutls modules using opkg on an ASUS AX88U and also installed pkg-config. It still does not add/compile gnutls into chronyd. There are no ".pc" files in it's search path. As a result, it doesn't believe gnutls is installed.

This security feature would be useful on embedded devices. 

- [X ] No similar package already added and/or this one got some new killer feature(s),
- [X ] Package is in active development (at least, not abandoned for 5 years or more),
- [X ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by butaford** [comment]
I'm not a developer, but I put together a package for your. Try it.

[chrony_ipk_entware.zip](https://github.com/Entware/Entware/files/5437895/chrony_ipk_entware.zip)
[chrony_src_entware.tar.gz](https://github.com/Entware/Entware/files/5437896/chrony_src_entware.tar.gz)
![2020-10-26_121538](https://user-images.githubusercontent.com/5542160/97155022-c352ba00-1785-11eb-89be-0ff72048af30.jpg)

**Comment by JGrana01** [comment]
Nice, thanks. I even see nettle!
Unfortunately, I am on an Asus RT-AX88U which uses aarch64-k3.10
Any chance you have that build environment?
Happy to test if you do!

**Comment by butaford** [comment]
aarch64:
[chrony_ipk_entware.zip](https://github.com/Entware/Entware/files/5439331/chrony_ipk_entware.zip)

**Comment by JGrana01** [comment]
Thanks, installed fine. The one issue is that NTS is still disabled. The chrony configure script doesn't think we have gnutls so it disables NTS:

chronyd -v

chronyd (chrony) version 4.0 (+CMDMON +NTP +REFCLOCK -RTC +PRIVDROP -SCFILTER -SIGND +ASYNCDNS **-NTS** -SECHASH +IPV6 -DEBUG)

I looked at the configure script. It uses pkg-config to determine if gnutls is present. Since we have no gnutls.pc file, it fails (silently) and does not add support for gnutls (which NTS requires).

Thanks again.

**Comment by ryzhovau** [comment]
This package was taken from upstream with no any changes https://github.com/openwrt/packages/tree/master/net/chrony

So chrony 4.0 will ariive here during next sync, which is planned in next couple of weeks.

**Comment by JGrana01** [comment]
Thanks ryzh0vau. BTW butaford, I installed the chrony-gnutls_4.0-1_aarch64-3.10.ipk after uninstalling chrony. It does now appear that NTS is working:
chronyd (chrony) version 4.0 (+CMDMON +NTP +REFCLOCK -RTC +PRIVDROP -SCFILTER -SIGND +ASYNCDNS +NTS -SECHASH +IPV6 -DEBUG)

I will do some testing with NTS

**Comment by butaford** [comment]
i forgot to add ca-bundle package as dependency

**Comment by jackyaz** [comment]
It looks like the version for aarch64 (RT-AC86U) at least (no way of checking other models from here) is missing NTS support:
![image](https://user-images.githubusercontent.com/6189420/101241951-69cd9b80-36f2-11eb-81f9-d95b897e0a7f.png)
I tried manually installing libgnutls from Entware (gnutls isn't available) but ldd shows the chronyd isn't looking for the lib
![image](https://user-images.githubusercontent.com/6189420/101242876-41df3780-36f4-11eb-915c-2433971d888b.png)
