### ISSUE TITLE
far2l support

### ISSUE THREAD

**Issue by arabesc** [Entware/Entware#555]
https://github.com/elfmz/far2l

Famous console file manager comes to Linux!

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Not sure we want to add alpha version, currently interesting only for enthusiasts.
