### ISSUE TITLE
lz4 binary

### ISSUE THREAD

**Issue by benneti** [Entware/Entware#556]
It would be nice to have a package for the binary of lz4 ([https://github.com/lz4/lz4/](https://github.com/lz4/lz4/)).

There is already a package available for the library [entware-packages/blob/master/libs/liblz4/Makefile](https://github.com/Entware/entware-packages/blob/master/libs/liblz4/Makefile) and it looks like it defines instructions for lz4 as well as liblz4 but on https://bin.entware.net/armv7sf-k3.2/ I can only find the liblz4.
This is also true on the device with
``` 
$ opkg -v
opkg version f2166a89b7e96e2c60002959731eebc5f45fa318 (2020-05-07)
$ uname -a
Linux reMarkable 4.14.78 #1 SMP PREEMPT Tue Sep 22 21:30:00 UTC 2020 armv7l GNU/Linux
```
.
It would be nice if you could include the package in line [armv7-3.2.config#L7002](https://github.com/Entware/Entware/blob/4fa08a36855ef9185eae017ba8977a28dba9e615/configs/armv7-3.2.config#L7002).

- [x] No similar package already added and/or this one got some new killer feature(s),
  (There are other compression algorithms but lz4 is suited for very fast compression)
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by butaford** [comment]
[lz4_1.9.2-4_mips-3.4.ipk.zip](https://github.com/Entware/Entware/files/5500916/lz4_1.9.2-4_mips-3.4.ipk.zip)
[lz4_1.9.2-4_mipsel-3.4.ipk.zip](https://github.com/Entware/Entware/files/5500917/lz4_1.9.2-4_mipsel-3.4.ipk.zip)
[lz4_1.9.2-4_x64-3.2.ipk.zip](https://github.com/Entware/Entware/files/5500918/lz4_1.9.2-4_x64-3.2.ipk.zip)
[lz4_1.9.2-4_x86-2.6.ipk.zip](https://github.com/Entware/Entware/files/5500919/lz4_1.9.2-4_x86-2.6.ipk.zip)
[lz4_1.9.2-4_aarch64-3.10.ipk.zip](https://github.com/Entware/Entware/files/5500920/lz4_1.9.2-4_aarch64-3.10.ipk.zip)

**Comment by benneti** [comment]
thank you for the links.
1) They work (at least for armv7) no problems so far!
2) How can I find these links myself to stay up to date (as long as they are not included in the accessible repo)?

**Comment by ryzhovau** [comment]
Binaries will be accessible after 1-2 weeks, after next sync with OpenWrt.

**Comment by benneti** [comment]
Awesome, thank you!

**Comment by token0** [comment]
Thanks, @butaford  !
