### ISSUE TITLE
Samba Update: Include VFS Recycle

### ISSUE THREAD

**Issue by auburnham** [Entware/Entware#56]
Package request: Update Samba to include VFS Recycle module/library
---
{Describe killer feature of package: https://www.samba.org/samba/docs/current/man-html/vfs_recycle.8.html}

- [ X ] No similar package already added and/or this one got some new killer feature(s),
- [ X ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I successfully tested added package on my {platform}.

---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by zyxmon** [comment]
We compile Samba3x with options from Openwrt. We will add more options after options are added upstream.

**Comment by auburnham** [comment]
Thanks, I will follow up there.  Do you handle Samba4x independently, or does that also flow down from Openwrt?

**Comment by zyxmon** [comment]
There is no Samba4 in openwrt.

**Comment by auburnham** [comment]
Is this one maintained here? https://github.com/Entware/rtndev/tree/master/samba4x
If so, is it possible to include the VFS Recycle library in the Samba4x build?

**Comment by zyxmon** [comment]
Yuo are welcome to make PR to add VFS Recycle to it.
