### ISSUE TITLE
'wkhtmltopdf' package support

### ISSUE THREAD

**Issue by asgraf** [Entware/Entware#562]
WkHtmlToPdf and WkHtmlToImage are open source (LGPLv3) command line tools to render HTML into PDF and various image formats using the Qt WebKit rendering engine. These run entirely "headless" and do not require a display or display service.
https://github.com/wkhtmltopdf/wkhtmltopdf

Some PHP libraries depend on wkhtmltopdf installation:
[example](https://github.com/FriendsOfCake/CakePdf)

**Comment by ryzhovau** [comment]
It uses forked Qt 4.8 with specific patches, won't add another one QT, sorry.
