### ISSUE TITLE
NTS missing in Chrony 4.0

### ISSUE THREAD

**Issue by JGrana01** [Entware/Entware#565]
**Describe the bug**
[chrony]: It appears chrony was built without NTS support. The chrony build configure script checks for GnuTLS. If not present, NTS support is not compiled. It doesn't appear that GnuTLS was in the compile/depends path?

**Environment (please complete the following information):**
 - Entware feed: [arm64]
 - Device [RT-AX88U]
 - Firmware version [asuswrt-merlin]

**Comment by jackyaz** [comment]
I'm seeing this too. See https://github.com/Entware/Entware/issues/552#issuecomment-739242532

**Comment by butaford** [comment]
add to config `CONFIG_PACKAGE_chrony-nts=m`  in https://github.com/Entware/Entware/blob/2df8313741e25bf260a4a3bb1d893371b11c8d51/configs/aarch64-3.10.config#L5985 and compile
![image](https://user-images.githubusercontent.com/5542160/101899314-ac91e680-3bbe-11eb-9bd4-fd012a479f88.png)

UPD:
[chrony-nts_4.0-3_aarch64-3.10.zip](https://github.com/Entware/Entware/files/5678964/chrony-nts_4.0-3_aarch64-3.10.zip)

**Comment by JGrana01** [comment]
Thanks!

**Comment by jackyaz** [comment]
Any updates on this making it into the repo, please?

**Comment by ryzhovau** [comment]
Depends on free time we have. We'll sync with upstream on the next week.

**Comment by jackyaz** [comment]
@ryzhovau Thanks!

**Comment by JGrana01** [comment]
Hi @ryzhovau , not to be a pain, but is there any progress on the NTS version of Chrony?

**Comment by jackyaz** [comment]
I can see package updates tonight, but nothing for chrony? :(
