### ISSUE TITLE
Python package is broken

### ISSUE THREAD

**Issue by iacchi** [Entware/Entware#568]
Hello, the python package is broken (or, better said, is misconfigured). Short version:

I can load a c-extension module `module.cpython-39.so` but not `module.cpython-39-x86_64-linux-gnu.so`. This is problematic since wheels I download from PyPI use the second form. The problem stems from `_imp.extension_suffixes()`, which comes from `sysconfig.get_config_var('SOABI')` which comes from the [`configure` script](https://github.com/python/cpython/blob/master/configure.ac#L4776) used to build python.

Long version, please see this bug that I opened in the numpy package issue tracker here on github, where the problem is analysed and identified: https://github.com/numpy/numpy/issues/17975

I will add that the python package in the old entware-ng project (that I still have installed on a different synology nas) didn't have this problem.

The version of Entware that I have installed on my system (as synology nas) is the x64 one.

**Comment by zyxmon** [comment]
The configure script - https://github.com/Entware/entware-packages/blob/master/lang/python/python3/Makefile#L99
This patch - https://github.com/Entware/entware-packages/blob/master/lang/python/python3/patches/014-remove-platform-so-suffix.patch
come from Openwrt - https://github.com/openwrt/packages/tree/master/lang/python/python3
Please contact Openwrt developers with this issue.
Openwrt (and Entware) does not guarantee compatibility with wheels from PyPI. One can try to compile modules using  wiki - https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules but some extra patches may be needed in this case. Numpy may need fortran compiler to be built that is absent in Entware.
