### ISSUE TITLE
eggdrop-1.8.3

### ISSUE THREAD

**Issue by badalamenti** [Entware/Entware#57]
Package request
eggdrop-1.8.3

{Describe killer feature of package}
Since eggdrop-1.8.2 have too many known bugs related to UTF-8-Invalid multibyte string, TLS, SSL and the botnet: dcc, ipv6 addresses and the eggs won't also transfer and share userfiles.

Regards, badalamenti

**Comment by ryzhovau** [comment]
Done. Binaires will arrive soon.
