### ISSUE TITLE
Lua - Update to latest version ?

### ISSUE THREAD

**Issue by nodecentral** [Entware/Entware#570]
Hi

I’ve just installed Lua and noticed the version is 5.1.5, would it be possible to add another package ? The latest release is 5.4.2 https://www.lua.org/versions.html

**Comment by zyxmon** [comment]
Lua 5.3 is here - https://github.com/Entware/Entware/tree/master/package/utils/lua5.3
We will consider adding package in next update.

**Comment by nodecentral** [comment]
Thanks !
