### ISSUE TITLE
proftpd: build with more features enabled

### ISSUE THREAD

**Issue by niks255** [Entware/Entware#571]
Package name: proftpd

 - Entware feed: mipssf-k3.4
 - Device Keenetic Duo (KN-2110)
 - Firmware version 3.5.6

Please enable all the features. Right now, it's compiled with the following ones:
  Features:
    - Autoshadow support
    - Controls support
    - curses support
    - Developer support
    - DSO support
    + IPv6 support
    + Largefile support
    + Lastlog support
    - Memcache support
    + ncurses support
    - NLS support
    - OpenSSL support
    - PCRE support
    - POSIX ACL support
    - Redis support
    + Sendfile support
    + Shadow file support
    - Sodium support
    + Trace support
    + xattr support

**Comment by freekweijers** [comment]
It would be great if mod_tls would be included. Using FTPS or encryption in general is standard nowadays.
