### ISSUE TITLE
Phoscon Deconz package (Zigbee software and USB-stick)

### ISSUE THREAD

**Issue by tomillr** [Entware/Entware#576]
**Describe the solution you'd like**
Any chance of getting the Phoscon Deconz package added to the repository as well?

https://phoscon.de/en/conbee2/install#ubuntu

They are makers of the Zigbee-USB Stick "Conbee", which is an easy and cheap way to add some smart home capabilities to your NAS or maker board

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Look like it's closed source project. Can't add it, sorry.
