### ISSUE TITLE
Could you please add these packages

### ISSUE THREAD

**Issue by rome1983** [Entware/Entware#578]
https://github.com/bypassrg/att/blob/master/README.md#nvg510

When using the above bypass method you would need to cross compile the packages for the asus router. The att bypass community is growing and it be nice to have these packages supported natively. 

https://www.dslreports.com/forum/r32426308-AT-T-Fiber-Using-Asuswrt-Merlin-to-bypass-RG

Thanks 

libubus
hostapd-common
wpa-supplicant
wpa-cli 
libubox  - already supported
fake-hwclock - already supported

- [y] No similar package already added and/or this one got some new killer feature(s),
- [y] Package is in active development (at least, not abandoned for 5 years or more),
- [y] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Looks like too rare case to be implemented, sorry.
