### ISSUE TITLE
Installation on DSM Synology bug

### ISSUE THREAD

**Issue by thibpoullain** [Entware/Entware#581]
Hi there :)

I reproduce the setup doc for synology : https://github.com/Entware/Entware/wiki/Install-on-Synology-NAS

My uname : 

Linux synology 3.10.105 armv7l GNU/Linux synology_armada38x_ds216j

This command failed :

```
mount -o bind "/volume1/@Entware/opt" /opt
=> mount: special device /volume1/@Entaware/opt does not exist
```

I created `/opt` in the root directory : `/` and `/volume1/@Entaware/opt` exist too.

For now I created a symlink :

```
ln -s /volume1/@Entaware/opt/ /opt
```

I don't know if it will work as expected. What do I have to do ?

**Comment by zyxmon** [comment]
Synology wiki entry was created by synology users. Try some synology forum/group for help.
