### ISSUE TITLE
Please update youtube-dl to latest version (v2021.01.03)

### ISSUE THREAD

**Issue by ncrra** [Entware/Entware#583]
After youtube-dl got DMCA taken down , it seems youtube-dl doesn't work. 
Please update youtube-dl to latest version 

https://youtube-dl.org/
https://github.com/ytdl-org/youtube-dl/

**Comment by derfrankie** [comment]
Since the youtube-dl fiasco has been resolved it would be great if we could get the latest version 😃

**Comment by ryzhovau** [comment]
Done.
