### ISSUE TITLE
Would you add the NIS family of apps?

### ISSUE THREAD

**Issue by sfloess** [Entware/Entware#585]
I'm hoping to request the NIS family of apps (ypbind, ypserv, etc) to entware?

I will definitely be more than happy to test here on my local network.

**Comment by ryzhovau** [comment]
This apps looks like obsolete for now. 
I'm afraid you'll be the one user of this packages:)

**Comment by sfloess** [comment]
@ryzhovau - I don't think NIS is obsolete.  But OK.
