### ISSUE TITLE
Wireshark installs, but unable to launch

### ISSUE THREAD

**Issue by JimmieJoeJr** [Entware/Entware#591]
**Wireshark installs, but says command unknown**
[Wireshark]: After installing wireshark, enter wireshark as command but erros saying wireshark is not a command

**DD-WRT Environment 
 - Entware feed: armv7-k3.2
 - Linksys EA6300v1 
 - Firmware version DD-WRT v3.0-r44715

**Comment by zyxmon** [comment]
```
 opkg files wireshark | grep /opt/bin
/opt/bin/mergecap
/opt/bin/reordercap
/opt/bin/dumpcap
/opt/bin/idl2wrs
/opt/bin/sharkd
/opt/bin/rawshark
/opt/bin/capinfos
/opt/bin/captype
/opt/bin/text2pcap
/opt/bin/editcap
/opt/bin/tshark
/opt/bin/randpkt

```

**Comment by JimmieJoeJr** [comment]
I got the same file list that you showed but wireshark still does not launch.

After enter wireshark as a command:
-sh:  wireshark: not found

**Comment by zyxmon** [comment]
There is no wireshark binary, only a set of command line utilities.

**Comment by JimmieJoeJr** [comment]
Thank you. It would be nice if there were this type of information about each of the packages somewhere. The description in the package list is very limited.
