### ISSUE TITLE
libxml unsupported encoding

### ISSUE THREAD

**Issue by joddude** [Entware/Entware#599]
I tried installing TT-RSS on my NAS and noticed an error while updating some news feeds. 
`libxml error 32 at line 1 (column 44): unsupported encoding windows-1251`

Then I tried to reproduce this error in a simple php file.
```
<?php
$doc = new DOMDocument();
$url = "https://4pda.ru/feed/";
$content = file_get_contents($url);
$doc->loadXML($content);
```
`Warning: DOMDocument::loadXML(): Unsupported encoding windows-1251`

Can such an error occur because libxml compiled without iconv support?
Is there any way to fix this? 

DNS-325, Alt-F firmware, armv5sf-k3.2

**Comment by zyxmon** [comment]
libxml2 is compiled without iconv. This comes from openwrt - https://github.com/openwrt/packages/blob/master/libs/libxml2/Makefile#L83
Please contact openwrt developers to make changes, we will follow these changes.
