### ISSUE TITLE
Package request: expect

### ISSUE THREAD

**Issue by JACK-THINK** [Entware/Entware#60]
Package request
---
{Expect is a program that "talks" to other interactive programs according to a script. Following the script, Expect knows what can be expected from a program and what the correct response should be. An interpreted language provides branching and high-level control structures to direct the dialogue. In addition, the user can take control and interact directly when desired, afterward returning control to the script.

Expectk is a mixture of Expect and Tk. It behaves just like Expect and Tk’s wish. Expect can also be used directly in C or C++ (that is, without Tcl). See libexpect(3).

The name "Expect" comes from the idea of send/expect sequences popularized by uucp, kermit and other modem control programs. However unlike uucp, Expect is generalized so that it can be run as a user-level command with any program and task in mind. Expect can actually talk to several programs at the same time.}

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I successfully tested added package on my {platform}.

**Comment by ryzhovau** [comment]
Did you tried `empty` package?

**Comment by JACK-THINK** [comment]
I didn't know this software before. Maybe I should give it a try. Thanks a lot for your reply. Could you give me some tutorials about this tool?

**Comment by ryzhovau** [comment]
I'm not ready to provide personal support, sorry.
