### ISSUE TITLE
Update https-dns-proxy and libcurl

### ISSUE THREAD

**Issue by sgobiraj** [Entware/Entware#602]
There is a bug in the current version which is very old (both https-dns-proxy and libcurl)

https-dns-proxy -a 192.168.10.1 -p 32 -b "1.1.1.1,1.0.0.1" -r "https://cloudflare-dns.com/dns-query"
[E] 1612837701.297803 https_client.c:259 libcurl bug detected: socket closed without ever being read.
[E] 1612837701.297885 https_client.c:260 Activating workaround.  PERFORMANCE WILL BE GREATLY DEGRADED!
Segmentation fault

**Comment by ryzhovau** [comment]
Both packages came from OpenWrt with no any changes. New version will arrive here during next sync in last decade of February.
