### ISSUE TITLE
Request update of Syncthing due to upstream bug fixes

### ISSUE THREAD

**Issue by VA1DER** [Entware/Entware#607]
**Describe the bug**
[Syncthing]: The current version, 1.11.1, of Syncthing has several panic errors that recent upstream releases have corrected. It would be nice to be able to take advantage of these fixes in Entware.  Request an updated release when time permits.

**Comment by zyxmon** [comment]
The current syncthing version is  1.13.1.

**Comment by VA1DER** [comment]
Thank-you!
