### ISSUE TITLE
Request:    gnokii

### ISSUE THREAD

**Issue by pyrwo** [Entware/entware#61]
Dear ryzhov_al,

Admirations for the excellent piece of work - entware.

If you could, please add gnokii to the repository packages? 

FYI as it might be relevant:
In the past I use to install gnokii using optware on ddwrt (following this guide: http://www.dd-wrt.com/wiki/index.php/Optware-ByHand)
After installation it would not work until I 
 remove  bluez2-libs_2.25-1_mipsel.ipk
and then
 install bluez-libs_3.36-1_mipsel.ipk

Please ignore the same request made on Googlecode.

Regards
Pyrwo

**Comment by YasharF** [comment]
OpenWRT SVN: https://dev.openwrt.org/browser/packages/utils/gnokii/Makefile

**Comment by ryzhovau** [comment]
Old Nokia's FBUS protocol (by AT commands), Windows Mobile phones, Symbian 3rd Edition phones and probably Blackberry. Not sure this phones are still living. No, sorry.

**Comment by pyrwo** [comment]
Thank you for considering it. 
I use gnokii not with a mobile phone but with USB 3G modems (widely available Huawei mobile internet dongle/modem/stick) plugged in the USB port of a router. It is a great tool for sending/receiveing SMS text messages.   
Anyway, I have managed to find a workaround using asterisk and chan_dongle.
