### ISSUE TITLE
Package update request: Latest Netdata, and can you enable netdata cloud

### ISSUE THREAD

**Issue by ChristopherSchek** [Entware/Entware#610]
Any chance you could update to the latest netdata, or atleast turn on cloud support for the one that's already been built?

**Comment by ryzhovau** [comment]
1.29.2 is here. This package came from OpenWrt with no any changes and we'll stay close to upstream as possible to simplify future updates.

**Comment by ChristopherSchek** [comment]
Doesn't seem that this one has NetData Cloud integration, any chance it can
be rebuilt with it?
