### ISSUE TITLE
Package Request: TriggerCMD

### ISSUE THREAD

**Issue by s-e-t-h** [Entware/Entware#611]
TriggerCMD for the Terramaster TOS.

https://www.triggercmd.com/forum/topic/375/install-triggercmd-agent-on-your-nas-or-router

Thanks in advance

**Comment by ryzhovau** [comment]
We can't add (and maintain) a big number of node-js packages, so we provided a necessary toolset to build it. Which is successfully used from link above.
Won't add, sorry.
