### ISSUE TITLE
vnstat 2.x

### ISSUE THREAD

**Issue by jackyaz** [Entware/Entware#612]
**Describe the solution you'd like**
https://github.com/vergoh/vnstat
Current version of 1.18 is quite old. 2.x brings SQLite backend amongst other features

- [ x] No similar package already added and/or this one got some new killer feature(s),
- [ x] Package is in active development (at least, not abandoned for 5 years or more),
- [ x] I'm ready to test added package on my platform [aarch86 RT-AC86U] and get a feedback about it.

**Comment by de-vnull** [comment]
I support this request. I'm using this on a Merlin router and having 2.x would be most helpful. Please update the package and I can help test.
