### ISSUE TITLE
strings

### ISSUE THREAD

**Issue by gth** [Entware/Entware#613]
A simple command-line utility, **strings** is common on other platforms and, in my current use case, a script depends on it.

Here's a manual page for **strings** on Debian -
https://manpages.debian.org/experimental/binutils-x86-64-linux-gnu/x86_64-linux-gnu-strings.1.en.html

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. synology x86_64] and provide feedback on it.

PS: Many thanks for your project - it's been useful many times over.

**Comment by zyxmon** [comment]
binutils-strings (package binutils) is renamed strings utility.
