### ISSUE TITLE
arp-scan / arping

### ISSUE THREAD

**Issue by wellloaded** [Entware/Entware#617]
This would allow new scenarios to happen and simplify a potential script to create network maps.

- [x ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Are you sure you are currently using modern Entware feed from https://bin.entware.net/mipselsf-k3.4 ?
Both utilities already there.
