### ISSUE TITLE
sqlsrv connect

### ISSUE THREAD

**Issue by Boban031** [Entware/Entware#619]
**Describe the solution you'd like**

Hi, can you add the drivers for sqlsrv_connect for php.
Opens a connection to a Microsoft SQL Server database.

https://www.php.net/manual/en/function.sqlsrv-connect.php

Thank you!

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
We keep php7 packages as close to [upstream](https://github.com/openwrt/packages/tree/master/lang/php7) as possible to simplify further updates. Won't add it, sorry.
