### ISSUE TITLE
7-Zip for Linux released

### ISSUE THREAD

**Issue by pasha-zzz** [Entware/Entware#620]
https://sourceforge.net/p/sevenzip/discussion/45797/thread/d401ab2966/

> The command line version of 7-Zip for Linux was released.
> 
> It's first version of my port of 7-Zip to Linux.
> That port of 7-Zip is similar to p7zip, but it's not identical to p7zip.

**Comment by ryzhovau** [comment]
Let me read your own link:
 > The source code of new version and another additional packages will be released later after some testing period.
