### ISSUE TITLE
Package Request: 7zip

### ISSUE THREAD

**Issue by Baltazar500** [Entware/Entware#623]
- [ ] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

Вышел официальный релиз консольного 7zip'a под Linux. Правда он пока в стадии альфы, но тем не менее. Может кто соберёт пакет под entware ? Или p7zip'ом всё и ограничится ? Исходники тут https://www.7-zip.org/a/7z1900-src.7z

**Comment by ryzhovau** [comment]
Это НЕ исходники для Linux. Пожалуйста, читайте новости дальше заголовка.

dup of https://github.com/Entware/Entware/issues/620
