### ISSUE TITLE
Package Request: ccache

### ISSUE THREAD

**Issue by Evengard** [Entware/Entware#624]
Compiling software on such devices is already time consuming, recompiling is even worse. And setting up the crosscompile environment is not always practical. Ccache can at least ease the pain.
https://ccache.dev/

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [armv7sf-k2.6] and get a feedback about it.

**Comment by ryzhovau** [comment]
Native compilation toolset is provided "as is" without any further support and/or extension. Won't add it, sorry.
https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation
