### ISSUE TITLE
sudo 1.9.5p2-1 (aarch64-k3.10) completely broken

### ISSUE THREAD

**Issue by kissglay** [Entware/Entware#626]
**Describe the bug**
[sudo]: Always says `"sudo: you do not exist in the passwd database"` even if just type `sudo` without any parameters. The previous version works just fine, and didn't modify any conf file.

---Edit---
Just revert back to 1.8.31 and all works fine.

**Environment (please complete the following information):**
 - Entware feed: [aarch64-k3.10]
 - Device [Asus RT-AX88U]
 - Firmware version [asuswrt-merlin 386.2]

**Comment by buergi** [comment]
Same for me, just for the reference for others, downgrading is easily possible via

    opkg install http://bin.entware.net/x64-k3.2/archive/prev/sudo_1.8.31-1_x64-3.2.ipk --force-downgrade
    
(obviously change the feed part `x64-k3.2` to match your installation)

Environment (please complete the following information):

    Entware feed: [x64-k3.2]
    Device [QNAP NAS TS-870 Pro]
    Firmware version [qts 4.2]

On an older QNAP NAS TS-239 where I use feed `x86-k2.6` it works fine.
