### ISSUE TITLE
Help: opkg permission denied

### ISSUE THREAD

**Issue by jakern** [Entware/Entware#63]
I'm trying to install on D-link DIR-866L-A1.
CPU is bcm4708x. 
I used the ARMv7 download

```bash
root@router:/opt/bin# ./opkg update
-sh: ./opkg: Permission denied
root@router:/opt/bin# ls -la
drwxr-xr-x    2 root     root         65536 May  9 20:53 .
drwxr-xr-x   43 root     root         65536 May 10 16:55 ..
-rwxr-xr-x    1 root     root        134856 May  9 20:53 opkg
-rwxr-xr-x    1 root     root           190 May  9 20:53 opkg.conf
```

**Comment by zyxmon** [comment]
What is the output of `uname -a` ?
What firmware your router runs, what busybox version is in firmware.

**Comment by zyxmon** [comment]
What installation script you are trying to run. My guess you have DD-WRT with busybox that downloads corrupted files - https://github.com/Entware/Entware-ng/issues/595

**Comment by ryzhovau** [comment]
No response.
