### ISSUE TITLE
Package request: libheif

### ISSUE THREAD

**Issue by becken** [Entware/Entware#632]
Please add libheif (https://github.com/strukturag/libheif) to the repository so I can convert iPhone HEIC images to JPEG on my NAS.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [armv7sf-k2.6] and get a feedback about it.

**Comment by ryzhovau** [comment]
Requires bunch of dependencies. Won't add it, sorry.

* libaom
* libdav1d
* libde265
* libx265
* rav1e
