### ISSUE TITLE
Add LIBCurl support to zabbix-agentd

### ISSUE THREAD

**Issue by diasdmhub** [Entware/Entware#633]
Zabbix Agent was not compiled with LIBCurl support.
```
# zabbix_agentd -t net.tcp.service[https]
net.tcp.service[https]                        [m|ZBX_NOTSUPPORTED] [Support for HTTPS check was not compiled in.]
```
According to [Zabbix documentation "net.tcp.service" checks](https://www.zabbix.com/documentation/current/manual/appendix/items/service_check_details), this key "**uses (and only works with) libcurl**".

Please, add LIBCurl support to zabbix-agentd to allow it to perform "net.tcp.service" and "net.tcp.service.perf" monitoring of host HTTPS service.

**Comment by ryzhovau** [comment]
We'll keep this package as close to [upstream](https://github.com/openwrt/packages/tree/master/admin/zabbix) as possible to simplify further updates. Won't add it, sorry.
