### ISSUE TITLE
dovecot tools: doveadm, dsync, doveconf

### ISSUE THREAD

**Issue by dajiahao** [Entware/Entware#634]
the dovecot package is missing the dovecot tools: doveadm, dsync, doveconf

it would be nice if those are also available with dovecot in entware either with the dovecot package or a seperate one
maybe an upgrade of dovecot itself also would be nice as the current package of openwrt includes the tools

https://github.com/Entware/entware-packages/blob/master/mail/dovecot/Makefile#L7
https://github.com/openwrt/packages/blob/master/mail/dovecot/Makefile#L131

**Comment by dryas** [comment]
If anyhow possible the "dovecot-sieve" package would also be fantastic (to support sieve scripting, e.g. for filter rules etc.). Thanks a lot for all the hard work BTW!
