### ISSUE TITLE
Can you add new RTL-SDR-BLOG for support new H/W features?

### ISSUE THREAD

**Issue by santus118** [Entware/Entware#635]
In new SDR device V3 now presents DIRECT SAMPLING Q-branch and BIAS TEE and many options in rtl_tcp and lib "librtlsdr", can you help with it?

https://github.com/rtlsdrblog/rtl-sdr-blog
https://github.com/librtlsdr/librtlsdr/

- [X ] This one got some new killer features
- [X ] Package is in active development
- [X ] I'm ready to test added package on my platforms:
- mipselsf-k3.4
- mipsel_24kc
- aarch64-k3.10

**Comment by ryzhovau** [comment]
Not sure we want to add another (3rd?) rtl-sdr fork. I'll keep this issue open forawhile to see is anyone request this fork too.
