### ISSUE TITLE
core 2.6.36 npm Illegal instruction

### ISSUE THREAD

**Issue by flyhigherpi** [Entware/Entware#636]
**Describe the bug**
[package name]: A clear and concise description of what the bug is and how to reproduce it. 

**Environment (please complete the following information):**
 - Entware feed: [e.g. mipselsf-k3.4]
 - Device [e.g. Asus RT-AX88U router]
 - ac68u
 - Firmware version [e.g. asuswrt-merlin]
 - merlin 384.18
 - 
![IMG_20210414_230217_802](https://user-images.githubusercontent.com/67776691/114732943-826f5180-9d75-11eb-8b88-60eaf929508d.jpg)

**Comment by zyxmon** [comment]
https://github.com/Entware/Entware/issues/233
