### ISSUE TITLE
 opkg_download_backend failed

### ISSUE THREAD

**Issue by kehuai007** [Entware/Entware#642]
hello, when execute  `opkg update`
there is sth wrong with connect http://ipk.80x86.io/aarch64/phicomm-n1/Packages.gz

[root@phicomm-n1:/opt]# opkg update
Downloading http://ipk.80x86.io/aarch64/phicomm-n1/Packages.gz.
wget: server returned error: HTTP/1.1 403 Forbidden
Collected errors:
 * opkg_download_backend: Failed to download http://ipk.80x86.io/aarch64/phicomm-n1/Packages.gz, wget returned 1.

**Comment by ryzhovau** [comment]
ipk.80x86.io has no relation to Entware.
