### ISSUE TITLE
ffmpeg / latest armv7sf-k3.2

### ISSUE THREAD

**Issue by nicksmart24** [Entware/Entware#645]
ffmpeg: libx264.so.161 missing
ffmpeg/libx264: just start ffmpeg. it cant be started due to missing libx264.so.161 

 - Entware feed: armv7sf-k3.2
 - Device: QNap
 - Firmware version: latest/of today

**Comment by ryzhovau** [comment]
Dup of https://github.com/Entware/Entware/issues/644
