### ISSUE TITLE
Add jsh portable javascript scripting language + webserver/appserver - created by the fossil/sqlite3 guy.

### ISSUE THREAD

**Issue by timoc** [Entware/Entware#646]
https://jsish.org/fossil/jsi/doc/ckout/README.md
Support for jsish scripting engine. 

Jsi is a javascript-ish interpreter with builtin websocket-server, sqlite and C-extensibility. It is an all in one, cross platform scripting tool. Essentially an embedded webserver with sql and mysql integration.  
It can also use zipfiles (zfs) and fossil repositories as the filesystems for the webserver, allowing you to deploy a web application as a single zipfile or version controlled fossil repository (sqlite) 

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Not sure we want another (6th?) web server in repo, sorry.

**Comment by timoc** [comment]
The cross platform scripting with node like web technology built in is how i would prefer to frame it. i added the webserver part, because it is a very interesting use case (2 files == database driven web application) for embedded devices.
