### ISSUE TITLE
Virtualpg loadable module for sqlite3

### ISSUE THREAD

**Issue by timoc** [Entware/Entware#647]
virtualpg is a plugin for sqlite3 to make postgresql integration transparent. 
https://www.gaia-gis.it/fossil/virtualpg/wiki?name=tutorial

It allows an sqlite3 application to connect to a postgresql database and map postgres tables into the sqlite database.  

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x]I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Too rare case for embedded devices. Won't add it, sorry.
