### ISSUE TITLE
Issue with libz.so

### ISSUE THREAD

**Issue by dryas** [Entware/Entware#648]
Hey,

it's not directly related to an official package, but maybe someone can help me on this as I don't get it fixed yet. :-(

I've created a new package for the newer 2.3.14 version of Dovecot (Entware only has 2.2.15) with the Makefile you can see at the bottom of my post. It compiles fine but during runtime I get the following error message:

`May 02 18:26:45 imap-login: Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): error:25066067:DSO support routines:dlfcn_load:could not load the shared library: filename(libz.so): libz.so: cannot open shared object file: No such file or directory, error:25070067:DSO support routines:DSO_load:could not load the shared library: user=<>, rip=xxx.xxx.xxx.xxx, lip=xxx.xxx.xxx.xxx, session=<3pOZT1vBPtFbQWYl>`

I really don't know how to fix this issue, does anyone know what's going on there?

I compile for: armv5-3.2
Device: QNAP TS-219P

Here is the makefile (It's work in progress, so please ignore some format issues etc. ^^):

```
#
# Copyright (C) 2006-2018 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=qdovecot
PKG_VERSION:=2.3.14
PKG_RELEASE:=$(AUTORELEASE)

PKG_SOURCE_NAME:=dovecot
PKG_SOURCE:=$(PKG_SOURCE_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://dovecot.org/releases/2.3
PKG_HASH:=c8b3d7f3af1e558a3ff0f970309d4013a4d3ce136f8c02a53a3b05f345b9a34a
PKG_LICENSE:=LGPL-2.1-only MIT BSD-3-Clause
PKG_LICENSE_FILES:=COPYING COPYING.LGPL COPYING.MIT

PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_SOURCE_NAME)-$(PKG_VERSION)
PKG_BUILD_DEPENDS:=libiconv

PKG_FIXUP:=autoreconf
PKG_INSTALL:=1

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/nls.mk

define Package/qdovecot
  SECTION:=QNAP
  CATEGORY:=Mail
  DEPENDS:=+libopenldap +libopenssl +librt +zlib +libzstd +libbz2 +libcap $(ICONV_DEPENDS)
  TITLE:=An IMAP and POP3 daemon
  URL:=http://www.dovecot.org/
  USERID:=dovecot=59:dovecot=59 dovenull=60:dovenull=60
endef

define Package/qdovecot/description
 Dovecot is a program which provides POP3 and IMAP services.
endef

CONFIGURE_ARGS += \
	--without-gssapi \
	--without-libunwind \
	--without-pam \
	--with-moduledir=/opt/lib/dovecot/modules \
	--with-notify=dnotify \
	--without-lzma \
	--without-lz4 \
	--without-sodium \
	--without-zstd \
	--with-ldap=yes

CONFIGURE_VARS += \
	RPCGEN= \
	i_cv_signed_size_t=no \
	i_cv_signed_time_t=no \
	i_cv_gmtime_max_time_t=32 \
	i_cv_mmap_plays_with_write=yes \
	i_cv_fd_passing=yes \
	i_cv_c99_vsnprintf=yes \
	lib_cv_va_copy=yes \
	lib_cv_va_copy=yes \
	lib_cv___va_copy=yes \
	ac_cv_prog_KRB5CONFIG="krb5-config" \
	lib_cv_va_val_copy=yes

TARGET_LDFLAGS += -Wl,--allow-multiple-definition

define Package/qdovecot/install
	$(INSTALL_DIR)  $(1)/opt/etc/init.d \
			$(1)/opt/etc/dovecot \
			$(1)/opt/share/doc/dovecot/example-config \
			$(1)/opt/lib/dovecot \
			$(1)/opt/bin \
			$(1)/opt/sbin
	$(CP) $(PKG_INSTALL_DIR)/opt/etc/dovecot/* $(1)/opt/etc/dovecot/
	$(CP) $(PKG_INSTALL_DIR)/opt/lib/dovecot/* $(1)/opt/lib/dovecot/
	$(CP) $(PKG_INSTALL_DIR)/opt/share/doc/dovecot/example-config $(1)/opt/share/doc/dovecot/example-config
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/opt/bin/doveconf $(1)/opt/bin/
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/opt/bin/doveadm $(1)/opt/bin/
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/opt/bin/dsync $(1)/opt/bin/
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/opt/sbin/* $(1)/opt/sbin/
	$(INSTALL_BIN) ./files/S90dovecot $(1)/opt/etc/init.d/
	rm  $(1)/opt/lib/dovecot/dovecot-config
	find $(1)/opt/lib/dovecot/ -name "*.a" -o -name "*.la" | xargs rm
endef

$(eval $(call BuildPackage,qdovecot))
```

The libz.so is available on the system:

/opt/lib/:
35652672    0 lrwxrwxrwx    1 admin    administ         9 May  2 18:39 libz.so -> libz.so.1*
35652770    0 lrwxrwxrwx    1 admin    administ        14 Apr 24 18:42 libz.so.1 -> libz.so.1.2.11*
35652771   80 -rwxr-xr-x    1 admin    administ     79292 Feb 26 09:59 libz.so.1.2.11*

Thanks for any help on that topic!

Best,

Ben

**Comment by zyxmon** [comment]
We do not provide this type of suppor. Probably package with certificates is not installed, or the binary tries to load  certificates from non /opt..... path.
Use strace to find out.
