### ISSUE TITLE
Intel Atom not supported? -sh: /opt/bin/opkg: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by ruanyl** [Entware/Entware#65]
Does `opkg` support Intel Atom cpu? I have synology DS214play and it runs `Intel Atom CE5335`.
I'm getting this error:
```
-sh: /opt/bin/opkg: cannot execute binary file: Exec format error
```

**Comment by zyxmon** [comment]
1. Does your atom support 64 bit instaructions?
2. Is your linux kernel 64 bit?
3. Is your kernel version 3.2 or higher?

If your answer is no for any question - you cannot install Entware. Install Entware-ng.
To check your linux kernel run `uname -a` and post output.

**Comment by zyxmon** [comment]
Your cpu is 32 bit according to https://wikidevi.com/wiki/Synology_DiskStation_Devices
You cannot install Entware.
We do not compile x86 version of Entware because only few devices need it.

**Comment by ruanyl** [comment]
@zyxmon Thank you for the reply.

**Comment by meiser79** [comment]
Please reconsider your decision. I also own a DS214play and I'd like to use Entware. Many thanks in advance!
