### ISSUE TITLE
Redis не работает.

### ISSUE THREAD

**Issue by shell1986** [Entware/Entware#650]
Всем привет, при установки redis-server и запуску его через конфиг по умолчанию

`redis-server /opt/etc/redis.conf `
происходит ошибка 

`8415:C 04 May 2021 15:14:29.880 # Can't chdir to '/opt/var/lib/redis': No such file or directory`

В самой папке /opt/var/lib/после установки ничего не появилось. 
Папка расшарена, nginx и mysql там спокойно встал. 

Использую Entware для android box armv7

**Comment by zyxmon** [comment]
Android не равно linux. Очень часто в android не хватает системных файлов linux. Используйте strace и другие средства отладки. Поищите решение в google.

**Comment by zyxmon** [comment]
После создания папки /opt/var/lib/redis у меня запускается
```
# redis-server /opt/etc/redis.conf
# ps | grep redis
19858 root     33268 SN   redis-server 127.0.0.1:6379
```

**Comment by shell1986** [comment]
> После создания папки /opt/var/lib/redis у меня запускается
> 
> ```
> # redis-server /opt/etc/redis.conf
> # ps | grep redis
> 19858 root     33268 SN   redis-server 127.0.0.1:6379
> ```

Спасибо заработало. В любом случае проблема не в андройде, а в отсутствии папки.
