### ISSUE TITLE
request Resilio Sync package

### ISSUE THREAD

**Issue by aarpro** [Entware/Entware#651]
is it possible to add a Resilio Sync package (ex BitTorrent Sync) ?
https://download-cdn.resilio.com/stable/linux-arm/resilio-sync_arm.tar.gz
https://download-cdn.resilio.com/stable/linux-armhf/resilio-sync_armhf.tar.gz

I have a NAS DLINK DNS-323 (D-Link DNS-323 rev.B1 • CPU: Marvell 88F5182) firmware ALT-F (entware including)

**Comment by ryzhovau** [comment]
No chance, sorry. Resilio sources are closed.
