### ISSUE TITLE
pmtud

### ISSUE THREAD

**Issue by wellloaded** [Entware/Entware#655]
As described and suggested here:
https://blog.cloudflare.com/path-mtu-discovery-in-practice/

It appears like this little package pmtud could be a smart synamic way to workaround Path MTU discovery and deal with ICMP blackholes in MTU detection.

https://github.com/cloudflare/pmtud

- [v] No similar package already added and/or this one got some new killer feature(s),
I guess iputils-tracepath might be similar but this is a deamon and works out of the box.

- [v] Package is in active development (at least, not abandoned for 5 years or more), 
Last updated 3 years ago

- [v] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.
I can help with testing if needed, sure.

**Comment by ryzhovau** [comment]
Are you sure you need to capture and broadcast ICMP messages related to MTU detection? I'll keep this issue open forawhile to see if someone else need it.
