### ISSUE TITLE
php7-dev 

### ISSUE THREAD

**Issue by kimdoyeonsa** [Entware/Entware#656]
Describe the solution you'd like
A clear and concise description of new features. Provide project URL and any other helpful context.

pecl install 
running: phpize
sh: phpize: not found
ERROR: `phpize' failed

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by zyxmon** [comment]
Please address this request upstream to openwrt developers. We use php7 and other packages from openwrt.
