### ISSUE TITLE
plp-mtu-discovery

### ISSUE THREAD

**Issue by wellloaded** [Entware/Entware#657]
https://github.com/Kavarenshko/plp-mtu-discovery

It performs an application layer PMTU dicovery which is way more effective than network layer and it doesn't suffer from ICMP blackhole issues.

- [ ] No similar package already added and/or this one got some new killer feature(s),
Not really, PMTU is already available via tracepath utility but this is more reliable.
- [v] Package is in active development (at least, not abandoned for 5 years or more),
- [v] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Quite simple and not very popular... Won't add it, sorry.
You may try to compile it right on router https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation
