### ISSUE TITLE
Cryptsetup Kernel Modules

### ISSUE THREAD

**Issue by vzhilov** [Entware/Entware#66]
Hello! Thank you for keeping this good repository! I just got new Asus RT-AC86U router and wanted to run disk encryption.

I have installed losetup and cryptsetup.

In order to compile dm-mod.ko I have forked asuswrt-merlin on my Linux Mint 18.3 (Ubuntu 16.04) machine. I have followed this manual (https://github.com/RMerl/asuswrt-merlin/wiki/Compile-Firmware-from-source-using-Ubuntu) to prepare for compilation. Then I put  

```
CONFIG_MD=y 
CONFIG_DM_CRYPT=m 
```
to config_base.6a file located in 

`~/asuswrt-merlin.ng/release/src-rt-5.02hnd/kernel/linux-4.1/`

 After then I used

`make rt-ac86u`

and the whole thing compiled just fine and as result I got the needed dm-mod.ko module.

However when I copied it to the router and tried 

`insmode entware/home/dm-mod.ko`

I get 

`insmod: can't insert 'entware/home/dm-mod.ko': unknown symbol in module, or unknown parameter`

While I think I compiled using the correct environment. Is there something I did wrong?

**Comment by zyxmon** [comment]
This is a wrong place to ask this question. I think the best place is https://www.snbforums.com/forums/asuswrt-merlin.42/
