### ISSUE TITLE
GPSD Utilities Request

### ISSUE THREAD

**Issue by stuart264** [Entware/Entware#660]
Could I please request an update of the GPSD package on Entware, specifically to include the utilities that are part of the package but not currently compiled in Entware as I require  uxbtool which is the only way to send commands to U-Blox GPS Modules, without which I am pretty much stuffed :(

Secondly adding PPS-Tools https://github.com/redlab-i/pps-tools to the repository would be really handy.

**Comment by ryzhovau** [comment]
Package updated https://github.com/Entware/entware-packages/commit/fde59a6669c815556ce75715d920bc550206cf40
Binaries will arrive on next week.
