### ISSUE TITLE
Samba vfs dirsort module for armv7

### ISSUE THREAD

**Issue by nickbardom** [Entware/Entware#666]
Hello,

I have a Zyxel NAS540 and I installed the samba4-server to replace the factory installed samba. The main reason I did that was to use the vfs dirsort module, as I have some clients that need this module. The problem I found after the installation is the samba4-server for Entware does not include this module. So I am asking if any one could please provide this module so I could use with the Entware samba4-server?

**Comment by ryzhovau** [comment]
This package came from OpenWrt with no any changes. We'll keep it in this state for further simple sync.
Won't add it, sorry.
