### ISSUE TITLE
Please, update yggdrasil-go package

### ISSUE THREAD

**Issue by Revertron** [Entware/Entware#668]
Please, update [yggdrasil-go](https://github.com/yggdrasil-network/yggdrasil-go/releases/latest/) package to 0.4.0.
Old versions are not compatible with new release.

**Comment by ryzhovau** [comment]
The newer version got different dependency tracking which is hard to cross-compile. Still, I'll keep this issue open as a reminder.

**Comment by zyxmon** [comment]
updated via https://github.com/Entware/entware-go/commit/bd6018f5eb1d11b7bc7c59e37aef0ed5a43bc58f
binaries will arrive soon
