### ISSUE TITLE
Doesn't upgrade from mipsel entware-ng (on Padavan)

### ISSUE THREAD

**Issue by ProBackup-nl** [Entware/Entware#67]
I expect the `opkg update && opkg upgrade` command to upgrade a standard installation of entware-ng to entware.

Actual it doesn't: 
```
# opkg update && opkg upgrade
Downloading http://pkg.entware.net/binaries/mipsel/Packages.gz.
Updated list of available packages in /opt/var/opkg-lists/entware-ng.
```

---
```
# uname -mr
3.4.113 mips

# opkg print-architecture
arch all 1
arch noarch 1
arch mipselsf 10

# cat /opt/etc/opkg.conf
src/gz entware-ng http://pkg.entware.net/binaries/mipsel

dest root /
lists_dir ext /opt/var/opkg-lists

# locate /sed
/bin/sed
/media/Main/opt/bin/sed
/opt/bin/sed
```

**Comment by zyxmon** [comment]
Entware-ng cannot be upgraded this way for mipsel. You are to manually uninstall entware-ng and install entware on Padavan firmware.

**Comment by ProBackup-nl** [comment]
@zyxmon What is the intended procedure to uninstall entware-ng and install entware on Padavan? 

Download the standard installer from http://bin.entware.net/mipssf-k3.4/installer/generic.sh and execute it?

Or first save all package configuration files, then uninstall all entware-ng packages and then start the standard installer from http://bin.entware.net/mipssf-k3.4/installer/generic.sh?

**Comment by zyxmon** [comment]
The Entware installer is already integrated in firmware - https://bitbucket.org/padavan/rt-n56u/commits/8ec3a1037a6d92b30052e8099be6658728e640c8
My recomendation is to save configuration files and probably packages list, clear /opt and start from scratch using installer from new firmware or doing something like your wiki - https://github.com/ProBackup-nl/Entware-ng-3x/wiki/Install-on-Padavan
BTW Entware-3x is updated automatically on Padavan firmware.

**Comment by ryzhovau** [comment]
1. Backup,
2. `/opt` cleanup,
3. Install.

I've [added](https://bitbucket.org/padavan/rt-n56u/commits/8ec3a1037a6d92b30052e8099be6658728e640c8) new installer recently, so you may use fresh Padavan f/w build to deploy Entware.

**Comment by ProBackup-nl** [comment]
I think this will be the shopping bag including terminal commands: 

> Upgrade Padavan firmware to a version newer then May 15th 2018.

`$ opkg list-installed`

> Save the needed package names that are needed somewhere.

> Backup`/opt` to a backup partition, for example using [my rotation backup script for padavan](https://gist.github.com/ProBackup-nl/82fb02c67dc05ca0310d0f9f8e8be14c) 

`$ /opt/usr/sbin/backup -o`

> Stop all running services and re-mount after unmount

`$ /usr/bin/opt-umount.sh && mount /dev/sda2 /opt`

> Clean everything in /opt except for a few configuration folders:

`cd /opt && find . ! -path "." ! -path "./etc" ! -path "./etc/config" ! -path "./etc/config/*" ! -path "./etc/nginx" ! -path "./etc/nginx/*" ! -path "./home" ! -path "./home/*" ! -path "./usr" ! -path "./usr/sbin" ! -path "./usr/sbin/*" ! -path "./var" ! -path "./var/mlocate" ! -path "./var/mlocate/*" \( -type d -print0 -o -delete \) | xargs -r0 rmdir; cd - >/dev/null`

> Now install the new Entware and packages

`$ /usr/bin/opt-opkg-upd.sh && opkg install ca-certificates coreutils-mktemp curl diffutils file findutils ionice mc mlocate nano nginx-extras openssl-util rsync`

> /usr/bin/opt-opkg-upd.sh will download and run [http://bin.entware.net/mipselsf-k3.4/installer/generic.sh](http://bin.entware.net/mipselsf-k3.4/installer/generic.sh) as installation script. That will return a few warnings that certain folders already do exist. This script will also install `opkg` meta package `entware-opt`. [Entware-opt](http://bin.entware.net/mipselsf-k3.4/entware-opt_227000-3_all.ipk) depends on: libc, libssp, librt, libpthread, libgcc, libstdcpp, libpthread, librt, entware-release, zoneinfo-asia, zoneinfo-europe, findutils, terminfo, locales, opkg, entware-upgrade, where `entware-release` and `entware-upgrade`. Where `entware_release` is a file in `/opt/etc` with entware info such as arch, cpu, gcc version, gcc flags, libc, libc version; and `entware-upgrade` is a helper package to upgrade Entware for future usage. Currently used to upgrade armv7soft  (2.3.36) to the new codebase. Because Padavan runs on mips cpu's `entware-upgrade`is not used at all.
