### ISSUE TITLE
php8

### ISSUE THREAD

**Issue by kimdoyeonsa** [Entware/Entware#670]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

https://downloads.openwrt.org/releases/packages-21.02/arm_cortex-a9/packages/php8-cgi_8.0.3-1_arm_cortex-a9.ipk
.
.
.
https://downloads.openwrt.org/releases/packages-21.02/arm_cortex-a9/packages/php8_8.0.3-1_arm_cortex-a9.ipk
https://www.php.net/

php8 all Packages

I want to install php 8.0. 

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.
aarch64-k3.10
armv5sf-k3.2 
armv7sf-k2.6
armv7sf-k3.2
mipselsf-k3.4
mipssf-k3.4
x64-k3.2
x86-k2.6

**Comment by butaford** [comment]
Without official support from Entware developers:
https://fw.pnpz.xyz/entware/repo-php8

**Comment by kimdoyeonsa** [comment]
repo-php8

PHP Startup: Unable to load dynamic library 'intl.so' (tried: /opt/lib/php/intl.so (libicuio.so.68: cannot open shared object file: No such file or directory), /opt/lib/php/intl.so.so (/opt/lib/php/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by butaford** [comment]
add repo in /opt/etc/opkg.conf: 
src/gz fwpnpz_php8 http://pnpz.xyz/files/fw/entware/repo-php8/_aarch64-3.10_
opkg update
opkg install php8-cli

ldd /opt/bin/php8-cli
/opt/bin/php8-cli -v
![image](https://user-images.githubusercontent.com/5542160/126862031-03c992cd-e1d9-43f4-8dc5-d171bc652877.png)

**Comment by The-BB** [comment]
check the configuration file /opt/etc/php.ini
https://github.com/Entware/entware-packages/blob/master/lang/php8/files/php.ini#L128

**Comment by kimdoyeonsa** [comment]
opkg install failed
wget: not an http or ftp url: https://fw.pnpz.xyz/entware/repo-php8/armv7sf-k3.2/Packages.gz
*** Failed to download the package list from https://fw.pnpz.xyz/entware/repo-php8/armv7sf-k3.2/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://fw.pnpz.xyz/entware/repo-php8/armv7sf-k3.2/Packages.gz, wget returned 1.

**Comment by butaford** [comment]
`opkg install ca-bundle`

**Comment by kimdoyeonsa** [comment]
[](url) 
![2021-07-24_173700](https://user-images.githubusercontent.com/48858134/126863889-b1e4b886-b36b-433b-9025-0550652dbefd.jpg)

**Comment by butaford** [comment]
**more attentively:**
 https://fw.pnpz.xyz/entware/repo-php8/**armv7-3.2**

**Comment by kimdoyeonsa** [comment]
php8-mod-intl
libicuio.so.68
libicuuc.so.68
libicudata.so.68
libicui18n.so.68
library file not found

**Comment by kimdoyeonsa** [comment]
php 8-mod-intl 
[
![2021-07-29_190821](https://user-images.githubusercontent.com/48858134/127487866-44264597-47e7-44c4-8f9c-4a80856704b0.jpg)
](url)

[
![2021-07-29_193520](https://user-images.githubusercontent.com/48858134/127487926-e031a3a4-1050-47ea-b709-9619e88c6d56.jpg)
](url)

**Comment by ryzhovau** [comment]
Done.
