### ISSUE TITLE
bzip2 uses wrong loader

### ISSUE THREAD

**Issue by berny156** [Entware/Entware#671]
I've installed https://bin.entware.net/armv7sf-k2.6/bzip2_1.0.8-1_armv7-2.6.ipk

**Observed**
`bzip2` results in:
> -sh: ./bzip2: not found

Reason is exposed by `file bzip2`:
> bzip2: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter **/lib/ld-linux.so.3**, for GNU/Linux 2.6.32, stripped

**Expected** interpreter: /opt/lib/ld-linux.so.3

**Workaround** `/opt/lib/ld-linux.so.3 /opt/bin/bzip2`

**Environment**
 - Entware feed: armv7sf-k2.6
 - RT-AC88U
 - asuswrt-merlin 386.3

**Comment by zyxmon** [comment]
Thanks for reporting. Fixed.
