### ISSUE TITLE
[feature-request] opkg: option to use cURL for downloads via https://

### ISSUE THREAD

**Issue by dnmTX** [Entware/Entware#673]
Hi there 👋 
As we all are very much aware how insecure is `http://` protocol and the fact that `opkg update/upgrade` is still using it it's kind of silly( i read the wiki about the workaround but why should i do it if simple option can be provided).
The last of the mohicans(correct me if i'm wrong here) who needed to use `http://` was **DD-WRT** due to not upgrading `wget` with SSL libs. and this is what i use on my end. Well with the latest builds **cURL** was updated to almost the latest and it's more then 
sufficient to handle the tasks. Simple option as `opkg update/upgrade --use-curl` would suffice,i believe(of course the opkg has to be coded for this as well). This is **cURL** with one of the latest **DD-WRT** builds:
```
curl 7.77.0 (arm-uclibc-linux) libcurl/7.77.0 OpenSSL/1.1.1k zlib/1.2.11.zlib-ng
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```
`Linux DD-WRT 4.4.276 #3725 SMP Mon Jul 26 03:02:07 +07 2021 armv7l DD-WRT`

Thank you for concidering it.I personally would appreciate having more secure `opkg` option fo feature downloads.
Big fan of `Entware` here,keep up the good work gus 👍  👍  👍

**Comment by ryzhovau** [comment]
Thanks!
We'll keep `opkg` as simple as possible to fit any embedded devices where it may appear, with minimal number of dependency and as close as possible to OpenWrt upstream.

Please, follow this guide if you want to use HTTPS https://github.com/Entware/Entware/wiki/Using-HTTPS-for-opkg
