### ISSUE TITLE
BIND9 and the tools might abort on routers with old kernels

### ISSUE THREAD

**Issue by arbv** [Entware/Entware#676]
My router runs fairly old kernel:

```
admin@RT-AC66U_B1-1C48:/# uname -a
Linux RT-AC66U_B1-1C48 2.6.36.4brcmarm #1 SMP PREEMPT Sun Jun 6 12:35:56 EDT 2021 armv7l ASUSWRT-Merlin
```

When running, for example `dig` or any tool which might create TCP connections, it will abort with the following message:

```
admin@RT-AC66U_B1-1C48:/# dig +tcp @1.1.1.1
netmgr/tcpdns.c:297: fatal error: RUNTIME_CHECK(result == 0) failed
Aborted
```

That happens because the code tries to set `TCP_USER_TIMEOUT` option on the socket, which is [available](https://man7.org/linux/man-pages/man7/tcp.7.html) only starting from the Linux kernel 2.6.37.

I can see two solutions to the problem here:

1. The proper one - compile BIND and its supplementary tools using older kernel headers. A lot of Broadcom based routers use the Linux kernel version 2.6.36, for example. That should prevent similar problems from happening.
2. A quick dirty hack to solve the problem at hand: patch the code. In particular, one could try to edit the `netmgr.c` file and remove/comment out the `TIMEOUT_OPTNAME` definition:

```
...
#if defined(TCP_CONNECTIONTIMEOUT)
#define TIMEOUT_TYPE	int
#define TIMEOUT_DIV	1000
#define TIMEOUT_OPTNAME TCP_CONNECTIONTIMEOUT
#elif defined(TCP_RXT_CONNDROPTIME)
#define TIMEOUT_TYPE	int
#define TIMEOUT_DIV	1000
#define TIMEOUT_OPTNAME TCP_RXT_CONNDROPTIME
#elif defined(TCP_USER_TIMEOUT)
#define TIMEOUT_TYPE	unsigned int
#define TIMEOUT_DIV	1
/* #define TIMEOUT_OPTNAME TCP_USER_TIMEOUT */
#elif defined(TCP_KEEPINIT)
#define TIMEOUT_TYPE	int
#define TIMEOUT_DIV	1000
#define TIMEOUT_OPTNAME TCP_KEEPINIT
#endif
...
```
Doing so will turn `isc__nm_socket_connectiontimeout()` into a no-op.

Running a publicly acessible BIND 9 instance on such an old version is not recommended for security reasons, but I would rather see a functional version of it and supplementary tools in the repository.

**Comment by arbv** [comment]
Or, the third option - to edit `isc__nm_socket_connectiontimeout()` definition to always return `ISC_R_SUCCESS`, even in the case of failure. I would opt for this one, to not compromise devices which run more recent kernels.

**Comment by ryzhovau** [comment]
Can't offer graceful solution here, sorry. We may recommend to use Entware-ng, which is deprecated for now.
http://pkg.entware.net/binaries/

**Comment by zyxmon** [comment]
@ryzhovau - we do support 2.6.36 for armv7 in Entware.
@arbv - can you make a PR. Kernel specific patches can be used like here - https://github.com/Entware/Entware/tree/master/package/utils/f2fs-tools (in patches-2.6 folder)

**Comment by arbv** [comment]
@zyxmon @ryzhovau

I have created an MR:

https://github.com/Entware/entware-packages/pull/17

Could you please review it and merge it? I would also appreciate any guidance if there is anything wrong with it.

**Comment by zyxmon** [comment]
I have recompiled bind with your patch and uploaded it to armv7sf-k2.6 repo without changing package version.

**Comment by arbv** [comment]
@zyxmon Thanks, I have verified that `dig` works now:

```
admin@RT-AC66U_B1-1C48:/tmp/home/root# dig +tcp @1.1.1.1

; <<>> DiG 9.17.13 <<>> +tcp @1.1.1.1
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30820
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;.                              IN      NS

;; ANSWER SECTION:
.                       517694  IN      NS      a.root-servers.net.
.                       517694  IN      NS      b.root-servers.net.
.                       517694  IN      NS      c.root-servers.net.
.                       517694  IN      NS      d.root-servers.net.
.                       517694  IN      NS      e.root-servers.net.
.                       517694  IN      NS      f.root-servers.net.
.                       517694  IN      NS      g.root-servers.net.
.                       517694  IN      NS      h.root-servers.net.
.                       517694  IN      NS      i.root-servers.net.
.                       517694  IN      NS      j.root-servers.net.
.                       517694  IN      NS      k.root-servers.net.
.                       517694  IN      NS      l.root-servers.net.
.                       517694  IN      NS      m.root-servers.net.

;; Query time: 20 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (TCP)
;; WHEN: Mon Aug 30 12:07:00 UTC 2021
;; MSG SIZE  rcvd: 239

```

**Comment by arbv** [comment]
So does it over `+tls` and `+https`.
