### ISSUE TITLE
Please update rclone to the latest version

### ISSUE THREAD

**Issue by wellloaded** [Entware/Entware#677]
Current rclone in entware: 1.55.1-1

Latest rclone available: v1.56.0 - 2021-07-20

https://rclone.org/changelog/

Latest version adds new features and introdces a long list of bugfixes. Please consider upgrading this in entware.

Thanks a lot for this beautiful project!

**Comment by ryzhovau** [comment]
[Done](https://github.com/Entware/entware-go/commit/c5aea00f25106e7857007015816d7be4a3d21a87). Binaries will arrive in next week.
