### ISSUE TITLE
named-compilezone is missing in BIND9 related packages

### ISSUE THREAD

**Issue by arbv** [Entware/Entware#679]
The `named-compilezone` tool, which is intended to be used to convert zone files between different formats, is missing in BIND9 related packages. Could it be included into the `bind-check` package, alongside the `named-checkzone`?

This tool is nice to have for anyone who, e.g. wants to run BIND from Entware as a hidden master. Having a tool to convert zone files to and fro human readable formats would be very helpful in this and similar situations.

**Comment by The-BB** [comment]
You can create it manually if you want.
```
~ # cat bind-9.17.13/bin/check/Makefile | grep -C 2 'compilezone'
install-exec-hook:
	ln -f $(DESTDIR)$(bindir)/named-checkzone \
	      $(DESTDIR)$(bindir)/named-compilezone
...
~ # 
```

**Comment by arbv** [comment]
Thanks! Still, I think it would be better to make it available after package installation, especially considering that it does not take any space.

**Comment by ryzhovau** [comment]
Bind came from OpenWrt with no changes. We'll keep it in this state to simplify next sync.
