### ISSUE TITLE
ps3netsrv

### ISSUE THREAD

**Issue by kjarex** [Entware/Entware#680]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

The package exists already but is 5 years old (compared to https://github.com/aldostools/webMAN-MOD/tree/master/_Projects_/ps3netsrv). My request is not about its age per se, but the currently available package is quite unreliable in my setup, and I'm hoping that in the newer versions bugs which cause this unreliability might have been fixed 
(I have not experienced those issues if I compile and run the current code on a computer - but I can't build and test it for my Entware powered device).

- [~] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [armv7] and give feedback about it.

**Comment by ryzhovau** [comment]
Bet you still on Entware-ng, which is deprecated for now.
The last 1.47.36 release is present in [armv7 feed](https://bin.entware.net/armv7sf-k2.6/) since June.
