### ISSUE TITLE
tidy-html5 Cmake compile error

### ISSUE THREAD

**Issue by kimdoyeonsa** [Entware/Entware#685]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

https://github.com/htacg/tidy-html5
tidy-html5 
tidy Exec format error

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Please, clarify: you want us to fix some compilation error or you request a new package?

**Comment by kimdoyeonsa** [comment]
new package request
