### ISSUE TITLE
Please add dash package

### ISSUE THREAD

**Issue by slycordinator** [Entware/Entware#687]
dash is the Debian Almquist shell, a POSIX-compliant /bin/sh shell meant to be as small as possible and which is pretty fast.

dd-wrt/openwrt use busybox, which incorporates dash as "ash", but it lacks some POSIX required features that I tend to use in scripts.

I'd prefer having something like dash available to allow me to force my /bin/sh symlink be to something that's fully-compliant and still small for using on devices such as these.

Thanks

**Comment by ryzhovau** [comment]
We've got four or five shells in repo and won't add another one, sorry.
