### ISSUE TITLE
mipselsf-k3.4 nginx is too old (legacy status)

### ISSUE THREAD

**Issue by Magissia** [Entware/Entware#69]
Package request
---
{nginx is a well known web server and reverse proxy, reverse proxy is interesting here as you cannot NAT the same 443 port to multiple machines in IPv4

Upgrading to supported version will introduce lots of security fixes}

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I successfully tested added package on my {platform}.

---

/media/Main # opkg update
Downloading http://bin.entware.net/mipselsf-k3.4/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
/media/Main # opkg upgrade
/media/Main # opkg list nginx
nginx - 1.12.2-1 - nginx is an HTTP and reverse proxy server, as well as a mail proxy server,
written by Igor Sysoev.

**Comment by zyxmon** [comment]
Please report upstream - https://github.com/openwrt/packages/tree/master/net/nginx
Try this package instead - https://github.com/Entware/rtndev/tree/master/nginx-extras

**Comment by Magissia** [comment]
Thanks
