### ISSUE TITLE
compile error when following the wiki 

### ISSUE THREAD

**Issue by fuji246** [Entware/Entware#692]
$ make package/tmux/compile V=s
make[1]: Entering directory '/media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware'
make[2]: Entering directory '/media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/package/libs/toolchain'
rm -rf /media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/build_dir/target-mips_mips32r2_-/toolchain/.pkgdir/libc.installed /media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/build_dir/target-mips_mips32r2_-/toolchain/.pkgdir/libc
mkdir -p /media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/build_dir/target-mips_mips32r2_-/toolchain/.pkgdir/libc
cp -fpR  /media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/build_dir/target-mips_mips32r2_-/toolchain/.pkgdir/libc/opt/lib/
cp: missing destination file operand after '/media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/build_dir/target-mips_mips32r2_-/toolchain/.pkgdir/libc/opt/lib/'
Try 'cp --help' for more information.
make[2]: *** [Makefile:738: /media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/build_dir/target-mips_mips32r2_-/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory '/media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/package/libs/toolchain'
time: package/libs/toolchain/compile#0.55#0.47#0.90
    ERROR: package/libs/toolchain failed to build.
make[1]: *** [package/Makefile:116: package/libs/toolchain/compile] Error 1
make[1]: Leaving directory '/media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware'
make: *** [/media/KingFast_6fb49c8c-b4e1-49ef-8494-2c03c2f892d4/Work/Entware/include/toplevel.mk:230: package/tmux/compile] Error 2

**Comment by zyxmon** [comment]
We do not support entware compilation. It look like you are not using our config file.
