### ISSUE TITLE
possible to support php extension ionCube?

### ISSUE THREAD

**Issue by glli** [Entware/Entware#695]
ionCube is used to encode and secure php files. Recently I am trying to host [filerun](https://filerun.com/requirements) which needs [ioncube loader](https://www.ioncube.com/loaders.php) to decode its php files. [Entware ](http://bin.entware.net/armv7sf-k3.2/)(armv7sf-k3.2 with php7.4) shows internal error when loading ioncube_loader_lin_7.4.so (armv7l 32 bits), not sure why. However I tried [openwrt php7.4](https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a15_neon-vfpv4/packages/), it is able to load ioncube_loader successfully.

**Comment by ryzhovau** [comment]
Not plans to add it so far. 
I'll re-open this one if somebody will ask it again.
