### ISSUE TITLE
Tailscale: tailscale/tailscaled exhibit 'illegal instruction' when executed on armv7sf-k2.6

### ISSUE THREAD

**Issue by davygravy** [Entware/Entware#696]
**Description:**
tailscale: tailscale and tailscaled both exhibit 'illegal instruction' when executed armv7sf-k2.6. 

**Environment:**
 - Entware feed: [armv7sf-k2.6]
 - Device [Linksys EA6900 and Netgear R6250 Routers]
 - Firmware version [Fresh Tomato ARM v2021.5]

**Comments**
 - perhaps compiler flag(s) not set correctly for this package
 - N.B. wireguard (`wg`) does seem to execute correctly - though I haven't tested its operation.  I mention this because `tailscale` is essentially a zeroconfig tool for wireguard.
 - I am **certain** that tailscale works on some other ARM devices (e.g. Kirkwood boxes) because I've tested it and I use it.

**Behavior**
Simple execution:
```
root@AirGate:/usr/sbin# tailscale
Illegal instruction
root@AirGate:/usr/sbin# tailscaled
Illegal instruction
```

Using `strace`:
```
root@AirGate:/usr/sbin# strace tailscale
execve("/opt/bin/tailscale", ["tailscale"], 0xbed21d10 /* 18 vars */) = 0
getpid()                                = 31244
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x5a6e8} ---
+++ killed by SIGILL +++
Illegal instruction
root@AirGate:/usr/sbin# strace tailscaled
execve("/opt/bin/tailscaled", ["tailscaled"], 0xbea64d10 /* 18 vars */) = 0
getpid()                                = 31533
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x5d174} ---
+++ killed by SIGILL +++
Illegal instruction
```

**Comment by zyxmon** [comment]
Probably you need to install nohf versions of go packages.

**Comment by davygravy** [comment]
You are correct.  Thank you and please close this issue.  If I see any further problem, I'll either reopen this or start a new one, as appropriate.

Thank you!

**Comment by sarkrui** [comment]
@davygravy I encountered the same issue. Could please elaborate on how you resolved it? I am actually confused by what @zyxmon said `install nohf versions of go packages`. Was it a particular tailscale package I need to install with? Thanks in advance!
***

[Solved] 

```
opkg list tailscale*
```

> aooo@RT-AC88U-5558:/tmp/home/root# opkg list tailscale*
> tailscale - 1.32.3-1 - Zero config VPN. Installs on any device in minutes, manages
>  firewall rules for you, and works from anywhere
> tailscale_nohf - 1.32.3-1 - Zero config VPN. Installs on any device in minutes, manages
>  firewall rules for you, and works from anywhere

if you have regular tailscale installed
```
opkg remove tailscale
```
reinstall with 
```
opkg install tailscale_nohf 
```

**Comment by davygravy** [comment]
IIRC, I just had to install the version is the armv7 k26 Tailscale package that had “nohf” in its name.

**Comment by davygravy** [comment]
Package name is: tailscale_nohf
