### ISSUE TITLE
Please add Perl Image::Magick Package

### ISSUE THREAD

**Issue by Digioso** [Entware/Entware#700]
**Describe the solution you'd like**

First, thanks a lot for adding the package of my last request. ( https://github.com/Entware/Entware/issues/686) :)

You already have the ImageMagick Basepackage in your package repo.
Would it also be possible to add Image::Magick Perl package, so that Perl can use ImageMagick?
I tried the last couple of hours to install it via cpan and also to compile ImageMagick including Perl from the source code, but no luck. :(
Unfortunately Image Magick comes with loadable objects so it needs to be compiled when you try it with the surce.

The only alterntive would be to use the command line interface and ImageMagick to use it, since you can execute external commands via Perl. But it would be a lot nicer if the Perl module would be available. :)

meta::cpan-page: https://metacpan.org/pod/Image::Magick
The package name for Debian/Ubuntu is libimage-magick-perl 
For Red Hat/CentOS ImageMagick-perl

Info on Debian package: https://packages.debian.org/buster/libimage-magick-perl

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [Synology DS920+] and get a feedback about it.

Thanks!

**Comment by The-BB** [comment]
please, test - http://bin.entware.net/x64-k3.2/test/perl-image-magick_7.0.11%2Bperl5.28-1_x64-3.2.ipk

**Comment by Digioso** [comment]
Thanks!

I was able to install it:

root@diginas:/tmp# wget http://bin.entware.net/x64-k3.2/test/perl-image-magick_7.0.11%2Bperl5.28-1_x64-3.2.ipk
--2022-08-25 21:11:47--  http://bin.entware.net/x64-k3.2/test/perl-image-magick_7.0.11%2Bperl5.28-1_x64-3.2.ipk
Resolving bin.entware.net... 2a06:98c1:3120::, 2a06:98c1:3121::, 188.114.97.0, ...
Connecting to bin.entware.net|2a06:98c1:3120::|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 103934 (101K) [application/x-gzip]
Saving to: 'perl-image-magick_7.0.11+perl5.28-1_x64-3.2.ipk'

perl-image-magick_7.0.11+perl5.28-1_x6 100%[===========================================================================>] 101.50K  --.-KB/s    in 0.02s

2022-08-25 21:11:47 (4.03 MB/s) - 'perl-image-magick_7.0.11+perl5.28-1_x64-3.2.ipk' saved [103934/103934]

root@diginas:/tmp# opkg install perl-image-magick_7.0.11+perl5.28-1_x64-3.2.ipk
Installing perl-image-magick (7.0.11+perl5.28-1) to root...
Configuring perl-image-magick.
root@diginas:/tmp# echo $?
0
root@diginas:/tmp#

Can't test the functionality it though, because I no longer need it.
