### ISSUE TITLE
Request Update: dnscrypt-proxy2 new fixes in Version 2.1.1

### ISSUE THREAD

**Issue by hub913** [Entware/Entware#701]
dnscrypt-proxy/ChangeLog 

# Version 2.1.1
  This is a bugfix only release, addressing regressions introduced in
version 2.1.0:
 - When using DoH, cached responses were not served any more when
experiencing connectivity issues. This has been fixed.
 - Time attributes in allow/block lists were ignored. This has been
fixed.
 - The TTL as served to clients is now rounded and starts decreasing
before the first query is received.
 - Time-based rules are properly handled again in
generate-domains-blocklist.
 - DoH/ODoH: entries with an IP address and using a non-standard port
used to require help from a bootstrap resolver. This is not the case
any more.

**Comment by jberlet** [comment]
Upvote this request - still running 2.0.45 as current 2.1.0 opkg-provided release breaks time-based blocked/allowed domain filtering. This particular issue was addressed in 2.1.1 of dnscrypt-proxy2. Thanks!

**Comment by ryzhovau** [comment]
Done. Binaries will available on next week.
https://github.com/Entware/entware-go/commit/caf29019c6726cd124d66d9edf315a480274ac85

**Comment by hub913** [comment]
Thank-You!!

    On Thursday, December 9, 2021, 12:33:57 PM UTC, Alexander Ryzhov ***@***.***> wrote:  
 
 


Done. Binaries will available on next week.
***@***.***

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
