### ISSUE TITLE
I2Pd update to 2.39.0

### ISSUE THREAD

**Issue by crcdll** [Entware/Entware#702]
Hello! There is new version at https://github.com/PurpleI2P/i2pd/releases/
May I ask you to update it for mipsel?
Thanks in advance.

**UPD**. It's already 2.40.0 now.

**Comment by ryzhovau** [comment]
Now it's moved to OpenWrt, so It's up to upstream. https://github.com/openwrt/packages/tree/master/net/i2pd
We'll keep it in this stay to simplify sync with OpenWrt.
