### ISSUE TITLE
Package request: Zabbix 5.4.5 agent

### ISSUE THREAD

**Issue by d1nd141** [Entware/Entware#704]
Hi,

the current zabbix_agent zabbix_get and zabbix_sender are quiet old (5.0.x).
Would be nice to have 5.4 as 5.0 is not (fully) compatible anymore with 5.4.x server/proxy.

Thanks

**Comment by diasdmhub** [comment]
It would be nice to have an updated Zabbix agent.
Also, there's the Zabbix Agent 2 as well.

**Comment by ryzhovau** [comment]
It's up to our upstream. https://github.com/openwrt/packages/tree/master/admin/zabbix
Zabbix arrived here with no changes to simplify synchronisations.
