### ISSUE TITLE
Please Update Documentation: Install on Synology NAS

### ISSUE THREAD

**Issue by gczychi** [Entware/Entware#705]
• The first line `mkdir -p /volume1/@Entware/opt` cannot be executed without root privileges. You need to `sudo -i` with your admin password in order for this to work.

• The same applies to step 4, Create Autostart Task
Here, you can’t choose the root user — the option is not made available in the dropdown menu.
Any ideas?

Tried on DSM ≥ 7.0

**Comment by zyxmon** [comment]
Synology wiki page was created by Synology users. You can edit it yourself and fix.
