### ISSUE TITLE
package request libc6-i386

### ISSUE THREAD

**Issue by tommi296** [Entware/Entware#706]
please add libc6-i386
This package contains the standard C runtime library and the standard math runtime library, as well as many other runtime libraries. This is the 32-bit version of the libraries intended for AMD64 systems and would help to run 32 bit applications on 64 bit systems

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by zyxmon** [comment]
Entware libs are somewhat special and can be used only with entware binaries.
