### ISSUE TITLE
aria2(1.36.0) upgrade

### ISSUE THREAD

**Issue by zi6xuan** [Entware/Entware#709]
**Describe the solution you'd like**
https://github.com/aria2/aria2/releases
There is a new version of aria2 that fixes an important function. After power off and restart, the wrong download project will be carried out.
If possible, I hope you can upgrade this plug-in.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Done. Binaries will be available on next week.
https://github.com/Entware/entware-packages/commit/2daa506c0822f32af8525742d30dd52e054e0f9b
