### ISSUE TITLE
[Package request] wireguard-go

### ISSUE THREAD

**Issue by maurerr** [Entware/Entware#71]
Package request.

https://git.zx2c4.com/wireguard-go/about/
---
Wireguard:
- Simple & Easy-to-use
- Cryptographically Sound
- Minimal Attack Surface
- High Performance
- Well Defined & Thoroughly Considered
- there is no similar package for kernels <= 3.10
- Package is in active development

**Comment by zyxmon** [comment]
We have recently added go compiler to Entware. Try to build it yourself and test if it works.

**Comment by maurerr** [comment]
your go version doesn't work
root@mytomato-ea6400:~#  go version
Illegal instruction

**Comment by zyxmon** [comment]
>> your go version doesn't work

What is your Entware feed? armv7-k2.6?

**Comment by maurerr** [comment]
correct:
src/gz entware http://bin.entware.net/armv7sf-k2.6
should I reinstall ?

**Comment by zyxmon** [comment]
>> should I reinstall ?

My guess the problem is your arm cpu does not have floating point. I'll try to build _nohf version later for broadcom armv7.  go works for other hardware:

```
 # /opt/bin/go/bin/go version
go version go1.10.1 linux/arm
 # /opt/bin/go/bin/go run hello.go
hello world
 # /opt/bin/go/bin/go build hello.go
 # ./hello
hello world
# cat /opt/etc/entware_release
release=entware
arch=arm
cpu=cortex-a9
cpu_subtype=unknown
float=soft
gcc=7.3.0
gcc_flags=-O2 -pipe -march=armv7-a -mtune=cortex-a9 -fno-caller-saves -mfloat-abi=soft
libc=glibc
libc_version=2.27
 # cat hello.go
package main
import "fmt"
func main() {
    fmt.Println("hello world")
}

```

**Comment by zyxmon** [comment]
@maurerr - please uninstall go and install go_nohf instead of it.
I have tested it on broadcom armv7 (tomato) and it works.

**Comment by maurerr** [comment]
it worked ! thanks !
now I'm trying to build the wireguard-go client

**Comment by maurerr** [comment]
I've managed to compile this but the tunnel does not work.
closing this
Thanks for your support !

**Comment by 0x5e** [comment]
https://github.com/Entware/Entware/issues/453
