### ISSUE TITLE
NodeJS Illegal instruction when using node legacy

### ISSUE THREAD

**Issue by risharde** [Entware/Entware#712]
Firstly thanks for this awesome repo called Entware!
My issue is that I'm using entware on a DDWRT Linksys EA6500 which has an ARMv7 processor:ARMv7 Processor rev 0 (v7l)
After trying to normal 'node' package, nodejs would output Illegal instruction (never executing my nodejs app).
Using the node legacy package running nodejs 0.10.48, the app works but suddenly exits with the same Illegal instruction message.

According to some research, this seems to happen when nodejs assumes that all ARMv7 processors can execute cpu instructions which may not be available to some armv7. It looks like a simple work around is to use an even older version of nodeJS - like 0.10.24

Problem is, I tried to download 0.10.24 to try to compile it from source on my router but it needs python 2 which is not available.

So can someone maybe get 0.10.24 into the repo OR make python 2 available in the repo???

Thanks!

**Comment by zyxmon** [comment]
We recommend to cross-compile packages - https://github.com/Entware/Entware/wiki/Compile-packages-from-sources
We do not support native package compilation.

**Comment by ryzhovau** [comment]
No response

**Comment by risharde** [comment]
I'm confused about something, where is the makefile for node under the entware project?
