### ISSUE TITLE
Update tinyproxy to 1.11.0

### ISSUE THREAD

**Issue by tramchamploo** [Entware/Entware#713]
As this version solves a memory leak I encountered.
https://github.com/tinyproxy/tinyproxy/issues/351
Thanks in advance.

**Comment by ryzhovau** [comment]
It's up to upstream. https://github.com/openwrt/packages/tree/master/net/tinyproxy
Tinyproxy came here with no changes and we'll keep it in this stay to simplify sync with OpenWrt.
