### ISSUE TITLE
Update request for ZeroTier package to latest 1.8.1 version.

### ISSUE THREAD

**Issue by Marty4RedNetGit** [Entware/Entware#714]
The latest ZeroTier 1.8.1 version is now publicly released. The 1.6.5 version is what's available for aarch64-k3.10 & armv7sf-k2.6 entware repos.  Please update the entware ZeroTier packages.

https://github.com/zerotier/ZeroTierOne/blob/master/RELEASE-NOTES.md

Thank you very much.

**Comment by ryzhovau** [comment]
Done. Binaries will be available on next week.
https://github.com/Entware/entware-packages/commit/56b1d0f795868729006b59082b39f54a802beb2c

**Comment by Marty4RedNetGit** [comment]
Thank you!
