### ISSUE TITLE
knot-resolver in entware-packages git repo, but not on bin.entware.net

### ISSUE THREAD

**Issue by tconnard** [Entware/Entware#717]
**Describe the bug**
knot-resolver can't be installed using opkg even though make files for it are in entware-packages

**Environment (please complete the following information):**
 - Entware feed: armv7sf-k3.2 but seems to be missing from all feeds
 - Device: Asus RT-AX82U
 - Firmware version: asuswrt-merlin gnuton prerelease

**Comment by zyxmon** [comment]
Entware has all Makefiles from Openwrt, not all of them are modified to be used in Entware.

**Comment by ryzhovau** [comment]
Done. Binaries will arrive soon.
