### ISSUE TITLE
Update stunnel to latest stable

### ISSUE THREAD

**Issue by maddie** [Entware/entware#72]
The one currently available in Entware is 4.33, and it has been since updated a lot, tons of bugs fixed and performance improved.

Currently (as of Sep. 29th, 2014) the latest stable version is 5.04, which can be downloaded here:
https://www.stunnel.org/downloads.html

Thanks!

**Comment by YasharF** [comment]
@maddie,
The current version 4.33 is being used because it is the version in OpenWRT, more specifically here: https://dev.openwrt.org/browser/packages/net/stunnel/Makefile ; can you submit a request to OpenWRT project and provide a link to the ticket here?

Thanks

**Comment by YasharF** [comment]
Ticket with OpenWRT: https://dev.openwrt.org/ticket/18896

**Comment by maddie** [comment]
@YasharF,

Sorry I missed your prior message. Thanks for submitting the ticket to OpenWRT :)

**Comment by YasharF** [comment]
It looks like that the reason the OpenWRT version is so old is because no one has officially adopted it in that project (see https://dev.openwrt.org/ticket/18896).  I found out that twisteroidambassador has doen a build https://sites.google.com/site/twisteroidambassador/openwrt/stunnel of the package outside of the official repo, so I contacted him through his website to see if he can adopt it.

**Comment by YasharF** [comment]
@maddie , I have not recieved any response from twisteroidambassador.  Can you be the backup person to adopt maintenance of stunnel in OpenWRT project, since you use it and can identify issues with its build?

**Comment by maddie** [comment]
@YasharF 
Sorry, I don't really think I'm the best person to maintain it since I don't really have any idea of how to do that.. and now I don't use it much, its performance combined with OpenVPN (which is my use case) is too bad.

**Comment by ryzhovau** [comment]
Could you try test package?
```
opkg install http://entware.wl500g.info/binaries/entware/archive/stunnel_5.10-1_entware.ipk
```
I've got no SSL cert and stunnel complained about non-fatal error:
```
# ./stunnel ./stunnel.conf
[.] stunnel 5.10 on mipsel-unknown-linux-gnu platform
[.] Compiled/running with OpenSSL 1.0.2 22 Jan 2015
[.] Threading:FORK Sockets:POLL,IPv6 TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
[ ] errno: (*__errno_location ())
[.] Reading configuration from file ./stunnel.conf
[.] UTF-8 byte order mark detected
[.] FIPS mode disabled
[ ] Compression disabled
[ ] PRNG seeded successfully
[ ] Initializing service [pop3s]
...
```
Is it normal? Please, provide a feedback. If package is working, I'll add a start script for it.

**Comment by maddie** [comment]
Somehow it still downloads and installs 4.33 instead.

I tried it after I did an 'opkg remove stunnel'

```
root@RT-AC66U:/tmp/home/root# opkg install http://entware.wl500g.info/binaries/entware/archive/stunnel_5.10-1_entware.ipk
No packages removed.
Downloading http://entware.wl500g.info/binaries/entware/archive/stunnel_5.10-1_entware.ipk.
Installing stunnel (4.33-1) to root...
Downloading http://entware.wl500g.info/binaries/mipselsf/stunnel_4.33-1_mipselsf.ipk.
Configuring stunnel.
Collected errors:
 * resolve_conffiles: Existing conffile /opt/etc/stunnel/stunnel.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/stunnel/stunnel.conf-opkg.
```

'stunnel -version' shows v4.33

```
root@RT-AC66U:/tmp/home/root# stunnel -version
stunnel 4.33 on mipsel-unknown-linux-gnu with OpenSSL 1.0.1i 6 Aug 2014
Threading:FORK SSL:ENGINE Sockets:POLL,IPv6 Auth:LIBWRAP

Global options
debug           = daemon.notice
pid             = /opt/var/run/stunnel/stunnel.pid
RNDbytes        = 64
RNDfile         = /dev/urandom
RNDoverwrite    = yes

Service-level options
cert            = /opt/etc/stunnel/stunnel.pem
ciphers         = ALL:!aNULL:!eNULL:!SSLv2
session         = 300 seconds
sslVersion      = SSLv3 for client, all for server
TIMEOUTbusy     = 300 seconds
TIMEOUTclose    = 60 seconds
TIMEOUTconnect  = 10 seconds
TIMEOUTidle     = 43200 seconds
verify          = none
```

**Comment by ryzhovau** [comment]
Too "smart" opkg. Try this way:
```
cd /opt/tmp
wget http://entware.wl500g.info/binaries/entware/archive/stunnel_5.10-1_entware.ipk
opkg install ./stunnel_5.10-1_entware.ipk
```

**Comment by maddie** [comment]
Yeah... it still does that:

```
root@RT-AC66U:/opt/tmp# opkg install ./stunnel_5.10-1_entware.ipk
Installing stunnel (4.33-1) to root...
Downloading http://entware.wl500g.info/binaries/mipselsf/stunnel_4.33-1_mipselsf.ipk.
Configuring stunnel.
Collected errors:
 * resolve_conffiles: Existing conffile /opt/etc/stunnel/stunnel.conf is different from the conffile in the new package. The new conffile will be placed at /opt/etc/stunnel/stunnel.conf-opkg.
root@RT-AC66U:/opt/tmp# stunnel -version
stunnel 4.33 on mipsel-unknown-linux-gnu with OpenSSL 1.0.1i 6 Aug 2014
Threading:FORK SSL:ENGINE Sockets:POLL,IPv6 Auth:LIBWRAP

Global options
debug           = daemon.notice
pid             = /opt/var/run/stunnel/stunnel.pid
RNDbytes        = 64
RNDfile         = /dev/urandom
RNDoverwrite    = yes

Service-level options
cert            = /opt/etc/stunnel/stunnel.pem
ciphers         = ALL:!aNULL:!eNULL:!SSLv2
session         = 300 seconds
sslVersion      = SSLv3 for client, all for server
TIMEOUTbusy     = 300 seconds
TIMEOUTclose    = 60 seconds
TIMEOUTconnect  = 10 seconds
TIMEOUTidle     = 43200 seconds
verify          = none
```

Try to do that again without the `./`

```
root@RT-AC66U:/opt/tmp# opkg install stunnel_5.10-1_entware.ipk
Package stunnel version 5.10-1 has no valid architecture, ignoring.
Package stunnel (4.33-1) installed in root is up to date.
```

**Comment by maddie** [comment]
I think the problem is that the architecture of this built package isn't correctly configured.

Renaming the ipk to zip and checking the 'control.tar.gz', in the file '.\control' you can see the properties of the package. The architecture is shown as `entware`.

Shouldn't it be something like `mipselsf`?

**Comment by maddie** [comment]
Alright, so I unzipped the ipkg manually, put the files into respective folders and ran `stunnel -version`, it seems the the new version depends on the stack protector libs?
```
root@RT-AC66U:/opt/tmp/opt/bin# stunnel -version
stunnel: can't load library 'libssp.so.0'
```

**Comment by ryzhovau** [comment]
The main feed of repo is `entware`, not `mipselsf`. Please, tell which one you are using next time.
``
cd /opt/tmp
wget http://entware.wl500g.info/binaries/mipselsf/archive/stunnel_5.10-1_mipselsf.ipk
opkg install ./stunnel_5.10-1_mipselsf.ipk
```

**Comment by maddie** [comment]
Oops, sorry I didn't know about that.

Now it works properly! Thanks :)

**Comment by ryzhovau** [comment]
Good. Which command line parameters are needed to start `stunnel`? I'm going to put it into start script.

**Comment by ryzhovau** [comment]
Package was updated.
