### ISSUE TITLE
pkg socksify: `wrong ELF class: ELFCLASS64`

### ISSUE THREAD

**Issue by HUMORCE** [Entware/Entware#725]
**Describe the bug**
[socksify]: does not work properly.

reproduction:

```shell
> opkg install socksify
> vi /opt/etc/socks.conf
...
> sockify curl example.org
ERROR: ld.so: object 'libdsocks.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

**Environment:**
 - Entware feed: aarch64-k3.10
 - Device: Asus RT-AX88U / RT-AC86U
 - Firmware version: asuswrt-merlin

**Comment by zyxmon** [comment]
https://github.com/Entware/Entware/issues/330
We will remove this package from repo.
I am keeping this issue opened and close it after package removal (with next sync).

**Comment by HUMORCE** [comment]
what alternative pkgs are available?

**Comment by ryzhovau** [comment]
LD_PRELOAD is a quite dirty hack, so any other socksifier will work as good (or as bad) as this one.
