### ISSUE TITLE
please add package

### ISSUE THREAD

**Issue by kimdoyeonsa** [Entware/Entware#726]
libtidy
https://github.com/kimdoyeonsa/kdy/tree/main/tidy-html5
hunspell
https://github.com/kimdoyeonsa/kdy/tree/main/hunspell
nuspell 
https://github.com/kimdoyeonsa/kdy/tree/main/nuspell
libenchant
https://github.com/kimdoyeonsa/kdy/tree/main/libenchant
libenchant2
https://github.com/kimdoyeonsa/kdy/tree/main/libenchant2
mariadb 10.7
https://github.com/kimdoyeonsa/kdy/tree/main/mariadb
php8 
https://github.com/kimdoyeonsa/kdy/tree/main/php8 
php81 php8.1
https://github.com/kimdoyeonsa/kdy/tree/main/php81
please package add & update

php8 tidy 
php8 enchant 
php8 zlib
php8 bz2
php8 zend_test
php8 sodium
php8 pspell
php8 php8-dbg 
php8 php8-embed
php8 php8-litespeed
php8.ini_production entware patch include
 
please add package

**Comment by ryzhovau** [comment]
Entware-ng is obsolete. Consider migration to Entware.
