### ISSUE TITLE
Package Request: DUC - web based disk analysis

### ISSUE THREAD

**Issue by siva008** [Entware/Entware#727]
** remote disk analysis or visualization through browser**

website: http://duc.zevv.nl
github: https://github.com/zevv/duc
license: open source

- [ ] No similar package already added and/or this one got some killer feature(s) that enables remote disk analysis through browser
- [ ] I'm ready to test added package on my platform [mycloud OS 3] and get a feedback about it.

**Comment by ryzhovau** [comment]
Can't provide graphical stats because of heavy dependencies like libcairo2 or libpango.
Pseudo graphical stats can be provided by `ncdu`.
