### ISSUE TITLE
Include mod_tls in proftpd package.

### ISSUE THREAD

**Issue by freekweijers** [Entware/Entware#728]
**Describe the solution you'd like**
Plain FTP is insecure. The current build of proftpd on Entware doesn't include mod_tls. Mod_tls adds encryption to proftpd. It would be great if it could be included in the package so you can use FTPS.

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Engine/Hardware support is disabled in openssl we're on. Won't add it, sorry.
