### ISSUE TITLE
npm fails with illegal instruction on nohf device

### ISSUE THREAD

**Issue by VA1DER** [Entware/Entware#729]
**Describe the bug**
node-npm]: The npm binary fails with an ilegal instruction error on Netgear r6700v1 device

**Environment:**
 - Entware feed:  #armv7sf-k2.6
 - Device: Netgear r6700v1
 - Firmware version: FreshTomato 2021.8

The assumption is that this error is related to this comment made when node.js and node-npm were added to entware-ng:
 #https://github.com/Entware/Entware-ng/issues/73

> some new node versions are incompatible with softfloat used in Entware. We will try to upgrade node with upstream upgrade - https://github.com/openwrt/packages/blob/master/lang/node/Makefile

Is there any way to get node and npm working on non-hardware-float devices?  IF this is not possible, recommend noting in the package descriptions that they require hardware float.

**Comment by zyxmon** [comment]
Try to install node-legacy, it may work. Packages node  and node-npm are incompatible fith softfloat arm cpu.
