### ISSUE TITLE
tcpdump  4.99.1 for MIPS (mipssf-k3.4)

### ISSUE THREAD

**Issue by Alozaros** [Entware/Entware#731]
Hi there folks,
thanks for the last opkg (entware) update on 12.12.2021
However I'd like to ask if you could update tcpdump too, it seems for MIPS
its been stacked on  4.9.3 since it came out 2019..is there any chance to update to 
4.9.9.1 as ver 5.00.0 is coming soon, i can see pre-git...is already there..but 4.9.9.1 will be ok.
Thanks in advance and happy holidays !

i can see my installed (MIPS) libpcap is already 1.10.1-1 (the last realise) 

**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
It's up to OpenWrt guys, where tcpdump came from. https://github.com/openwrt/openwrt/tree/master/package/network/utils/tcpdump

We keep it in current state to make future sync easier.
