### ISSUE TITLE
Request GNU gettext

### ISSUE THREAD

**Issue by VA1DER** [Entware/Entware#732]
**Describe the solution you'd like**
Request GNU gettext and its accompanying tools (ie: msgfmt).  This utility is ubiquitous in virtually any environment where you want to compile almost anything.

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
No plans to develop native compilation tools, sorry.

**Comment by VA1DER** [comment]
Not asking for them to be developed.  Asking for the [GNU gettext](https://www.gnu.org/software/gettext/) tools to be compiled into an Entware package.  Since libintl is already provided as a package, it can't be a stretch to include the rest of the gettext tools.  Not sure I understand the reasoning behind providing Entware packages for go and gcc (including a nice set of include files for gcc) if native compilation tools are out.
