### ISSUE TITLE
openssh connection error

### ISSUE THREAD

**Issue by kimdoyeonsa** [Entware/Entware#733]
**Describe the bug**
[package name]: A clear and concise description of what the bug is and how to reproduce it. 
Remote side unexpectedly closed network connection 
[
![2021-12-13_172947](https://user-images.githubusercontent.com/48858134/145778280-ce0d4582-8915-4924-95f7-85eff45887de.png)
](url)
please update
 line 232: -> $(INSTALL_BIN) $(PKG_INSTALL_DIR)/opt/sbin/sshd $(1)/opt/sbin/ssh
files/S40sshd
line 9:
/opt/sbin/ssh
**Environment (please complete the following information):**
 - Entware feed: armv7sf-k3.2
 - Device iptime nas1dual 
 - Firmware version [e.g. asuswrt-merlin]

**Comment by zyxmon** [comment]
Please decribу your problem with more details. I have just tried openssh-server on Qnap Nas (armv7sf-k3.2) without problems.

**Comment by zyxmon** [comment]
My guess - your are using some 3rd party scripts that rely on busybox from Entware is installed.

**Comment by kimdoyeonsa** [comment]
Loss of connection over time.

**Comment by zyxmon** [comment]
Probably it is a problem with your device - may be some sleep mode. I've waited several houres with active ssh connection with my NAS. Connection is OK.

**Comment by kimdoyeonsa** [comment]
My guess was that my nas was blocking the /sbin/sshd service. Renaming it to /sbin/ssh solved the problem.
