### ISSUE TITLE
less: command not found

### ISSUE THREAD

**Issue by GregThib** [Entware/Entware#734]
**Describe the bug**
[less]: After the last upgrade (Dec 11, 2021), the command less disappeared.

**Environment (please complete the following information):**
 - Entware feed: x64-k3.2
 - Device: Synology DS1512+
 - Firmware version: DSM 6.2

**Bug Inspection:**
I checked for purpose the difference between:
- before-update pkg : https://bin.entware.net/x64-k3.2/archive/less_590-1_x64-3.2.ipk
- after-update pkg: https://bin.entware.net/x64-k3.2/archive/less_590-2_x64-3.2.ipk

The first one install the file /opt/bin/less,
whenever the second one install the file /opt/libexec/less-gnu (not in common PATH values)

May I missed a thing about installation, or this is just a mistake in the package?

**Comment by ryzhovau** [comment]
Thanks for report.
