### ISSUE TITLE
mkvtoolnix update

### ISSUE THREAD

**Issue by alexdelprete** [Entware/Entware#736]
**Describe the solution you'd like**
Please update mkvtoolnix, it is really old and full of bugs respect to latest v63.0.

Thanks a lot for your great work.

**Comment by ryzhovau** [comment]
The newer version requires heavy QT [dependencies](https://gitlab.com/mbunkus/mkvtoolnix/-/blob/main/NEWS.md#build-system-changes-2) which we trying to avoid.

**Comment by alexdelprete** [comment]
> The newer version requires heavy QT [dependencies](https://gitlab.com/mbunkus/mkvtoolnix/-/blob/main/NEWS.md#build-system-changes-2) which we trying to avoid.

So v58 will be the last version you'll make available on entware?

**Comment by ryzhovau** [comment]
Yes, I think so.

**Comment by alexdelprete** [comment]
Ok, thanks.
