### ISSUE TITLE
superstartrek internal help command non-functional

### ISSUE THREAD

**Issue by VA1DER** [Entware/Entware#738]
**Describe the bug**
[superstartrek]: The documentation file sst.doc is not distributed with the game.  This means that the internal help command will not function.

**Environment (please complete the following information):**
 - Entware feed: [all]
 - Device [n/a]
 - Firmware version [n/a]

This version of Super Star Trek has an internal help function that is important to the understanding of the game.  The internal help command requires the file "sst.doc" to work.  As coded, the game simply looks for sst.doc in the current directory which is not very appropriate for Entware/OpenWRT.  I made a very simple patch to cause it to look for sst.doc under /opt/share/superstartrek/sst.doc instead.  This should be appropriate for all Entware and OpenWRT versions.  The second patch is to the Entware build system to cause it to include sst.doc and copy it to /opt/share/superstartrek.
```
--- sst_orig/sst.c	2021-12-20 18:30:16.515240194 +0000
+++ sst/sst.c	2021-12-20 18:30:41.675538354 +0000
@@ -149,15 +149,15 @@
 	else {
 		strcpy(cmdbuf, "  Mnemonic:  ");
 		j = 0;
 		while ((cmdbuf[j+13] = toupper(commands[i][j])) != 0) j++;
 	}
-	fp = fopen("sst.doc", "r"));
+	fp = fopen("/opt/share/superstartrek/sst.doc", "r");
 	if (fp == NULL) {
 		prout("Spock-  \"Captain, that information is missing from the");
 		prout("   computer. You need to find SST.DOC and put it in the");
-		prout("   current directory.\"");
+		prout("   correct directory.\"");
 		return;
 	}
 	i = strlen(cmdbuf);
 	do {
 		if (fgets(linebuf, 132, fp) == NULL) {
```
```
--- superstartrek_orig/Makefile	2021-12-20 13:48:50.277773874 -0400
+++ superstartrek/Makefile	2021-12-20 14:54:36.570734569 -0400
@@ -36,8 +36,10 @@
 endef
 
 define Package/superstartrek/install
 	$(INSTALL_DIR) $(1)/opt/bin
 	$(INSTALL_BIN) $(PKG_BUILD_DIR)/sst $(1)/opt/bin
+	$(INSTALL_DIR) $(1)/opt/share/superstartrek
+	$(INSTALL_DATA) $(PKG_BUILD_DIR)/sst.doc $(1)/opt/share/superstartrek
 endef
 
 $(eval $(call BuildPackage,superstartrek))
```

Please feel free to pass these patches up to OpenWRT as required to get sst to function correctly.

**Comment by ryzhovau** [comment]
Thanks for patches!
