### ISSUE TITLE
GCC 8.3.0

### ISSUE THREAD

**Issue by Peke** [Entware/Entware#743]
GCC 7.4.0 is getting obsolete.

Is there any chance to see 8.3.0+ Versions for x86_x64?

**Comment by ryzhovau** [comment]
Kernel 3.2 too, but still widely used on embedded devices.
Also, there's  no goal to be on the last GCC version: there's no any features we missing at this moment.

We plan to start new feed in the next year, but can't promise anything:)

**Comment by zyxmon** [comment]
We are using gcc 8.4.0 to build packages. As for native compilation - please address upstream - https://github.com/openwrt/packages/blob/master/devel/gcc/Makefile#L26
