### ISSUE TITLE
Rust Compiler

### ISSUE THREAD

**Issue by iwkse** [Entware/Entware#745]
**Describe the solution you'd like**
Would be great to have rustc and cargo

**Comment by ryzhovau** [comment]
We don't support native compilation, sorry.

**Comment by HuJK** [comment]
Why don't support native compilation?

gcc/golang works fine in entware, will it be dropped for the reason "We don't support native compilation"?

**Comment by ryzhovau** [comment]
It's out of project goal. https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation#general-information

**Comment by ryzhovau** [comment]
Rust compiler has been added, binaries will arrive soon

**Comment by mfe-** [comment]
@ryzhovau Is there a related PR? I can't find the package in the repo by searching for "rust"
