### ISSUE TITLE
please add package gcc-8.5.0

### ISSUE THREAD

**Issue by kimdoyeonsa** [Entware/Entware#747]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

https://github.com/kimdoyeonsa/kdy/tree/main/gcc/patches
https://github.com/kimdoyeonsa/kdy/blob/main/gcc/Makefile
please add package gcc-8.5.0

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
No plans to develop native compilation tools, sorry.
The existing tool set [provided](https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation) "as is" without any further development.

**Comment by ryzhovau** [comment]
BTW, this package came from upstream with no changes. It's better to send PR to OpenWrt guys.
https://github.com/openwrt/packages/tree/master/devel/gcc
