### ISSUE TITLE
git cannot clone on MIPSEL - missing ftp/http/https helpers

### ISSUE THREAD

**Issue by VA1DER** [Entware/Entware#749]
**Describe the bug**
[git]: git on MIPSEL k3.4 seems to be missing the remote helpers for ftp, http, and https.  This causes clone commands to fail.

When compared against files distributed on ARM k2.6 and k3.4 versions, these are the missing files:
-/opt/lib/git-core/git-http-backend
-/opt/lib/git-core/git-http-fetch
-/opt/lib/git-core/git-remote-ftp
-/opt/lib/git-core/git-remote-ftps
-/opt/lib/git-core/git-remote-http
-/opt/lib/git-core/git-remote-https
-/opt/lib/opkg/info/git-http.control
-/opt/lib/opkg/info/git-http.list

**Environment (please complete the following information):**
 - Entware feed: [mipselsf-k3.4]
 - Device [Netgear R6700v2 router]
 - Firmware version [DD-WRT v3.0-r47942]

Happy New Year.  Thanks for the last year of Entware.

**Comment by ryzhovau** [comment]
`opkg install git-http`
