### ISSUE TITLE
help:MariaDB-Server 10.1.32 Cannot Initialize

### ISSUE THREAD

**Issue by sunjingwei789** [Entware/Entware#75]
![5](https://user-images.githubusercontent.com/39703355/40655467-05108b02-6374-11e8-9aed-a882609c14f2.png)
![1](https://user-images.githubusercontent.com/39703355/40655480-09d72272-6374-11e8-95a3-54e88bebfbc1.png)
After an error occurs, many code returns -sh: /: Permission denied
/opt/bin/mysql
/opt/bin/mysql -u root mysql/opt/bin/mysqld --skip-grant-tables
--general-log&
And ./bin/mysql_install_db --defaults-file =~/ .my.cnf is there and
Cd /opt
./bin/mysql_install_db --force error
Just died in the permissions

**Comment by sunjingwei789** [comment]
Cannot set user name to root due to router
You can only debug with the admin account, but it belongs to the root user group.
Has been user.admin in my.cnf, the above error

**Comment by sunjingwei789** [comment]
Cannot set user name to root due to router
I can only debug with the admin account, but it belongs to the root user group.
Has been user.admin in my.cnf, the above error

**Comment by sunjingwei789** [comment]
Cannot set user name to root due to router
I can only debug with the admin account, but it belongs to the root user group.
Has been user=admin in my.cnf, the above error

**Comment by sunjingwei789** [comment]
I have put user=admin in my.cnf
Cannot set user name to root due to router
I can only debug with the admin account, but it belongs to the root user group.

**Comment by zyxmon** [comment]
The same as  https://github.com/Entware/Entware/issues/73
