### ISSUE TITLE
Add map package for RFC7599 compatibility

### ISSUE THREAD

**Issue by Nik3a1r** [Entware/Entware#751]
Hi,

In order to test if with DD-WRT I am able to configure a MAP-T RFC7599 connection, I ask to add  the map package https://openwrt.org/packages/pkgdata/map to ENTWARE.

Now I'm using a WRT3200AC with ENTWARE installed.

From http://bin.entware.net/armv7sf-k3.2/Packages.html I was not able to find the map package

Thank you in advance

**Comment by alfiodlr941** [comment]
Any news about that? Thanks

**Comment by ryzhovau** [comment]
Looks like it's OpenWrrt-specific package with ubus/ubox dependency. No plans no add it, sorry.
