### ISSUE TITLE
Package request hugo

### ISSUE THREAD

**Issue by dufei99** [Entware/Entware#755]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

https://github.com/gohugoio/hugo/releases
armv7l Error running Hugo: Illegal instruction

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by The-BB** [comment]
please, test:
http://bin.entware.net/armv7sf-k2.6/test/hugo_0.101.0-1_armv7-2.6.ipk
or http://bin.entware.net/armv7sf-k2.6/test/hugo_nohf_0.101.0-1_armv7-2.6.ipk
or http://bin.entware.net/armv7sf-k3.2/test/hugo_0.101.0-1_armv7-3.2.ipk
or http://bin.entware.net/armv7sf-k3.2/test/hugo_nohf_0.101.0-1_armv7-3.2.ipk

**Comment by ryzhovau** [comment]
No response.
