### ISSUE TITLE
iotop error

### ISSUE THREAD

**Issue by dvds-ok** [Entware/Entware#756]
**iotop** is a great tool that watches I/O usage information output by the Linux kernel (requires 2.6.20 or later) and displays a table of current I/O usage by processes or threads on the system.

**Environment:**
 - Entware feed: [armv7l-k2.6]
 - Device [Asus RT-AC68U v3]
 - Firmware version [FreshTomato 2021.8 K26ARM USB AIO-64K]

**package name** [iotop - 0.6-20200108-1]
**iotop** I run it from an armv7l architecture with a 2.6.36 kernel but it presents the following error:

root@ASUS:/tmp/home/root# iotop
**Could not run iotop as some of the requirements are not met:**
**- Linux >= 2.6.20 with**
  **- I/O accounting support (CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING)**

Thank you.

**Comment by zyxmon** [comment]
Your kernel does not support iotop
