### ISSUE TITLE
Deluge update to 2.1.0

### ISSUE THREAD

**Issue by PapaFuchs84** [Entware/Entware#758]
Please can someone update Deluge to the latest version 2.1.0 available on http://git.deluge-torrent.org/deluge ?
This new version should be compatible to python 3.10.

**Comment by zyxmon** [comment]
Current version is compatible with python 3.10. Deluge 3.10 is currently beta. We will (try to) update to the latest stable version (3.0.5 or later) with next Entware update.

**Comment by zyxmon** [comment]
Deluge was updated to 3.05
