### ISSUE TITLE
Package cloudreve

### ISSUE THREAD

**Issue by dufei99** [Entware/Entware#762]
https://cloudreve.org/
```
root@MiWiFi:/opt/root# ./cloudreve
bash: ./cloudreve: No such file or directory
```
root# uname -a
Linux MiWiFi 2.6.36.4brcmarm #16 SMP PREEMPT Tue Dec 21 07:59:19 CET 2021 armv7l Tomato

root# cat /proc/cpuinfo
Processor : ARMv7 Processor rev 0 (v7l)
processor : 0
BogoMIPS : 1998.84

processor : 1
BogoMIPS : 1998.84

Features : swp half thumb fastmult edsp
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x3
CPU part : 0xc09
CPU revision : 0

Hardware : Northstar Prototype
Revision : 0000
Serial : 0000000000000000

**Comment by The-BB** [comment]
please, test:
http://bin.entware.net/armv7sf-k2.6/test/cloudreve_3.5.3-2_armv7-2.6.ipk
or http://bin.entware.net/armv7sf-k2.6/test/cloudreve_nohf_3.5.3-2_armv7-2.6.ipk

**Comment by ryzhovau** [comment]
No response.
