### ISSUE TITLE
request dogcom(src https://github.com/hanwckf/dogcom.git)

### ISSUE THREAD

**Issue by zypluckyphoenix** [Entware/Entware#765]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Not plans to add it, sorry.
