### ISSUE TITLE
glibc-locale

### ISSUE THREAD

**Issue by axl7777** [Entware/Entware#766]
As a vs code user, I want to be able to remote-ssh into my synology.
glibc-locale is a requirement for vs code to function properly.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by zyxmon** [comment]
Entware has locales package that is compiled from glibc source.
