### ISSUE TITLE
[Package Request]

### ISSUE THREAD

**Issue by dpackham** [Entware/Entware#767]
I would like some type of file shipper like filebeat to send /var/log/messages and others to an external logging server.  this would be for the UDM Pro.  the UDM Pro logs a ton of info that is needed but it cant really be accessed ON the UDM and needs to be offloaded

**Comment by modacs** [comment]
Would much appreciate command reptyr to be added to available packages for install

**Comment by ryzhovau** [comment]
It uses MySQL or PostgreSQL as backend, which is too heavy for most of embedded devices.
No plans to add it, sorry.

**Comment by ryzhovau** [comment]
AFAIK, `syslog-ng` git this feature.
