### ISSUE TITLE
Obfs4proxy, obfs4

### ISSUE THREAD

**Issue by xapukserge** [Entware/Entware#768]
I use Entware packets on my Dlink DNS320L, which is based on SoC Marvell Kirkwood armV5
Tor packet had been working for several years, but Tor  was closed for my country several months ago. And now I need to use bridges. I cannot find "obfs4" packet in entwware  repository. That is why I cannot use Tor annymmore on my device. What can I do?

**Comment by ryzhovau** [comment]
Please, consider switch to Entware.
Entware-ng is EoL.
