### ISSUE TITLE
support for hidraw

### ISSUE THREAD

**Issue by jdesai61** [Entware/Entware#772]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

It will be nice to see libhidapi-hidraw support so that Flirc and Wyze sensor dongles that need hidraw drivers could be used, Here is an old but similar request

https://github.com/Entware/Entware-ng/issues/854

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
It's a part of `hidapi` package:
```
alpine86:~# opkg files hidapi
Package hidapi (0.10.1-1) is installed on root and has the following files:
/opt/lib/libhidapi-libusb.so.0
/opt/lib/libhidapi-hidraw.so.0
/opt/lib/libhidapi-libusb.so.0.0.0
/opt/lib/libhidapi-hidraw.so.0.0.0
```
