### ISSUE TITLE
Update: libopenssl

### ISSUE THREAD

**Issue by decaz** [Entware/Entware#779]
Can you update **libopenssl** package to the latest  **1.1.1n** version, please? There are two security advisories of [moderate](https://www.openssl.org/news/secadv/20220128.txt) and [high](https://www.openssl.org/news/secadv/20220315.txt) severities.

Also I didn't found header files and opensslconf.h file, - why there are not included in the package?

**Comment by decaz** [comment]
And one more question: why there is no openssl package in repository?

**Comment by ryzhovau** [comment]
Done.
