### ISSUE TITLE
duktape javascript broken

### ISSUE THREAD

**Issue by bayonne** [Entware/Entware#78]
Package duktape provides a javascript engine.
Javascript session:

```
duk> print('a')
ReferenceError: identifier 'print' undefined
    at [anon] (duk_js_var.c:1198) internal
    at global (input:1) preventsyield

```
Any idea how to fix that ?

**Comment by zyxmon** [comment]
http://duktape.org/guide.html#compiling.2.1
Probably default configuration has "No debug printing, no asserts, etc".
Probably @ryzhovau  will be more specific.

**Comment by zyxmon** [comment]
@ryzhovau - I think we should leave libduktape in binary repo for gerbera and remove executables.

**Comment by ryzhovau** [comment]
Also, it's an optional dep for `pyload` as the only modern JS-engine in our repo.
I'll look what else I can do.

**Comment by bayonne** [comment]
Thank you. Sorry to have called the package broken.
I come from `pyload` :)

**Comment by ryzhovau** [comment]
Looks like `print()` is [no longer automatically provided](https://github.com/svaarala/duktape/issues/1167#issuecomment-266135612).

**Comment by ryzhovau** [comment]
Done via https://github.com/Entware/rtndev/commit/b7721f4f54a65462a40d7f0447dff9c6da150a65
