### ISSUE TITLE
I2Pd update to 2.41 (mipselsf-k3.4)

### ISSUE THREAD

**Issue by Regloom** [Entware/Entware#783]
Latest version for mipselsf-k3.4 in repo is 2.38.0-1. It crashes after 10-40 mins of activity ([link to issue](https://github.com/PurpleI2P/i2pd/issues/1738#issuecomment-1069413649)). 

Please update package to the latest version.

There is new version at [PurpleI2P/i2pd](https://github.com/PurpleI2P/i2pd/releases/ )
- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Thanks for report.

This package was taken by OpenWrt and it's up to OpenWrt guys for now.
Please, send PR/Issue to them.

**Comment by r4sas** [comment]
FYI, OpenWRT has 2.41.0 in master for 2 months.
https://github.com/openwrt/packages/commit/c08bb2df62297967b3bced182bd77fcebac8fc9f

> It crashes after 10-40 mins of activity ([link to issue](https://github.com/PurpleI2P/i2pd/issues/1738#issuecomment-1069413649)).

It it same issue... problem is about development new transport protocol, which is not handled by versions below 2.41.0.

**Comment by ryzhovau** [comment]
Looks like we have to stay on 2.38.0 version. Some of our kernel 2.6 based feeds can't handle newer versions.

**Comment by Regloom** [comment]
> Looks like we have to stay on 2.38.0 version. Some of our kernel 2.6 based feeds can't handle newer versions.

Ничего не понял, на роутере ядро 3.4
```
~ # uname -r
3.4.113
```

**Comment by ryzhovau** [comment]
Набор пакетов единый для всех фидов из http://bin.entware.net/

**Comment by r4sas** [comment]
Так а в чем проблема протащить в ваш фид один пакет из мастера? У нас приложение собирается gcc вплоть до 4.8 (вижу что сейчас используется 8.3.0).

**Comment by r4sas** [comment]
И ядро 2.6 так же без проблем поддерживается (привет из полу-мертвой CentOS 7).

**Comment by Regloom** [comment]
Штош собираем сами тогда.
@ryzhovau наверное стоит убрать тогда пакет i2pd совсем, так как текущая версия не совместима с новым протоколом (не работает).

**Comment by The-BB** [comment]
Если очень сильно хочется, копайте отсюда - https://github.com/PurpleI2P/i2pd/commit/ed42948051afb308cd7585d4284d286f49829a08 и дальше вверх...

**Comment by r4sas** [comment]
Я проверю сборку пакета, посмотрим чего там не так...

**Comment by r4sas** [comment]
Дублирую сообщение отправленное в чат в Телеграме:

Пытаюсь собрать для теста пакет из репозитория (см. https://github.com/Entware/Entware/issues/783), но попадаю на ошибку с libffi.

Порядок действий:
```
git clone ...
make package/symlinks
cp -v configs/armv7-2.6.config .config
make -j$(nproc) tools/install
make -j$(nproc) toolchain/install
make package/i2pd/compile V=s
```

Чего получаю в ответ:
```
make[2]: Entering directory '/home/wrt/Entware/feeds/packages/libs/libffi'
CFLAGS="<cut>" make -j1 -C /home/wrt/Entware/build_dir/hostpkg/libffi-3.4.2
make[3]: Entering directory '/home/wrt/Entware/build_dir/hostpkg/libffi-3.4.2'
make[3]: *** No targets specified and no makefile found.  Stop.
make[3]: Leaving directory '/home/wrt/Entware/build_dir/hostpkg/libffi-3.4.2'
make[2]: *** [Makefile:90: /home/wrt/Entware/build_dir/hostpkg/libffi-3.4.2/.built] Error 2
make[2]: Leaving directory '/home/wrt/Entware/feeds/packages/libs/libffi'
time: package/feeds/packages/libffi/host-compile#0.31#0.27#0.51
    ERROR: package/feeds/packages/libffi [host] failed to build.
make[1]: *** [package/Makefile:114: package/feeds/packages/libffi/host/compile] Error 1
make[1]: Leaving directory '/home/wrt/Entware'
make: *** [/home/wrt/Entware/include/toplevel.mk:230: package/i2pd/compile] Error 2
```
ЧЯДНТ?

**Comment by r4sas** [comment]
Проблема ясна, для совместимости добавлен код: https://github.com/PurpleI2P/i2pd/commit/1326597226257cbf54eb69f89923c807fc82f76a

Пояснение: для сборки пакетов, как я понимаю, используются собранные на базе musl компиляторы и заголовочные файлы. Из-за этого boost изначально начинает работать с заголовками `netinet` и это не дает нормально инклуднуть заголовки `linux/in6.h`, что и ломает сборку. По этому придется отказаться на системах, где эти заголовки используются, от функционала (предпочтение постоянных IPv6 адресов временным).

**Comment by ryzhovau** [comment]
Класс! Было бы обидно исключить пакет, который когда-то благодаря нам [появился](https://twitter.com/i2porignal/status/574994873159303168).

musl в Entware не используется, тулчейны на glibc.

**Comment by The-BB** [comment]
начиная с ядра 3.12 с `#if __UAPI_DEF_*` в `linux/in6.h` можно собирать без "костыля"...

**Comment by r4sas** [comment]
> начиная с ядра 3.12 с `#if __UAPI_DEF_*` в `linux/in6.h` можно собирать без "костыля"...

Оно так и будет, когда не будет инклудиться netinet.

**Comment by Regloom** [comment]
Отличная работа, спасибо @r4sas @ryzhovau !
