### ISSUE TITLE
Package Request reptyr

### ISSUE THREAD

**Issue by modacs** [Entware/Entware#784]
Would much appreciate the reptyr command be added to available packages for install

https://github.com/nelhage/reptyr

- [X] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by zyxmon** [comment]
Done via https://github.com/Entware/entware-packages/commit/5e3b8e203989891a9ad4e92366e6df3b778797e2
Binary will be ready in few days (not for mips*)
