### ISSUE TITLE
MiniDLNA - dependency broken in mipselsf-k3.4/1.3.0-1

### ISSUE THREAD

**Issue by hogehoge61** [Entware/Entware#787]
Since the package update of 2022/04/14, mipselsf-k3.4/minidlna 1.3.0-1 is not working.

> minidlnad -f /opt/etc/minidlna.conf
> minidlnad: error while loading shared libraries: libavformat.so.58: cannot open shared object file: No such file or directory

From reading the error message, it appeared that there was a mismatch in the versions of the dependent libraries. 

Workaround: downgrade libffmpeg-full and libffmpegthumbnailer to the previous version so that the current package (minidlna 1.3.0-1) will work.

>Downgrading libffmpeg-full on root from 5.0-1 to 4.3.2-1...
>Downgrading libffmpegthumbnailer on root from 2.2.2-2 to 2.2.2-1...

**Comment by ryzhovau** [comment]
Unfortunately, opkg is too simple to track down dependency changes. Please, follow this note:

https://github.com/Entware/Entware/wiki#%EF%B8%8F-package-upgrade-notes

**Comment by hogehoge61** [comment]
I followed the description in the note and it solved the problem. It seems that the problem was exactly as in the example.
I am sorry to have caused you unnecessary trouble with something I could have solved on my own.
