### ISSUE TITLE
Rtorrent/Rutorrent webui not working.

### ISSUE THREAD

**Issue by fireqpeg** [Entware/Entware#788]
http://bin.entware.net/armv7sf-k3.2

device: RT-AX56U Firmware Version:[386.5_2]

II installed rtorrent, rutorrent. And your webui won't load! I tried to use a different config. Set a different port. It doesn't work either. Please explore and correct this error!

**Comment by fireqpeg** [comment]
http://bin.entware.net/armv7sf-k3.2

device: RT-AX56U Firmware Version:[386.5_2]

II installed rtorrent, rutorrent. And your webui won't load! I tried to use a different config. Set a different port. It doesn't work either. Please explore and correct this error!

**Comment by ryzhovau** [comment]
Look's like we have to rework this package. As a temporary solution, try `ln -sf php8-fcgi /opt/bin/php-fcgi`.

**Comment by fireqpeg** [comment]
Thank you help me! (ln -sf php8-fcgi /opt/bin/php-fcgi.) It works like this!

**Comment by The-BB** [comment]
fixed via https://github.com/Entware/entware-packages/commit/9e9e8ca83bb0785e777c14abe6826dbb29f80a6f
