### ISSUE TITLE
libtorrent rasterbar 2.0.5.0 package

### ISSUE THREAD

**Issue by fireqpeg** [Entware/Entware#789]
http://bin.entware.net/armv7sf-k3.2
device: RT-AX56U Firmware Version:[386.5_2]

I can't understand slowly for half a year. Updated libtorrent rasterbar 2.0.5.0. In comparison, is there still the libtorrent rasterbar version 1. *. *? It's pretty excruciating that it's been half a year. And you put back the same high CPU usage version 1. *. I hope you are upgraded to the new version. 2.0. *. *. If I've been waiting for asuswrt for $ 300 (USD) for a NAS level router. Then the minimum to expect is that. Thanks in advance!

**Comment by zyxmon** [comment]
Deluge has ipv6 problems with 2.05.
