### ISSUE TITLE
rclone 

### ISSUE THREAD

**Issue by cdthompso1** [Entware/Entware#79]
The latest rclone binary does not run on mipsel devices because of a soft-float toolchain issue.  Here is the error in dmesg when running on a mips32r2-based Asus RT-AC66u. Can this be rebuilt and added to the repo?

`FPU emulator disabled, make sure your toolchainwas compiled with software floating point support (soft-float)`

The install history and entware info:

```
root@DD-WRT:/opt/tmp# opkg install rclone
Installing rclone (1.39-1) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/rclone_1.39-1_mipsel-3.4.ipk
Configuring rclone.
```

```
root@DD-WRT:/opt/tmp# more /opt/etc/entware_release 
release=entware
arch=mipsel
cpu=mips32r2
cpu_subtype=unknown
float=soft
gcc=7.3.0
gcc_flags=-O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -msoft-float
libc=glibc
libc_version=2.27
```

Many thanks. Love this project. I want rclone to do cloud backups from USB attached SAN disks.

**Comment by ryzhovau** [comment]
AFAIK, RT-N66U/AC66U is the last devices with kernel 2.6-based (legacy) f\w toolchain.
Not sure Entware (with newer kernel 3.4 based toolchain) will run on this devices with no issues.
