### ISSUE TITLE
[Request] Navidrone [Request]

### ISSUE THREAD

**Issue by jumpsmm7** [Entware/Entware#791]
<a href="https://www.navidrome.org"><img src="resources/logo-192x192.png" alt="Navidrome logo" title="navidrome" align="right" height="60px" /></a>

# Navidrome Music Server

[![Last Release](https://img.shields.io/github/v/release/navidrome/navidrome?logo=github&label=latest&style=flat-square)](https://github.com/navidrome/navidrome/releases)
[![Build](https://img.shields.io/github/workflow/status/navidrome/navidrome/Build?logo=github&style=flat-square)](https://nightly.link/navidrome/navidrome/workflows/pipeline/master)
[![Downloads](https://img.shields.io/github/downloads/navidrome/navidrome/total?logo=github&style=flat-square)](https://github.com/navidrome/navidrome/releases/latest)
[![Docker Pulls](https://img.shields.io/docker/pulls/deluan/navidrome?logo=docker&label=pulls&style=flat-square)](https://hub.docker.com/r/deluan/navidrome)
[![Dev Chat](https://img.shields.io/discord/671335427726114836?logo=discord&label=discord&style=flat-square)](https://discord.gg/xh7j7yF)
[![Subreddit](https://img.shields.io/reddit/subreddit-subscribers/navidrome?logo=reddit&label=/r/navidrome&style=flat-square)](https://www.reddit.com/r/navidrome/)
[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v2.0-ff69b4.svg?style=flat-square)](CODE_OF_CONDUCT.md)

## [Check out our Live Demo!](https://www.navidrome.org/demo/)

Navidrome is an open source web-based music collection server and streamer. It gives you freedom to listen to your 
music collection from any browser or mobile device. It's like your personal Spotify!

It is compatible across numerous platforms including LINUX. While there are debian, arch linux, and alpine based ways to run it, they provide the binaries that would be useful in creating an entware package solution. 

Both Alpine and Arch linux have their own package handlers for this project. It would be nice if it could be ported to Entware repo. 
 
https://github.com/navidrome/navidrome

Precompiled binaries located: 
https://github.com/navidrome/navidrome/releases/tag/v0.47.5

Compile instructions for binaries not precompiled:
https://www.navidrome.org/docs/installation/build-from-source/

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by The-BB** [comment]
please, test - http://bin.entware.net/mipselsf-k3.4/test/navidrome_0.47.5-1_mipsel-3.4.ipk

**Comment by jumpsmm7** [comment]
> please, test - http://bin.entware.net/mipselsf-k3.4/test/navidrome_0.47.5-1_mipsel-3.4.ipk

It looks promising I am currently investigating it right now.

**Comment by spinline** [comment]
error while loading shared libraries: libtag.so.1: cannot open shared object file: No such file or directory

**Comment by ryzhovau** [comment]
As long as discussion hangs, I'm closing this one.
I'll open it again if someone will be interested.
