### ISSUE TITLE
Last update breaks Dovecot authentication

### ISSUE THREAD

**Issue by LincDavis** [Entware/Entware#792]
After updating Entware on a QNAP NAS, dovecot throws this error:

`dovecot: auth: Error: dovecot/auth: error while loading shared libraries: liblber-2.4.so.2: cannot open shared object file: No such file or directory`

It was working before the update and the configuration didn't change. I had to manually create a symbolic link:

> ln -s liblber.so.2.0.200 /opt/lib/liblber-2.4.so.2

**Comment by ryzhovau** [comment]
It's up to `opkg`, which won't track dependency changes.
https://github.com/Entware/Entware/wiki#%EF%B8%8F-package-upgrade-notes
