### ISSUE TITLE
Memory exhausted error

### ISSUE THREAD

**Issue by risharde** [Entware/Entware#793]
During install:

Entware uses separate locale-archive file independent from main system
Creating locale archive /opt/usr/lib/locale/locale-archive
Adding en_EN.UTF-8
memory exhausted
Adding ru_RU.UTF-8
memory exhausted
locale-archive file was not created, not enough memory? Downloading...

Environment:
CPU ModelBroadcom BCM5357 chip rev 2 
CPU Cores1 
CPU Clock300 MHz

**Comment by ryzhovau** [comment]
That is normal situation for devices with low RAM volume.
Even if locales creation failed, pre-created ones will be downloaded.
https://github.com/Entware/rtndev/blob/1182142d422ecb1e3b64ce5b2dcc4de6481ea73e/locales/Makefile#L50
