### ISSUE TITLE
[Package Request] Domoticz

### ISSUE THREAD

**Issue by asrrd6** [Entware/Entware#797]
Please port the package Domoticz (home automation).
It is already present in OpenWRT for some time. Most of the dependancies are already present in Entware.

- [*] No similar package already added and/or this one got some new killer feature(s),
- [*] Package is in active development (at least, not abandoned for 5 years or more),
- [*] I'm ready to test added package on my platform [armel-k2.6] and get a feedback about it.

**Comment by ryzhovau** [comment]
Dup of https://github.com/Entware/Entware/issues/684
