### ISSUE TITLE
[Issue] Packages Node and Node-NPM give "Illegal instruction"

### ISSUE THREAD

**Issue by asrrd6** [Entware/Entware#798]
**Describe the bug**
[Node]: responds to one command only "-v" giving the version v14.18.3. All other commands give "Illegal instruction" error.
[Node-NPM]: reacts with "Illegal instruction" to all commands - i.e. install, config, cache, help or even start without any commands.
Package Node-legacy is working correctly - i.e. npm commands do work.

**Environment (please complete the following information):**
 - Entware feed: armv7sf-k2.6
 - Device: Asus RT-N18U router
 - Firmware version: Freshtomato

**Comment by zyxmon** [comment]
https://github.com/Entware/Entware/issues/729
