### ISSUE TITLE
package: nut-driver-blazer_ser missing

### ISSUE THREAD

**Issue by mikeS7** [Entware/Entware#8]
### Package: nut-driver-blazer_ser

there are no nut-driver-blazer_ser in repository, it was before.

Could you please restore package.

Спасибо
PS. Приходится руками "старый" пакет переустанавливать

**Comment by ryzhovau** [comment]
That was the oldest open issue for this moment. Thanks for patience.

Не прошло и полгода.

**Comment by mikeS7** [comment]
Спасибо, теперь жду сборку ...
