### ISSUE TITLE
Wiki owncloud appears to be outdated

### ISSUE THREAD

**Issue by Jishun** [Entware/Entware#802]
**Describe the bug**
It appears this guide to install owncloud is out dated, the guide uses php7 but the latest package source doesn't provide those anymore 

**Environment (please complete the following information):**
 - Entware feed: armelsf-k2.6
 - Device netgear R7000
 - Firmware version  Fresh tomato

**Comment by ryzhovau** [comment]
Feel free to fix it! You've got all necessary rights to edit it.

**Comment by sophtron** [comment]
Well. took a try and finally figured that.. owncloud can't run with php8..

**Comment by Jishun** [comment]
Well. took a try and finally figured that.. owncloud can't run with php8.

**Comment by Jishun** [comment]
instead, I managed to get nextcloud running with the current available packages, 
I'm unable to get ssl working yet,  because the current lighttpd package appears missing mod_openssl.so
I did it by mostly following the owncloud wiki guide, except installed different packages, 
here is what I had to install 
btw: It took me a long time to fix when I decided not to install it to the path as instructed in the wiki, the problem is, there is a document root setting in php.ini that needs to be updated too, after changing the root in lightttpd.conf 

```
opkg install \
coreutils-stat \
coreutils-mktemp \
git-http \
bzip2 \
php8-cgi \
php8-cli \
lighttpd-mod-fastcgi \
lighttpd-mod-access \
lighttpd-mod-expire \
lighttpd-mod-setenv \
php8-mod-ctype \
php8-mod-curl \
php8-mod-dom \
php8-mod-fileinfo \
php8-mod-gd \
php8-mod-iconv \
php8-mod-mbstring \
php8-mod-pcntl \
php8-mod-pdo \
php8-mod-pdo-sqlite \
php8-mod-session \
php8-mod-simplexml \
php8-mod-sqlite3 \
php8-mod-xml \
php8-mod-xmlwriter \
php8-mod-xmlreader \
php8-mod-openssl \
php8-mod-intl \
php8-mod-zip \
php8-fpm \ 
php8-mod-mysqli \
php8-mod-mbstring \
php8-pecl-redis  \
php8-mod-bcmath \
php8-mod-gmp \
php8-pecl-imagick \
php8-mod-filter \
imagemagick
```

**Comment by ryzhovau** [comment]
> I'm unable to get ssl working yet, because the current lighttpd package appears missing mod_openssl.so

Are you sure? 
https://github.com/Entware/Entware/issues/806

**Comment by Jishun** [comment]
yeah your are right. thanks, I'm able to install that mod now, I might have been trying with the old ng repo back and forth to mess this up while following the guide with php7

weird, I also came across some topic mentioning the mod_openssl should have been built in to lighttpd(ssl) while it is the `ssl` version. 

anyway, thanks,  the server is able to start with this installed now, yet not able to serve the content. I'll see what else I can find.

**Comment by ryzhovau** [comment]
Closing for now.

**Comment by muratyuceer** [comment]
Hi @Jishun

Hi, did you manage to get owncloud working? I have php8 problem like you..
