### ISSUE TITLE
Package update request NUT Network UPS Tools

### ISSUE THREAD

**Issue by TheBarista1** [Entware/Entware#803]
Would like to see a package update for NUT Network UPS Tools. 
Latest version 2.8 was released 2022-04-26. 
Previous NUT 2.7.4 was released 2016-03-09

https://networkupstools.org 
https://github.com/networkupstools/nut

**Comment by ryzhovau** [comment]
This package came from [upstream](https://github.com/openwrt/packages) with no changes. Please, send this issue to OpenWrt guys and new version will be there after next sync.
