### ISSUE TITLE
GNU Stow

### ISSUE THREAD

**Issue by HeyItsJono** [Entware/Entware#804]
I was hoping to have [GNU Stow](https://github.com/aspiers/stow) added for config and dotfile management if possible. Thanks!

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by The-BB** [comment]
please, test - http://bin.entware.net/mipselsf-k3.4/test/perl-stow_2.3.1-1_mipsel-3.4.ipk
