### ISSUE TITLE
mod_openssl.so appears to be missing from lighttpd package

### ISSUE THREAD

**Issue by sophtron** [Entware/Entware#806]
**Describe the bug**
According to what I searched and understood, this mod should be included in the default package,  it is missing in the version 8 package though, this made it impossible to setup https

**Environment (please complete the following information):**
 - Entware feed: armelsf-k26]
 - Device netgear r7000
 - Firmware version tomato

**Comment by ryzhovau** [comment]
`opkg install lighttpd-mod-openssl`
