### ISSUE TITLE
Package Update Request - NodeJS

### ISSUE THREAD

**Issue by IanE-Official** [Entware/Entware#807]
Would like to see a package update for NodeJS as LTS 14.x is no longer the active LTS version.
Latest Active LTS version 16.15.1 was released 2022-06-01.
Previous (Now Maintenance LTS) version 14.18.3-1 was released 2022-01-10.

https://nodejs.org/en/about/releases/
https://github.com/nodejs/node

Thank you for all of your had work and for your consideration of this request.

**Comment by ryzhovau** [comment]
[Done](https://github.com/Entware/entware-packages/commit/0e93bb72aa901620edd3fb53870c0f89bc2dd09d), binaries will arrive soon.
