### ISSUE TITLE
python-borgbackup doesn't work cause of missing python-msgpack

### ISSUE THREAD

**Issue by j1warren** [Entware/Entware#809]
**Describe the bug**
python-borgbackup

**Environment (please complete the following information):**
 - Entware feed: aarch64-k3.10
 - Device: Asus RT-AC86U router
 - Firmware version: asuswrt-merlin latest

```
# opkg install python3-borgbackup
Installing python3-borgbackup (1.2.0-1) to root...
Downloading https://bin.entware.net/aarch64-k3.10/python3-borgbackup_1.2.0-1_aarch64-3.10.ipk
Configuring python3-borgbackup.
# borg
Traceback (most recent call last):
  File "/opt/lib/python3.10/site-packages/borg/archiver.py", line 38, in <module>
  File "/opt/lib/python3.10/site-packages/borg/helpers/__init__.py", line 14, in <module>
  File "/opt/lib/python3.10/site-packages/borg/helpers/misc.py", line 16, in <module>
  File "/opt/lib/python3.10/site-packages/borg/helpers/msgpack.py", line 19, in <module>
ModuleNotFoundError: No module named 'msgpack'
```

**Comment by slackluis** [comment]
Same problem with QNAP TS-859U . 

[/opt/bin] # opkg --version
opkg version 2edcfad1bb9a32f31199d5842aa087b4d30ec6f5 (2022-01-09)

[/opt/bin] # uname -a
Linux QNAP 3.4.6 #1 SMP Fri Mar 4 20:19:54 CST 2022 x86_64 unknown

[/opt] # opkg install python3-borgbackup
Installing python3-borgbackup (1.2.0-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-borgbackup_1.2.0-1_x64-3.2.ipk
Installing zlib (1.2.12-1) to root...
Downloading http://bin.entware.net/x64-k3.2/zlib_1.2.12-1_x64-3.2.ipk
Installing libpython3 (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/libpython3_3.10.4-1_x64-3.2.ipk
Installing python3-base (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-base_3.10.4-1_x64-3.2.ipk
Installing libffi (3.4.2-2) to root...
Downloading http://bin.entware.net/x64-k3.2/libffi_3.4.2-2_x64-3.2.ipk
Installing libbz2 (1.0.8-1a) to root...
Downloading http://bin.entware.net/x64-k3.2/libbz2_1.0.8-1a_x64-3.2.ipk
Installing libtirpc (1.3.2-1) to root...
Downloading http://bin.entware.net/x64-k3.2/libtirpc_1.3.2-1_x64-3.2.ipk
Installing python3-light (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-light_3.10.4-1_x64-3.2.ipk
Installing python3-asyncio (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-asyncio_3.10.4-1_x64-3.2.ipk
Installing python3-email (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-email_3.10.4-1_x64-3.2.ipk
Installing python3-cgi (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-cgi_3.10.4-1_x64-3.2.ipk
Installing python3-pydoc (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-pydoc_3.10.4-1_x64-3.2.ipk
Installing python3-cgitb (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-cgitb_3.10.4-1_x64-3.2.ipk
Installing python3-codecs (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-codecs_3.10.4-1_x64-3.2.ipk
Installing python3-ctypes (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-ctypes_3.10.4-1_x64-3.2.ipk
Installing libgdbm (1.21-1) to root...
Downloading http://bin.entware.net/x64-k3.2/libgdbm_1.21-1_x64-3.2.ipk
Installing python3-dbm (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-dbm_3.10.4-1_x64-3.2.ipk
Installing python3-decimal (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-decimal_3.10.4-1_x64-3.2.ipk
Installing python3-distutils (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-distutils_3.10.4-1_x64-3.2.ipk
Installing python3-logging (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-logging_3.10.4-1_x64-3.2.ipk
Installing liblzma (5.2.5-3) to root...
Downloading http://bin.entware.net/x64-k3.2/liblzma_5.2.5-3_x64-3.2.ipk
Installing python3-lzma (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-lzma_3.10.4-1_x64-3.2.ipk
Installing python3-multiprocessing (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-multiprocessing_3.10.4-1_x64-3.2.ipk
Installing libncursesw (6.3-1a) to root...
Downloading http://bin.entware.net/x64-k3.2/libncursesw_6.3-1a_x64-3.2.ipk
Installing python3-ncurses (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-ncurses_3.10.4-1_x64-3.2.ipk
Installing libopenssl (1.1.1n-1) to root...
Downloading http://bin.entware.net/x64-k3.2/libopenssl_1.1.1n-1_x64-3.2.ipk
Installing ca-certificates (20211016-1) to root...
Downloading http://bin.entware.net/x64-k3.2/ca-certificates_20211016-1_all.ipk
Installing python3-openssl (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-openssl_3.10.4-1_x64-3.2.ipk
Installing libreadline (8.1-1) to root...
Downloading http://bin.entware.net/x64-k3.2/libreadline_8.1-1_x64-3.2.ipk
Installing python3-readline (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-readline_3.10.4-1_x64-3.2.ipk
Installing libsqlite3 (3370000-1) to root...
Downloading http://bin.entware.net/x64-k3.2/libsqlite3_3370000-1_x64-3.2.ipk
Installing python3-sqlite3 (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-sqlite3_3.10.4-1_x64-3.2.ipk
Installing python3-unittest (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-unittest_3.10.4-1_x64-3.2.ipk
Installing python3-urllib (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-urllib_3.10.4-1_x64-3.2.ipk
Installing libuuid (2.37.3-3) to root...
Downloading http://bin.entware.net/x64-k3.2/libuuid_2.37.3-3_x64-3.2.ipk
Installing python3-uuid (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-uuid_3.10.4-1_x64-3.2.ipk
Installing libexpat (2.4.7-2) to root...
Downloading http://bin.entware.net/x64-k3.2/libexpat_2.4.7-2_x64-3.2.ipk
Installing python3-xml (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-xml_3.10.4-1_x64-3.2.ipk
Installing python3 (3.10.4-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3_3.10.4-1_x64-3.2.ipk
Installing python3-pkg-resources (58.1.0-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-pkg-resources_58.1.0-1_x64-3.2.ipk
Installing python3-pyparsing (2.4.7-2) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-pyparsing_2.4.7-2_x64-3.2.ipk
Installing python3-six (1.16.0-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-six_1.16.0-1_x64-3.2.ipk
Installing python3-packaging (20.9-1) to root...
Downloading http://bin.entware.net/x64-k3.2/python3-packaging_20.9-1_x64-3.2.ipk
Installing libattr (2.5.1-3) to root...
Downloading http://bin.entware.net/x64-k3.2/libattr_2.5.1-3_x64-3.2.ipk
Installing libacl (2.3.1-3) to root...
Downloading http://bin.entware.net/x64-k3.2/libacl_2.3.1-3_x64-3.2.ipk
Installing libzstd (1.5.2-1) to root...
Downloading http://bin.entware.net/x64-k3.2/libzstd_1.5.2-1_x64-3.2.ipk
Installing zstd (1.5.2-1) to root...
Downloading http://bin.entware.net/x64-k3.2/zstd_1.5.2-1_x64-3.2.ipk
Configuring zlib.
Configuring libpython3.
Configuring python3-base.
Configuring libffi.
Configuring libbz2.
Configuring libtirpc.
Configuring python3-light.
Configuring python3-pyparsing.
Configuring python3-email.
Configuring python3-urllib.
Configuring python3-pydoc.
Configuring libattr.
Configuring libacl.
Configuring liblzma.
Configuring libzstd.
Configuring python3-cgi.
Configuring python3-cgitb.
Configuring python3-decimal.
Configuring python3-asyncio.
Configuring python3-codecs.
Configuring python3-ctypes.
Configuring libgdbm.
Configuring python3-dbm.
Configuring python3-distutils.
Configuring python3-logging.
Configuring python3-lzma.
Configuring python3-multiprocessing.
Configuring libncursesw.
Configuring python3-ncurses.
Configuring libopenssl.
Configuring ca-certificates.
Configuring python3-openssl.
Configuring libreadline.
Configuring python3-readline.
Configuring libsqlite3.
Configuring python3-sqlite3.
Configuring python3-unittest.
Configuring libuuid.
Configuring python3-uuid.
Configuring libexpat.
Configuring python3-xml.
Configuring python3.
Configuring python3-pkg-resources.
Configuring python3-six.
Configuring python3-packaging.
Configuring zstd.
Configuring python3-borgbackup.

[/opt] # borg 
Traceback (most recent call last):
  File "/opt/lib/python3.10/site-packages/borg/archiver.py", line 38, in <module>
  File "/opt/lib/python3.10/site-packages/borg/helpers/__init__.py", line 14, in <module>
  File "/opt/lib/python3.10/site-packages/borg/helpers/misc.py", line 16, in <module>
  File "/opt/lib/python3.10/site-packages/borg/helpers/msgpack.py", line 19, in <module>
ModuleNotFoundError: No module named 'msgpack'
