### ISSUE TITLE
Bird2 package version update request

### ISSUE THREAD

**Issue by hondaspb** [Entware/Entware#810]
Please update bird2, bird2c, bird2cl packages to the latest version 2.0.9 https://bird.network.cz/download/bird-2.0.9.tar.gz
Current version in entware is 2.0.8 which is about a year old.

**Comment by ryzhovau** [comment]
[Done](https://github.com/Entware/entware-routing/commit/ce301d44614146513435ea95aad3149ed5c2b1f7), binaries will arrive soon.
