### ISSUE TITLE
Enable TCP port reuse for trojan

### ISSUE THREAD

**Issue by lukefloyd** [Entware/Entware#814]
**Describe the solution you'd like**
Current trojan build disabled tcp port reuse.
https://github.com/Entware/rtndev/blob/master/trojan/Makefile#L40
-DENABLE_REUSE_PORT=OFF

tcp port reuse is helpful for multi-core system, can we enable it?

**Comment by ryzhovau** [comment]
Some of Entware targets do not support port reuse. So we leave it disabled for now.
