### ISSUE TITLE
request package for mips-all architecture profile

### ISSUE THREAD

**Issue by naveen1hot** [Entware/Entware#817]
hi team,
i'm using mips_24kc architecture. due to architecture mismatch unable to install packages. so kindly make mips_24kc packages or common mips architecture packages. thanks in advance

**Comment by zyxmon** [comment]
mips_24kc architecture is fully compatible with mips32.  you should know if your firmware is little endian or big endian. I guess it is le and you should use http://bin.entware.net/mipselsf-k3.4/ repo and appropriate installer.
