### ISSUE TITLE
[Package Request] git-lfs

### ISSUE THREAD

**Issue by Miladiir** [Entware/Entware#823]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.
Loved and hated by developers all around the world: Git Large File Storage.

https://github.com/git-lfs/git-lfs

I think it is fairly well known. It enables ~different~ *better* large file support for git.

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by The-BB** [comment]
please, test - http://bin.entware.net/mipselsf-k3.4/test/git-lfs_3.2.0-1_mipsel-3.4.ipk

**Comment by Miladiir** [comment]
Thanks!

Unfortunately I don't have anything with mipsel. One embedded device I own is a remarkable 2
```
root@reMarkable:~# uname -a
Linux reMarkable 5.4.70-v1.2.2-rm11x #1 SMP PREEMPT Fri Jun 17 11:31:49 UTC 2022 armv7l GNU/Linux
```
I could test this with it.

**Comment by The-BB** [comment]
You can find this package [here](http://bin.entware.net/armv7sf-k2.6/test/) or [here](http://bin.entware.net/armv7sf-k3.2/test/)

**Comment by Miladiir** [comment]
Works! Thank you.
