### ISSUE TITLE
Package update request NUT Network UPS Tools

### ISSUE THREAD

**Issue by FlipUberFlop** [Entware/Entware#826]
Would like to see a package update for NUT Network UPS Tools.
Latest version 2.8 was released 2022-04-26.
Previous NUT 2.7.4 was released 2016-03-09

https://networkupstools.org/
https://github.com/networkupstools/nut

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
This package came from [upstream](https://github.com/openwrt/packages/blob/master/net/nut/Makefile) with no changes. Please, send similar request to OpenWrt guys, re-newed package will came here after next sync.
