### ISSUE TITLE
napt66

### ISSUE THREAD

**Issue by geyee** [Entware/Entware#827]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

IPv6-IPv6 Network Address Port Translation, or upgrade ip6tables version with nat support.
the project url is https://github.com/mzweilin/napt66.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [x86-64 -kernel 3.4.6] and get a feedback about it.

**Comment by ryzhovau** [comment]
What's the killer feature of `napt66` in front of `tayga`?

**Comment by geyee** [comment]
> What's the killer feature of `napt66` in front of `tayga`?

Tayga is nat64, while napt66 is ipv6 nat66. IE, napt66 is IPv6 to IPv6 NAT (nat6), while taya is IPv6 to IPv4 translation. one is nat66, the other is nat64, they are in different direction on packets translation. Napt66 can help  devices behind the router or linux pc (kernel under 3.7) connect to IPv6 network if the gateway hava a public IPv6 address, while tayga couldn't.
As https://www.man7.org/linux/man-pages/man8/iptables.8.html said, "IPv6 NAT support is available since kernel 3.7.".
As [Linux IPv6 HOWTO (en)](https://mirrors.bieringer.de/Linux+IPv6-HOWTO/nat-netfilter6..html) said, "Since at least Linux kernel version 3.9.0 and using ip6tables since 1.4.18 also Network Address Translation (NAT) is usable". 

From the [issues 46](http://web.archive.org/web/20160326080704/https://code.google.com/p/napt66/issues/detail?id=46), one can download Makefile  [napt66.zip](http://web.archive.org/web/20160326080704/https://napt66.googlecode.com/issues/attachment?aid=460000000&name=napt66.zip&token=ABZ6GAdjJMY64WMeDCeJtVdcldEyQ_DKMg%3A1458979625057&id=46&mod_ts_token=ABZ6GAebo8CHIP9vv7on2_I4O4XBZk8_lQ%3A1458979625057) for openwrt. There is a third party napt66 [modified verison ](http://bbs.routerclub.com/forum.php?mod=attachment&aid=MjE0OTF8YzEwODJlOGZ8MTMyMjg5MTg2NHw2ODF8NDg5NTg%3D) via https://www.routerclub.com/blog-681-7134.html.

From https://github.com/hanwckf/rt-n56u/tree/master/trunk/user/napt66, we can get Makefile for rt-n56u router.

Thanks.

**Comment by ryzhovau** [comment]
Just figured out that is the kernel module.
To keep Entware firmware independent, we do not apply any kernel specific modules, sorry.
