### ISSUE TITLE
Package update request: Unrar

### ISSUE THREAD

**Issue by Kallek57** [Entware/Entware#828]
There is a bug in UNRAR 6.10 beta 3 that is currently used. It breaks direct unpack in sabnzbd. Can you please update Unrar to 6.10 stable.

https://forums.sabnzbd.org/viewtopic.php?t=25931&sid=3887265a1150eeb523330c6f1cac5d98

**Comment by ryzhovau** [comment]
This package came from [upstream](https://github.com/openwrt/packages/blob/master/utils/unrar/Makefile) with no changes. Please, address this issue to OpenWrt guys, new one will arrive here after next sync.
