### ISSUE TITLE
ncat segfaults when connecting to unix socket

### ISSUE THREAD

**Issue by dotted** [Entware/Entware#829]
**Describe the bug**
[ncat and ncat-ssl]: Bug is described upstream and has a [patch for 7.91](https://github.com/nmap/nmap/issues/2154#issuecomment-708882514): https://github.com/nmap/nmap/issues/2154

**Environment (please complete the following information):**
 - Entware feed: x64-k3.2
 - Device [QNAP TS-251D]
 - Firmware version [QTS 5.0.0.2055]

**Comment by zyxmon** [comment]
fixed via https://github.com/Entware/entware-packages/commit/7181624c0987436e80628b5901e86acd37e08d47
thanks for reporting and finding solution
