### ISSUE TITLE
Requesting PHP Module: MySQL

### ISSUE THREAD

**Issue by nobutyeahbutno** [Entware/Entware#83]
Package Requested: php-mysql or php-mysqli. I was originally on entware-ng had php mysql module installed all working well, i then did opkg update and opkg upgrade and i was updated to the new entware but it is missing the php mysql module and I am unable to access phpmyadmin or postfixadmin on my site :( I can attach screenshots of main pages for phpmyadmin and postfixadmin showing mysql module missing for php if requested.

I use ASUS-DSL-AC68U and uname -a returns:

asusxxxxxxx@xxxxxx:/tmp/mnt/xxxx/entware-ng.arm/root# uname -a

Linux xxxxxx.com 2.6.36.4brcmarm #.1 SMP PREEMPT Thu Mar 29 21:00:32 CST 2018 armv7l GNU/Linux

The multiple xxx is to remove my username and domain details from what is shown and # has a . added by me after and before the 1 to prevent linking to other issue. :)

**Comment by ryzhovau** [comment]
Please, install appropriate PHP module.
```
opkg list *mysql*
```

**Comment by nobutyeahbutno** [comment]
Thanks that worked. Had to remove php and modules then install mysql mod first followed by other php7 installs :) all working great now. Thanks once again.
