### ISSUE TITLE
[Package Request] mbim-utils

### ISSUE THREAD

**Issue by Nmzik** [Entware/Entware#832]
We've already have libmbim package. Please also add mbim-utils (which contains mbimcli  and mbim-network) to be able to establish a connection with LTE modems via MBIM protocol.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Done!
