### ISSUE TITLE
[Package Request] Coturn

### ISSUE THREAD

**Issue by Tokarak** [Entware/Entware#834]
**Describe the solution you'd like**
[See](https://github.com/coturn/coturn) for project. Coturn is an opensource TURN server. Entware does not yet have a turn server.

I am aware that turn severs in production environments are not to be run on embedded devices, but there is a perfectly good use case to utilise turn servers for personal use, in which case they do not use many resources. I need coturn for direct webrtc calls.

Official build instructions can be found [here](https://github.com/coturn/coturn/blob/master/rpm/build.instructions.txt). (edit: thats for RPM, my bad.)
- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform (Asuswrt-Merlin) and provide feedback about it.

**Comment by The-BB** [comment]
please, test - http://bin.entware.net/mipselsf-k3.4/test/coturn_4.5.2-4_mipsel-3.4.ipk

**Comment by Tokarak** [comment]
It runs perfectly (aarch64), as far as I can tell right now. I had to change proc-user in the default config, but thats not a problem. Further testing may be required, and I'll update this thread if I find anything. Thank you very much.
