### ISSUE TITLE
[Package Request] Byobu

### ISSUE THREAD

**Issue by blucey** [Entware/Entware#835]
Please add a package for byobu!

Byobu is a wrapper around tmux or screen that makes the interaction with those tools much easier, as well as adds additional features.

It can be found at:
https://launchpad.net/byobu
and:
https://github.com/dustinkirkland/byobu

My platform:
Linux [hostname redacted] 4.4.180+ #42661 SMP Mon Jun 27 15:08:06 CST 2022 x86_64 GNU/Linux synology_r1000_rs422+

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by The-BB** [comment]
please, test - http://bin.entware.net/x64-k3.2/test/byobu_5.133-1_all.ipk and http://bin.entware.net/x64-k3.2/test/byobu-utils_5.133-1_all.ipk (deps: http://bin.entware.net/x64-k3.2/test/libnewt_0.52.21-4_x64-3.2.ipk http://bin.entware.net/x64-k3.2/test/python3-newt_0.52.21-4_x64-3.2.ipk)

**Comment by blucey** [comment]
@The-BB  My apologies for missing this.  It looks to work perfectly.  It would be great if it could be added to the package list!
