### ISSUE TITLE
shntool patches (from debian project)

### ISSUE THREAD

**Issue by bayonne** [Entware/Entware#837]
The version of shntool supplied with entware cannot handle 24-bit flac files properly (on my Qnap NAS intel x86_64).

For example, I get this in response to ``shntool hash``:

`shntool [hash]: warning: unsupported format 0xfffe (Unknown) while processing file: [01. Walk On.flac]
`

A bug report mentions the issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950803

It turns out that a patch addresses this issue. It can be found at https://salsa.debian.org/debian/shntool/-/tree/master/debian/patches along with a few other patches.

**Comment by zyxmon** [comment]
Please check if this package fixes the problem - http://test.entware.net/x64-k3.2/shntool_3.0.10-3_x64-3.2.ipk

`opkg install http://test.entware.net/x64-k3.2/shntool_3.0.10-3_x64-3.2.ipk`

**Comment by bayonne** [comment]
Hello.,
I tried to shntool hash 24-bit flac files with this test package and it worked.

**Comment by zyxmon** [comment]
fixed via https://github.com/Entware/rtndev/commit/8b8e2e4e6eddb72bb3a817c295beef82159c4474
