### ISSUE TITLE
Could we get, Stubby and GetDNS updated to the last verssion ??

### ISSUE THREAD

**Issue by Alozaros** [Entware/Entware#839]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

Hi there I'm a DDWRT/Entware user,  I run Entware on mipsel, mips and arm platforms...so,
if we can get **Stubby and GetDNS** updated to their last version...please ??
Thanks in advance and keep doing the great job! 

https://github.com/getdnsapi/getdns/releases/tag/v1.7.2
https://github.com/getdnsapi/stubby/tree/d4eff9bf415a968b1849c99720d51af98a10bdee

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
We sync with OpenWrt upstream from time to time, but we leave their versions unchanged to simplify synchronization.
