### ISSUE TITLE
[Package Request] MicroPython 

### ISSUE THREAD

**Issue by ens4dz** [Entware/Entware#844]
MicroPython is a lean and efficient implementation of the Python 3, that includes a small subset of the Python standard library and is optimised to run on microcontrollers and in constrained environments.

https://openwrt.org/packages/pkgdata/micropython
https://github.com/micropython/micropython

- [x] No similar package already added
- [x] Package is in active development
- [x] I'm ready to test added package on my platform: **armv5tejl-2.6 legacy** and get a feedback about it.

**Comment by ryzhovau** [comment]
No plans to add it, sorry.
I see no use case for that while we are on full-blown glibc library.
