### ISSUE TITLE
[Package Request] testdisk

### ISSUE THREAD

**Issue by A13xund3r** [Entware/Entware#847]
Basically I'm looking for data recovery tool, I see there was extundelete request but it is abandoned, maybe after 3 years it is worth a second look.
Need for it arise when added second drive and Alt-F system formatted old and new disc when selected was only new.

[Testdisk](https://www.cgsecurity.org/wiki/TestDisk)

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
testdisk present here since Apr 14, 2021.
