### ISSUE TITLE
Rtorrent not installing  (PHP issue)

### ISSUE THREAD

**Issue by coolrags123** [Entware/Entware#849]
Hi There,

I had rtorrent running previously, but after merlin upgrades it stopped working. I tried uninstalling and installing again, but it gives me following errors.

admin@RT-AX3000-D8A0:/tmp/home/root# opkg install rtorrent-easy-install
Installing rtorrent-easy-install (0.2-6) to root...
Downloading https://bin.entware.net/armv7sf-k2.6/rtorrent-easy-install_0.2-6_armv7-2.6.ipk
Installing rutorrent-plugin-rpc (3.10-2) to root...
Downloading https://bin.entware.net/armv7sf-k2.6/rutorrent-plugin-rpc_3.10-2_armv7-2.6.ipk
Installing php8 (8.1.7-2) to root...
Configuring rutorrent-plugin-rpc.
Collected errors:
* check_conflicts_for: The following packages conflict with php8:
* check_conflicts_for:     php7 *
* opkg_install_cmd: Cannot install package rtorrent-easy-install.

Kindly advise and appreciate your efforts.

Using asus ax 3000 merlin latest fw

**Comment by ryzhovau** [comment]
Hey, @coolrags123! Looks like you've got some `php7-*` packages installed.
`php7` was completely replaced by `php8`, so it's time to get rid of them:

* get a list of installed  `php7-*` packages by `opkg list_installed php7*`,
* remove them by `opkg --force-depends php7*`,
* install php8-* package one by using list you've previously got,
* run `opkg upgrade` again.

The preferable way is to install Entware from scratch.
