### ISSUE TITLE
Package update request: dbus 1.14

### ISSUE THREAD

**Issue by MrDelik** [Entware/Entware#850]
Update Dbus to 1.14 to use it with home assistant via container.

Some improvements:
- dbus-send has added a "--sender" option that requests a name and will hold it until the signal has been sent.
- dbus-daemon now emits an "ActivatableServicesChanged" signal when the list of activatable services may have changed.
- dbus-daemon now filters messages that it relays in removing header fields that it does not understand.
- Support for disabling traditional/non-systemd service activation at build-time.
- GetConnectionCredentials() will now include Unix group IDs when running on Linux 5.13+ and a new enough Glibc.

Some build changes
- Requiring at least basic support for C99 variadic macros, which means GCC 3 or newer and all versions of Clang. In practice unless you are building DBus on some horribly old toolchain, you should be fine. Similarly, DBus now requires a C99-compatible va_copy() macro for non-Windows platforms.
- On the Microsoft Windows front, only Windows Vista and later are now supported.
- CMake 3.4 is now required for the build system support.

**Comment by ryzhovau** [comment]
This one came from OpenWrt upstream with no changes. We'll keep the same version as upstream to simplify syncing.
