### ISSUE TITLE
Compiling a Python package leads to the internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by ivankravets** [Entware/Entware#851]
**Describe the bug**
I've just formatted the flash card and re-installed Entware (the latest). It uses Python 3.10 and it is impossible to build any Python package. 
It seems to me that the compiler is broken.

For example, try to build the https://pypi.org/project/frozenlist/ package:

```
 frozenlist: internal compiler error: Segmentation fault
 ```

**Environment (please complete the following information):**
 - Entware feed:  mipselsf-k3.4
 - Device MI-R3G

**Comment by ryzhovau** [comment]
We provide native compilation with no any support.
https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation
