### ISSUE TITLE
new openssl - r and libopenssl-r is available

### ISSUE THREAD

**Issue by Alozaros** [Entware/Entware#852]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.
Hi Entware team,
Could we have the new updated **libopenssl - 1.1.1r**... , along with **getDNS** and **Stubby** as those are vital...for DNS security...
https://github.com/openssl/openssl 

Thanks in advance!

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Those versions are came from upstream with no changes.
