### ISSUE TITLE
[Package Request] kopia

### ISSUE THREAD

**Issue by barnumbirr** [Entware/Entware#856]
`kopia` is a cross-platform backup tool for Windows, macOS & Linux with fast, incremental backups, client-side end-to-end encryption, compression and data deduplication. CLI and GUI included. 

https://github.com/kopia/kopia

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
We've got several backup solution. What's the killer feature of this one?

**Comment by ryzhovau** [comment]
Done.
https://github.com/Entware/entware-go/commit/894711263542a50be40e46c41a00bc210bb569b8
