### ISSUE TITLE
[Package Request] newest build Igmpproxy

### ISSUE THREAD

**Issue by AfromD** [Entware/Entware#857]
~~The release version of igmpproxy 0.3 is discarding broadcasts to the router which I need forwarded to my Sonos players in another subnet.
After release, [Issue #54 was fixed ](https://github.com/pali/igmpproxy/commit/cfad33001fc5031399bdd073048ca86889378678)to change over from hardcoded blacklicting to explicit blacklisting. This commit no longer automtically discards the packets Sonos is sending out for device discovery.
Although the fix is more than a year old now, there is no new release version, so this fix is not in the entware repository version. I would appreciate to include a current build with this fix in the repository.~~

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by AfromD** [comment]
Release version 0.4 of igmpproxy has now been released. I would very much appreciate an update of the repo.
Thanks!

**Comment by AfromD** [comment]
I see the newest build is not included in the repo update,
I am willing to test 0.4. 
My platform is mipselsf-k3.4

**Comment by ryzhovau** [comment]
This package came from OpenWrt upstream with no any changes. So we'll keep the same version as in upstream to keep syncing process as simple as possible.
