### ISSUE TITLE
Easily fixable incompatibility between dstat 0.8.0 and Python 3.10

### ISSUE THREAD

**Issue by Lem970** [Entware/Entware#860]
**Describe the bug**
dstat 0.8.0 is not fully supporting Python 3.10. When launched:
`[...]File "/opt/bin/dstat", line 515, in show
     if isinstance(self.val[name], collections.Sequence) and not isinstance(self.val[name], six.string_types):
AttributeError: module 'collections' has no attribute 'Sequence'`

In Python 3.10 the chance to import `collections` has been completely dropped in favor of `collections.abc`.
Since Python 3.3 till Python 3.9 there had been just a warning.

To fix, simply do this. In the dstat.py directory:

`sed -i "s/import collections/import collections.abc/g"  dstat.py`
`sed -i "s/collections.Sequence/collections.abc.Sequence/g" dstat.py`

**Environment (please complete the following information):**

Entware feed: aarch64-k3.10

Bye.

**Comment by ryzhovau** [comment]
Works for now.
