### ISSUE TITLE
can‘t compile any software

### ISSUE THREAD

**Issue by lirise** [Entware/Entware#861]
I can't compile any software

I use the AX86U and installed entware . After that, I installed gcc make autoconf automake binutils etc. I wish I could complie some software I need, but I can't. when I run the ./confiugre --prefix=/opt received the following error:

Error: Invalid switch

*** Usage:
 dw/dh/db <physical address in hex> <number> 
 dw/dh/db <-k> <virtual address in hex> <number> 
 sw/sh/sb <physical address in hex> <data value1> <data value2> ..<data valueN> 
 sw/sh/sb <-k> <virtual address in hex> <data value1> <data value2> ..<data valueN> 
 fw/fh/fb  <physical address in hex> <data value> <length> 
 fw/fh/fb <-k> <virtual address in hex> <data value> <length> 
  -s (currently works with physical addresses for d*/s*/f* commands
and virtual addresses for s*/f* commands)

Error: Invalid switch

*** Usage:
 dw/dh/db <physical address in hex> <number> 
 dw/dh/db <-k> <virtual address in hex> <number> 
 sw/sh/sb <physical address in hex> <data value1> <data value2> ..<data valueN> 
 sw/sh/sb <-k> <virtual address in hex> <data value1> <data value2> ..<data valueN> 
 fw/fh/fb  <physical address in hex> <data value> <length> 
 fw/fh/fb <-k> <virtual address in hex> <data value> <length> 
  -s (currently works with physical addresses for d*/s*/f* commands
and virtual addresses for s*/f* commands)

/usr/sbin/sh: unrecognized option '--prefix=/opt'
Error: Invalid switch

*** Usage:
 dw/dh/db <physical address in hex> <number> 
 dw/dh/db <-k> <virtual address in hex> <number> 
 sw/sh/sb <physical address in hex> <data value1> <data value2> ..<data valueN> 
 sw/sh/sb <-k> <virtual address in hex> <data value1> <data value2> ..<data valueN> 
 fw/fh/fb  <physical address in hex> <data value> <length> 
 fw/fh/fb <-k> <virtual address in hex> <data value> <length> 
  -s (currently works with physical addresses for d*/s*/f* commands
and virtual addresses for s*/f* commands)

What should I do? How can I solve this error?

Thanks everyone !

**Comment by rampageX** [comment]
Use tomatoware: https://github.com/lancethepants/tomatoware/releases/tag/v5.0

**Comment by ryzhovau** [comment]
Can't provide personal support, sorry.
https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation

**Comment by lirise** [comment]
> Use tomatoware: https://github.com/lancethepants/tomatoware/releases/tag/v5.0

Thanks very mouch !

**Comment by lirise** [comment]
> Can't provide personal support, sorry.
> https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation

Thanks !  With this guidance, I successfully compiled the software .
