### ISSUE TITLE
 The zerotier in mipselsf-k3.4 has not been used normally since 1.4.6

### ISSUE THREAD

**Issue by csl0918** [Entware/Entware#865]
The zerotier in mipselsf-k3.4 has not been used normally since 1.4.6. It shows that when I have joined the network, I cannot ping other devices, so I have to drop to 1.4.6 to use it. Other users on zerotier's github website have provided solutions. It is OK to comment out 230-234 lines of code in ZeroTierOne/osdep/Linux EthernetTap.cpp file. For details, see 
#https://github.com/zerotier/ZeroTierOne/issues/1524#issuecomment-1052481604

Can I update it through the above? Thank you.

**Comment by ryzhovau** [comment]
«has not been used normally…» on ancient kernels, to be clearer.
This compatibility fix LGTM, but keep in mind, we plan to drop any support of old kernels in near future.
