### ISSUE TITLE
Any hope of getting some LaTeX distribution?

### ISSUE THREAD

**Issue by cesss** [Entware/Entware#867]
**Describe the solution you'd like**
I know a complete LaTeX is a huge package, but I just got a reMarkable 2 tablet, installed toltec on it, and found out that with toltec and entware I have almost everything I need for doing UNIX stuff on it while on travel... except for one thing: being able to compile my papers in LaTeX format.

So, have you considered if it would be possible to add some sort of LaTeX distribution, even if it's a minimalistic one?

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
I'm afraid, it's out of project goal. Sorry.
