### ISSUE TITLE
[Package request] php8-pecl-apcu

### ISSUE THREAD

**Issue by atbest** [Entware/Entware#870]
**Describe the solution you'd like**
Nextcloud recommends to use PECL [APCu](https://pecl.php.net/package/APCu) module to [improve performance](https://docs.nextcloud.com/server/25/admin_manual/configuration_server/caching_configuration.html), but it is not available currently. 

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. aarch64-k3.10] and get a feedback about it.

**Comment by ryzhovau** [comment]
Done! Binaries will be deployed soon.
