### ISSUE TITLE
Package Request libx265

### ISSUE THREAD

**Issue by LeftPinkie** [Entware/Entware#872]
Please create package for "libx265".

- [X] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
No plans to add it, sorry. We can't provide it on every Entware targets.
