### ISSUE TITLE
Please update rclone to the latest version

### ISSUE THREAD

**Issue by ksa-real** [Entware/Entware#873]
**Describe the solution you'd like**
Current `rclone` package has an issue with the dlna server: it has mistake in `urn:schemas-upnp-org:service:ContentDirectory:1#Browse` response. Devices that strictly check the schema fail to recognize the response (e.g. LG TV, KODI). The latest package doesn't have this issue.

**Comment by GwynethLlewelyn** [comment]
Let me add my own vote for this request :-)

@ksa_real in my case I usually cross-compile `rclone` from its Go source... because, well, sadly the Entware maintainers are lagging behind many, many versions...

**Comment by ksa-real** [comment]
Sure, I've done that.

**Comment by ksa-real** [comment]
Sure, I've done that. If anyone needs it:
```
git clone git@github.com:rclone/rclone.git
cd rclone
GOOS=linux GOARCH=arm64 go build
# replace with your own address / path
scp rclone admin@router.asus.com:12345:/tmp/mnt/USBSTICK/bin/
```
Note that rclone allows watching your videos directly from many sources (Google Drive, Amazon S3, WebDAV, ...) on your DLNA-supporting TV/Firestick/Google Chromecast/... without pre-downloading.
Just need to launch the "service" on your router:
```
#!/bin/sh
set -x
while true; do
  /tmp/mnt/USBSTICK/bin/rclone serve dlna --name rclone myremote: --addr=<YOUR IP>:8000 --read-only \
    --transfers=2 --config /opt/etc/rclone.config -v
done
```

**Comment by ryzhovau** [comment]
Done https://github.com/Entware/entware-go/commit/7d0acbbba871dbfa1a54770ebdb606d11de33b2d
