### ISSUE TITLE
Syncthing using incorrect home dir

### ISSUE THREAD

**Issue by bogdane** [Entware/Entware#875]
**Describe the bug**
[syncthing]: Both packages "syncthing - 1.20.3-1" and "syncthing_nohf - 1.20.3-1" have an "incomplete" /opt/etc/init.d/S92syncthing startup script, in the sense that ARGS are empty, but the script itself references /opt/etc/syncthing/, meaning this was the intended home dir for syncthing (which is perfectly OK).
Currently, due to empty ARGS, syncthing creates its config files under ~/.config/syncthing, generally under /root if run as root, which is really not recommended, as in some devices /root can be volatile.

To fix this the ARGS env var must not be empty in /opt/etc/init.d/S92syncthing, e.g.:
ARGS="--home=/opt/etc/syncthing"

I would have made a pull request myself but I cannot fin out where is the correct place to fix it.

**Environment (please complete the following information):**
 - Entware feed: unknown?
 - Device: Zyxel NAS542
 - Firmware version: V5.21(ABAG.9)

**Comment by zyxmon** [comment]
Not confirmed

```
/share/CACHEDEV1_DATA/.qpkg/Entware/root # syncthing
[start] 2022/12/10 18:17:45 INFO: syncthing v1.20.3 "Fermium Flea" (go1.18.4 linux-arm) papa@debian10 2022-07-27 16:41:18 UTC [noupgrade]
[start] 2022/12/10 18:17:45 INFO: Generating ECDSA key and certificate for syncthing...
[start] 2022/12/10 18:17:45 INFO: Default folder created and/or linked to new config
[start] 2022/12/10 18:17:45 INFO: Default config saved. Edit /opt/etc/syncthing/config.xml to taste (with Syncthing stopped) or use the GUI

```
