### ISSUE TITLE
Update ADB to latest version

### ISSUE THREAD

**Issue by Raicuparta** [Entware/Entware#876]
The available version of ADB is very outdated and missing important features. Could it be updated to the latest version?

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
This one came from OpenWrt with no changes. We keep the same version as in upstream to simplify syncing.
