### ISSUE TITLE
[Package request] .NET

### ISSUE THREAD

**Issue by pengweiqhca** [Entware/Entware#877]
**Describe the solution you'd like**

[.NET](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) support arm64, but I test it is not compatible on my asus AX86U.

`./dotnet: relocation error: /opt/lib/libpthread.so.0: symbol __sigtimedwait, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference`

Add .NET package or make glib compatible .NET.

[.NET libc compatibility](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#libc-compatibility).

**Comment by ryzhovau** [comment]
No plans to add it, sorry. We can't bring it on half of Entware targets.
