### ISSUE TITLE
New vitetris version on github

### ISSUE THREAD

**Issue by yoyoma2** [Entware/Entware#88]
Entware gets vitetris 0.57 from http://www.victornils.net/tetris/ but that page now says to get the latest version from github.

https://github.com/vicgeralds/vitetris

At the time of writing the vitetris version on github is 0.57.1

It would be preferable for Entware to get vitetris from github than from a no longer updated personal webpage.  There are no build changes to vitetris 0.57.1 so the transition to github should be straightforward.

**Comment by ryzhovau** [comment]
Done, binaries will arrive soon.

**Comment by yoyoma2** [comment]
Can confirm upgrading to the new "vitetris - 0.57.2-1" works great.  You entware guys rock!

**Comment by ryzhovau** [comment]
Thanks for feedback.
