### ISSUE TITLE
ipset v7.16: Cannot open session to kernel.

### ISSUE THREAD

**Issue by olsh** [Entware/Entware#882]
**Describe the bug**
When I can the following command
```
ipset create mylist hash:ip
```

I get the error mentioned in the title
```
ipset v7.16: Cannot open session to kernel.
```

**Environment (please complete the following information):**
 - Entware feed: mipselsf-k3.4
 - Device: Zyxel Keenetic Extra
 - Device firmware: v2.08(AANS.4)C2

I've also installed all the additional modules for the router
![image](https://user-images.githubusercontent.com/3613592/209918237-b8a51ce2-631a-42fe-a551-617e9986a710.png)

**Comment by ryzhovau** [comment]
Looks like kernel is too old. Just checked [that one](https://keenetic-gi.ga/2022/12/17/adguardhome-and-selective-routing.html ) on mipsel and aarch64 with no issues.
```
~ # opkg install ipset
...
~ # ipset -V
ipset v7.16, protocol version: 7
Warning: Kernel support protocol versions 6-6 while userspace supports protocol versions 6-7
~ # ipset create myipset hash:ip
~ # uname -a
Linux chewbacca 4.9-ndm-5 #0 SMP Thu Dec 22 16:05:14 2022 mips GNU/Linux
```

**Comment by olsh** [comment]
@ryzhovau thanks for the quick answer.
Are there any workarounds for this? Probably there is a way to install an older version of ipset?

**Comment by ryzhovau** [comment]
You may find any version of ipset ever been compiled for mipsel here http://bin.entware.net/mipselsf-k3.4/archive/

**Comment by olsh** [comment]
Welp, it looks like I have a super old router :)
The oldest version shows the same error:
```
ipset create myipset hash:ip
ipset v6.34: Cannot open session to kernel.
```

Thank you anyway! 👍🏻
