### ISSUE TITLE
yt-dlp not working

### ISSUE THREAD

**Issue by bloksma** [Entware/Entware#884]
yt-dlp_2022.9.1-1 not working. 

Traceback (most recent call last):
  File "/opt/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.9.1', 'console_scripts', 'yt-dlp')())
  File "/opt/bin/yt-dlp", line 25, in importlib_load_entry_point
    return next(matches).load()

Environment:
 - Entware feed: armv7sf-k2.6
 - Device: Zyxel NAS326

**Comment by zyxmon** [comment]
Some python packages are missing in dependencies. We will fix it later. Just run to fix manually
```
opkg install python3-logging
opkg install python3-uuid
```

**Comment by bloksma** [comment]
Package python3-logging (3.10.7-1) installed in root is up to date.
Package python3-uuid (3.10.7-1) installed in root is up to date.

I've tries to use --autoremove and reinstall python3 and yt-dlp, still not working.

**Comment by zyxmon** [comment]
It works on my hardware. Please show the full error log.

```
~ # uname -a
Linux ws880 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jun 17 15:39:25 MSK 2015 armv7l GNU/Linux
~ # yt-dlp

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by bloksma** [comment]
~ # uname -a
Linux NAS326 3.10.39 #1 Wed May 11 14:14:53 CST 2022 armv7l GNU/Linux
~ # yt-dlp
Traceback (most recent call last):
  File "/opt/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.9.1', 'console_scripts', 'yt-dlp')())
  File "/opt/bin/yt-dlp", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
~ #

**Comment by zyxmon** [comment]
You can remove Entware package and try to install yt-dlp manually with pip. Read here
https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip

**Comment by zyxmon** [comment]
and here
https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules
