### ISSUE TITLE
[Package Request] upmpdcli

### ISSUE THREAD

**Issue by Larouso163** [Entware/Entware#885]
Please add the upmpdcli package from openWRT. It is not part of the synced packages. 
https://github.com/openwrt/packages/tree/openwrt-21.02/sound/upmpdcli

It can act as an UPnP/DLNA interface to mpd, what in combination makes is possible to use one linux device as UPnP-Server as well as renderer -> perfectly suited if you want to use your machine for highRes Streaming when hooked to a DAC.

Thanks for looking into it. 
Best regards. 
Lars

**Comment by ryzhovau** [comment]
Done! I forgot to tell about it, sorry.
https://github.com/Entware/entware-packages/commit/f83f7440989976a02888733779b1f81737661e75
