### ISSUE TITLE
locales install failed: package "locales" preinst script returned status 1.

### ISSUE THREAD

**Issue by S-trace** [Entware/Entware#886]
locales_2.27-9

I'm trying to install Entware using [alternative.sh](https://bin.entware.net/mipssf-k3.4/installer/alternative.sh) installer.

When I run it, it fails with the following output:
```
Collected errors:
 * pkg_run_script: package "locales" preinst script returned status 1.
 * preinst_configure: Aborting installation of locales.
 * opkg_install_cmd: Cannot install package entware-opt.
cp: /opt/etc/passwd.1: No such file or directory
cp: /opt/etc/group.1: No such file or directory
cp: /opt/etc/shells.1: No such file or directory
```
Complete installer output: [install_output.txt](https://github.com/Entware/Entware/files/10418571/install_output.txt)

I checked the preinst script for locale package, it's very simple:
```
#!/bin/sh

if [ -x '/opt/bin/locale.new' ] && [ -z "$(/opt/bin/locale.new -V | grep 2.27)" ]; then
	echo 'locale-archive needs upgrade, deleting old one.'
	rm -f /opt/usr/lib/locale/locale-archive
fi
```
I'm doing a clean installation, and so I don't have /opt/bin/locale.new and /opt/usr/lib/locale/locale-archive

/bin/sh is a BusyBox v1.00 (2022.08.12-08:34+0000) Built-in shell (msh)
When I'm running this preinst script using system shell (/bin/sh) - it exits with code 1, but if I run it using opkg's /opt/bin/sh - it exits with code 0.
If I add `exit 0` at last line - script exits with code 0 on system sh.

Minimal reproducible example:
```
/opt # cat test.sh
if false; then
  true
fi
```
Results:
```
/opt # /bin/sh test.sh; echo $?
1

/opt # /opt/bin/sh test.sh; echo $?
0
```

Is it poissible to add `exit 0` to locales preinst script as workaround for firmwares with old busybox?

**Environment:**
 - Entware feed: `mips-3.4`
 - Device: `Iskratel RT-GM2-9`
 - Firmware version: `1.6.942`
 - Kernel version: `Linux RT-GM2-9 3.18.21 #6 SMP Fri Aug 12 16:33:43 CST 2022 mips unknown`

**Comment by ryzhovau** [comment]
Thanks for info. I think it worth to implement.
