### ISSUE TITLE
Busybox from entware breaks opkg downloads

### ISSUE THREAD

**Issue by pelepelin** [Entware/Entware#887]
**Describe the bug**
Busybox from entware breaks opkg downloads. Looks like busybox-wget does not support https.

**Environment (please complete the following information):**
 - Entware feed: ??? aarch64-k3.10
 - Device ASUS RT-AX86U
 - Firmware version ASUSWRT-Merlin RT-AX86U 388.1_0

As shown in the log below, sed (or any other package) is not installable if busybox is installed.

```
# opkg install sed
Installing sed (4.9-1) to root...
Downloading https://bin.entware.net/aarch64-k3.10/sed_4.9-1_aarch64-3.10.ipk
Configuring sed.
# opkg remove sed
Removing package sed from root...
# opkg install busybox
Installing busybox (1.35.0-3) to root...
Downloading https://bin.entware.net/aarch64-k3.10/busybox_1.35.0-3_aarch64-3.10.ipk
Configuring busybox.

[ snip ]

# opkg install sed
Installing sed (4.9-1) to root...
Downloading https://bin.entware.net/aarch64-k3.10/sed_4.9-1_aarch64-3.10.ipk
wget: not an http or ftp url: https://bin.entware.net/aarch64-k3.10/sed_4.9-1_aarch64-3.10.ipk
Collected errors:
 * opkg_download: Failed to download https://bin.entware.net/aarch64-k3.10/sed_4.9-1_aarch64-3.10.ipk, wget returned 1.
 * opkg_install_pkg: Failed to download sed. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package sed.
# opkg remove --force-removal-of-essential-packages busybox
Removing essential package busybox under your coercion.
        If your system breaks, you get to keep both pieces
Removing package busybox from root...
# opkg install sed
Installing sed (4.9-1) to root...
Downloading https://bin.entware.net/aarch64-k3.10/sed_4.9-1_aarch64-3.10.ipk
Configuring sed.
#
```

**Comment by zyxmon** [comment]
`Downloading https://bin.entware.net/aarch64-k3.10/sed_4.9-1_aarch64-3.10.ipk``

`opkg.conf` file does not have https links. You've modified (or some installation script not from Entware) it and wget applet from busybox cannot download https. temporary switch to http, run `opkg install wget-ssl`, switch back to https.
You can read more discussion on using https in Entware here in Issues and other places.
PS you can also just delete wget applet (Entware busybox) and not install wget from Entware.

**Comment by pelepelin** [comment]
Interesting. I definitely didn't touch `opkg.conf` and didn't run any scripts from Merlin's `amtm` except of entware installation.
Of course, first line of `opkg.conf` is
```
src/gz entware https://bin.entware.net/aarch64-k3.10
```
Might it be an inconsistency of amtm entware script with "no https" policy?

**Comment by pelepelin** [comment]
There's something in here

https://github.com/decoderman/amtm/blob/e03fe5317a03d47fa0fe92aecb97dad7a10611d9/amtm_modules/entware.mod#L16

and here

https://github.com/decoderman/amtm/blob/e03fe5317a03d47fa0fe92aecb97dad7a10611d9/amtm_modules/entware_setup.mod#L51

@decoderman FYI

**Comment by zyxmon** [comment]
Entware installation script must be a part of Merlin's firmware. Everything will work correctly until you replace wget with a version that does not support https. Just remove /opt/bin/wget symlink - this will fix https problem.
Original Entware scripts (and opkg.conf) are here - https://bin.entware.net/aarch64-k3.10/installer/

**Comment by pelepelin** [comment]
For reference.

https://github.com/Entware/Entware/wiki/Using-HTTPS-with-opkg
for alternative instructions

Conclusion for the moment, on Asuswrt-Merlin do either:
- don't use `amtm` script to install Entware (and use http)
- install Entware using `amtm` and don't ever install Entware `busybox` (therefore install coreutils packages for anything missing in built-in `busybox`)
- install Entware using `amtm` but link `/opt/bin/wget` to `/usr/sbin/wget` to prevent (?) accidental break if/when Entware `busybox` installed
- install Entware using `amtm` and install `wget-ssl` with `opkg install wget-ssl ca-certificates` to prevent accidental break if/when Entware `busybox` installed

**Comment by zyxmon** [comment]
This is not a great idea to use wget-ssl package. In case openssl is updated (it is updated before wget-ssl) wget-ssl stops to work and cannot update itself.
One more option

- install Entware using amtm and change https to http in opkg.conf )))

**Comment by pelepelin** [comment]
> In case openssl is updated (it is updated before wget-ssl) wget-ssl stops to work and cannot update itself.

Then it should be noted on https://github.com/Entware/Entware/wiki/Using-HTTPS-with-opkg
