### ISSUE TITLE
Package Request : Nodogsplash

### ISSUE THREAD

**Issue by FilipoMoake** [Entware/Entware#89]
Dear all,

A package request please : Nodogsplash

---
Nodogsplash
(http://nodogsplash.readthedocs.io/en/latest/overview.html)
(https://github.com/nodogsplash/nodogsplash)

"Nodogsplash offers a solution to this problem: You want to provide controlled and reasonably secure public access to an internet connection; and while you want to require users to give some acknowledgment of the service you are providing, you don’t need or want the complexity of user account names and passwords and maintaining a separate database-backed authentication server. "

- No similar package already added and/or this one got some new killer feature(s),
- Package is in active development, 
- Package already exist on other deposits (for example : https://github.com/Entware/entware-ng-routing) 
---

I would like to use it on my RT-AC68U

Many thanks to you in advance,

Kind regards

**Comment by ryzhovau** [comment]
No plans to add any captive portals, sorry. It requires too firmware specific implementations.
