### ISSUE TITLE
'>>' instead of '>' in the Installation script on the Zyxel NAS 542

### ISSUE THREAD

**Issue by vladimirvanchytsky** [Entware/Entware#890]
Please use ">>" instead of ">" in the Installation script on the Zyxel NAS 542, in part
`echo entware > /i-data/.system/zy-pkgs/USRPKG_DEPS_START`
becaus of possibility of another user scripts inicialization already exists there, just like you do it in shutdown part:
`echo sdentware >> /i-data/.system/zy-pkgs/USRPKG_DEPS_SHUTDOWN`

Thank you for your long-term great efforts!!

**Comment by zyxmon** [comment]
We have not published any scripts for Zyxel NASes. If you want to fix wiki section - you can do it yourself.
