### ISSUE TITLE
Nordlynx

### ISSUE THREAD

**Issue by hansw1969** [Entware/Entware#892]
Having a entware nordlynx package in repository which enables different routers to use this advanced wirequard (nordlynx) protocoll.
https://support.nordvpn.com/General-info/1438624372/What-is-NordLynx.htm
https://nordvpn.com/de/blog/nordlynx-protocol-wireguard/

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X ] Package is in active development (at least, not abandoned for 5 years or more),
- [X ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

i would test it on my netgear r9000 router flashed with dd-wrt firmware, and maybe as well on some of my Gli Routers

**Comment by ryzhovau** [comment]
No plans to add it, sorry.
