### ISSUE TITLE
generic installer results in failure to download opkg, cascades to "cannot install entware-opt"

### ISSUE THREAD

**Issue by rushowr** [Entware/Entware#895]
When running the generic installer script (following the instructions given at [Install on TomatoUSB and FreshTomato](https://github.com/Entware/Entware/wiki/Install-on-TomatoUSB-and-FreshTomato#entware-on-freshtomato-and-other-tomatousb-forks) ), the following occurs:

1. The download of [opkg_2022-02-24-d038e5b6-1_armv7-2.6.ipk](http://bin.entware.net/armv7sf-k2.6/opkg_2022-02-24-d038e5b6-1_armv7-2.6.ipk) fails with wget message: `wget: bad address 'bin.entware.net'`.
2. The installer continues on, configuring libgcc, libc, libssp, etc
3. grep kicks out an error (likely one that is supposed to occur?) `grep: /opt/etc/profile: No such file or directory`. As stated, I do not believe this particular item is an issue, but putting in here for complete reporting's sake.
4. install script continues on without issue until after `Configuring findutils`, when the following is displayed:
```
Collected errors:
 * opkg_download: Failed to download http://bin.entware.net/armv7sf-k2.6/opkg_2022-02-24-d038e5b6-1_armv7-2.6.ipk, wget returned 1.
 * opkg_install_pkg: Failed to download opkg. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package entware-opt.
Info: Congratulations!
Info: If there are no errors above then Entware was successfully initialized.
```
Running `opkg update` manually followed by `opkg install entware-opt` resolves the issue.
[entware-opt]: fails to install using the arm7sf-k2.6 generic installer at the address given at the instruction page above. 
To reproduce, use the above referenced installer script to attempt installation of Entware.

**Environment:**
 - Entware feed: armv7sf-k2.6
 - Device: Netgear R8000
 - Firmware version: FreshTomato Version 2022.7

**Comment by zyxmon** [comment]
It looks like an issue with dns settings/internet connection on your device. May be an issue with wget on your firmware.
