### ISSUE TITLE
Entware - xmllint package request - Synology NAS DS920+ - OPKG

### ISSUE THREAD

**Issue by C0nw0nk** [Entware/Entware#896]
I can't seem to find a xmllint package with `opkg`

On linux i use this package. `apt -y install libxml2-utils`

But with entware on a `Synology NAS DS920+` i can not seem to find a working package.

This is irrelevant but il share my setup anyway.

https://gist.github.com/C0nw0nk/7e762cba9aa0e7eee41744d51bf19c5d

**Comment by ryzhovau** [comment]
`opkg install libxml2-utils`
