### ISSUE TITLE
Installer downloads files over plain HTTP protocol

### ISSUE THREAD

**Issue by cunlem** [Entware/Entware#898]
https://bin.entware.net/aarch64-k3.10/installer/generic.sh

```sh
echo 'Info: Opkg package manager deployment...'
URL=http://bin.entware.net/${ARCH}/installer
wget $URL/opkg -O /opt/bin/opkg
```
Is this intentional? Perhaps it can be changed to `https`

**Comment by ryzhovau** [comment]
https://github.com/Entware/Entware/wiki/Using-HTTPS-with-opkg

**Comment by cunlem** [comment]
I see. Why is it a opt in feature? Are there many devices with not TLS-enabled wget?

**Comment by ryzhovau** [comment]
Sure. There's a lot of embedded devices with primitive base linux system.
