### ISSUE TITLE
Request for: hardlink

### ISSUE THREAD

**Issue by herrold** [Entware/Entware#9]
### Package: hardlink

congratulations on the merger

For new package to be added:

- make sure there's no similar package already added,

none known

- describe killer features of new package,

reduces space consumed by  bitwise identical files with hard links

 The maintainer thinks it is useful for Linux kernel developers, but it is a 'general' de-duplication solution within a single file-system

I use it heavily for mirroring of Source packages generally, which have great commonality, so much sacing results

- make sure it's open source and not abandoned (at least for last 5 years or so),

it is current and in maintenance
upstream maintainer page: https://pagure.io/hardlink

upstream GIT: https://pagure.io/hardlink.git

The package in in active maintenance, last git commit Aug 19 2017 per Changelog

- please, use native compilation for additional PHP, Perl, Ruby, Python modules for non-MIPS platforms.

N/A -- it is C code and a man page

### Platform:

- please, tell us what feed and\or devices are you using.

http://pkg.entware.net/binaries/armv7/Packages.gz

- be ready to check issue-related  changes or it will be closed after 30 days with "no response" status.

I follow GitHub each weekday, watch for notifications,  and try to clear issues promptly

**Comment by ryzhovau** [comment]
```
Summary:	Create a tree of hardlinks
```
Looks like a simple script over `ln` command to compare number of directories. Not sure there is sense to add such trivial things, sorry.
