### ISSUE TITLE
[Package Request] inotify-tools ( to limit directory size )

### ISSUE THREAD

**Issue by nwaizer** [Entware/Entware#902]
I am running a FTP server, and want to limit the maximum size of the directory.
I ask to add the [inotify-tools](https://github.com/inotify-tools/inotify-tools/wiki) which
is a C library and a set of command-line programs for Linux providing a simple interface to [inotify](http://en.wikipedia.org/wiki/Inotify)
This will allow me to remove the last written file, when a new file appears.

- [ X] No similar package already added and/or this one got some new killer feature(s),
- [ X] Package is in active development (at least, not abandoned for 5 years or more),
- [ X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

Thanks to how ever assist me with this.
Niv

**Comment by zyxmon** [comment]
Entware has inotify-tools packages that is split into inotifywatch, inotifywait and a library.
