### ISSUE TITLE
Transmission 4.0.0

### ISSUE THREAD

**Issue by jun6lee** [Entware/Entware#906]
Could we look to add the newer transmission 4.0.0 released a couple of weeks back?
https://github.com/transmission/transmission/releases/tag/4.0.0

**Comment by g0blin-NN** [comment]
4.0.3
https://github.com/transmission/transmission/releases/latest

**Comment by ryzhovau** [comment]
4.0.0 was known as unstable. We'll give it a second try. 
What feed are you on? x64 or arm?

**Comment by jun6lee** [comment]
x64

**Comment by ryzhovau** [comment]
Done. Binaries will arrive on weekend.
https://github.com/Entware/entware-packages/commit/c4b37b30b30ac49fb79b696863afdbd47678d630

**Comment by juvenn** [comment]
Such a smooth upgrade, and it works great on my aarch64 device. Thank you @ryzhovau !
