### ISSUE TITLE
Use /ent (or another directory) instead of /opt

### ISSUE THREAD

**Issue by NiQ1** [Entware/Entware#910]
I've run multiple times into issues where Entware cannot be installed because /opt is already used by the device's OEM firmware, in which case there's a serious risk of Entware installation itself or a package overwriting existing files, potentially bricking the device.

I'm aware that doing this might be painful, but I suggest that on the next major version have the installation directory changed to "/ent" or something else that is unlikely to already exist.

**Comment by zyxmon** [comment]
/opt is hardcoded in Entware. It is used in dynamic loader and rpath. In your case you can use chroot installation to any directory, as described here - https://forums.zyxmon.org/viewtopic.php?f=5&t=5797 (Russian). In case you need special busybox for your architecture - please inform.
