### ISSUE TITLE
[Package Request] snowflake-client

### ISSUE THREAD

**Issue by dartraiden** [Entware/Entware#911]
This will be very useful for Tor users in Russia, where access to entry nodes is blocked, so users are forced to use bridges. Right now the only option for Entware users is to use obfs bridges (`obfs4` package). `snowflake-client` package contains the Snowflake client which provides the Snowflake bridge to Tor. Snowflake is more convenient because it does not require changing bridge IPs in the torrc as they stop working (for example, if the obfs bridge has stopped working or is blocked).

**Comment by zyxmon** [comment]
What feed (architecture) package can you test? Makefile is ready.

**Comment by dartraiden** [comment]
mipselsf-k3.4

**Comment by dartraiden** [comment]
Just tested it — works great, thanks!

/opt/etc/torrc:
```
UseBridges 1

ClientTransportPlugin snowflake exec /opt/bin/snowflake-client \
-url https://snowflake-broker.torproject.net.global.prod.fastly.net/ \
-front cdn.sstatic.net \
-ice stun:stun.voip.blackberry.com:3478,stun:stun.altar.com.pl:3478,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.sonetel.net:3478,stun:stun.stunprotocol.org:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478

Bridge snowflake 192.168.1.1:1
```
