### ISSUE TITLE
bind-server with support for statistics

### ISSUE THREAD

**Issue by cthu1hoo** [Entware/Entware#916]
Would it be possible to either rebuild bind-server with support for statistics channel (this requires libxml2 & libjson2) or maybe add a separate package with this feature enabled?

Prometheus bind exporter uses this feature, having it would really improve monitoring for bind instances running on Entware.

- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

I'm using Entware on several Keenetic routers (mips).

edit: I found a similar issue for OpenWRT - https://github.com/openwrt/packages/issues/5090 - maybe this would help.

**Comment by ryzhovau** [comment]
Bind came from OpenWrt with no changes. We'll keep it in current state to simplify syncing process.
