### ISSUE TITLE
[Package Request] frp a revers proxy server 

### ISSUE THREAD

**Issue by sconan32** [Entware/Entware#917]
Please consider adding the reverse proxy package.

https://github.com/fatedier/frp
A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet.

My router is  asus ax86u.  (aarch64-k3.10)

Thank you.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by zyxmon** [comment]
http://zyxnerd.zyxmon.org/files/frp-go_0.48.0-1_aarch64-3.10.ipk
test and report back plz

**Comment by sconan32** [comment]
Thank you. 
it works fine.

**Comment by zyxmon** [comment]
https://github.com/Entware/entware-go/commit/fb5d2ad4796f1f7e9c8585254517b87cedc8aad6
