### ISSUE TITLE
mc show error when i try run a command

### ISSUE THREAD

**Issue by EugenSoloviov** [Entware/Entware#918]
When i try run a command in mc, mc shows error message:
"The shell is alredy running a command"

[package name]: mc (Midnight Commander)

**Environment (please complete the following information):**
 - Entware feed: [e.g. mipselsf-k3.4]
 - Device [ Zyxel Keenetic Ultra II router]
 - Firmware version [3.4.3.9L-101_289c95a  (Padavan & N56U project community & Linaro & Alxdm) ]

**Comment by EugenSoloviov** [comment]
This bug may solve by mc version downgrade.
For solving on my Zyxel Keenetic Ultra II, was executed following commands:


cd /media/Main

wget http://bin.entware.net/mipselsf-k3.4/archive/mc_4.8.26-1b_mipsel-3.4.ipk

opkg install /media/Main/mc_4.8.26-1b_mipsel-3.4.ipk --force-downgrade

ln -s /media/Main/opt/lib/libmbedcrypto.so.7 /media/Main/opt/lib/libmbedcrypto.so.3

**Comment by ryzhovau** [comment]
https://github.com/Entware/Entware/wiki#%EF%B8%8F-package-upgrade-notes

**Comment by ryzhovau** [comment]
Can't reproduce it on x64 or aarch64. Looks like device-specific bug.
