### ISSUE TITLE
Suggested improvement to rtndev/entware-opt/files/rc.func

### ISSUE THREAD

**Issue by atx32** [Entware/Entware#919]
When rc.func is called for a package that uses multiple processes (i.e. $PROC contains a space delimited list) the logger and echo commands use $DESC and the user cannot tell which individual process is being acted upon.

By replacing $DESC with $PROC as shown in the patch file, the user will see for each loop the exact process that is being started, stopped, or checked.

[rc.func.patch](https://github.com/Entware/Entware/files/11024182/rc.func.patch)

**Comment by ryzhovau** [comment]
You can separate several instances of the same binary process by $DESC. So we leave it as is.

**Comment by atx32** [comment]
It's great that this is possible with $DESC, but I cannot see how to do that. Can you share an example? Thanks.

**Comment by ryzhovau** [comment]
Sorry for keeping you waiting. We just finished another massive update.

The only example I can remember is about dnscrypt-proxy. When users wants to keep two instances of dnscrypt daemon, they make a symlink (like `ln -s /opt/sbin/dnscrypt-proxy /opt/sbin/dnscrypt-proxy2`) and create separate start script with their own $DESC/$PROC values. So, you can separate processes by its name in system log (dnscrypt-proxy and dnscrypt-proxy2).

If I browse syslog, I see binary file name as the source of record in most cases. So, why we should change it to $DESC? I'm afraid, I don't understand:(

**Comment by atx32** [comment]
I apologize for taking this long to add more information.

In my case, the issue occurs with samba4-server and the S91smb script. This file doesn't make use of rc.func but instead has its own routines for starting and stopping both smbd and nmbd. The problem is that it doesn't implement all the commands from rc.func such as "check" (and it also uses "reload" instead of "reconfigure".) As I needed the "check" function, I created my own script that used rc.func calls like what is provided with other Entware packages. Since the samba4-server needs to start both smbd and nmbd, I included a line like this:

`PROCS="smbd nmbd"`

This way both daemons are started when you execute:

`./S91smb start`

This is when you get the issue I tried to describe in the bug report. Syslog shows:
```
Starting smbd nmbd... done.     <-really just smbd
Starting smbd nmbd... done.     <-really just nmbd
```
This is what led me to patch rc.func so that each line in syslog shows the specific process being started, stopped, checked, etc.

For my use there is an issue with the S91smb script, but a complete solution using rc.func capabilities also needs a patch to rc.func itself. I hope this makes sense. I had proposed the update to rc.func in this report as I thought the change would be useful to all, but I guess I should also propose a change to the S91smb script in a separate issue report.

**Comment by atx32** [comment]
I also added an additional change to support "status" and "reload" in addition to the existing commands "check" and "reconfigure" since I see packages using different commands in their own scripts. Seemed like a good enhancement.

[rc.func.patch (updated)](https://github.com/Entware/Entware/files/12449944/rc.func.patch)

**Comment by ryzhovau** [comment]
> Since the samba4-server needs to start both smbd and nmbd, I included a line like this:

Usually, we've got separate script for each daemon instread.

**Comment by atx32** [comment]
I understand that, however the samba package was already using one script to start the two separate daemons (just not using the available rc.func calls.) The rc.func script already supports starting multiple processes.

`for PROC in $PROCS; do
`

I was just trying to use the common code in rc.func instead of creating something unique for each package's start/stop script. That's what led to the changes I proposed to provide better log feedback.

In any case, it is your call if the changes are beneficial to your project.
