### ISSUE TITLE
Last updates seems to break symlinks (and Samba)

### ISSUE THREAD

**Issue by TCB13** [Entware/Entware#92]
Hello,

First of all many thanks fro maintaining this project. It is very, very useful. Now, I've been using entware on a Netgear R7000 and everything was working fine until I decided to run `opkg update; opkg upgrade` last week.

Samba3.6 stopped working right on that moment. I couldn't connect to the server, however it was running. Did some digging into the log files and... found this:
``````
smbd main failed to setup system user info
``````

I'm not sure what package got updated and messed this up however, I also found that the ` /opt/etc/passwd` symlink disappeared. It should be there since:  `in standard case /opt/etc/passwd is a symlink to /etc/passwd file.`

I fixed this issue manually by:
``````
ln -s /etc/passwd /opt/etc/passwd
ln -s /etc/group /opt/etc/group
``````

Now the error above is gone. Why are the symlink gone? I also tried to install `shadow*` to fix symlink before trying to manually create them and it didn't work.

**Comment by TCB13** [comment]
**Update**: Samba is not working after reboot, however... why did symlinks disappear? Is my fix okay?

**Comment by zyxmon** [comment]
What was repo url was before update and after update? Probably you are in the middle of converting Entware-ng to Entware. Please post more info about your hardware(feed) and opkg upgrade log.
http://bin.entware.net/Readme.txt

**Comment by TCB13** [comment]
@zyxmon thanks for the answer. I'm not sure what URL your talking about, is it the one at `/opt/etc/opkg.conf`? If so: ` http://bin.entware.net/armv7sf-k2.6` before and after.

Unfortunately I don't have the terminal log from the upgrade. But I do have another device, same hardware and entware where I didn't run the upgrade yet. Probably running what I had on the other system, since I've installed the both devices on the same day.

Here is a diff of the packages in the system not updated (left) and the updated one (right): https://www.diffchecker.com/qRvlTuK9 is this helpful? entware looks the same.

Info on the device:

- Hardware: Netgear R7000
- Firmware/kernel: Linux Swift 4.4.109-rc1 #482 SMP Wed Jan 3 15:42:11 CET 2018 armv7l DD-WRT

**Comment by zyxmon** [comment]
Why have you installed Entware for old kernel? For your kernel you can use armv7sf-k3.2 feed.
I cannot tell what went wrong with Entware upgrade in your case without log. We have no similar reports.
You can save your current Entware in another folder and reinstall using appropriate script from - https://github.com/Entware/Entware/wiki/Alternative-install-vs-standard
You can move package configuration files to the new installation.
Please note that `/opt/etc/passwd` is a symlink for standard installation and a regular file for alternative one.

**Comment by TCB13** [comment]
Just a note, I decided to update the other device in similar conditions and I didn't get this error. Everything went just fine.
```````````
root@Stardust:~# cat /opt/etc/opkg.conf
src/gz entware http://bin.entware.net/armv7sf-k2.6

root@Stardust:~# uname -a
Linux Stardust 4.4.124 #548 SMP Wed Mar 28 09:52:34 CEST 2018 armv7l DD-WRT

root@Stardust:~# opkg update
Downloading http://bin.entware.net/armv7sf-k2.6/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
root@Stardust:~# opkg upgrade
Upgrading transmission-daemon-openssl on root from 2.93-7 to 2.94-1...
Downloading http://bin.entware.net/armv7sf-k2.6/transmission-daemon-openssl_2.94-1_armv7-2.6.ipk
Upgrading transmission-web on root from 2.93-7 to 2.94-1...
Downloading http://bin.entware.net/armv7sf-k2.6/transmission-web_2.94-1_armv7-2.6.ipk
Configuring transmission-daemon-openssl.
Configuring transmission-web.
Collected errors:
 * resolve_conffiles: Existing conffile /opt/etc/transmission/settings.json is different from the conffile in the new package. The new conffile will be placed at /opt/etc/transmission/settings.json-opkg.
```````````
So I'm closing this. Thank you very much.
