### ISSUE TITLE
lighttpd-mod-usertrack version mismatch

### ISSUE THREAD

**Issue by nearPath** [Entware/Entware#921]
The lighttpd version is 1.4.69-1 after update, but lighttpd-mod-usertrack version is still 1.4.65-1. The plugin-version doesn't match lighttpd version, the initialization of plugin failed, lighttpd goes down. Please update lighttpd-mod-usertrack.

Output of "opkg list lighttpd*"

lighttpd - 1.4.69-1 - A flexible and lightweight web server
lighttpd-mod-access - 1.4.69-1 - Access restrictions module
lighttpd-mod-accesslog - 1.4.69-1 - Access logging module
lighttpd-mod-alias - 1.4.69-1 - Directory alias module
lighttpd-mod-auth - 1.4.69-1 - Authentication module
lighttpd-mod-authn_file - 1.4.69-1 - File-based authentication module
lighttpd-mod-authn_ldap - 1.4.69-1 - LDAP-based authentication module
lighttpd-mod-cgi - 1.4.69-1 - CGI module
lighttpd-mod-deflate - 1.4.69-1 - Compress dynamic output module
lighttpd-mod-evhost - 1.4.69-1 - Enhanced Virtual-Hosting module
lighttpd-mod-expire - 1.4.69-1 - Expire module
lighttpd-mod-extforward - 1.4.69-1 - Extract client module
lighttpd-mod-fastcgi - 1.4.69-1 - FastCGI module
lighttpd-mod-magnet - 1.4.69-1 - Magnet module
lighttpd-mod-openssl - 1.4.69-1 - TLS using openssl module
lighttpd-mod-proxy - 1.4.69-1 - Proxy module
lighttpd-mod-redirect - 1.4.69-1 - URL redirection module
lighttpd-mod-rewrite - 1.4.69-1 - URL rewriting module
lighttpd-mod-rrdtool - 1.4.69-1 - RRDtool module
lighttpd-mod-scgi - 1.4.69-1 - SCGI module
lighttpd-mod-setenv - 1.4.69-1 - Environment variable setting module
lighttpd-mod-simple_vhost - 1.4.69-1 - Simple virtual hosting module
lighttpd-mod-ssi - 1.4.69-1 - SSI module
lighttpd-mod-status - 1.4.69-1 - Server status display module
lighttpd-mod-userdir - 1.4.69-1 - User directory module
**lighttpd-mod-usertrack - 1.4.65-1**
lighttpd-mod-vhostdb - 1.4.69-1 - Virtual Host Database module
lighttpd-mod-webdav - 1.4.69-1 - WebDAV module
lighttpd-mod-wstunnel - 1.4.69-1 - Websocket tunneling module

**Comment by zyxmon** [comment]
lighttpd-mod-usertrack was  removed in the previous Entware upgrade in 2022.
