### ISSUE TITLE
request for mt-st

### ISSUE THREAD

**Issue by AnthraX1** [Entware/Entware#922]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

https://github.com/iustin/mt-st

mt and stinit, used for dealing with Linux-specific tape-drive handling.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
I think the number of users of embedded devices with SCSI tape drives is near to zero.
Won't add it for now, sorry.

May be I missing some cool use case for it. Let me know if so.

**Comment by AnthraX1** [comment]
> I think the number of users of embedded devices with SCSI tape drives is near to zero. Won't add it for now, sorry.
> 
> May be I missing some cool use case for it. Let me know if so.

entware is not only used on embedded devices. Many people like me install it on NAS such as QNAP devices which have PCIE/ SCSI ports

**Comment by ryzhovau** [comment]
It's out of project goal, sorry.
