### ISSUE TITLE
request maturin supported for homeassistant

### ISSUE THREAD

**Issue by WaveBird** [Entware/Entware#923]
Hi, I would like to install homeassistant in my Netgear R7000 and it ran into   error: can't find Rust compiler while installing and it came from thecompiling of maturin, I hope someone can help me with this or give a hints, thanks a lot.

**Comment by ryzhovau** [comment]
We do not provide personal support here, sorry.

https://github.com/Entware/Entware/issues/863

**Comment by ryzhovau** [comment]
Rust packages has been added, including this one. Binaries will arrive soon
