### ISSUE TITLE
[Package Request] "opkg-web" [Web Manager for OPKG]

### ISSUE THREAD

**Issue by Twincam99** [Entware/Entware#924]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

I just upgraded FreshTomato [to v2023.2] on a test router and took the opportunity to install Entware. I use Optware on my "Live" routers and I know that is well past its "sell by" date. The Entware installation went smoothly and I installed nano and htop to confirm everything was OK.

I then searched for an opkg equivalent to "[ipkg-web](https://github.com/Optware/Optware/blob/master/make/ipkg-web.mk)" [**very** old and, I note, outside the 5 year "Development Window"!] but was unable to locate one. Are there plans to produce such a tool for opkg? I'd be delighted to test [armv7l] and provide feedback where possible but I'm no expert.

I really liked the features offered by "ipkg-web" and I think other opkg Users may appreciate it too. [Here](http://www.pembo.co.uk/2008/08/21/ipkg-web/) is a good visual representation of what it looks like. Thanks.

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
opkg stays CLI-only solution, sorry.
Any WebUI implementation can crash upon `opkg update`.
Consider using web terminal like `shellinabox`.
