### ISSUE TITLE
[Package Request] Youtube-uploader

### ISSUE THREAD

**Issue by zetaooreticuli** [Entware/Entware#925]
Hello!
Is it possible to create a package with this like functionality:
https://github.com/youtube/api-samples/blob/master/python/upload_video.py
https://github.com/tokland/youtube-upload/

It must be very helpful to have an instrument for uploading videos on youtube using dd-wrt on router.

**Comment by ryzhovau** [comment]
Did you tried to install it as python module? https://github.com/Entware/Entware/wiki/Self-installation-of-python-modules

**Comment by ryzhovau** [comment]
No response.
