### ISSUE TITLE
[Package Request] Podman

### ISSUE THREAD

**Issue by memiks** [Entware/Entware#926]
**I would like to be able to execute containers based on Podman deamon**
the package is already provided in OpenWrt repo:

https://github.com/Entware/entware-packages/tree/master/utils/podman

https://github.com/containers/podman/
https://podman.io/

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
As for now, we can't provide any of container implementation on Entware targets, and we see no sense to add it to x64 target only.
