### ISSUE TITLE
[Package request] orjson for homeassistant

### ISSUE THREAD

**Issue by WaveBird** [Entware/Entware#927]
Hi, there, I am installing homeassistant and run into orjson compile which require rust and it failed, I really hope entware can make a pre-compiled pkg, thank you.

**Comment by ryzhovau** [comment]
Duplicate of https://github.com/Entware/Entware/issues/863

**Comment by ryzhovau** [comment]
Rust packages has been added, including `python3-orjson`. Binaries will arrive soon
