### ISSUE TITLE
[Package Request] stress-ng for benchmarking and stress testing

### ISSUE THREAD

**Issue by ostrich** [Entware/Entware#928]
`stress` is already in the repo but [`stress-ng`](https://github.com/ColinIanKing/stress-ng) is far more powerful. My main interest is for its basic benchmarking capabilities. For example, running `stress-ng --cpu 0 -t60 --metrics-brief` gives a basic CPU benchmark that can be compared across platforms. But it can stress/benchmark far more than just CPU, including RAM, I/O, and many other things. Would be a nice addition for comparing routers.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
It requires a bunch of dependences, like apparmor and so on. Also, it requires some kernel capabilities, which can't be provided on some Entware targets.
Won't add it, sorry.
