### ISSUE TITLE
[Package Request] coral-edgetpu-stable

### ISSUE THREAD

**Issue by ManClone** [Entware/Entware#929]
Adding the driver installation of Google Coral PCIe. This would add the possibility to use the EDGE TPU on Synology NAS.

https://coral.ai/docs/m2/get-started/#2a-on-linux

the needed packages would be gasket-dkms libedgetpu1-std

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
It will be useless on most of Entware targets.
Won't add x64-specific package, sorry.
