### ISSUE TITLE
MTProto-proxy

### ISSUE THREAD

**Issue by brain5lug** [Entware/Entware#93]
Package request
---
Official telegram messenger proxy
https://github.com/TelegramMessenger/MTProxy
---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by themiron** [comment]
it supports x86 & x86-64 archs only

**Comment by Kirya2k** [comment]
There is an unofficial implementation MTProxy based on the python3-cryptography library. Cryptography is present in Entware.
https://github.com/alexbers/mtprotoproxy
On which platform do you want to run MTProxy ?

**Comment by ryzhovau** [comment]
Duplicate of #76 and #85.
