### ISSUE TITLE
[Package Request] exa (a modern replacement for ls)

### ISSUE THREAD

**Issue by pro-sumer** [Entware/Entware#930]
# exa

A modern replacement for ls

https://github.com/ogham/exa

> exa is a modern replacement for the venerable file-listing command-line program ls that ships with Unix and Linux operating systems, giving it more features and better defaults. It uses colours to distinguish file types and metadata. It knows about symlinks, extended attributes, and Git. And it’s small, fast, and just one single binary.

> By deliberately making some decisions differently, exa attempts to be a more featureful, more user-friendly version of ls. For more information, see [exa’s website](https://the.exa.website/).

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [aarch64] and get a feedback about it.

**Comment by ryzhovau** [comment]
Rust package is still out our scope, sorry.

**Comment by ryzhovau** [comment]
Rust packages has been added, including `eza` (exa successor). Binaries will arrive soon

**Comment by mezhgano** [comment]
Installed eza from Entware to ASUS Router and got this:

```bash
# eza
eza: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
```

```bash
# uname -a
Linux RT-AX56U 4.1.52 #1 SMP PREEMPT Fri Apr 26 14:33:31 EDT 2024 armv7l ASUSWRT-Merlin
```
i check this file, it is located in `/opt/lib/libgcc_s.so.1`

Any clues?

**Comment by ryzhovau** [comment]
Can't reproduce on mipsel or x64 targets. Try to re-install Entware from scratch.
