### ISSUE TITLE
[Package Request] luci-app-signdog_3.1.1_aarch64_cortex-a53

### ISSUE THREAD

**Issue by klcb2010** [Entware/Entware#932]
This software is used for website check-in and has been tested and run on Merlin firmware using the ASUS GT-AX6000 testing device.
[luci-app-signdog_3.1.1_aarch64_cortex-a53.zip](https://github.com/Entware/Entware/files/11287570/luci-app-signdog_3.1.1_aarch64_cortex-a53.zip)

**Comment by ryzhovau** [comment]
We've got no LUCI here, sorry.
