### ISSUE TITLE
Install on Asus stock firmware  Cannot create directory `/opt/var': Read-only file system.

### ISSUE THREAD

**Issue by klcb2010** [Entware/Entware#933]
![截屏图片 (2)](https://user-images.githubusercontent.com/32628414/233415632-ec24b15e-d535-4366-8d62-2a506cf59211.jpg)

**Comment by ryzhovau** [comment]
Some Asus-specific questions better to discuss with other device users.
Please, try to reach out [SNB community](https://www.snbforums.com/forums/asus-wireless.37/).
