### ISSUE TITLE
[Package Request] pppd 2.4.9

### ISSUE THREAD

**Issue by rsend** [Entware/Entware#935]
- Current version available is 2.4.8, it is 3 years old and seem.s to have some incompatibility talking to 2.4.9 which is found on most other distributions

**Comment by zyxmon** [comment]
https://github.com/Entware/Entware/blob/master/package/network/services/ppp/Makefile#L7

Entware still supports old kernels.

**Comment by rsend** [comment]
My dd-wrt device only has builds for kernels 4.x, but these 3.x packages still run. However, ppp has a kernel component / dependence, maybe that's why it's acting up. What would you suggest? I can't downgrade the device, so could I build 2.4.9 for Entware instead?

**Comment by zyxmon** [comment]
Just use dd-wrt toolchain, not Entware.
