### ISSUE TITLE
[Package Request]

### ISSUE THREAD

**Issue by MrCee** [Entware/Entware#936]
I’d like to try out ripgrep. Can you please add. More info [here](https://blog.burntsushi.net/ripgrep/#:~:text=Unlike%20GNU%20grep%2C%20ripgrep%20stays,in%20ripgrep%27s%20default%20regex%20engine.)

- [X] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [Synology DSM 7] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by The-BB** [comment]
https://github.com/Entware/Entware/issues/707
