### ISSUE TITLE
gnuplot package

### ISSUE THREAD

**Issue by gilgrissom** [Entware/entware#94]
Hello, is there any chance of having a gnuplot package compiled and compatible with shibby 123 on rt-n66u?
Regards, Gil.

**Comment by YasharF** [comment]
The makefile in OpenWRT's trunk: https://dev.openwrt.org/browser/packages/utils/gnuplot/Makefile
It needs to be patched since it has references to /usr on line 56 and 57.

**Comment by ryzhovau** [comment]
@gilgrissom, sorry for the late answer. How you going to use that? For what?

**Comment by gilgrissom** [comment]
@ryzhovau for plotting raw availability data like this:
![capture396](https://cloud.githubusercontent.com/assets/10052441/6485828/09b64542-c24c-11e4-8591-df6ff33d1c54.png)
I managed to build the standard gnuplot 5.0 tarball on the router itself but for some reason I get issues with formatting of time values...

**Comment by ryzhovau** [comment]
Implemented in https://github.com/Entware-ng
