### ISSUE TITLE
Package request : ngrok/ngrok-c

### ISSUE THREAD

**Issue by fbigun** [Entware/Entware#94]
Package: ngrok or ngrok-c
Exposing a local server behind a NAT or firewall to the internet.

Repo for ngrok: https://github.com/inconshreveable/ngrok
Repo for ngrok-c: https://github.com/dosgo/ngrok-c

Pagekit in repo is obviously not suitable for embedded devices

Pagekite has c language implementation libpagekite: https://github.com/pagekite/libpagekite
Ngrok also has the implementation of c language ngrokc

**Comment by ryzhovau** [comment]
Did you tried `pagekite` from our repo?

**Comment by fbigun** [comment]
I have tried using `pagekite`. He can run and use, but it is too resource intensive.

However, he is based on an application running in python and is not well suited for running on low-configuration routes.

`ngrokc` is compiled as a client for c and is suitable for long-term operation on the router. And you can use the unofficial server by modifying the service information in the configuration on your own server, which is more free.

`libpagekit` is also implemented in C language. But I have not used it because I have not compiled it successfully and put it into use.

**Comment by ryzhovau** [comment]
[Proven as working](https://github.com/nu1ee/asuswrt-entware-ng-ngrokc). Ok then.
