### ISSUE TITLE
Unrar 6.10 beta 3 causes problem with Sabnzbd

### ISSUE THREAD

**Issue by headburger** [Entware/Entware#942]
Sabnzbd direct unpack fails when using Unrar from latest Entware (via Sherpa package on QNAP but maybe elsewhere)
Apparently there is a bug in beta 3 that causes this problem.

Would it be possible to revert Entware to Unrar 6.10 stable until this issue is resolved?

https://forums.sabnzbd.org/viewtopic.php?t=25931

**Comment by ryzhovau** [comment]
As a temporary solution, you can use any previous unrar version from `https://bin.entware.net/<arch>/archive/`

**Comment by ryzhovau** [comment]
Dup of https://github.com/Entware/Entware/issues/828
