### ISSUE TITLE
New OpenSSL update is out currently 3.1.1 and 1.1.1u

### ISSUE THREAD

**Issue by Alozaros** [Entware/Entware#944]
Could we have the new **Openssl** updated...? 
It seams Entware abandoned support for  1.1.1x 
but now using 3.0.8-2a instead, the new from 30May is 3.1.1 could we have it Please ?
https://www.openssl.org/
I run Entware on  multiple platforms mostly ARM or MIPS...
Thanks in advance !

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Sorry, it's out of project goal.
We don't try to catch newer version if package came from upstream.
So, this one came from OpenWrt with no changes to simplify further support.
