### ISSUE TITLE
[Package Request] LXD

### ISSUE THREAD

**Issue by mcondarelli** [Entware/Entware#946]
This might be a difficult one.
[LXD](https://linuxcontainers.org/) is a full Hypervisor similar to Docker, enabling deployment of containerized applications.
Synology and friends already include Docker and thus this should be feasible, but probably not trivial.
Main difference between Docker and LXD is the former is geared toward single-process containerization while the latter can handle "system level" (i.e.: multiple process) containerization (e.g.: it has full `systemd` support).

- [x] No similar package already added,
- [x] Package is in active development,
- [x] I'm ready to test added package on my platform (Synology DS422+, 6GRAM) and get a feedback about it.

Project is built using `go` which is already available in Entware (Entware go  version is OK, I checked).
Recommended installation method for LXD is `snap`, which is obviously a no-go, but compilation instructions are available [here](https://linuxcontainers.org/lxd/docs/latest/installing/#installing-lxd-from-source).

I am available to help, if useful, as I have a bit of experience with Linux, but I'm an Entware newbie.

**Comment by ryzhovau** [comment]
There's several [kernel requirements](https://linuxcontainers.org/lxd/docs/latest/requirements/#kernel-requirements) that can't be met.

**Comment by leonpano2006** [comment]
> There's several [kernel requirements](https://linuxcontainers.org/lxd/docs/latest/requirements/#kernel-requirements) that can't be met.

link is dead
