### ISSUE TITLE
[Package Request] coturn

### ISSUE THREAD

**Issue by YikeStone** [Entware/Entware#947]
This package will enable support for stun/turn server. Currently its not available in entware repo.

https://openwrt.org/packages/pkgdata/coturn

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by YikeStone** [comment]
Hey, I ended up installing openwrt. Thanks anyways.

**Comment by ryzhovau** [comment]
Thanks for letting us know.
