### ISSUE TITLE
Zabbix Server cannot connect to Mariadb Database

### ISSUE THREAD

**Issue by hbsimon** [Entware/Entware#948]
zabbix-server - 6.2.3-3a fails with following error on startup when connecting to mariadb database:
["[Z3001] connection to database 'zabbix' failed: [0] connection to server at "localhost", port 3306 failed: expected authentication request from server, but received \" .]

**Environment (please complete the following information):**
 - Entware feed: [zabbix-server - 6.2.3-3a]
 - Device [QNAP-NAS TS-451 D2]
 - Firmware version [Linux qnap-nas 5.10.60-qnap #1 SMP]

When checking on github, it shows that the zabbix-server is build for postgresql only. QNAP uses mariadb, so can this application please be build using mysql/mariadb for databse.
Thanks and Regards,
Horst

**Comment by ryzhovau** [comment]
This package came from [upstream](https://github.com/openwrt/packages/blob/master/admin/zabbix/Makefile) with no any changes. We'll keep it as is to easier further sync.
