### ISSUE TITLE
libdht is outdated - please update. 

### ISSUE THREAD

**Issue by abir1909** [Entware/Entware#952]
**Describe the bug**
[package name]: A clear and concise description of what the bug is and how to reproduce it. 

**Environment (please complete the following information):**
 - Entware feed: [e.g. mipselsf-k3.4]
 - Device [e.g. Asus RT-AX88U router]
 - Firmware version [e.g. asuswrt-merlin]

**Comment by atkinsom** [comment]
As per sad-spirit from SNBForums re: Transmission 4.0.3 - [https://www.snbforums.com/threads/transmission-stopped-working.84082/post-849860](url)

"Running transmission via startup script from /opt/etc/init.d causes it to exit immediately with no messages. However, I tried starting transmission-daemon in foreground:

...:/tmp/home/root# transmission-daemon -g /opt/etc/transmission -f
transmission-daemon: symbol lookup error: /opt/lib/libdht.so: undefined symbol: dht_random_bytes

Checking the mentioned .so file shows the following:

...:/tmp/home/root# opkg search /opt/lib/libdht.so
libdht - 2022-04-27-11123089-1


Reinstalling libdht package does not help, version string hints that it is a bit dated anyway.

I strongly suspect that it's entware problem, libdht should be upgraded for transmission to work."

**Comment by atkinsom** [comment]
Further comment from sad-spirit on SNBForums

"Now I'm actually sure of this, I managed to start transmission-daemon with the switch to disable DHT

 -O   --no-dht                          Disable distributed hash tables (DHT)

and successfully downloaded a torrent."

**Comment by zyxmon** [comment]
What architecture (feed) has problems with new transmission? armv7sf-k2.6?

**Comment by zyxmon** [comment]
Transmission 4.03 bug is discussed here - https://github.com/Entware/Entware/issues/953

**Comment by zyxmon** [comment]
I am closing issue as incorrect. Entware uses the latest libdht version.
