### ISSUE TITLE
transmission 4.03 does not start on arm7-k2.6

### ISSUE THREAD

**Issue by zyxmon** [Entware/Entware#953]
The problem is discussed here - https://www.snbforums.com/threads/transmission-stopped-working.84082/post-849863
The temporary solution is to disable dht.

**Comment by AkteX** [comment]
The root cause of the problem is that the function dht_random_bytes is not available in libdht. The source file dht-example.c must be compiled and linked to the library as shown below.

```
define Build/Compile
        $(TARGET_CC) $(FPIC) -Wall -c -o $(PKG_BUILD_DIR)/dht.o $(PKG_BUILD_DIR)/dht.c
        $(TARGET_CC) $(FPIC) -Wall -c -o $(PKG_BUILD_DIR)/dht-example.o $(PKG_BUILD_DIR)/dht-example.c
        $(TARGET_CC) -shared -lcrypt -o $(PKG_BUILD_DIR)/libdht.so $(PKG_BUILD_DIR)/dht.o $(PKG_BUILD_DIR)/dht-example.o
endef
```

**Comment by zyxmon** [comment]
updated libdht package - https://test.entware.net/armv7sf-k2.6/libdht_2022-04-27-11123089-1a_armv7-2.6.ipk

**Comment by AkteX** [comment]
I tested it with x86-2.6. Can you please update the libdht package for all architectures?

**Comment by zyxmon** [comment]
It looks like only 2 architectures (k2.6) need this.

**Comment by AkteX** [comment]
I checked bin.entware.net and found libdht in all architectures. As long as libdht is used it shall be build with dht-example.c. Otherwise some symbols which are exported by dht.h are not available. This was the reason why transmission didn't start.

**Comment by zyxmon** [comment]
tr-dht.cc (transmission sources) has dht_random_bytes function. For some reasons it is not used in two architectures (for old kernels).
aarch64 transmission runs correctly with dht enabled and without dht_random_bytes in libdht. It also runs correctly with "new" libdht (just tested it). I am waiting response from  arm7-k2.6 owners to commit your changes to the repo.

**Comment by AkteX** [comment]
I just tested Entware arm7-k2.6. With libdht from the repo transmission-daemon doesn't start. After the installation of https://test.entware.net/armv7sf-k2.6/libdht_2022-04-27-11123089-1a_armv7-2.6.ipk transmission-daemon is running.

**Comment by zyxmon** [comment]
IMHO а better approach to solve the issue is to link libdht statically (as in transmission 3 and earlier versions).
Here is a fixed daemon https://test.entware.net/armv7sf-k2.6/transmission-daemon_4.0.3-2a_armv7-2.6.ipk
Other transmission ipk can be found here - https://test.entware.net/armv7sf-k2.6/

**Comment by zyxmon** [comment]
Fixed via https://github.com/Entware/entware-packages/commit/fb12474c80fd9834482c13ca549894d0b0ac4a0c
