### ISSUE TITLE
Restic

### ISSUE THREAD

**Issue by newdanceradio** [Entware/Entware#954]
Could it be possible to add "restic" package to entware repository.
Restic is very powerfull backup solution.

Project URL: https://restic.net/

Thanks in advance.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [aarch64-k3.10] and get a feedback about it.

**Comment by glemag** [comment]
+1

**Comment by zyxmon** [comment]
aarch64 package for testing - https://test.entware.net/aarch64-k3.10/restic-go_0.15.2-1_aarch64-3.10.ipk

**Comment by newdanceradio** [comment]
Thank you @zyxmon 
I can confirm, that package is working properly
![image](https://github.com/Entware/Entware/assets/17381301/751c477a-d3e2-4aef-8278-477a05cf8662)
![image](https://github.com/Entware/Entware/assets/17381301/1dadf375-a511-4942-ba4c-dd9f408675fa)

**Comment by ryzhovau** [comment]
Thanks for feedback!
