### ISSUE TITLE
Toolchain update

### ISSUE THREAD

**Issue by ttc0419** [Entware/Entware#957]
Hi, are there any plans to update the current toolchain environment? It still uses linux 3.10 and glibc 2.27 for aarch64. Newer Asus routers are using linux 4.19 and glibc 2.30, not to mention the latest version of glibc is 2.37.

**Comment by zyxmon** [comment]
The new toolchain wil drop old devices support. May be we will make a separate Entware4 for devices with new kernels. But we do not think there will be great benefits from it now.
