### ISSUE TITLE
Latest transmission-daemon stops working with enabled DHT

### ISSUE THREAD

**Issue by gjf** [Entware/Entware#962]
**Describe the bug**
[package name]: transmission-daemon crashes with enabled DHT.
To reproduce it:
1, Install Transmission in a normal way like
`opkg install transmission-web transmission-daemon`
2. Ensure you have enabled DHT in /opt/etc/transmission/settings.json:
`"dht-enabled": true,`
3. Try to start transmission-daemon:
`/opt/etc/init.d/S88transmission start`
You will notice the daemon will stop with no error in logs.

**Environment (please complete the following information):**
 - Entware feed: armv7sf-k2.6
 - Device Asus RT-AX86U
 - Firmware version Asuswrt-Merlin 388.2_2

The problem was discussed here: https://www.snbforums.com/threads/transmission-stopped-working.84082
Also it was mentioned here: https://github.com/Entware/Entware/issues/952
and here: https://github.com/Entware/Entware/issues/953

For some reason the issues were closed possibly because they were not opened according to the rules.

**Comment by zyxmon** [comment]
duplicate - https://github.com/Entware/Entware/issues/953
