### ISSUE TITLE
sstp-client version >1.0.15

### ISSUE THREAD

**Issue by dominiaz** [Entware/Entware#965]
There is a bug with sstp-client 1.0.15 which is described here:

[https://sourceforge.net/p/sstp-client/discussion/1499218/thread/f96014d027/?limit=25](url)

sstp-client 1.0.15 is useless with pppd 2.4.8 in Entware repo.

1) Please compile sstp-client 1.0.15 with patch from the link 
or 
2) Compile new package with fixed issue - minimal version sstp-client 1.0.16 or newer.

I need that package in armv7sf-k3.2 architecture.

**Comment by zyxmon** [comment]
here is it (patched) - https://test.entware.net/armv7sf-k3.2/sstp-client_1.0.15-1a_armv7-3.2.ipk
Please report results.

**Comment by dominiaz** [comment]
Unfortunately there is still an issue.

root@p722:/ # ln -s /opt/lib/sstp-pppd-plugin.so /opt/lib/pppd/2.4.8/sstp-pppd-plugin.so
root@p722:/ # /opt/sbin/pppd call peer-sstp-example.txt
/opt/sbin/pppd: /opt/lib/pppd/2.4.8/sstp-pppd-plugin.so: undefined symbol: mppe_get_recv_key
/opt/sbin/pppd: Couldn't load plugin sstp-pppd-plugin.so

**Comment by zyxmon** [comment]
https://test.entware.net/armv7sf-k3.2/sstp-client_1.0.16-1_armv7-3.2.ipk
and this one?

**Comment by dominiaz** [comment]
This one looks ok. Thank you. I will be testing the package.

**Comment by zyxmon** [comment]
fixed via https://github.com/Entware/entware-packages/commit/c832a8ce83cdde0fa4edb6f53a0c6f00266a7b0b
