### ISSUE TITLE
Squid version is very old (2.7) and has CVE security issues

### ISSUE THREAD

**Issue by ck-on** [Entware/entware#97]
Any chance someone is talented enough to build a newer version of Squid?

The 2.7 version on entware is ancient, 5+ years old and has many known security issues.

3.4 would be lovely but I've been unable to successfully build it for mipsel environment.

**Comment by YasharF** [comment]
OpenWRT package feed is already on version 3.4.10: https://github.com/openwrt/packages/blob/3df768771fbd7ba064d475fcee535af3ad9f343f/net/squid/Makefile

**Comment by ryzhovau** [comment]
Done.
