### ISSUE TITLE
fork #2 failed: 12 (Cannot allocate memory) 

### ISSUE THREAD

**Issue by diman82** [Entware/Entware#97]
When running on Entware (Asus rt-ac86u - armv8):
pyload --daemon --configdir=/opt/var/pyload

I get the following error message:
fork #2 failed: 12 (Cannot allocate memory)

How to debug this issue? What is wrong? 

P. S Already opened an issue [for](https://github.com/pyload/pyload/issues/3199) pyload, they refered me to you.

**Comment by ryzhovau** [comment]
Try to add swap file first. Looks like `pyload` consumes too much RAM on start up.

**Comment by diman82** [comment]
@ryzhovau Can you please refer me how this should be achieved? Yoy mean swap partition?

**Comment by ryzhovau** [comment]
> Can you please refer me how this should be achieved?

Depends on current firmware. I'm not ready to provide personal support, sorry.

**Comment by diman82** [comment]
Found relevant information: https://www.snbforums.com/threads/need-command-to-create-swap-file.37291/

**Comment by diman82** [comment]
Adding a swap partition worked. 
You may close this issue.
