### ISSUE TITLE
QNAPCLUB

### ISSUE THREAD

**Issue by the-moog** [Entware/Entware#972]
Not a bug as such, but the [qnapclub.eu](https://www.qnapclub.eu/en) website certificate has expired, their repo has not had activity in a year and the only way I coud tell them that is via Google+ (linked on their site) which died in 2019.

Perhaps remove the mention of qnapclub from this project wiki?

**Comment by zyxmon** [comment]
You can do it yourself.

**Comment by the-moog** [comment]
> You can do it yourself.

I would not do that as I don't know if I am correct, I was hoping somebody on this project would also be on that project would know a little more.  I am not a contributor to this project so would not commit changes that are presumptions. 
I don't have Twitter or Facebook or any way to gain more insight.

**Comment by krvi** [comment]
I edited the wiki for you.
