### ISSUE TITLE
unbound 1.7.3

### ISSUE THREAD

**Issue by underd0se** [Entware/Entware#98]
Unbound version in the Entware repo is 1.6.7-1 and dated back to Oct 2017. 

`# opkg info unbound
Package: unbound
Version: 1.6.7-1
`

Newest version which has lots of fixes for critical bugs and vulnerabilities, according to their [SVN](https://unbound.nlnetlabs.nl/svn/) is 1.7.3. 

Can you update the Entware repo with the latest version for each platform? 

Thanks in advance.

**Comment by zyxmon** [comment]
The current version of unbound is 1.7.1 in Entware. @underd0se - probably you are speaking about Entware-ng, that is not maintained now. We will update unbount with next openwrt sync - https://github.com/openwrt/packages/blob/master/net/unbound/Makefile

**Comment by ryzhovau** [comment]
Done. Binaires will arrive soon.
