### ISSUE TITLE
bash can not read /etc/bash_completion, no such file

### ISSUE THREAD

**Issue by mzhboy** [Entware/entware#98]
```
root@ac66u:/tmp/home/root# bash
root@ac66u:/tmp/home/root# source /etc/profile 
sed: can't read /etc/bash_completion: No such file or directory
```
so, please change the build path of bash_completion to:
```
/opt/etc/bash_completion
```

**Comment by YasharF** [comment]
I tried to reproduce this problem to see if I can patch it.  However, it looks like that it is already resolved; I did not get any errors.

<code>
user@router:/tmp/mnt/sdb# bash
bash: bash: command not found
user@router:/tmp/mnt/sdb# opkg install bash-completion
Installing bash-completion (20080705-2) to root...
Downloading http://entware.wl500g.info/binaries/entware/bash-completion_20080705-2_all.ipk.
Installing bash (4.3.30-1) to root...
Downloading http://entware.wl500g.info/binaries/entware/bash_4.3.30-1_entware.ipk.
Configuring bash.
Configuring bash-completion.
user@router:/tmp/mnt/sdb# bash
user@router:/tmp/mnt/sdb# echo $BASH_VERSION
4.3.30(1)-release
user@router:/tmp/mnt/sdb# source /etc/profile
user@router:/tmp/mnt/sdb#
</code>

**Comment by mzhboy** [comment]
@YasharF 

```
root@ac66u:/tmp/etc# opkg install bash-completion
Installing bash-completion (20080705-2) to root...
Downloading http://entware.wl500g.info/binaries/entware/bash-completion_20080705-2_all.ipk.
Installing bash (4.3.30-1) to root...
Downloading http://entware.wl500g.info/binaries/entware/bash_4.3.30-1_entware.ipk.
Configuring bash.
Configuring bash-completion.
root@ac66u:/tmp/etc# bash
root@ac66u:/etc# cd /opt/etc
root@ac66u:/opt/etc# . profile
sed: can't read /etc/bash_completion: No such file or directory
root@ac66u:/opt/etc/profile.d# cat /etc/profile 
export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/home/$USER:/mmc/sbin:/mmc/bin:/mmc/usr/sbin:/mmc/usr/bin:/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin:`nvram get env_path`"
export PS1='\u@\h:\w\$ '

alias l='ls -lFA'
alias ll='ls -lF'

ldd() {
	LD_TRACE_LOADED_OBJECTS=1 $*;
}

[ -f /jffs/etc/profile ] && . /jffs/etc/profile
[ -f /opt/etc/profile ] && . /opt/etc/profile

root@ac66u:/opt/etc/profile.d# . /etc/profile
sed: can't read /etc/bash_completion: No such file or directory
```

**Comment by ryzhovau** [comment]
Thanks for the feedback. This is 7 years old bash-completion package, taken from Debian. Half of script relies on Debian system config files, which is absent on embedded devices. As a result, built-in completion list is empty (you may list rules by `complete -p`). 

I don't know why OpenWrt guys made this package, I see no sense to keep it in repo, it will be deleted.
