### ISSUE TITLE
[Package Request] vifm

### ISSUE THREAD

**Issue by pedropombeiro** [Entware/Entware#984]
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

[Vifm](https://github.com/vifm/vifm) is a file manager with curses interface, which provides Vim-like environment for managing objects within file systems, extended with some useful ideas from mutt.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by jose1711** [comment]
duplicate #956
