### ISSUE TITLE
[Package Request] rathole

### ISSUE THREAD

**Issue by diskdance** [Entware/Entware#985]
**Describe the solution you'd like**
[rathole](https://github.com/rapiz1/rathole) is a lightweight alternative to frp. It is written in rust and has better performance and less memory consumption.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
Done. Please, provide a feedback.
