### ISSUE TITLE
qbittorrent - 4.5.4-1 will not start on WD PR4100 NAS because libatomic.so.1 is missing.

### ISSUE THREAD

**Issue by Myron-S** [Entware/Entware#988]
**Describe the bug**
Used _opkg update && opkg upgrade_ which upgraded _qbittorrent - 4.5.4-1_. When installed _qbittorrent_nox_ will not start because _/opt/lib/libatomic.so.1_ can not be found.

Because this library is part of WD PR4100's NAS firmware, this command fixed the issue:
`ln -s /usr/local/modules/lib/libatomic.so.1 /opt/lib/libatomic.so.1`

Once the symbolic link is created qBtorrent works.

**Environment:**
 - Entware feed: qbittorrent - 4.5.4-1
 - Device: Western Digital PR4100 NAS
 - Firmware version: 5.26.300

**Comment by ryzhovau** [comment]
https://github.com/Entware/Entware/wiki#%EF%B8%8F-package-upgrade-notes
