### ISSUE TITLE
transmission-cfp

### ISSUE THREAD

**Issue by cfpp2p** [Entware/Entware#99]
### Package: transmission-cfp

update existing package transmission-cfp

PKG_NAME:=transmission-cfp
PKG_VERSION:=2.77plus-20180711
PKG_REV:=533d05019bbfc2cca5a8fe48fa98ef961d202a32
PKG_RELEASE:=1

thank you

**Comment by cfpp2p** [comment]
@ryzhovau  also

define Download/transmission-cfp-web-client
  FILE:=transmission-cfp-web-client-$(PKG_VERSION).tar.bz2
  URL:=$(PKG_SOURCE_URL)
  PROTO:=git
  VERSION:=a2d1a0a5c1296739550b03b8ad8068765c2e4c77
  SUBDIR:=transmission-cfp-web-client-$(PKG_VERSION)

**Comment by ryzhovau** [comment]
Done. Binaires will arrive soon.
