### ISSUE TITLE
tailscaled dies on faccessat2 syscall

### ISSUE THREAD

**Issue by knl** [Entware/Entware#990]
**Describe the bug**
tailscale: When I start running tailscaled (command is essentially `/opt/bin/tailscaled --state=/opt/var/tailscaled.state`, `dmesg` shows:

```
tailscaled[4041]: syscall 439
Code: f94017e3 f9401be4 f9401fe5 d4000001 (b13ffc1f)
CPU: 0 PID: 4041 Comm: tailscaled Tainted: P        W  O    4.1.27 #2
Hardware name: Broadcom-v8A (DT)
task: ffffffc012d4cac0 ti: ffffffc013ff0000 task.ti: ffffffc013ff0000
PC is at 0x13600
LR is at 0x135bc
pc : [<0000000000013600>] lr : [<00000000000135bc>] pstate: 20000000
sp : 000000400061f5c0
x29: 000000400061f5b8 x28: 00000040003d24e0
x27: 0000000000000000 x26: 0000000000b2e088
x25: 000000400004b860 x24: 0000000000000000
x23: 0000000000000000 x22: 00000040005a0000
x21: 0000004000196000 x20: 000000400061f230
x19: 0000000000000000 x18: 0000000000000000
x17: 000000400061f7a0 x16: 00000040006003a0
x15: 003b9aca00000000 x14: 0000000000000007
x13: 000000000000002a x12: 000000000000000f
x11: 0000000000000000 x10: 0000000000000000
x9 : 000000400069c0e0 x8 : 00000000000001b7
x7 : 0000000000000001 x6 : 0000000000000000
x5 : 0000000000000000 x4 : 0000000000000000
x3 : 0000000000000200 x2 : 0000000000000001
x1 : 000000400069c0e0 x0 : ffffffffffffff9c
```

syscall 439 is faccessat2, if I'm not mistaken. After a couple of minutes, the process dies...

**Environment (please complete the following information):**
 - Entware feed: `aarch64-k3.10`
 - Server in use: `bin.entware.net`
 - Device: `Asus RT-AC86U router`
 - Firmware version: `asuswrt-merlin 386.12`

**Comment by zyxmon** [comment]
It looks like this bug is device/firmware specific. Tailscale runs on my aarch64 Qnap NAS for ages without problems. May be here - https://github.com/tailscale/tailscale/issues you can find more support.

**Comment by knl** [comment]
I did another test now and rebooted the router. The process still runs. Previously, it was started via init (`/opt/etc/init.d/S06tailscaled start`), and would die when I get logged out from the router. So probably something kernel/go related.
