### ISSUE TITLE
Can I compile the i2c tools software package? 

### ISSUE THREAD

**Issue by happytrudy** [Entware/Entware#996]
Can I compile the i2c tools software package? 

The i2c tools software package contains a different set of I2C tools for Linux: bus detection tool, chip dumper, register level SMBus access helper, EEPROM decoding script, EEPROM programming tool, and Python module for SMBus access. As long as I2C support is included in the kernel, all versions of Linux are supported

**Comment by ryzhovau** [comment]
Please, follow OpenWrt Buildroot docs.
Sorry, we're not ready to provide personal support.
